### ISSUE TITLE
我要着变化有何用？

### ISSUE THREAD

**Issue by arronliu1989** [oceanbase/oceanbase#10]
开了关，关了又开，本次开了还关吗？

**Comment by raywill** [comment]
This time we are taking this very very seriously! Time will prove.

**Comment by glkappe** [comment]
这是开，这是关，这是开还是关 @arronliu1989

**Comment by Helmsman-Lab** [comment]
纠结

**Comment by nowheretodo** [comment]
别说了 现在晋升季 负责的工程师要靠这个晋升P8P9呢 你们这么打脸让他们怎么办啊 等晋升完再留你们个烂摊子项目喷

**Comment by hnwyllmm** [comment]
你说的吓死人。不管怎么说，先把代码捞下来学习一下是正经

**Comment by xuelangos** [comment]
开源晋升一个p9,升上去之后，我再闭源，下一任，我再开源；快乐就是这么来的

**Comment by boatrainlsz** [comment]
哎，就是玩

**Comment by longdafeng** [comment]
行内一些朋友看到OB将一个300多万行的的成熟系统开源出来, 忍不住就说
“OB 开源是动真格了”

 另外, 我们非常欢迎大家提一些建议或反馈一些问题.
