### ISSUE TITLE
[Bug]: Failed to change tenant's locality from F type to Full 

### ISSUE THREAD

**Issue by TobyYaochen** [oceanbase/oceanbase#1005]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version 3.1.4
- Hardware parameter:OS type 7.6
- Others
```

### Fast Reproduce Steps(Required)

alter tenant test locality='FULL{1}@zone,FULL{1}@zone1'

### Actual Behavior

ERROR 4179 (HY000): primary zone F type replica not enough in its region not allowed

**Comment by hnwyllmm** [comment]
3.x is freezed.
