### ISSUE TITLE
Get ERROR 1235 (0A000): Not supported feature or function when insert data into table has a foreign key refer to other table

### ISSUE THREAD

**Issue by reeingal** [oceanbase/oceanbase#101]
The SQL below can be executed well in MySQL:

```SQL
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t1;
CREATE TABLE `t1` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY);
CREATE TABLE `t2` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `t1_id` integer NOT NULL);
ALTER TABLE `t2` ADD CONSTRAINT `t2sss` FOREIGN KEY (`t1_id`) REFERENCES `t1` (`id`);
INSERT INTO `t1` (`id`) VALUES (1);
INSERT INTO `t2` (`t1_id`) VALUES (1);
```

The code above just defines two table t1 and t2, and t2 has a column named t1_id refer to the id column of t1.

But when  the last SQL be executed in OceanBase, it gets error below:

```
ERROR 1235 (0A000): Not supported feature or function
```

I may miss the  description of foreign key restriction in document, can you help me.

**Comment by longdafeng** [comment]
Thanks for you feedback. 

We will investigate this issue and give you response as soon as possible.

**Comment by simonjoylet** [comment]
I guess that you run the test on sys tenant. the sys tenant dose NOT support gts service, which is required in some distributed transactions. see [this](https://www.oceanbase.com/community/answer/detail?id=254)
You need to create a tenant and try it again. please refer to this [doc](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/create-a-user-tenant).
It works in my cluster.
![image](https://user-images.githubusercontent.com/5274450/121999692-32962080-cde0-11eb-8fc6-4b7c470fef98.png)

**Comment by reeingal** [comment]
> I guess that you run the test on sys tenant. the sys tenant dose NOT support gts service, which is required in some distributed transactions. see [this](https://www.oceanbase.com/community/answer/detail?id=254)
> You need to create a tenant and try it again. please refer to this [doc](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/create-a-user-tenant).
> It works in my cluster.
> ![image](https://user-images.githubusercontent.com/5274450/121999692-32962080-cde0-11eb-8fc6-4b7c470fef98.png)

Yes, it solved my problem. I created a new tenant, and a new user belong to it. Then logged in and ran the SQL well. Thank you for your reply.

**Comment by longdafeng** [comment]
Please refer to this doc  "How to create a tenant" https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/create-a-user-tenant
