### ISSUE TITLE
[Feature]Reset root passwd

### ISSUE THREAD

**Issue by akaError** [oceanbase/oceanbase#1011]
**Is your feature request related to a problem? Please describe.**
Currently when root password lost, OceanBase do not support safe reset mode as mysql do
**Describe the solution you'd like**
Learned from mysql to provide a safe reboot mode for reseting root password, but more powerful, OceanBase do not required to shut down the whole database cluster because of its distributed architecture.
**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
After discussion with our security department, they doesn't allow this kind of action, this will lead to critical security risk to whole system. 

This is by design.
