### ISSUE TITLE
[Enhancement] little optimization about observer parameter reading

### ISSUE THREAD

**Issue by Vendredimatin** [oceanbase/oceanbase#1012]
**Is your feature request related to a problem? Please describe.**
几天前，我提出了一个增加一个参数指定clog磁盘大小的feature（#990）。实现过程中，我增加了一个配置项clog_disk_limit_size，并且定义了它的range是"[0G, )".但是当我启动observer之后，发现observer在读取这个range时报错，debug后发现是observer读取配置的range时，如果没有明确设置右区间，那么逗号和右括号之间不能有空格，否则observer会读取失败(如果设置了右区间，即使有空格也不会有异常)
例如：
1. (0G, ) => wrong
2. (0G,) => right

在钉钉开源群中，我发现除了我还是有人会有在代码层面改observer配置项的需求，目前配置项range部分没有明确的格式定义，而人们写代码习惯性会在逗号后打空格。所以我决定顺手改一下这个点，以免其他小伙伴踩坑。

**Describe the solution you'd like**
在observer遍历解析range时，忽略逗号之后的空格。

**Describe alternatives you've considered**
也可以定义明确的配置项规范。

**Is your feature request related to a problem? Please describe.**
A few days ago, I proposed a feature (#990) that adds a parameter to assign the clog disk size. During the implementation, I added a configuration item (clog_disk_limit_size)  and defined its range as "[0G,  )". However, when I started the observer, I got an error about reading the range. During debugging, I found that  if  right interval of the range is not explicitly set and one or more blanks exist  between the comma and the closing bracket, an error will happen (if the right interval is set and a blank exists,  the error doesn't occur)
for example:
1. (0G,  ) => wrong
2. (0G,) => right

In the DingTalk of oceanbase community,  besides me, some people also need to change the observer configuration items at the code level. Currently, there is no clear format definition for the range part of the configuration items. Programmers habitually write a blank after the comma,  so I decided to optimize configuration item reading, so as to prevent other people from stepping on this pit.

**Describe the solution you'd like**
When the observer traverses and parses the range, ignore the space after the comma.

**Describe alternatives you've considered**
It is also possible to define explicit configuration item specifications.

**Comment by caifeizhi** [comment]
Good suggestion!

**Comment by hnwyllmm** [comment]
DONE
