### ISSUE TITLE
add comment in View is not supported in Mysql tenant

### ISSUE THREAD

**Issue by nmj1992** [oceanbase/oceanbase#1017]
当前Mysql租户，视图不支持增加任何注释，
建议增加注释功能，可以查看视图里的字段注释

**Comment by caifeizhi** [comment]
hi，是否可以补充一下描述信息；
1. 具体复现的语句，比如通过什么样的行为增加注释，具体报错信息；
2. 和mysql的行为差异；

**Comment by nmj1992** [comment]
现在是不支持增加注释，mysql应该也是不支持的，
只是提个需求，看是否可以增加这个功能，oracle的视图可以
oracle的视图字段注释功能：comment on col table.col_name is '中文注释';

**Comment by longdafeng** [comment]
If mysql doesn't support this feature, oceanbase won't support either.
