### ISSUE TITLE
Conventions of commit message

### ISSUE THREAD

**Issue by ShiKaiWi** [oceanbase/oceanbase#103]
**Is your feature request related to a problem? Please describe.**
Now the commit messages seem casual and simple. I guess it will be better if a set of conventions for commit message is provided to follow.

**Describe the solution you'd like**
A good example is the style of [golang project](https://github.com/golang/go/wiki/CommitMessage).

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by LINxiansheng** [comment]
Thanks for your feedback.

Now we have some plans and are going to optimize the process to commit code to the repository continuously.
