### ISSUE TITLE
Lower system resource requirement. I hope i can full replace mysql

### ISSUE THREAD

**Issue by cnmade** [oceanbase/oceanbase#1046]
For my thought, If you want to beat off MySQL, You must do more powerfull than MySQL

I hope there be a minimal version OceanBase, which can beat MySQL,

1 core cpu is ok, if it large than 1Ghz
128MB memory is ok?

5GB disk or less requirement

a tiny single execute file less than 500MB(pelase no so big)

a single exe + a config file can start up a full standard OceanBase server.

simple , fast, but powerful.

**Comment by cnmade** [comment]
If OceanBase can do this, who need MySQL anymore?

**Comment by hnwyllmm** [comment]
Great idea！
We are working for it right now, it will take a long time as it is a hard work.
In 4.x, which will be released at this year, the resource required is 4C 8G and it is a stable version.
But I this 128M is not our target as the memory is so cheap. Did you meet some scenarios?

**Comment by cnmade** [comment]
@hnwyllmm aliyun.com basic ecs will start from 1GB memory.
i guess it is a very good start

**Comment by cnmade** [comment]
@hnwyllmm 
![image](https://user-images.githubusercontent.com/278153/187121515-21eccf62-81e3-46f4-9bd1-57e44ad2766a.png)
If we can save money. who want to pay more ?

**Comment by hnwyllmm** [comment]
I don't think it is a good choice for database.
1G memory: 200M for OS, and the 50% of the last for database?
Server with memory too low can only used for study but not production. I think embedded database is a better choice.

**Comment by cnmade** [comment]
Good answer, so i am using mysql current. thanks for let me know.
