### ISSUE TITLE
source code of development-kit

### ISSUE THREAD

**Issue by cheeye** [oceanbase/oceanbase#106]
To build the OB, it requires some dependent packages. It seems they are not standard packaged provided by Red Hat. Could you also provide the source code of those rpm packages for users to compile by themselves?  

```
repo=http://mirrors.aliyun.com/oceanbase/development-kit/el/8/x86_64/

[deps]
devdeps-gtest-1.8.0-3.el8.x86_64.rpm
devdeps-isa-l-static-2.22.0-3.el8.x86_64.rpm
devdeps-libcurl-static-7.29.0-3.el8.x86_64.rpm
devdeps-libunwind-static-1.5.0-3.el8.x86_64.rpm
devdeps-mariadb-connector-c-3.1.12-3.el8.x86_64.rpm
devdeps-openssl-static-1.0.1e-3.el8.x86_64.rpm
devdeps-libaio-0.3.112-3.el8.x86_64.rpm

[tools]
obdevtools-bintuils-2.30-3.el8.x86_64.rpm
obdevtools-bison-2.4.1-3.el8.x86_64.rpm
obdevtools-ccache-3.7.12-3.el8.x86_64.rpm
obdevtools-cmake-3.20.2-3.el8.x86_64.rpm
obdevtools-flex-2.5.35-3.el8.x86_64.rpm
obdevtools-gcc-5.2.0-3.el8.x86_64.rpm
obdevtools-llvm-11.0.1-3.el8.x86_64.rpm
```

**Comment by MizuhaHimuraki** [comment]
Thanks for your question.

>  Could you also provide the source code of those rpm packages for users to compile by themselves?

All packages provided as RPM packages are built from unmodified source code, and these projects are also easy to get from the public domain. You can refer to our [dependency list](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code) to prepare them yourself.

We offer these packages just to make the compilation easier for beginners. Not everyone expects to start with compiling llvm or gcc.

Maybe we will add a script to build the third-party dependencies in the future, but the priority of this work is low.

**Comment by longdafeng** [comment]
@cheeye  Can you resolve this problem by the answer of @MizuhaHimuraki ?

**Comment by cheeye** [comment]
> @cheeye Can you resolve this problem by the answer of @MizuhaHimuraki ?

@longdafeng @MizuhaHimuraki Thanks! I'm looking into those dependency list. It seems couple packages are not provided by RHEL repos.  I will double check it.
