### ISSUE TITLE
[Bug]: unittest test_row_reader failed in release compile mode

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1068]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

build oceanbase in release mode;
run unittest test_row_reader

### Actual Behavior

test_number_float failed

### Expected Behavior

test_number_float success

### other information

the code in test_number_float:
```cpp
uint32_t digits = 8;
write_obj.set_number_float(ObNumber(3, &digits));
```

invalid construct ObNumber

the 3 in ObNumber means the digits's number is 3.
refer to `ObNumber::encode` in ob_number_v2.h and `struct ObNumberDesc` in ob_define.h

**Comment by watchpoints** [comment]
`TestRowReader.test_number_float (2 ms)  is ok
`
which is ok  not failed ?

**Comment by raygift** [comment]
I found out that cap_ was filled with len_ in ObNumber::decode

should cap_ be filled with len_ in encode() as in decode()?

Also i notice this test will PASS in debug mode, however the write_obj and read_obj seems different in desc_ , is that right?
