### ISSUE TITLE
observer program health check failed for invalid tg id

### ISSUE THREAD

**Issue by watchpoints** [oceanbase/oceanbase#107]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

obd cluster start obtest -v
my conf:
~~~
oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
    - 127.0.0.1
  global:
    home_path: /root/data/observer
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: lo
    mysql_port: 2881
    rpc_port: 2882
    zone: zone1
    cluster_id: 1
    # please set memory limit to a suitable value which is matching resource. 
    memory_limit: 4G
    system_memory: 2G
    stack_size: 512K
    cpu_count: 6
    cache_wash_threshold: 1G
    __min_full_resource_pool_memory: 2684354
    workers_per_cpu_quota: 10
    schema_history_expire_time: 1d
    # The value of net_thread_count had better be same as cpu's core number. 
    net_thread_count: 2
    sys_bkgd_migration_retry_num: 3
    minor_freeze_times: 10
    enable_separate_sys_clog: 0
    enable_merge_by_turn: FALSE
    datafile_disk_percentage: 20
    syslog_level: INFO
    enable_syslog_recycle: true
    max_syslog_file_count: 4
~~~

**Your Environments (__must be provided__)**

* OS: `uname -a` mac +docker 
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu` 8g+4core
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

- obd --version
OceanBase Deploy: 1.0.0

- obd cluster start obtest -v
~~~
observer program health check x
-- 127.0.0.1 program health check
-- local execute: cat /root/data/observer/run/observer.pid -- exited code 1, error output:
cat: /root/data/observer/run/observer.pid: No such file or directory
~~~

[WARN] failed to start 127.0.0.1 observer
- sub start ref count to 0
- export start
~~~
-  observer.log

~~~
[2021-06-16 03:32:49.038316] ERROR stop (ob_ddl_task_executor.cpp:176) 257[Y0-0000000000000000] [lt=8] invalid tg id BACKTRACE:0x90a3c0e 0x900348b 0x24c2cfb 0x24c03b5 0x625a2f6 0x5ef31c0 0x65e2a4f 0x87001af 0x8701abd 0x24c1415 0x7f20177b9493 0x24c00ee 

ger destroyed
[2021-06-16 03:45:26.595502] WARN  [SERVER] destroy (ob_server.cpp:413) [332][0][Y0-0000000000000000] [lt=12] destroy observer end
[2021-06-16 03:45:26.595527] ERROR [SERVER] main (main.cpp:485) [332][0][Y0-0000000000000000] [lt=20] observer init fail(ret=-4147) BACKTRACE:0x90a3c0e 0x900348b 0x24c413f 0x24c3106 0x24c166e 0x7f35af0d5493 0x24c00ee

~~~

**Comment by frf12** [comment]
memory_limit cannot be less than 8G

**Comment by watchpoints** [comment]
> memory_limit cannot be less than 8G

1. why must be  memory_limit cannot be less than 8G 。this 

DEF_CAP_WITH_CHECKER(memory_limit, OB_CLUSTER_PARAMETER, "0", common::ObConfigMemoryLimitChecker, "[0M,)",
    "the size of the memory reserved for internal use(for testing purpose). Range: [0M,)",

**Comment by frf12** [comment]
see this [issue](https://github.com/oceanbase/oceanbase/issues/97#issuecomment-859327237)

**Comment by watchpoints** [comment]
There is inner restriction that memory_limit should be [8G, ).

Documents and parameter description are wrong, and we will fix this later.

For your question, set memory_limit to 8G may solve the problem.

Thank you very much for your feedback
