### ISSUE TITLE
[feat.]: Cloud Native

### ISSUE THREAD

**Issue by ChenpiDog** [oceanbase/oceanbase#1082]
### Please check the issue list for the same feature first

- [X] Please checked issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### A full description of the feature and provide some example if the same feature exists in other products, such as mysql

```markdown
It is recommended to support cloud-native deployment and evolve towards cloud-native architecture, like PolarDB-X.
```

**Comment by longdafeng** [comment]
今天云上的产品, 其中有一半的数据库产品号称自己是云原生. 

云原生的概念起源于K8S, 后来被各大云厂商在各种产品中宣称自己产品是云原生, 很多时候, 太多的产品反而让用户真正不能理解什么是云原生. 

今天去看各种云产品和各种云原生产品, 再回归到字面上的理解 “非常适合云的产品”,   我们再往下深究一层 什么是 “适合云的产品”, 我想今天会各种概念会回归到一个根本性的需求 “极致弹性”. 


今天去看“极致弹性” 这件事情, 我个人比较中意的3个架构是
OceanBase, Auroa, Polar-for-MySQL, 这3款产品有着不错的弹性架构设计

OceanBase 的弹性在于:
1. 多租户的设计, 在一套集群上任意调整租户的资源量, 这种设计让业务方很快就可以适应业务的增长. 
2. 集群的任意伸缩, 比如最新的4.x  单机分布式一体化, 可以从单机扩容到多机, 小集群可以扩容到大集群. 

Auroa & Polar-for-MySQL 的弹性在于:
1. 使用共享存储和计算层的快速升降级, 将数据存储在一个分布式文件系统或者storage service, 然后在计算层可以快速弹性升降级. 


不知道, 有没有看11月4号polarx 的云栖大会分享, polarx 提出“集中式分布式一体化”设计和多租户, 而这些以前是没有的, 不是很清楚polarx 是不是在借鉴ob, 感觉业界向OB 这个方向靠拢的反而更多. 

中间件 + 底层数据库的这种架构, 在解决弹性这个问题上, 会遇到很多棘手的问题: 
1. 底层数据如何做rehash
3. 计算层如何保障多机均衡
4. 事务如何保障一致性, 并且可以支撑更高的并发和更大的事务. 
这些问题很多都难解决, 有些系统解决的并不是特别好. 

以上个人观点, 不代表官方.
