### ISSUE TITLE
[Bug]: 写入varbinary字段时校验字符集

### ISSUE THREAD

**Issue by beifangxiuwhx** [oceanbase/oceanbase#1088]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- 3.1.4版本
- 任意环境均可复现
```

### Fast Reproduce Steps(Required)

创建utf8mb4的表格，包含varbinary字段

写入GBK编码汉字

### Actual Behavior

<img width="653" alt="image" src="https://user-images.githubusercontent.com/17411129/193187692-3ae5b77b-9768-42aa-b8e2-6b6f9b9d3f5d.png">

### Expected Behavior

varbinary不应该校验字符集

### other information

提了个PR https://github.com/oceanbase/oceanbase/pull/1086

请审议

**Comment by akaError** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/97499944/193195802-39a60566-b27a-4988-8efa-3c91a6818518.png">
你好，目前我这边来看是正常的， 其实你建utf8mb4 就是用的 utf8编码,和汉字或说gbk编码是没有关系的，你上面的情况可能与你的环境有关
<img width="517" alt="image" src="https://user-images.githubusercontent.com/97499944/193195983-34b71526-2a72-40d6-92f3-cd2149af3ae4.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/97499944/193196043-381c35a1-8f07-43bb-af92-1999abe42044.png">
上面我给了'憧'字的utf8和gbk编码，下面我给出E688的utf8和 gbk表示, 其中E688不是一个合规的utf8编码表示，并不是说utf8不能表示憧的，而是传到数据库的编码就不应该是 E688
<img width="508" alt="image" src="https://user-images.githubusercontent.com/97499944/193196130-f40ab927-a204-47a9-90a1-5e5e50d20ff6.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/97499944/193196143-e996a7f8-b82e-4c17-9624-effca155ad02.png">

另外注意到你的sql是`insert into t1 values ('憧)` ，应该是`insert into t1 values ('憧')` ,憧的右边少了一个标点

**Comment by beifangxiuwhx** [comment]
你好，问题可能没表述清楚，这个问题的出处就是对错误编码的处理，mysql是可以写入成功的，但是OB是会按出错处理。而我们的业务由于上游的问题有很多这类的数据，导致业务无法切过来。

**Comment by beifangxiuwhx** [comment]
对于varbinary来说，数据库不能因为E688不是utf8编码而拒绝写入

**Comment by beifangxiuwhx** [comment]
> <img alt="image" width="482" src="https://user-images.githubusercontent.com/97499944/193195802-39a60566-b27a-4988-8efa-3c91a6818518.png">
> 
> 你好，目前我这边来看是正常的， 其实你建utf8mb4 就是用的 utf8编码,和汉字或说gbk编码是没有关系的，你上面的情况可能与你的环境有关
> <img alt="image" width="517" src="https://user-images.githubusercontent.com/97499944/193195983-34b71526-2a72-40d6-92f3-cd2149af3ae4.png">
> 
> <img alt="image" width="519" src="https://user-images.githubusercontent.com/97499944/193196043-381c35a1-8f07-43bb-af92-1999abe42044.png">
> 
> 上面我给了'憧'字的utf8和gbk编码，下面我给出E688的utf8和 gbk表示, 其中E688不是一个合规的utf8编码表示，并不是说utf8不能表示憧的，而是传到数据库的编码就不应该是 E688
> <img alt="image" width="508" src="https://user-images.githubusercontent.com/97499944/193196130-f40ab927-a204-47a9-90a1-5e5e50d20ff6.png">
> 
> <img alt="image" width="511" src="https://user-images.githubusercontent.com/97499944/193196143-e996a7f8-b82e-4c17-9624-effca155ad02.png">
> 
> 另外注意到你的sql是`insert into t1 values ('憧)` ，应该是`insert into t1 values ('憧')` ,憧的右边少了一个标点

少了标点是因为终端的字符集不是GBK，显示问题

**Comment by beifangxiuwhx** [comment]
另外你的测试复现步骤是不对的，请把终端字符集调整正确

![img_v2_5c1e7e3c-b402-4e04-8ee6-b83b83eb43bg](https://user-images.githubusercontent.com/17411129/193201359-cf589ac7-36a9-43c2-9542-671d0577b070.jpg)

**Comment by beifangxiuwhx** [comment]
> <img alt="image" width="482" src="https://user-images.githubusercontent.com/97499944/193195802-39a60566-b27a-4988-8efa-3c91a6818518.png">
> 
> 你好，目前我这边来看是正常的， 其实你建utf8mb4 就是用的 utf8编码,和汉字或说gbk编码是没有关系的，你上面的情况可能与你的环境有关
> <img alt="image" width="517" src="https://user-images.githubusercontent.com/97499944/193195983-34b71526-2a72-40d6-92f3-cd2149af3ae4.png">
> 
> <img alt="image" width="519" src="https://user-images.githubusercontent.com/97499944/193196043-381c35a1-8f07-43bb-af92-1999abe42044.png">
> 
> 上面我给了'憧'字的utf8和gbk编码，下面我给出E688的utf8和 gbk表示, 其中E688不是一个合规的utf8编码表示，并不是说utf8不能表示憧的，而是传到数据库的编码就不应该是 E688
> <img alt="image" width="508" src="https://user-images.githubusercontent.com/97499944/193196130-f40ab927-a204-47a9-90a1-5e5e50d20ff6.png">
> 
> <img alt="image" width="511" src="https://user-images.githubusercontent.com/97499944/193196143-e996a7f8-b82e-4c17-9624-effca155ad02.png">
> 
> 另外注意到你的sql是`insert into t1 values ('憧)` ，应该是`insert into t1 values ('憧')` ,憧的右边少了一个标点

你的测试复现步骤是不对的，请把终端字符集调整正确，按照如图所示复现

![img_v2_5c1e7e3c-b402-4e04-8ee6-b83b83eb43bg](https://user-images.githubusercontent.com/17411129/193201886-625ddcdd-4e53-40a3-a76c-d268b7ba2ac9.jpg)

**Comment by hnwyllmm** [comment]
![1](https://user-images.githubusercontent.com/5187215/193203488-74050ba7-c315-4333-bf3f-165defa3efd6.png)


![2](https://user-images.githubusercontent.com/5187215/193203427-9087f220-e0ed-44c4-84c1-724608cda02d.png)



设置了终端配置，没有重现。除了终端LANG相关的配置，还有其它的配置信息吗？

**Comment by hnwyllmm** [comment]
除了LANG和LC_ALL，你的终端工具有没有调整编码？比如我的iterm 配置了gbk编码
![3](https://user-images.githubusercontent.com/5187215/193203714-fb001ac1-3520-4186-9c7d-45ecd3d114f8.png)

**Comment by beifangxiuwhx** [comment]
> 除了LANG和LC_ALL，你的终端工具有没有调整编码？比如我的iterm 配置了gbk编码 ![3](https://user-images.githubusercontent.com/5187215/193203714-fb001ac1-3520-4186-9c7d-45ecd3d114f8.png)

我的是配了的，你的版本和我一样吗

**Comment by beifangxiuwhx** [comment]
请把你的结果hex一下看是不是gbk编码

**Comment by beifangxiuwhx** [comment]
> <img alt="image" width="635" src="https://user-images.githubusercontent.com/5187215/193205909-9e954027-ccd3-4292-bcf4-7c3d2a2e23e8.png">
> 
> 可以重现了

好的，解决方法可以考虑下相关 PR，我们自己大概测了下没啥问题，或者有更好的解决方法也行。请审议
