### ISSUE TITLE
是否支持arm平台？？

### ISSUE THREAD

**Issue by zhangshaoning1** [oceanbase/oceanbase#109]
**我在aarch64平台部署oceanbase遇到以下问题：**
(1)官方只提供x86架构的二进制和编译指导，没有提供arm架构的二进制
(2)源码编译oceanbase，发现依赖的gcc版本较低(gcc-5.2)，并且没有aarch64的二进制
(3)手动编译gcc-5.2，出现大量源码级别的报错，不好解决
(4)使用高版本的(gcc-7.3和gcc-8.3)直接编译oceanbase，出现大量不支持的编译选项

**所以请教下各位大佬，有没有人在arm平台成功适配过oceanbase，或者说oceanbase是否支持arm平台？**

**Comment by MizuhaHimuraki** [comment]
Currently, OceanBase Community Edition does not support building or deployment on the aarch64 platform. We will make it later.

**Comment by zhangshaoning1** [comment]
> Currently, OceanBase Community Edition does not support building or deployment on the aarch64 platform. We will make it later.

Ok, got it, thank you very much～

**Comment by LINxiansheng** [comment]
We support the arm now.
