### ISSUE TITLE
[Question]: springboot独立的报表项目，要求所有访问对只读副本操作

### ISSUE THREAD

**Issue by lbj812** [oceanbase/oceanbase#1091]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

springboot独立的报表项目，要求所有访问对只读副本操作。
如何从会话级别设置设置  ob_read_consistency 变量。
或者整个项目如何设置  ob_read_consistency？

**Comment by zhangdiaxss** [comment]
Refer to the document [弱一致性读](https://www.oceanbase.com/docs/community-observer-cn-10000000000449516)

**Comment by lbj812** [comment]
> Refer to the document [弱一致性读](https://www.oceanbase.com/docs/community-observer-cn-10000000000449516) [读写分离](https://www.oceanbase.com/docs/community-observer-cn-10000000000450647)

具体到 springboot代码层面，如何实现

**Comment by longdafeng** [comment]
2个步骤:
1. 将你的数据库配置成为 “读写分离” 架构, 参考文档 [读写分离](https://www.oceanbase.com/docs/community-observer-cn-10000000000450647)

**Comment by longdafeng** [comment]
Close this issue, if you have any other question, please feel free to reopen this issue and ask. 

We prefer to ask question in English in Github, if you want to ask in Chinese, please ask your question in ask.oceanbase.com.

Thanks
