### ISSUE TITLE
[feat.]: resource_hard_limit设置超卖后所有资源都超卖了，希望能分资源控制超卖

### ISSUE THREAD

**Issue by lenmore** [oceanbase/oceanbase#1099]
### Please check the issue list for the same feature first

- [X] Please checked issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### A full description of the feature and provide some example if the same feature exists in other products, such as mysql

```markdown
当设置 resource_hard_limit=200 后， __all_virtual_server_stat 里看到cpu_total/mem_total/disk_total都翻倍了，也就是超卖了。
但是一般超卖CPU是相对安全的，超卖内存、磁盘就比较危险了。
测试过程中也遇到过超卖内存导致的无法分配内存的报错。

所以建议能够分资源控制超卖，或者限制仅CPU可以超卖。
```

**Comment by askdb** [comment]
OceanBase 4.0 里已经不支持内存的超卖，仅支持cpu的超卖。

**Comment by lenmore** [comment]
谢谢回复，期待4.0早日发布。
