### ISSUE TITLE
[Question]: how to set ide with clangd or ccls

### ISSUE THREAD

**Issue by luooofan** [oceanbase/oceanbase#1101]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

I can't set ide correctly with clangd or ccls according to [how_to_set_ide_with_ccls · oceanbase/oceanbase Wiki](https://github.com/oceanbase/oceanbase/wiki/how_to_set_ide_with_ccls)

Is there a more detailed wiki/artical/blog?

The behavior of vscode with ccls:
![image](https://user-images.githubusercontent.com/46896167/198880564-1d2d56b4-cc55-4dde-97a0-7b749e36fdf9.png)
![image](https://user-images.githubusercontent.com/46896167/198880476-a699be19-12a3-4ff1-b7de-cebec390d80f.png)

The behavior of vscode with clangd:
![image](https://user-images.githubusercontent.com/46896167/198880681-8fa82deb-7233-49af-8a37-22a154ae7581.png)
![image](https://user-images.githubusercontent.com/46896167/198880758-e394459f-6982-476d-ab78-22b76049fc49.png)

The compile_commands.json is generated by command `bash build.sh debug_no_unity --init -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

**Comment by LINxiansheng** [comment]
First have a try to set the ide clang config to the download clang in oceanbase folder(deps folder)

**Comment by luooofan** [comment]
I think the downloaded clang tools has already been used.
![image](https://user-images.githubusercontent.com/46896167/198921679-a2a84bf8-a929-4d80-9c39-799057b308a2.png)
![image](https://user-images.githubusercontent.com/46896167/198922276-d1a81da1-6d49-48cd-b7ae-87708036ffa4.png)
