### ISSUE TITLE
[Bug]: #!/bin/sh 某些系统下sh并不是bash的软连接，导致编译报错

### ISSUE THREAD

**Issue by FrankXMX** [oceanbase/oceanbase#1105]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Fast Reproduce Steps(Required)

./build.sh --init --make

### Actual Behavior

./build.sh: 13: Syntax error: "(" unexpected

### other information

$ ll /bin/sh
lrwxrwxrwx 1 root root 4 Aug  8 10:09 /bin/sh -> dash*
在Ubuntu 22.04.1 LTS下 sh是dash的软连接，而不是bash的软连接

**Comment by hnwyllmm** [comment]
有意思。后面测试一把看

**Comment by LINxiansheng** [comment]
It is right and we will fix it as soon as possible.
