### ISSUE TITLE
[Bug]: left info from information_schema.PROCESSLIST return Invalid argument

### ISSUE THREAD

**Issue by vzong** [oceanbase/oceanbase#1109]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
Server version:		5.7.25 OceanBase 3.1.4 (r10000092022071511-b4bfa011ceaef428782dcb65ae89190c40b78c2f) (Built Jul 15 2022 11:45:14)
```

### Fast Reproduce Steps(Required)

mysql> select left(INFO,10000) INFO from information_schema.PROCESSLIST where info is not null;
ERROR 1210 (HY000): Invalid argument
mysql> select INFO from information_schema.PROCESSLIST where info is not null;
--some lines unicode  are garbled--
20 rows in set (0.02 sec)

### Actual Behavior

ERROR 1210 (HY000): Invalid argument

**Comment by vzong** [comment]
oceanbase log:

[2022-11-08 15:26:08.812711] WARN  [SERVER] process (obmp_query.cpp:291) [18886][2310][YB420A6DD311-0005E541469C5C50] [lt=6] [dc=0] fail execute sql(sql_id="", sql=select ID,USER,HOST,DB,COMMAND,TIME,STATE,left(INFO,10000) INFO,date_format(now(),'%Y-%m-%d %H:%i:%s') gettime
    from information_schema.PROCESSLIST
    where USER not in ('usvr_replication','system user')
    and DB not in ('oceanbase')
    and INFO not like '%PROCESSLIST%'
    order by TIME desc limit 30;
    , sessid=3222093094, ret=-4002, ret="OB_INVALID_ARGUMENT", need_disconnect=false)

**Comment by gys-git** [comment]
oceanbase-4.0 already fixed
