### ISSUE TITLE
社区版本中表组支持二级分区吗？

### ISSUE THREAD

**Issue by chtallcn** [oceanbase/oceanbase#111]
我使用如下命令创建一个新的二级分区表组，提示：Error : Not implemented feature 。
不知道是社区版本不支持二级分区的表组，还是我创建表组的语法有问题呢？

CREATE TABLEGROUP t_order_group PARTITION by RANGE SUBPARTITION by RANGE SUBPARTITION TEMPLATE (
    subpartition sub01 values less than (1),
    subpartition sub02 values less than (2),
    subpartition sub03 values less than (3),
    subpartition sub04 values less than (4),
    subpartition sub05 values less than (5),
    subpartition sub06 values less than (6),
    subpartition sub07 values less than (7),
    subpartition sub08 values less than (8),
    subpartition sub09 values less than (9),
    subpartition sub10 values less than (10),
    subpartition sub11 values less than (11),
    subpartition sub12 values less than (12),
    subpartition sub13 values less than (13),
    subpartition sub14 values less than (14),
    subpartition sub15 values less than (15),
    subpartition sub16 values less than (16)
)
(
    partition p2019 values less than (UNIX_TIMESTAMP('2020-01-01 00:00:00')),
    partition p2020 values less than (UNIX_TIMESTAMP('2021-01-01 00:00:00')),
    partition p2021 values less than (UNIX_TIMESTAMP('2022-01-01 00:00:00')),
    partition p2022 values less than (UNIX_TIMESTAMP('2023-01-01 00:00:00')),
    partition p2023 values less than (UNIX_TIMESTAMP('2024-01-01 00:00:00')),
    partition p2024 values less than (UNIX_TIMESTAMP('2025-01-01 00:00:00')),
    partition p2025 values less than (UNIX_TIMESTAMP('2026-01-01 00:00:00')),
    partition p2026 values less than (UNIX_TIMESTAMP('2027-01-01 00:00:00'))
);

**Comment by LINxiansheng** [comment]
Thanks for your question.

Maybe the reason is that we did not support range-rangelist in the early version. 
Later we develop 227X table and we also do not support the table group.

As a reference.

**Comment by longdafeng** [comment]
@shendachuan  Could you please help to answer this question?

**Comment by shendachuan** [comment]
Partition and subpartition by same type is not supported now.
