### ISSUE TITLE
[Bug]: Duplicate function calling in multi-tenant module?

### ISSUE THREAD

**Issue by lmsreborn** [oceanbase/oceanbase#1110]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

Code here:
https://github.com/oceanbase/oceanbase/blob/master/src/observer/omt/ob_multi_tenant.cpp#L831-L834

Why calling ```tenant->update_thread_cnt``` twice? Is this a bug?

**Comment by caifeizhi** [comment]
yes, it is a bug，maybe caused by code conflict;
can you fix this bug?

**Comment by hnwyllmm** [comment]
close as fixed
