### ISSUE TITLE
[Bug]: Ubuntu 22.04 build error

### ISSUE THREAD

**Issue by jojo195** [oceanbase/oceanbase#1112]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- Ubuntu 22.04 LTS
- g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
- glibc ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
```

### Fast Reproduce Steps(Required)

I have taken steps according to https://github.com/oceanbase/oceanbase/wiki/Build-from-source-code
When I execute this instruction
`bash build.sh debug --init --make -j8`
It seems link error occurred. 
Does Oceanbase support Ubuntu 22.04 environment? How can I fix it? What is the proper glibc version that Oceanbase need? Or, how can I explicitly specify a glibc version in the source code?

### Actual Behavior

[ 97%] Built target obcdc_static
[ 97%] Linking CXX shared library libobcdc.so
ld.lld: error: undefined symbol: pthread_mutexattr_setrobust_np
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_create) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> did you mean: pthread_mutexattr_setrobust_np@GLIBC_2.4
>>> defined in: /lib/x86_64-linux-gnu/libc.so.6

ld.lld: error: undefined symbol: pthread_mutex_consistent_np
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_acquire) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_tryacquire) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> did you mean: pthread_mutex_consistent_np@GLIBC_2.4
>>> defined in: /lib/x86_64-linux-gnu/libc.so.6

ld.lld: error: undefined symbol: sys_siglist
>>> referenced by signals.c
>>>               signals.o:(apr_signal_description_get) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a

ld.lld: error: undefined symbol: pthread_yield
>>> referenced by thread.c
>>>               thread.o:(apr_thread_yield) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/observer/CMakeFiles/observer.dir/build.make:154: src/observer/observer] Error 1
make[1]: *** [CMakeFiles/Makefile2:10153: src/observer/CMakeFiles/observer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target obcdc
make: *** [Makefile:166: all] Error 2

### Expected Behavior

Generate observer executable file.

**Comment by PinkDoc** [comment]
### Environment
```
- Ubuntu 22.04 LTS
- g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
- glibc ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
```
### Steps
After cloning the repository, run this command：
```
bash build.sh --init --make
```
cmake error:

```
Check for working CXX compiler: /home/pink/projects/database/ob-race/2022_ob_competition/deps/3rd/usr/local/oceanbase/devtools/bin/clang++ - broken
CMake Error at deps/3rd/usr/local/oceanbase/devtools/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/home/pink/projects/database/ob-race/2022_ob_competition/deps/3rd/usr/local/oceanbase/devtools/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pink/projects/database/ob-race/2022_ob_competition/build_debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_a1f32/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_a1f32.dir/build.make CMakeFiles/cmTC_a1f32.dir/build

```

**Comment by BiteTheDDDDt** [comment]
It looks like libapr-1.65 cannot be compiled under higher version of glibc

**Comment by BiteTheDDDDt** [comment]
glibc2.31 or lower may can work, not sure.

**Comment by caifeizhi** [comment]
pthread_yield is deprecated since glibc 2.34:https://man7.org/linux/man-pages/man3/pthread_yield.3.html

**Comment by jty20120310** [comment]
> pthread_yield is deprecated since glibc 2.34:https://man7.org/linux/man-pages/man3/pthread_yield.3.html

Thank you for your reply. 

Therefore, is there's a easily accessible method to solve this problem? 

I would appreciate if you could recommend some practical method.

**Comment by BiteTheDDDDt** [comment]
> 

I think you can try to build a glibc2.31, I tried build OB with 2.31 and work well.

**Comment by dongdxf** [comment]
a temporary solution on aarch64:

1. download apr-1.7.2 from https://dlcdn.apache.org//apr/apr-1.7.2.tar.gz
2. decompress && configure && make install
3. copy libapr-1.a to deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
4. you will get "error: undefined symbol: __aarch64_ldadd4_acq_rel"、"error: undefined symbol: __aarch64_cas4_acq_rel"、"error: undefined symbol: __aarch64_swp4_acq_rel"、"error: undefined symbol: __aarch64_cas8_acq_rel"、"error: undefined symbol: __aarch64_swp8_acq_rel"
5. copy /lib/gcc/aarch64-linux-gnu/9/libgcc.a to deps/3rd/usr/local/oceanbase/devtools/lib/gcc/aarch64-redhat-linux/9/libgcc.a

**Comment by YVEF** [comment]
It would be great if someone knows when the apr can be upgraded to the new vesion?
Thanks

**Comment by hnwyllmm** [comment]
> It would be great if someone knows when the apr can be upgraded to the new vesion? Thanks

Do you mean upgrade apr's version to 1.7.0?
Or publish a apr library in el9? (It's in progress now)

**Comment by YVEF** [comment]
> > It would be great if someone knows when the apr can be upgraded to the new vesion? Thanks
> 
> Do you mean upgrade apr's version to 1.7.0? Or publish a apr library in el9? (It's in progress now)

Whichever is possible. Thank you for the good news.

**Comment by caifeizhi** [comment]
fix in https://github.com/oceanbase/oceanbase/commit/791ec736a10d3128ecd3eb500d31f3616b98bf59

**Comment by yujiabin123** [comment]
I have a new question.
I use temporary solution. download  apr-1.7.2,and decompress && configure && make install  and replace the libapr-1.a.
but When I recompile, I get the following error.

**Comment by yujiabin123** [comment]
ld.lld: error: can't create dynamic relocation R_AARCH64_ABS64 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in ../../../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a(proc_mutex.o)
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(mutex_fcntl_methods) in archive ../../../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a

**Comment by hnwyllmm** [comment]
You don't need compile the apr by yourself. Please fetch the latest code and recompile again. It can work on Ubuntu 22.04 now.

**Comment by yujiabin123** [comment]
OK, i will try it again. but my os is openEuler 20.03

**Comment by hnwyllmm** [comment]
openEuler is not in the check list. But it's easy to fix. Please check [this file](https://github.com/oceanbase/oceanbase/blob/develop/deps/init/dep_create.sh) and you can find the version check logic easily.

**Comment by yujiabin123** [comment]
I fetch the latest code and compile. but still canot success. :)
ld.lld: error: undefined symbol: pthread_mutexattr_setrobust_np
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_create) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> did you mean: pthread_mutexattr_setrobust_np@GLIBC_2.17
>>> defined in: /lib64/libc.so.6

**Comment by yujiabin123** [comment]
I did it, I modify this file ,and add this.

  elif [[ "${OS_ARCH}x" == "aarch64x" ]]; then
    case "$ID" in
      openEuler)
        OS_RELEASE=7 && return
        ;;
      alios)
        version_ge "8.0" && compat_centos8 && return
        version_ge "7.0" && compat_centos7 && return
        ;;
      centos)

**Comment by yujiabin123** [comment]
Maybe should use OS_RELEASE=9?

**Comment by hnwyllmm** [comment]
Yes, 9 is the right version. refer to `compat_centos9`.

**Comment by yujiabin123** [comment]
OK ,I will try it again.

**Comment by hnwyllmm** [comment]
> OK ,I will try it again.

Hi, how was it going?

**Comment by yujiabin123** [comment]
Thank you for your attention.
I changed OS_RELEASE=9, and compiled successfully.  ：）
