### ISSUE TITLE
'CAST(COALESCE(null, -99) AS UNSIGNED)' Error

### ISSUE THREAD

**Issue by SilvaXiang** [oceanbase/oceanbase#112]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

1.create table
`CREATE TABLE a(b BIGINT UNSIGNED);`
2.insert the null value
`INSERT INTO a(b) VALUES(NULL);`
3.query the data
`select CAST(COALESCE(null, -99) AS UNSIGNED);`
![image](https://user-images.githubusercontent.com/22973642/122354739-df5cd300-cf83-11eb-80f2-0020c06d7f67.png)

but I change the sql to:
`select CAST(COALESCE(a.b, -99) AS UNSIGNED) from a;`
the result is:
![image](https://user-images.githubusercontent.com/22973642/122354797-ebe12b80-cf83-11eb-8b11-24dd6f5e8040.png)

this result is different from mysql 8.0

**Your Environments (__must be provided__)**

* OS: `Linux 10-24-14-128 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Compliler: `g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1.create table
`CREATE TABLE a(b BIGINT UNSIGNED);`
2.insert the null value
`INSERT INTO a(b) VALUES(NULL);`
3.query the data
`select CAST(COALESCE(null, -99) AS UNSIGNED);`
![image](https://user-images.githubusercontent.com/22973642/122354739-df5cd300-cf83-11eb-80f2-0020c06d7f67.png)

but I change the sql to:
`select CAST(COALESCE(a.b, -99) AS UNSIGNED) from a;`
the result is:
![image](https://user-images.githubusercontent.com/22973642/122354797-ebe12b80-cf83-11eb-8b11-24dd6f5e8040.png)

this result is different from mysql 8.0

**Expected behavior**

the ideal result of the last query is:`18446744073709551517`

**Comment by shendachuan** [comment]
Currently OceanBase is compatible with Mysql 5.6.
```
mysql> select CAST(COALESCE(a.b, -99) AS UNSIGNED) from a;
+--------------------------------------+
| CAST(COALESCE(a.b, -99) AS UNSIGNED) |
+--------------------------------------+
|                                    0 |
+--------------------------------------+
```
The difference may result from result type of COALESCE(NULL, -99) and COALESCE(a.b, -99) are different.
mysql> select cast(cast(-99 as signed) as unsigned);
```
+---------------------------------------+
| cast(cast(-99 as signed) as unsigned) |
+---------------------------------------+
|                  18446744073709551517 |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> select cast(cast(-99 as decimal) as unsigned);
+----------------------------------------+
| cast(cast(-99 as decimal) as unsigned) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

**Comment by longdafeng** [comment]
@SilvaXiang  Right now, OceanBase is compatiable with 5.6, it will be compatiable in the September of this year. 

We start to work for supporting MySQL 8.0 in the next year. 
If you want to upgrade from MySQL 8.0 to OceanBase, maybe you need check the difference between MySQL 5.7 and 8.0.
