### ISSUE TITLE
[feat.]: load data丢失数据，没有错误提示

### ISSUE THREAD

**Issue by zxbange** [oceanbase/oceanbase#1121]
### Please check the issue list for the same feature first

- [X] Please checked issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### A full description of the feature and provide some example if the same feature exists in other products, such as mysql

```markdown
1、load data发现数据有丢失，但是没有报错
2、查看load的错误日志，没有给出明确的错误提示
```

### other information

1、load data发现数据有丢失，但是没有报错，实际需要写入119994608条，实际写入119993308条
![image](https://user-images.githubusercontent.com/26746322/202644177-360f8a15-3540-4a97-992d-9589a56f9690.png)
2、查看load错误日志，没有明确的错误提示，无法判断因为什么原因导致部分数据导入不进去
![image](https://user-images.githubusercontent.com/26746322/202644601-6d9f8daa-ed99-42f9-9e00-421fc6417221.png)
3、建议有明确提示哪些行数据没有写进去，因为什么原因

**Comment by hnwyllmm** [comment]
fixed
