### ISSUE TITLE
observer need bootstarp x

### ISSUE THREAD

**Issue by coding01000** [oceanbase/oceanbase#116]
When I tried to restart the observer, the following error was reported:
> observer obd cluster restart lo
Get local repositories and plugins ok
Start observer ok
observer program health check ok
Connect to observer ok
observer need bootstarp x

The configuration is as follows：
>oceanbase-ce:
  tag: myob
  servers:
    # Please don't use hostname, only IP can be supported
    - 127.0.0.1
  global:
    home_path: /data/observer
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: lo
    mysql_port: 2883
    rpc_port: 2882
    zone: lo_z1
    # if current hardware's memory capacity is smaller than 50G, please use the setting of "mini-single-example.yaml" and do a small adjustment.
    memory_limit: 100G
    datafile_disk_percentage: 40
    cluster_id: 1

But ob still started successfully

**Comment by jw-guo** [comment]
During restart, observer can not provide services. Therefore, if obd finds that the observer is not ready after a certain time, a failure result will be returned. However, this does not indicate that the observer fails to start. Usually, observer can provide services after restart successfully.

**Comment by coding01000** [comment]
> During restart, observer can not provide services. Therefore, if obd finds that the observer is not ready after a certain time, a failure result will be returned. However, this does not indicate that the observer fails to start. Usually, observer can provide services after restart successfully.

thanks
