### ISSUE TITLE
[Question]: How to set port of prometheus by obd

### ISSUE THREAD

**Issue by FrankXMX** [oceanbase/oceanbase#1184]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

Prometheus default port is 9090，how to set port 9999 by obd?

**Comment by wayyoungboy** [comment]
you can change prometheus's port.
the demo doc about  port: https://github.com/oceanbase/obdeploy/blob/master/example/prometheus/prometheus-only-example.yaml

**Comment by FrankXMX** [comment]
Got it,thanks.
