### ISSUE TITLE
[Question]: Terminal process after killing

### ISSUE THREAD

**Issue by zrcx123** [oceanbase/oceanbase#1185]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

【Product Name】oceanbase-cs

【Product Version】3.1

【Problem Description】

show proxysession attribute 17;

server_sessid 3221938678

show full process list;

Id 3221938678

Are the server_sessid column in the result of "show proxysession attribute 17" and the id column in the result of "show full processlist" the same thing?

 If it is the same thing, multiple explanations are given before and after the document, can you give a definite and easy-to-understand explanation:

   OBServer session ID number,

   the client ID of the backend connection,

   The client connection id on the observer

**Comment by longdafeng** [comment]
Please refer to these two documents
[如何管理 OceanBase 数据库连接](https://www.oceanbase.com/docs/community-tutorials-cn-10000000000012280)
[展示 Session 详细状态](https://www.oceanbase.com/docs/community-observer-cn-10000000000449472)
