### ISSUE TITLE
can't grant privilege to user

### ISSUE THREAD

**Issue by luyiqu** [oceanbase/oceanbase#120]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**
when i grant all privilege to root, but it doesn't work.  how can i to deal with it?
![image](https://user-images.githubusercontent.com/42026475/123534319-f4d5b800-d74e-11eb-8adc-b20224ef0b6c.png)

**Comment by simonjoylet** [comment]
which behavior is unexpected? please provide more details.

**Comment by luyiqu** [comment]
I want to load data infile, but I find that access denied because the file_priv is N. Therefore, I want to grant root with all privilege to solve it ,but I find that it doesn't change any privilege of root after I grant all privileges on root.
Take a look at picture, after i grant the privileges, the privileges such as  file_priv,reload_priv are still N.

**Comment by simonjoylet** [comment]
try this:
`set global secure_file_priv = "";`
for more info, please refer to this doc: [data-loading-technology-of-oceanbase](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/data-loading-technology-of-oceanbase)

**Comment by luyiqu** [comment]
![image](https://user-images.githubusercontent.com/42026475/123580806-1f864600-d80d-11eb-9db7-2fc8e8384817.png)
I try it, following the doc, unfortunately, it still doesn't work

**Comment by wjhh2008** [comment]
> ![image](https://user-images.githubusercontent.com/42026475/123580806-1f864600-d80d-11eb-9db7-2fc8e8384817.png)
> I try it, following the doc, unfortunately, it still doesn't work

It might be a bug of view mysql.user. The file_priv may be already granted if the "grant file" statement is executed successfully. It can be verified by checking the value of file_priv in meta table:
select priv_file from oceanbase.__all_user where user_name = 'root';

**Comment by luyiqu** [comment]
It works ! Thanks for your time and attention.
