### ISSUE TITLE
[Question]: Access denied for user 'root'@'xxx.xxx.xxx.xxx'

### ISSUE THREAD

**Issue by wapache** [oceanbase/oceanbase#1204]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

Oceanbase 4.0

use obd create an new Oceanbase cluster, and cerate new tenant
```
obd cluster tenant create obcluster1 -n test
```

use root@sys
```
obclient -h10.150.90.236 -uroot@sys -P2881 -p -A -c
```
can connect

use root@test
```
obclient -h10.150.90.236 -uroot@test -P2881 -p -A -c
Enter password:
ERROR 1045 (42000): Access denied for user 'root'@'xxx.xxx.xxx.xxx' (using password: YES)
```
failed.

why?

**Comment by zxbange** [comment]
try this :  obclient -h10.150.90.236 -uroot@test -P2881 -A -c , without -p

**Comment by wapache** [comment]
> try this : obclient -h10.150.90.236 -uroot@test -P2881 -A -c , without -p

[root@server1 oceanbase]# obclient -h10.150.90.236 -uroot@test -P2881 -A -c , without -p
obclient  Ver  Distrib 10.4.18-MariaDB, for Linux (x86_64) using readline 5.1
Copyright (c) 2000, 2018, OB Corporation Ab and others.

Usage: obclient [OPTIONS] [database]
... ...

**Comment by wapache** [comment]
> try this : obclient -h10.150.90.236 -uroot@test -P2881 -A -c

remove `-p` , it work.
