### ISSUE TITLE
错误提示单词拼写错误

### ISSUE THREAD

**Issue by rgyu** [oceanbase/oceanbase#121]
下面的错误提示中， observer need bootstarp.  这里bootstarp 应该是bootstrap. 
问题不大，只是看着难受，如果能改的话，最好还是改一下。

Start observer ok
observer program health check ok
Connect to observer ok
observer need bootstarp x
Start obproxy ok
obproxy program health check x
[WARN] failed to start aa.aa.aa.aa obproxy
[WARN] failed to start bb.bb.bb.bb obproxy
[WARN] failed to start bb.bb.bb.bb obproxy
[ERROR] obproxy start failed

下面的几处代码，用的也是bootstarp. 

Ob_basic_session_info.cpp (sql\session):940
// used for bootstarp, in which we can not get system variables from inner table.
int ObBasicSessionInfo::load_default_sys_variable(const bool print_info_log, const bool is_sys_tenant)
{
Ob_cluster_info_proxy.cpp (share):286
      LOG_WARN("get empty cluster info, maybe in bootstarp", K(ret));
      ret = OB_SUCCESS;
    } else {
Ob_root_service.cpp (rootserver):10688
      LOG_WARN("not allow to update table schema while not in bootstarp");
    } else if (OB_FAIL(
                   ddl_service_.get_tenant_schema_guard_with_version_in_inner_table(arg.tenant_id_, schema_guard))) {

**Comment by simonjoylet** [comment]
good catch!
would you please to provide some pull requests to correct this?

**Comment by raywill** [comment]
Thanks!

for all typos, I think that we will hold on for a while (may be one or two weeks), as we have a typo-checker on its way.

We will scan our code base and fix as much typos as we can. Let's do it in batch so that we don't have to waste too much time on this again and again.

**Comment by tycable** [comment]
nb, that's super great, typo checker!
