### ISSUE TITLE
how to use 'log_level' and 'ob_log_level '?

### ISSUE THREAD

**Issue by wxy-raaaa** [oceanbase/oceanbase#122]
How to use 'log_level' and 'ob_log_level'?
Please give some examples for all kinds of settings of 'log_level' and 'ob_log_level';
In this document, (https://open.oceanbase.com/docs/oceanbase-code-style-guide/oceanbase-code-style-guide/V3.1.0/log-specifications),I just can konw this thing ,but I can,t use it.
Please give some specific sql,thanks.

**Comment by simonjoylet** [comment]
logs are everywhere in the code of oceanbase.
take [src/storage/ob_partition_group.cpp](https://github.com/oceanbase/oceanbase/blob/master/src/storage/ob_partition_group.cpp) as an example.
line 118: `STORAGE_LOG(WARN, "component does not exist", "component name", cp_name);` means the `log_level` is `WARN` and the `log_module` is `STORAGE`.
line 191: `LOG_WARN("failed to do table scan", K(ret), "this", *this);` means the `log_level` is `WARN` and the `log_module` is defined by the macro `USING_LOG_PREFIX` which is at top of the file.

**Comment by wxy-raaaa** [comment]
I mean  ,how to set 'log_level' or 'ob_log_level' on the client by sql, I have tryed some sql,but always failed.

**Comment by simonjoylet** [comment]
there are some parameters to control log levels:
connect oceanbase with `root@sys` like `obclient -u root@sys -D oceanbase`
execute `show parameters like '%syslog%';` to check all these parameters.
for example, if you want to change the `log_level` to `WARN` on the cluster, execute `alter system set syslog_level = 'WARN';`

**Comment by wxy-raaaa** [comment]
Thanks a lot!
