### ISSUE TITLE
LOG_WARN单词拼写错误

### ISSUE THREAD

**Issue by vzong** [oceanbase/oceanbase#123]
下面的错误提示中，这里trunate  应该是truncate .

src/rootserver/ob_ddl_service.cpp : 7794
LOG_WARN("not support trunate table has materialized view", K(ret));

**Comment by raywill** [comment]
Thanks!

for all typos, I think that we will hold on for a while (may be one or two weeks), as we have a typo-checker on its way.

We will scan our code base and fix as much typos as we can.

**Comment by longdafeng** [comment]
Could you please raise one pull request for us.
