### ISSUE TITLE
When will 4.0 docker image be ready?

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#1238]
### Discussed in https://github.com/oceanbase/oceanbase/discussions/1103

<div type='discussions-op-text'>

<sup>Originally posted by **Lukiya** November  3, 2022</sup>
When will 4.0 docker image be ready?</div>

**Comment by hnwyllmm** [comment]
4.0 docker is ready now:
https://hub.docker.com/r/oceanbase/oceanbase-ce/tags
