### ISSUE TITLE
Create table failed while it is successful in mysql

### ISSUE THREAD

**Issue by zouyonghao** [oceanbase/oceanbase#127]
This bug is found by our fuzzing tool.

**Describe the bug (__must be provided__)**

Create table failed while it is successful in mysql

```
mysql> create table t_sa ( 
    -> c_mn INTEGER NOT NULL,
    -> c_d4i TEXT ,
    -> c_lngdt TEXT NOT NULL,
    -> c_c3v INTEGER ,
    -> primary key(c_c3v),
    -> unique(c_mn),
    -> check(1=1)
    -> );
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near 'check(1=1)
)' at line 8
```

**Your Environments (__must be provided__)**

* OS: Linux virtual 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: clang 11
* CPU:i7-8700K
* Commit id 2ef6e5e944182be844733f421ac2ab0066f938e0

**How To Reproduce(__must be provided__)**

```
create database abc;
use abc;
create table t_sa ( 
c_mn INTEGER NOT NULL,
c_d4i TEXT ,
c_lngdt TEXT NOT NULL,
c_c3v INTEGER ,
primary key(c_c3v),
unique(c_mn),
check(1=1)
);
```

**Expected behavior**

```
mysql> create table t_sa ( 
    -> c_mn INTEGER NOT NULL,
    -> c_d4i TEXT ,
    -> c_lngdt TEXT NOT NULL,
    -> c_c3v INTEGER ,
    -> primary key(c_c3v),
    -> unique(c_mn),
    -> check(1=1)
    -> );
Query OK, 0 rows affected (0.14 sec)
```

**Comment by shendachuan** [comment]
`
create database abc;
use abc;
create table t_sa ( 
c_mn INTEGER NOT NULL,
c_d4i TEXT ,
c_lngdt TEXT NOT NULL,
c_c3v INTEGER ,
primary key(c_c3v),
unique(c_mn),
constraint cst check(1=1)
);
`
OceanBase only supports check constraint with a name in syntax, but it will also cause a not_suppoted error.
OceanBase is compatible with Mysql 5.6, while check constraint is truly supported in Mysql 8.0.

**Comment by zouyonghao** [comment]
> ```
> create database abc;
> use abc;
> create table t_sa (   
> c_mn INTEGER NOT NULL,  
> c_d4i TEXT ,
> c_lngdt TEXT NOT NULL,
> c_c3v INTEGER ,
> primary key(c_c3v),
> unique(c_mn),
> constraint cst check(1=1)
> );
> ```
> 
> OceanBase only supports check constraint with a name in syntax, but it will also cause a not_suppoted error.
> OceanBase is compatible with Mysql 5.6, while check constraint is truly supported in Mysql 8.0.

I test it in MySQL 5.6 and the table is created.

**Comment by shendachuan** [comment]
> > ```
> > create database abc;
> > use abc;
> > create table t_sa (   
> > c_mn INTEGER NOT NULL,  
> > c_d4i TEXT ,
> > c_lngdt TEXT NOT NULL,
> > c_c3v INTEGER ,
> > primary key(c_c3v),
> > unique(c_mn),
> > constraint cst check(1=1)
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OceanBase only supports check constraint with a name in syntax, but it will also cause a not_suppoted error.
> > OceanBase is compatible with Mysql 5.6, while check constraint is truly supported in Mysql 8.0.
> 
> I test it in MySQL 5.6 and the table is created.

MySQL 5.6 only support check constraint syntactically, you can insert values that violate the constraint.
