### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [oceanbase/oceanbase#1277]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [allocer_t](https://github.com/oceanbase/oceanbase/blob/6af7f9ae79cd0ecbafd4b1b88e2886ccdba0c3be/deps/oblib/unittest/lib/hash/hash_benz.cpp#L58 "Destructor for allocer_t")
- [Wrapper](https://github.com/oceanbase/oceanbase/blob/6af7f9ae79cd0ecbafd4b1b88e2886ccdba0c3be/deps/oblib/src/lib/thread_local/ob_tsi_factory.h#L250 "Destructor for Wrapper")

**Comment by hnwyllmm** [comment]
Yes, you are right. But it is required in oceanbase:
https://github.com/oceanbase/oceanbase/blob/master/docs/coding_standard.md#57-function-parameters.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by hnwyllmm** [comment]
Thanks a lot. It looks interesting and I think there are many other useful tips.
I'll use the clang-tidy in another project first.
