### ISSUE TITLE
Does Oceanbase not support the foreach tag of mybatis: UNION ALL, and how to commit multiple sql statements like begin....end in oracle

### ISSUE THREAD

**Issue by KamSss** [oceanbase/oceanbase#128]
- OB version： 2.2.50

I try to commit multiple sql statements when i using the mybatis like:

`    
        
     <insert id="bulkInsertResource_oracle" parameterType="java.util.List" useGeneratedKeys="false">
        INSERT INTO ${prefix}ACT_GE_BYTEARRAY
        (
        ID_,
        REV_,
        NAME_,
        BYTES_,
        DEPLOYMENT_ID_,
        GENERATED_
        )
        <foreach collection="list" item="resource" index="index" separator="union all">
        (
            SELECT
            #{resource.id, jdbcType=VARCHAR},
            1,
            #{resource.name, jdbcType=VARCHAR},
            #{resource.bytes, jdbcType=BLOB},
            #{resource.deploymentId, jdbcType=VARCHAR},
            #{resource.generated, jdbcType=BOOLEAN}
            FROM DUAL
        )
        </foreach>
    </insert>`
and i got the error like:
![image](https://user-images.githubusercontent.com/37392012/123917058-f0123d80-d9b4-11eb-851f-ba17ed1de4ea.png)

So I changed the sql statement to:
`    

      <insert id="bulkInsertResource_oracle" parameterType="java.util.List">
        begin
        <foreach collection="list" item="resource" index="index" separator=";">
            INSERT INTO ${prefix}ACT_GE_BYTEARRAY
            (
            ID_,
            REV_,
            NAME_,
            BYTES_,
            DEPLOYMENT_ID_,
            GENERATED_
            )
            VALUES
            (
            #{resource.id, jdbcType=VARCHAR},
            1,
            #{resource.name, jdbcType=VARCHAR},
            #{resource.bytes, jdbcType=BLOB},
            #{resource.deploymentId, jdbcType=VARCHAR},
            #{resource.generated, jdbcType=BOOLEAN}
            )
        </foreach>
        ;end;
    </insert>`
and i got another error like:
![image](https://user-images.githubusercontent.com/37392012/123918048-0d93d700-d9b6-11eb-8196-af095b933f14.png)

**Comment by longdafeng** [comment]
@shenchai  could you please take a look at this issue?

**Comment by shenchai** [comment]
> * OB version： 2.2.50
> 
> I try to commit multiple sql statements when i using the mybatis like:
> 
> `
> 
> ```
>  <insert id="bulkInsertResource_oracle" parameterType="java.util.List" useGeneratedKeys="false">
>     INSERT INTO ${prefix}ACT_GE_BYTEARRAY
>     (
>     ID_,
>     REV_,
>     NAME_,
>     BYTES_,
>     DEPLOYMENT_ID_,
>     GENERATED_
>     )
>     <foreach collection="list" item="resource" index="index" separator="union all">
>     (
>         SELECT
>         #{resource.id, jdbcType=VARCHAR},
>         1,
>         #{resource.name, jdbcType=VARCHAR},
>         #{resource.bytes, jdbcType=BLOB},
>         #{resource.deploymentId, jdbcType=VARCHAR},
>         #{resource.generated, jdbcType=BOOLEAN}
>         FROM DUAL
>     )
>     </foreach>
> </insert>`
> ```
> 
> and i got the error like:
> ![image](https://user-images.githubusercontent.com/37392012/123917058-f0123d80-d9b4-11eb-851f-ba17ed1de4ea.png)
> 
> So I changed the sql statement to:
> `
> 
> ```
>   <insert id="bulkInsertResource_oracle" parameterType="java.util.List">
>     begin
>     <foreach collection="list" item="resource" index="index" separator=";">
>         INSERT INTO ${prefix}ACT_GE_BYTEARRAY
>         (
>         ID_,
>         REV_,
>         NAME_,
>         BYTES_,
>         DEPLOYMENT_ID_,
>         GENERATED_
>         )
>         VALUES
>         (
>         #{resource.id, jdbcType=VARCHAR},
>         1,
>         #{resource.name, jdbcType=VARCHAR},
>         #{resource.bytes, jdbcType=BLOB},
>         #{resource.deploymentId, jdbcType=VARCHAR},
>         #{resource.generated, jdbcType=BOOLEAN}
>         )
>     </foreach>
>     ;end;
> </insert>`
> ```
> 
> and i got another error like:
> ![image](https://user-images.githubusercontent.com/37392012/123918048-0d93d700-d9b6-11eb-8196-af095b933f14.png)

Now OB is  mysql mode, you can insert multi sql statement like this:
   <insert id="insertList" parameterType="java.util.List">
        insert into S_USER(_key,userId, userName,userPwd, userPower) values
        <foreach collection="list" item="user" separator="," close=";">
            (#{user._key}, #{user.userId},#{user.userName},#{user.userPwd}, #{user.userPower})
        </foreach>
    </insert>
