### ISSUE TITLE
[Bug]: some json type ddl will destory the availability of the table

### ISSUE THREAD

**Issue by TyphoonTai** [oceanbase/oceanbase#1286]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
Server version: 5.6.25 OceanBase 3.1.4 (r1-20910756798b33b8addd998237b9e37c8a743dd4) (Built Jul 13 2022 18:20:12)
```

### Fast Reproduce Steps(Required)

When we add a json column and change it from not null to null, the table become disabled. it's so terrible!
```
mysql> CREATE TABLE tny3 (
    ->             id DECIMAL not null COMMENT '主键',
    ->             trade_no VARCHAR(64) not null
    ->             );
Query OK, 0 rows affected (0.05 sec)

mysql> 
mysql> select * from tny3;
Empty set (0.05 sec)

mysql> 
mysql> alter table tny3 add column channel json not null;
Query OK, 0 rows affected (0.03 sec)

mysql> 
mysql> select * from tny3;
Empty set (0.00 sec)

mysql> 
mysql> alter table tny3 modify channel json null;
ERROR 1210 (HY000): Invalid argument
mysql> 
mysql> select * from tny3;
ERROR 1210 (HY000): Invalid argument

```

### Actual Behavior

This change destory the availability of the table and we can not even drop it! What's more, It also effect some problems on meta data table.

### Expected Behavior

Execute successfully or this change is not allowed. Please fix this bug as soon as possible.

**Comment by caifeizhi** [comment]
thanks for your feedback;
this bug fixed in https://github.com/oceanbase/oceanbase/commit/1b88c27061b48d8f566ddd5c4765e726d4f1ffb1

**Comment by whatvn** [comment]
@caifeizhi will this fix applied to 3.x version?
