### ISSUE TITLE
[Question]: rollback alter table primay_zone

### ISSUE THREAD

**Issue by boysxw8755773** [oceanbase/oceanbase#1305]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

mysql> alter table test primary_zone zone1;
then i want rollback table level primary_zone set ，but i can't do this ?
mysql> alter table test primary_zone '';
ERROR 4179 (HY000): set primary_zone empty not allowed

**Comment by hnwyllmm** [comment]
primary_zone='RANDOM'

**Comment by boysxw8755773** [comment]
thank you very much,I test change tenant primary_zone ,partition leader swith work well,
