### ISSUE TITLE
[Question]: How to start oceanbase from binary

### ISSUE THREAD

**Issue by qaqcatz** [oceanbase/oceanbase#1308]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

I want to calculate the coverage of oceanbase, so I need to compile and start oceanbase myself.
However, I don't know how to start the binary after building the release version of oceanbase according to the document (https://www.oceanbase.com/en/docs/community-observer-en-10000000000209369),  and I haven't found tutorial documents like "install / start oceanbase from binary".
I tried to run `/usr/local/bin/observer`, but it only returned "observer" and did nothing.
Is there a tutorial on starting oceanbase from binary?

**Comment by akaError** [comment]
currently, to boost oceanbase binary manually is difficult, there is a thrick!
<img width="678" alt="image" src="https://user-images.githubusercontent.com/97499944/220244316-6fcf646c-9134-485d-916d-0024734e5ce6.png">

use 'ps -ef | grep ob' to find the process, and then kill it first , but remember to copy the start code, just replace the binary address as the blud bine (ignore the red part, i use it to cover some privacy)

**Comment by qaqcatz** [comment]
Unfortunately, I still can not start `observer`.
First, I created an official docker container `docker run -itd --name oceanbasetest -p 2881:2881 oceanbase/oceanbase-ce:latest` and executed `ps -ef | grep ob`. After that, I got the following arguments:
```shell
/root/ob/bin/observer -r 127.0.0.1:2882:2881 -p 2881 -P 2882 -z zone1 -n obcluster -c 1 -d /root/ob/store -i lo -l INFO -o __min_full_resource_pool_memory=2147483648,memory_limit=6G,system_memory=1G,datafile_size=5G,log_disk_size=5G,cpu_count=16,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4
```
Then, I created a new docker container, built oceanbase, mkdir `/root/ob/store`, and started `observer` with the above arguments.
However, it just print some messages, no services started:
```shell
[root@0d65f8f92a40 bin]# ./observer -r 127.0.0.1:2882:2881 -p 2881 -P 2882 -z zone1 -n obcluster -c 1 -d /root/ob/store -i lo -l INFO -o __min_full_resource_pool_memory=2147483648,memory_limit=6G,system_memory=1G,datafile_size=5G,log_disk_size=5G,cpu_count=16,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4
./observer -r 127.0.0.1:2882:2881 -p 2881 -P 2882 -z zone1 -n obcluster -c 1 -d /root/ob/store -i lo -l INFO -o __min_full_resource_pool_memory=2147483648,memory_limit=6G,system_memory=1G,datafile_size=5G,log_disk_size=5G,cpu_count=16,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4
rs list: 127.0.0.1:2882:2881
mysql port: 2881
rpc port: 2882
zone: zone1
appname: obcluster
cluster id: 1
data_dir: /root/ob/store
devname: lo
log level: INFO
optstr: __min_full_resource_pool_memory=2147483648,memory_limit=6G,system_memory=1G,datafile_size=5G,log_disk_size=5G,cpu_count=16,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4
```
I tried `losf -i:2881` and `ps -ef | grep ob`, but I could not find `observer`.
Do you have any other suggestions?

**Comment by qaqcatz** [comment]
To be honest, I just want to calculate the coverage of oceanbase. 
I tried compiling oceanbase (with --coverage) into `rpm` and starting it through `obd`. In this way, I can start oceanbase successfully, but I can't get the `gcda` coverage files (I don't know why...QAQ).
Another way is to start oceanbase from binary. In this way, I can see my `gcda` files, but no services started as I described above.
I would appreciate it if anyone could give me some suggestions.

**Comment by caifeizhi** [comment]
can you start with 'obd', see https://github.com/oceanbase/oceanbase/wiki/Deploy

**Comment by qaqcatz** [comment]
> can you start with 'obd', see https://github.com/oceanbase/oceanbase/wiki/Deploy

Yes, in the way I can start oceanbase from binary successfully!
I am sure that the `observer` started by `obd.sh` is my instrumented binary. I find the path of the binary through `ps -ef | grep ob` and tried to run it manually. After that, I can see my `gcda` files.
> However, when the `observer` is started by `obd.sh` instead of manually, I still cannot get the `gcda` files after executing `obd.sh stop ob`.
Anyway, the problem of starting oceanbase from binary has been solved. Next, I will try to find out why my `gcda` files are not generated. Thank you!
