### ISSUE TITLE
请教ob for oracle 模式如何使用golang来连接访问？[Question]: 

### ISSUE THREAD

**Issue by freeman983** [oceanbase/oceanbase#1314]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

查看官网只给了Go-SQL-Driver/MySQL的连接方案，如果是oracle模式，除了OCI有没有可推荐的方案。

例如：
是否可以使用golang的oracle 相关驱动来访问ob for oracle 模式呢
https://github.com/godror/godror

**Comment by caifeizhi** [comment]
目前暂不支持Oracle模式的go驱动

**Comment by a1iive** [comment]
目前只推荐使用go-oic8

**Comment by freeman983** [comment]
@a1iive go-oic8原作者已经不维护了，godror也是同一作者发起的。请问是否有评估测试过godror的连接兼容性？

**Comment by longdafeng** [comment]
麻烦问一下, 你公司的名称, 因为企业版这边喊go 支持的声音比较少, 如果公司知名度比较大, 我们会调高优先级.

**Comment by freeman983** [comment]
@Longda-Feng 南京树安信息技术有限公司 - 我们是做数据库安全工具的公司，我们底层技术堆栈是用go，我们有很多客户有使用我们工具连接ob for oracle的需求,谢谢
