### ISSUE TITLE
[Enhancement] Compile guide does not tell how to run

### ISSUE THREAD

**Issue by tisonkun** [oceanbase/oceanbase#1338]
@caifeizhi 

After resolving issue https://github.com/oceanbase/oceanbase/issues/1337, I notice that the executable isn't under the root of build dir, nor we have a `bin` folder. Actually, it locates at `${BUILD_DIR}/src/observer/observer`.

By executing this binary, it exits without any information and I don't know how to connect to the server or even the server is running now.

```
$ ./src/observer/observer   
./src/observer/observer

$ echo $!
0

$ lsof -i :2881
# empty
```

Perhaps we should elaborate the compile guide about how to run observer with the manually compiled binary. Also, the compile guide (on wiki page) is hard to collaborate and I may suggest we move it to a `docs` folder to serve as develop document.

**Comment by caifeizhi** [comment]
```observer``` need deploy by ```obd```, see more info in : https://github.com/oceanbase/oceanbase/wiki/Deploy

**Comment by caifeizhi** [comment]
> 
> Perhaps we should elaborate the compile guide about how to run observer with the manually compiled binary. Also, the compile guide (on wiki page) is hard to collaborate and I may suggest we move it to a `docs` folder to serve as develop document.

We used to put these contents on the wiki because it was easier to edit, but we didn't consider the collaborative aspect. Your suggestion seems like a good idea, and we will consider this approach.

**Comment by caifeizhi** [comment]
Thank you for your suggestion @tisonkun . I think it's a good decision to put the "Contributor's Guide" in the source code.

**Comment by whhe** [comment]
> Thank you for your suggestion @tisonkun . I think it's a good decision to add a `docs` dir, and put the "Contributor's Guide" in it;

I think it's great to move these contents into a directory like `docs`. 

As we used the `docs` directory to build the documentation website in the past, we should add a description about the scope of the contents that should be stored in the `docs` directory, maybe in the readme file, and also we should let users know that the database documents are open sourced in other repos.

**Comment by tisonkun** [comment]
Thanks for your updates!

I'm going to close this issue and supersede it with a dedicated tracking issue. I'll divide down subtasks and start working on it in days.

**Comment by a1iive** [comment]
@tisonkun Thanks for your willingness to contribute！Are you planning to start soon?

**Comment by tisonkun** [comment]
Yep. Sorry for the delay due to holiday and coming back from holiday. Let me make the tracking issue _today_.

**Comment by tisonkun** [comment]
Closed in favor of https://github.com/oceanbase/oceanbase/issues/1386.

This issue can be referred as background.
