### ISSUE TITLE
new tenant root hanging at login

### ISSUE THREAD

**Issue by yungoo** [oceanbase/oceanbase#134]
**Describe the bug (__must be provided__)**

when i create a new tenant, i cannot use obclient/mysql client to login root user in this new tenant, it's hanging.

**Your Environments (__must be provided__)**

* OS: `Linux localhost.localdomain 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Compliler: `g++ (GCC) 5.2.0`
* CPU: `Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz`
* Commit id: `99866eb99df8ec3d65ebdfabaee61ef551f0cc90`

**How To Reproduce(__must be provided__)**

1. create a tenant

2. login root within tenant

```
# obclient -h 127.0.0.1 -P 2881 -u root@tenant1 -c -A -p
Welcome to oceanbase ....
```

3. the ObClient hanging without response

**Expected behavior**

```
# obclient -h 127.0.0.1 -P 2881 -u root@tenant1 -c -A -p
Welcome to oceanbase ....
...
obclient>
```

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by geekfivestart** [comment]
have a try without "-p" option
`obclient -h 127.0.0.1 -P 2881 -u root@tenant1 -c -A`

**Comment by yungoo** [comment]
> have a try without "-p" option
> `obclient -h 127.0.0.1 -P 2881 -u root@tenant1 -c -A`

auth is ok, but it hanging at Quering DB version, the query handling have bug when  the cgroup ctrl files of tenant is missing or not been created.
