### ISSUE TITLE
[feat.]: DBLINK in MySQL mode

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1349]
### Please check the issue list for the same feature first

- [X] Please checked issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### A full description of the feature and provide some example if the same feature exists in other products, such as mysql

```markdown
DBLINK in MySQL mode
only read
```

**Comment by c278095492** [comment]
可以创建读写的dblink吗，sql server 与oracle中都可以跨数据源进行写入，例如在sql server中可以执行 
insert into linkserver.db.table select * from db1.dbo.tableA where xxxx

**Comment by hnwyllmm** [comment]
一期功能已经完成，工单关闭，后面有什么问题，欢迎随时讨论。
