### ISSUE TITLE
[feat.]: Small-size optimization

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1356]
Optimize small-scale OLTP performance and reduce idle CPU consumption in small-scale environments.

- OLTP 20% performance improvement
- No more than 25% CPU cost in idle scenes

**Comment by tisonkun** [comment]
Can we associate the related commits here?

**Comment by hnwyllmm** [comment]
https://github.com/oceanbase/oceanbase/commit/8fb50cdf6598d4de818055be0253c835f08f48c1
