### ISSUE TITLE
[feat.]: Do not occupy too much disk space at once, instead allocate on demand

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1363]
### Please check the issue list for the same feature first

- [X] Please checked issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### A full description of the feature and provide some example if the same feature exists in other products, such as mysql

```markdown
Do not occupy too much disk space at once, instead allocate on demand
```

**Comment by caifeizhi** [comment]
supported in https://github.com/oceanbase/oceanbase/commit/2293904cc0b23b69a4b36298e7cca010d0fdf22e
