### ISSUE TITLE
启动observer时的pidfile_test的报错

### ISSUE THREAD

**Issue by rgyu** [oceanbase/oceanbase#137]
用命令行启动Observer的时候，有如下的提示信息：

/home/obuser/oceanbase/bin/observer -r A:2882:2883;B:2882:2883;C:2882:2883 -o datafile_size=16G,memory_limit=8G,system_memory=4G,stack_size=512K,cpu_count=4,cache_wash_threshold=1G,workers_per_cpu_quota=4,schema_history_expire_time=1d,net_thread_count=4,major_freeze_duty_time=Disable,minor_freeze_times=10,enable_separate_sys_clog=0,enable_merge_by_turn=False,datafile_disk_percentage=20,idc=xx -z zone1 -p 2883 -P 2882 -c 1 -d /db/observer/store -i eth0 -l ERROR -n H
rs list: A:2882:2883;B:2882:2883;C:2882:2883
optstr: datafile_size=16G,memory_limit=8G,system_memory=4G,stack_size=512K,cpu_count=4,cache_wash_threshold=1G,workers_per_cpu_quota=4,schema_history_expire_time=1d,net_thread_count=4,major_freeze_duty_time=Disable,minor_freeze_times=10,enable_separate_sys_clog=0,enable_merge_by_turn=False,datafile_disk_percentage=20,idc=xx
zone: zone1
mysql port: 2883
rpc port: 2882
cluster id: 1
data_dir: /db/observer/store
devname: eth0
log level: ERROR
appname: H
[2021-07-04 20:02:54.601179] ERROR [LIB] pidfile_test (utility.cpp:1153) [17627][0][Y0-0000000000000000] [lt=0] fid file doesn't exist(pidfile="run/observer.pid") BACKTRACE:0x771c1ba 0x7656366 0x1a007ed 0x1a8ba4c 0x7720bf5 0x1a0ac53 0x7efd9e4dfc05 0x19fc269

其中的ERROR [LIB] pidfile_test 报错信息很迷惑。我以为是哪里不对。看了代码，应该是预期的信息，不至于报错。pidfile_test在文件不存在的时候，会抛出如上错误。但是在start_daemon里，ret == OB_FILE_NOT_EXIST是预期行为，ret直接变成了OB_SUCCESS.

所以，在pidfile_test 里，LOG_ERROR这句应该注释掉。
  if (fd < 0) {
    LOG_ERROR("fid file doesn't exist", K(pidfile));
    ret = OB_FILE_NOT_EXIST;
  }

observer的版本信息如下：

observer (OceanBase CE 3.1.0)
REVISION: -00672c3c730c3df6eef3b359eae548d8c2db5ea2
BUILD_BRANCH: master
BUILD_TIME: Jun 22 2021 12:46:28
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

下面是代码部分：文件路径是：oceanbase\deps\oblib\src\lib\utility\utility.cpp

int start_daemon(const char* pidfile)
{
  int ret = OB_SUCCESS;

  ret = pidfile_test(pidfile);

  if (ret != OB_SUCCESS && ret != OB_FILE_NOT_EXIST) {
    LOG_ERROR("pid already exists");
  } else {
    ret = OB_SUCCESS;
  }

  // start daemon
  if (OB_SUCC(ret) && OB_FAIL(use_daemon())) {
    LOG_ERROR("create daemon process fail", K(ret));
  }

  if (OB_SUCC(ret)) {
    int fd = open(pidfile, O_RDWR | O_CREAT, 0600);
   // 后面略

static int pidfile_test(const char* pidfile)
{
  int ret = OB_SUCCESS;
  int fd = open(pidfile, O_RDONLY);

  if (fd < 0) {
    LOG_ERROR("fid file doesn't exist", K(pidfile));
    ret = OB_FILE_NOT_EXIST;
  } else {
    if (lockf(fd, F_TEST, 0) != 0) {
      ret = OB_ERROR;
    }
    close(fd);
  }

  return ret;
}

**Comment by longdafeng** [comment]
Good catch!!!

Could you please raise one pull request??
