### ISSUE TITLE
observer --help result is not complete

### ISSUE THREAD

**Issue by rgyu** [oceanbase/oceanbase#138]
版本号：
REVISION: -00672c3c730c3df6eef3b359eae548d8c2db5ea2
BUILD_BRANCH: master
BUILD_TIME: Jun 22 2021 12:46:28
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

重现步骤：

observer --help
observer [OPTIONS]
  -h,--help                print this help
  -z,--zone ZONE           zone
  -p,--mysql_port PORT     mysql port
  -P,--rpc_port PORT       rpc port
  -N,--nodaemon            don't run in daemon
  -n,--appname APPNAME     application name
  -c,--cluster_id ID       cluster id
  -d,--data_dir DIR        OceanBase data directory
  -i,--devname DEV         net dev interface
  -o,--optstr OPTSTR       extra options string
  -r,--rs_list RS_LIST     root service list
  -l,--log_level LOG_LEVEL server log level
  -6,--ipv6 USE_IPV6   server use ipv6 address
  -m,--mode MODE server mode
  -f,--scn flashback_scn

这里的输出信息不全，可以再加一条：
  -V  --version  print out version information

**Comment by longdafeng** [comment]
Thanks  for your response. 

We will fix this issue in this release or the next release. 

In our plan, we will release one version per month.

**Comment by liboyang0730** [comment]
> 版本号：
> REVISION: -00672c3c730c3df6eef3b359eae548d8c2db5ea2
> BUILD_BRANCH: master
> BUILD_TIME: Jun 22 2021 12:46:28
> BUILD_FLAGS: RelWithDebInfo
> BUILD_INFO:
> 
> 重现步骤：
> 
> observer --help
> observer [OPTIONS]
> -h,--help print this help
> -z,--zone ZONE zone
> -p,--mysql_port PORT mysql port
> -P,--rpc_port PORT rpc port
> -N,--nodaemon don't run in daemon
> -n,--appname APPNAME application name
> -c,--cluster_id ID cluster id
> -d,--data_dir DIR OceanBase data directory
> -i,--devname DEV net dev interface
> -o,--optstr OPTSTR extra options string
> -r,--rs_list RS_LIST root service list
> -l,--log_level LOG_LEVEL server log level
> -6,--ipv6 USE_IPV6 server use ipv6 address
> -m,--mode MODE server mode
> -f,--scn flashback_scn
> 
> 这里的输出信息不全，可以再加一条：
> -V --version print out version information
