### ISSUE TITLE
[Bug]: There is a broken url in the webpage of Contribute to OceanBase

### ISSUE THREAD

**Issue by shaoting** [oceanbase/oceanbase#1381]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

the ULR is broken. 
https://cdn.nlark.com/yuque/0/2022/png/106206/1669169298516-0133f3d8-7a5a-4893-a59f-55d42d92a35a.png?x-oss-process=image%2Fresize%2Cw_675%2Climit_0

![11](https://user-images.githubusercontent.com/2166425/236982735-bfae3061-0363-4794-93c6-f9da90997117.png)

### Actual Behavior

There is a broken url in the he webpage of. [Contribute to OceanBase](https://github.com/oceanbase/oceanbase/wiki/Contribute-to-OceanBase) 
Please check the url of WeChat, it should point to  the WeChat " OBCE666"

**Comment by caifeizhi** [comment]
I have already corrected the wrong URL. Additionally, since it is inconvenient to modify the wiki page (only administrators have permissions), we need to maintain the contributing.md file in order for everyone to be able to submit pull requests for modification in the future.
