### ISSUE TITLE
Feature Request: MySQL function Area/ST_area

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1398]
Area is a MySQL function but OceanBase does not support it.

Information:
[Area](https://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html#function_area)

[ST_area](https://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html#function_st-area)

Information below is from mysql doc:

Returns a double-precision number indicating the area of the Polygon or MultiPolygon argument, as measured in its spatial reference system. For arguments of dimension 0 or 1, the result is 0. If the argument is an empty geometry the return value is 0. If the argument is NULL the return value is NULL.

**Comment by tisonkun** [comment]
<img width="1728" alt="image" src="https://github.com/oceanbase/oceanbase/assets/18818196/e54101b8-d2e3-433c-ad03-90ae30dca2b7">

I check the behavior of OB 4.0. It seems ST_Area is already supported (see [ob_expr_st_area.cpp](https://github.com/oceanbase/oceanbase/blob/master/src/sql/engine/expr/ob_expr_st_area.cpp)). But we may still add an alias for these functions.

**Comment by tisonkun** [comment]
How can I add aliases then? It seems we need a subclass and change `ObExprOperator::name` inited.

**Comment by akaError** [comment]
> How can I add aliases then? It seems we need a subclass and change `ObExprOperator::name` inited.

hi, tison, take a look on "ObExprOperatorFactory::get_function_alias_name", it is easily to add a alias name !

**Comment by hnwyllmm** [comment]
> How can I add aliases then? It seems we need a subclass and change `ObExprOperator::name` inited.

Would you like to pick up this issue?

**Comment by tisonkun** [comment]
@hnwyllmm Yep. You can assign me. Hopefully, I'd submit a patch this week.
