### ISSUE TITLE
Call for FULLTEXT INDEX feature of open source OB

### ISSUE THREAD

**Issue by geekfivestart** [oceanbase/oceanbase#140]
It is claimed that OB is compatible with MySQL, however, I notice that the open-sourced version of OB doesn't support the FULLTEXT INDEX. FULLTEXT INDEX is essential for text search, which is supported by the commercial version of OB, I believe the introduction of such a feather won't incur much extra work.

**Comment by longdafeng** [comment]
Thanks for your feedback. 

The difference between opensource and commerical version will be released soon. please wait for a short time. I think it will be release before September of this year.

**Comment by LINxiansheng** [comment]
Now we support FULLTEXT in 4.0 version
