### ISSUE TITLE
Feature Request: MySQL function ExteriorRing/ST_exteriorRing

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1400]
ExteriorRing/ST_exteriorRing is a MySQL function but OceanBase does not support it.

Information:
[ExteriorRing](https://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html#function_exteriorring)

[ST_exteriorRing](https://dev.mysql.com/doc/refman/5.7/en/gis-polygon-property-functions.html#function_st-exteriorring)

Returns the exterior ring of the Polygon value poly as a LineString. If the argument is NULL or an empty geometry, the return value is NULL.

**Comment by watchpoints** [comment]
pick up
