### ISSUE TITLE
crash when mysql-client send longdatacmd,

### ISSUE THREAD

**Issue by yu34po** [oceanbase/oceanbase#143]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Centos7
* Compliler: `g++ --version` or `clang++ --version`
* g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
latest
**How To Reproduce(__must be provided__)**

1. use golang go-mysql-driver insert some data to oceanbase, like "INSERT INTO tname (col....) values ('xxx',.....)"
2. oceanbase coredump sometimes,
![image](https://user-images.githubusercontent.com/4360599/124866571-2ec87900-dfef-11eb-9561-353719ad5916.png)

log.Info 
observer.log.wf.20210708124031:[2021-07-08 12:33:48.373622] WARN  [SERVER] process (obmp_default.h:38) [176601][2200][YB420A266BB9-0005C69362CCD5F4] [lt=5] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.373833] WARN  [SERVER] process (obmp_default.h:38) [176539][2076][YB420A266BB9-0005C69362DCD5FA] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.374064] WARN  [SERVER] process (obmp_default.h:38) [176601][2200][YB420A266BB9-0005C69362CCD5F5] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.374275] WARN  [SERVER] process (obmp_default.h:38) [176539][2076][YB420A266BB9-0005C69362DCD5FB] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.374512] WARN  [SERVER] process (obmp_default.h:38) [176601][2200][YB420A266BB9-0005C69362CCD5F6] [lt=5] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.374723] WARN  [SERVER] process (obmp_default.h:38) [176539][2076][YB420A266BB9-0005C69362DCD5FC] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.374941] WARN  [SERVER] process (obmp_default.h:38) [176601][2200][YB420A266BB9-0005C69362CCD5F7] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.375168] WARN  [SERVER] process (obmp_default.h:38) [176539][2076][YB420A266BB9-0005C69362DCD5FD] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.375385] WARN  [SERVER] process (obmp_default.h:38) [176601][2200][YB420A266BB9-0005C69362CCD5F8] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.375608] WARN  [SERVER] process (obmp_default.h:38) [176539][2076][YB420A266BB9-0005C69362DCD5FE] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.375824] WARN  [SERVER] process (obmp_default.h:38) [176601][2200][YB420A266BB9-0005C69362CCD5F9] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.376038] WARN  [SERVER] process (obmp_default.h:38) [176539][2076][YB420A266BB9-0005C69362DCD5FF] [lt=4] [dc=0] MySQL command not supported(cmd=24)
observer.log.wf.20210708124031:[2021-07-08 12:33:48.376282] WARN  [SERVER] process (obmp_default.h:38) [176636][2270][YB420A266BB9-0005C693634CD434] [lt=7] [dc=0] MySQL command not supported(cmd=24)
2. 

**Expected behavior**
expect oceanbase support longdatacmd function
**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by longdafeng** [comment]
Thanks for response. 

We will fix this bug in this month's release.

**Comment by simonjoylet** [comment]
fixed. see [this commit](https://github.com/oceanbase/oceanbase/commit/f02d4c0d305034f863732ad76951701ef6d4c13e)
