### ISSUE TITLE
[Enhancement]: Unknown system variable 'lc_time_names'.

### ISSUE THREAD

**Issue by zhengwanbo** [oceanbase/oceanbase#1436]
**Enhancement**
MySQL has the lc_time_names parms, but ob can not find. 

=============================
[opc@bastion-bigdata ~]$ mysql -uroot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1463
Server version: 5.7.40 MySQL Community Server (GPL)

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SHOW VARIABLES LIKE '%lc_time_names%';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| lc_time_names | en_US |
+---------------+-------+
1 row in set (0.01 sec)

mysql> SET lc_time_names='zh_CN';
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES LIKE '%lc_time_names%';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| lc_time_names | zh_CN |
+---------------+-------+
1 row in set (0.00 sec)

**Comment by hnwyllmm** [comment]
It looks interesting. We will take a look.

**Comment by BOBChenRH** [comment]
I would like to tackle this feature, thx

**Comment by bobbird1995** [comment]
I want to  tackle this feature.
