### ISSUE TITLE
[Bug]: typo publis -> publish

### ISSUE THREAD

**Issue by El-even-11** [oceanbase/oceanbase#1445]
**Describe the bug**

typo in `src/share/schema/ob_server_schema_service.cpp`. publis -> publish.
**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  

**Fast Reproduce Steps(Required)**

**Expected behavior**

**Actual Behavior**

**Additional context**

**Comment by hnwyllmm** [comment]
thanks for your contributing
