### ISSUE TITLE
[Feature]: 在使用pt-archiver时候无法进行数据的导入[load local]

### ISSUE THREAD

**Issue by skymoou** [oceanbase/oceanbase#1452]
**Use Case**

使用pt-archiver归档数据到ob报错

DBD::mysql::st execute failed: load data local not supported [for Statement "LOAD DATA LOCAL INFILE ? INTO TABLE `posx_agent`.`sbtest1`CHARACTER SET utf8mb4(`id`,`k`,`c`,`pad`)" with ParamValues: 0='/tmp/PuxfDp0kVSpt-archiver'] at /usr/bin/pt-archiver line 6986.
**Describe the solution you'd like**

**Describe alternatives you've considered**

希望可以支持对pt归档的支持

**Additional context**

**Comment by hnwyllmm** [comment]
`load data local` 功能现在还不支持，预计在4.3上线。
ref #941

**Comment by hnwyllmm** [comment]
closed by 4d4732b7c73a6c110c60756eec97909a10c23817
