### ISSUE TITLE
[Bug]: yum install ob-sysbench: Error: Unable to find a match: ob-sysbench

### ISSUE THREAD

**Issue by yanxiaoqi932** [oceanbase/oceanbase#1456]
**Describe the bug**
can't install ob-sysbench by yum.

**Comment by hnwyllmm** [comment]
1. What's your operation system and version? ubuntu? centos? rocky?
2. What's the error message?

**Comment by yanxiaoqi932** [comment]
system version: CentOS Linux release 8.5.2111
error message: No match for argument: ob-sysbench
                         Error: Unable to find a match: ob-sysbench

**Comment by hnwyllmm** [comment]
you should execute the command below first:
```bash
yum install -y yum-utils
yum-config-manager --add-repo https://mirrors.aliyun.com/oceanbase/OceanBase.repo
```

**Comment by yanxiaoqi932** [comment]
ok, ob-sysbench is installed successfully, thanks.
