### ISSUE TITLE
[Enhancement]: suspect useless while loop 

### ISSUE THREAD

**Issue by El-even-11** [oceanbase/oceanbase#1457]
**Enhancement**

## Summary
Found an useless while loop in `ObServerSchemaService::refresh_full_schema()`.

## Details
In `ObServerSchemaService::refresh_full_schema()`:

https://github.com/oceanbase/oceanbase/blob/b53ede3e68efffb5754732aaac4db6f47a720d9b/src/share/schema/ob_server_schema_service.cpp#L5308-L5478

The outer while loop (line 5318) seems to be useless.

https://github.com/oceanbase/oceanbase/blob/b53ede3e68efffb5754732aaac4db6f47a720d9b/src/share/schema/ob_server_schema_service.cpp#L5317-L5319

First, we will always enter this loop for the first time:

```cpp
int ret = OB_SUCCESS;  
const uint64_t tenant_id = schema_status.tenant_id_;
ObSchemaMgr *schema_mgr_for_cache = NULL;
if (!check_inner_stat()) {
  ret = OB_INNER_STAT_ERROR;
  LOG_WARN("inner stat error", KR(ret), K(schema_status));
} else {
  while (OB_SUCC(ret)) {  // ret == OB_SUCCESS, always enter
    ...
  }
}  
```

Second, we will never enter this while block for the second time:

```cpp
while (OB_SUCC(ret)) {
  ...
  while (OB_SUCC(ret) && (core_schema_change || sys_schema_change)) {
    // refresh schemas
    ...
  } 

  if (OB_SUCC(ret)) {
    break;  // ret == OB_SUCCESS, break, exit while 
  } else {
    ... // ret will not be changed, meaning that ret != OB_SUCCESS
  }
  // ret != OB_SUCCESS, condition is false, exit while 
}
```

I noticed that there is a potentially relevant comment:

https://github.com/oceanbase/oceanbase/blob/b53ede3e68efffb5754732aaac4db6f47a720d9b/src/share/schema/ob_server_schema_service.cpp#L5333-L5334

But the outer loop doesn't work now.

Can we remove this `while` safely?

**Comment by hnwyllmm** [comment]
It looks you are right. We will check it seriously.

**Comment by hnwyllmm** [comment]
It's confirmed but I'm so sorry we cannot fix it now as there is a feature branch has changed it a lot.

**Comment by El-even-11** [comment]
> It looks you are right. We will check it seriously.

Thanks for your attention!
