### ISSUE TITLE
[Question]: Alma linux9 does not support the tcp_tw_recycle configuration

### ISSUE THREAD

**Issue by yaochen1205** [oceanbase/oceanbase#1464]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
Alma linux9 does not support the tcp_tw_recycle configuration
error message : sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory
**Environment**
AlmaLinux release 9.1 (Lime Lynx) 
- OS Version and CPU Arch(`uname -a`):
Linux xxxx 5.14.0-162.23.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Apr 11 10:43:28 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
v3.1.5_CE_HF1

**Comment by hnwyllmm** [comment]
Where did you find the error message?

**Comment by yaochen1205** [comment]
Run sudo sysctl -p

**Comment by hnwyllmm** [comment]
But why do you execute this command? Does the oceanbase require?
I found that tcp_tw_recycle was deprecated in linux 4.x, so there should be another solution to handle your real problem.

**Comment by yaochen1205** [comment]
https://www.oceanbase.com/docs/community-observer-cn-10000000000449657

**Comment by hnwyllmm** [comment]
Please remove the tcp_tw_recycle line and rerun.
