### ISSUE TITLE
[Feature]: Adding defaultvalue to parameter

### ISSUE THREAD

**Issue by BOBChenRH** [oceanbase/oceanbase#1465]
**Use Case**
When using virtual_table such as __all_virtual_sys_parameter_stat or __all_virtual_tenant_parameter_stat I would like to see the default value of the parameter.

**Describe the solution you'd like**
When initializing  parameters, save the default value of the parameter for further use such as collected by some virtual table

**Describe alternatives you've considered**
Or at least letting me know that the current value of the parameter is different from the default setting.

**Comment by hnwyllmm** [comment]
Great. Could you display the configuration items that have been modified from their default values but are currently invisible?

**Comment by hnwyllmm** [comment]
fixed
