### ISSUE TITLE
[Enhancement]: Provide a new B+ Tree with higher performance and more efficient implementation for the memtable

### ISSUE THREAD

**Issue by Handora** [oceanbase/oceanbase#1478]
**Enhancement**
Current B+ Tree implementation has the following disadvantages:
1. The performance of the leftmost insert is terrible 
2. The leaf node has no sibling pointer with poor scan performance
3. The Copy on Write strategy may not be good for memory management and allocation
4. The current implementation is from 10 years ago with many patches, so improvement is necessary

So, we want to make the B+ tree better with the idea from paper:
https://pdos.csail.mit.edu/papers/masstree:eurosys12.pdf

**Comment by ZelKnow** [comment]
I would like to pick this

**Comment by longdafeng** [comment]
Please try the new implementation on this project: https://github.com/oceanbase/miniob.

The B+ tree is a key component of a database, but it is also very complicated and represents a huge task. Additionally, there are many tricky actions that may not appear very smooth but help to resolve certain issues. Any changes made will impact not only performance but also the stability of the entire storage and transaction engine.


Implementing a new B+ tree may seem very sexy, but it requires strong C++ skills. It is recommended to approach this task step by step.
