### ISSUE TITLE
Cannot connect to OceanBase with general tenants.

### ISSUE THREAD

**Issue by Amber1990Zhang** [oceanbase/oceanbase#148]
version:3.1.0

I created the resource unit, the resource pool, and the tenant successfully, but I can't connect to OceanBase with my own tenant.

```sql
create resource unit S2 max_cpu=8, min_cpu=8, max_memory='16G',min_memory='16G',max_iops=10000,min_iops=10000,max_session_num=10000,max_disk_size='1024G';
Query OK, 0 rows affected (0.028 sec)

create resource pool amber_1 unit=S2,unit_num=1;
Query OK, 0 rows affected (0.011 sec)

create tenant amber_babe resource_pool_list=("amber_1");
Query OK, 0 rows affected (1.087 sec)
```

```bash
obclient -h 172.30.198.252 -P 2883 -uroot@amber_babe  -A -c
ERROR 1227 (42501): Access denied
```

```sql
select * from oceanbase.gv$tenant;
+-----------+-------------+-----------+--------------+----------------+---------------+-----------+------------------------------------+
| tenant_id | tenant_name | zone_list | primary_zone | collation_type | info          | read_only | locality                           |
+-----------+-------------+-----------+--------------+----------------+---------------+-----------+------------------------------------+
|         1 | sys         | z1;z2;z3  | z1;z2,z3     |              0 | system tenant |         0 | FULL{1}@z1, FULL{1}@z2, FULL{1}@z3 |
|      1001 | amber_babe  | z1;z2;z3  | RANDOM       |              0 |               |         0 | FULL{1}@z1, FULL{1}@z2, FULL{1}@z3 |
+-----------+-------------+-----------+--------------+----------------+---------------+-----------+------------------------------------+

**Comment by simonjoylet** [comment]
please show your obd cluster config.
maybe the `clog_dir` reach the `clog_disk_usage_limit_percentage` if your `clog_dir` shares the same disk of the `data_dir`. this will halt all writing requests.
typically because you only config the `home_path` and use a large `datafile_disk_percentage`

**Comment by Amber1990Zhang** [comment]
> please show your obd cluster config.
> maybe the `clog_dir` reach the `clog_disk_usage_limit_percentage` if your `clog_dir` shares the same disk of the `data_dir`. this will halt all writing requests.
> typically because you only config the `home_path` and use a large `datafile_disk_percentage`

thank you. You've got it right. Really helps.

**Comment by Amber1990Zhang** [comment]
I make changes as your suggested, but it still won't work.

**Comment by Amber1990Zhang** [comment]
show parameters where name in ('clog_disk_usage_limit_percentage')
    -> ;
+------+----------+----------------+----------+----------------------------------+-----------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---------+---------+---------+-------------------+
| zone | svr_type | svr_ip         | svr_port | name                             | data_type | value | info                                                                                                                                                     | section | scope   | source  | edit_level        |
+------+----------+----------------+----------+----------------------------------+-----------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---------+---------+---------+-------------------+
| z2   | observer | 172.30.198.247 |    33334 | clog_disk_usage_limit_percentage | NULL      | 95    | maximum of clog disk usage percentage before stop submitting or receiving logs, should be greater than clog_disk_utilization_threshold. Range: [80, 100] | TRANS   | CLUSTER | DEFAULT | DYNAMIC_EFFECTIVE |
| z1   | observer | 172.30.198.246 |    33332 | clog_disk_usage_limit_percentage | NULL      | 95    | maximum of clog disk usage percentage before stop submitting or receiving logs, should be greater than clog_disk_utilization_threshold. Range: [80, 100] | TRANS   | CLUSTER | DEFAULT | DYNAMIC_EFFECTIVE |
| z3   | observer | 172.30.198.248 |    33336 | clog_disk_usage_limit_percentage | NULL      | 95    | maximum of clog disk usage percentage before stop submitting or receiving logs, should be greater than clog_disk_utilization_threshold. Range: [80, 100] | TRANS   | CLUSTER | DEFAULT | DYNAMIC_EFFECTIVE |
+------+----------+----------------+----------+----------------------------------+-----------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---------+---------+---------+-------------------+
The default value is 95%

**Comment by simonjoylet** [comment]
ALTER TENANT amber_babe SET VARIABLES ob_tcp_invited_nodes='%';
maybe it's a simple and stupid mistake. try this.
