### ISSUE TITLE
Is it possible to proofread the returning messages of this kind?

### ISSUE THREAD

**Issue by Amber1990Zhang** [oceanbase/oceanbase#149]
![image](https://user-images.githubusercontent.com/42762957/125379860-dfee5b00-e3c3-11eb-8166-f7dc0c2b1125.png)
As title, will you optimize the `info` to make it more readable?

**Comment by pengmq1** [comment]
Do you mean the 'info' column too wide?   use multi line to show the info text?

**Comment by Amber1990Zhang** [comment]
> Do you mean the 'info' column too wide? use multi line to show the info text?

No, I mean the info content. I want to improve the English expressions.
