### ISSUE TITLE
[Enhancement]: ob导出的表结构，引擎是oceanbase，导入mysql会报错，是否需要兼容一下

### ISSUE THREAD

**Issue by zzps** [oceanbase/oceanbase#1495]
**Enhancement**
如标题所言

**Comment by hnwyllmm** [comment]
你使用的哪个导入导出工具

**Comment by zzps** [comment]
> 你使用的哪个导入导出工具

navicat

**Comment by hnwyllmm** [comment]
楼主说的是导出时的SQL语句显示 storage_engine='oceanbase' 这样？导致无法导入mysql吗？

**Comment by zzps** [comment]
> 楼主说的是导出时的SQL语句显示 storage_engine='oceanbase' 这样？导致无法导入mysql吗？

是的
![lQLPJwZEMmN44IzNAjHNBzGwywqZ583DS7kExQ0NqwCjAA_1841_561](https://github.com/oceanbase/oceanbase/assets/33255974/3b8aa987-b317-4259-8578-e75907513838)

**Comment by hnwyllmm** [comment]
如果仅仅是这个问题，我建议导出后手工全局替换一下。engine写其它名字也不合适。
替换后还会有其它问题吗？

**Comment by zzps** [comment]
> 



> 如果仅仅是这个问题，我建议导出后手工全局替换一下。engine写其它名字也不合适。 替换后还会有其它问题吗？

替换后没有问题，另外一个问题是按库导入导出一个库中的多个表结构不行，需要一个个导，这个很不方便，是否有优化改进计划

**Comment by zzps** [comment]
> 



> 如果仅仅是这个问题，我建议导出后手工全局替换一下。engine写其它名字也不合适。 替换后还会有其它问题吗？

替换后没有问题，另外一个问题是按库导入导出一个库中的多个表结构不行，需要一个个导，这个很不方便，是否有优化改进计划

**Comment by hnwyllmm** [comment]
不太明白“需要一个一个导”。
是说：
1. 有多个库，比如test1, test2，这两个库要test1和test2一个一个来？
2. 或者，test 数据库下，有两个表table1, table2，需要一个表一个表来操作？

另外，一个一个导，这个动作，是navicat界面上操作的吗？是不是navicat工具本身的限制？

**Comment by zzps** [comment]
> 不太明白“需要一个一个导”。 是说：
> 
>     1. 有多个库，比如test1, test2，这两个库要test1和test2一个一个来？
> 
>     2. 或者，test 数据库下，有两个表table1, table2，需要一个表一个表来操作？
> 
> 
> 另外，一个一个导，这个动作，是navicat界面上操作的吗？是不是navicat工具本身的限制？
是2这种情况
test 数据库下，有两个表table1, table2，需要一个表一个表来操作。是在navicat上操作的，不是工具本身的问题，其他mysql，tidb数据库都可以，ob数据库会报错不支持events 这样的信息

**Comment by zzps** [comment]
> 不太明白“需要一个一个导”。 是说：
> 
>     1. 有多个库，比如test1, test2，这两个库要test1和test2一个一个来？
> 
>     2. 或者，test 数据库下，有两个表table1, table2，需要一个表一个表来操作？
> 
> 
> 另外，一个一个导，这个动作，是navicat界面上操作的吗？是不是navicat工具本身的限制？
是2这种情况
test 数据库下，有两个表table1, table2，需要一个表一个表来操作。是在navicat上操作的，不是工具本身的问题，其他mysql，tidb数据库都可以，ob数据库会报错不支持events 这样的信息

**Comment by hnwyllmm** [comment]
收到，我们来评估一下这个需求

**Comment by hnwyllmm** [comment]
![image](https://github.com/oceanbase/oceanbase/assets/5187215/40f19088-b785-4868-894a-ac1ee2b0448f)
我测试了一下，可以一键导出，你要的是这种功能吗？

**Comment by zzps** [comment]
> ![image](https://user-images.githubusercontent.com/5187215/258780158-40f19088-b785-4868-894a-ac1ee2b0448f.png) 我测试了一下，可以一键导出，你要的是这种功能吗？

是的
![1691405850619](https://github.com/oceanbase/oceanbase/assets/33255974/45f38a3a-971d-4064-a0fd-8f0d6340a210)

**Comment by hnwyllmm** [comment]
有两个疑问：
1. 你的数据库连接，选择的是"oceanbase"吗？navicat对oceanbase做过适配，如果不是可以改下试试看
2. qt_finance 下的表结构可以分享吗？我在本地测试一下。导出表结构通常不需要访问events表

**Comment by zzps** [comment]
> 有两个疑问：
> 
>     1. 你的数据库连接，选择的是"oceanbase"吗？navicat对oceanbase做过适配，如果不是可以改下试试看
> 
>     2. qt_finance 下的表结构可以分享吗？我在本地测试一下。导出表结构通常不需要访问events表

是oceanbase，通过obproxy连的，我就是一个库只有一张表也是这个报错，如果你方便我可以给你钉钉远程协助你自己操作看看

**Comment by hnwyllmm** [comment]
我的邮箱 hnwyllmm@126.com

**Comment by zzps** [comment]
> 
你直接搜我钉钉吧
13067778967

**Comment by hnwyllmm** [comment]
总结一下：
1. navicat 从ob导出表结构DDL语句，显示engine='oceanbase',导致无法直接导入MySQL。当前建议做手动全局替换
2. navicat 导出表结构时会出现 information_schema.events 表查不到的情况，此时需要在建立navicat数据库连接时，选择 oceanbase，而不是MySQL。
