### ISSUE TITLE
[Question]:source_code:memory:ABlock merge process

### ISSUE THREAD

**Issue by noahhuhu** [oceanbase/oceanbase#1497]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
Assume AObject::nobjs_ field means the size of a AObject，but ABlock do not have size field。check BlockSet::free_block
use Chunk->blk_bs_ and unused_blk_bs_ bitmaps can calc each block size。why the differences between each other?
i check block merge process ,it more effective than AObject。
**Environment**

- OS Version and CPU Arch(`uname -a`):

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

**Comment by hnwyllmm** [comment]
It seems that ABlock's memory size is fixed: ABLOCK_SIZE except the large block.
I think blk_bs_ means that which block is valid and unused_blk_bs_ means that which block is free.

**Comment by noahhuhu** [comment]
allocate large object which more than ABLOCK_SIZE，it can get block size more than ABLOCK_SIZE from a chunk。i think blk_bs_ mean the chunk split process which  bitmap pos represent offset between chunk->data and block address, middle of the two bit 1 ranges indicates the block size (pos1-pos2) * ABLOCK_SIZE  , and unused_blk_bs_  means alloc block is free or not.

**Comment by hnwyllmm** [comment]
What do you mean about "middle of the two bit 1 ranges indicates the block size (pos1-pos2) * ABLOCK_SIZE"?
