### ISSUE TITLE
[Bug]: HiKariCP连接池使用OceanBase-Oracle有bug

### ISSUE THREAD

**Issue by qq12157138** [oceanbase/oceanbase#1498]
Java JDBC连接方式使用HikariCpConfig在不设置setConnectionTestQuery的情况下，会强制执行SQL -> SELECT 1 ，然而这在OceanBase-Oracle中是不可执行的。

**Comment by hnwyllmm** [comment]
Oceanbase Oracle需要使用OB提供的JDBC，MySQL或者其它第三方组件不行。
建议找你的专业支持团队索取相关jar包，并可以获取相关技术支持。

**Comment by qq12157138** [comment]
> Oceanbase Oracle需要使用OB提供的JDBC，MySQL或者其它第三方组件不行。 建议找你的专业支持团队索取相关jar包，并可以获取相关技术支持。

我用的就是Oceanbase Oracle的驱动，
···
<dependency>
          <groupId>com.oceanbase</groupId>
          <artifactId>oceanbase-client</artifactId>
      </dependency>
···
驱动包：com.oceanbase.jdbc.Driver

**Comment by qq12157138** [comment]
> Oceanbase Oracle需要使用OB提供的JDBC，MySQL或者其它第三方组件不行。 建议找你的专业支持团队索取相关jar包，并可以获取相关技术支持。

我能提出这个问题肯定是照着你们官方文档来的。

**Comment by qq12157138** [comment]
> setConnectionTestQuery

我指定了setConnectionTestQuery之后就完全不报错 后续查询都正常

**Comment by hnwyllmm** [comment]
> > Oceanbase Oracle需要使用OB提供的JDBC，MySQL或者其它第三方组件不行。 建议找你的专业支持团队索取相关jar包，并可以获取相关技术支持。
> 
> 我能提出这个问题肯定是照着你们官方文档来的。

我是想说，既然你使用了企业版，联系你们的专业技术支持人员，可以获得比在社区上更高效更专业的支持。
