### ISSUE TITLE
[Feature]: 希望支持load data local功能

### ISSUE THREAD

**Issue by deskau** [oceanbase/oceanbase#1507]
再使用工具pt-archiver归档时，发现会报错不支持load data local 这个功能。希望ob能够支持此功能

**Comment by deskau** [comment]
![image](https://github.com/oceanbase/oceanbase/assets/109035173/d35f64b1-d188-43de-b0b2-f40073715e80)
如图所示

**Comment by hnwyllmm** [comment]
fixed
