### ISSUE TITLE
[Bug]: build ccache has low hit rate

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1517]
**Describe the bug**

The ccache build hit rate is lower than 30%, so we cannot take benefit from the ccache.

**Fast Reproduce Steps(Required)**
Create a pull request and then you can get the compile ccache result from the action.

**Expected behavior**

High hit rate(>=80%) or remove the ccahce.

**Actual Behavior**

```
stats updated                       Tue Aug 15 09:49:50 2023
stats zeroed                        Tue Aug 15 08:35:45 2023
cache hit (direct)                    86
cache hit (preprocessed)              17
cache miss                           293
cache hit rate                     26.01 %
cleanups performed                    31
files in cache                      1235
cache size                           4.2 GB
max cache size                       5.0 GB
```

**Additional context**

https://github.com/oceanbase/oceanbase/actions/runs/5864644001/job/15901693155

**Comment by hnwyllmm** [comment]
build cache is removed now.

**Comment by nautaa** [comment]
I think this issue is due to not updating the ccache in time after adding it. this action was run one month ago, but the ccache is two months added until now. I observed that recently the ccache hit rate even went to 0.
