### ISSUE TITLE
[Bug]: The column 'oceanbase.__all_virtual_table.auto_increment' is not correct

### ISSUE THREAD

**Issue by meiq4096** [oceanbase/oceanbase#1518]
**Describe the bug**

The column 'oceanbase.__all_virtual_table.auto_increment' is not correct

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  
```bash
[admin@server066 oceanbase]$bin/observer -V
bin/observer -V
observer (OceanBase_CE 4.2.0.0)

REVISION: 100000152023080109-8024d8ff45c45cf7c62a548752b985648a5795c3
BUILD_BRANCH: HEAD
BUILD_TIME: Aug  1 2023 09:54:19
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

Copyright (c) 2011-present OceanBase Inc.
```

**Fast Reproduce Steps(Required)**

create two tables in mysql tenant. One has an auto-increment id column, the other doesn't have.
```sql
CREATE TABLE t_auto(id BIGINT NOT NULL auto_increment PRIMARY KEY,c1 varchar(100));
CREATE TABLE t_not_auto(id BIGINT NOT NULL PRIMARY KEY,c1 varchar(100));
```

Then query the inner virtual table `__all_virtual_table`

```sql
SELECT tenant_id,table_id,table_name,database_id,auto_increment
 from __all_virtual_table 
where 1=1 
  and tenant_id in (1004) 
  and table_name IN ('t_auto','t_not_auto');
```

**Expected behavior**

|tenant_id|table_id|table_name|database_id|auto_increment|
|---------|--------|----------|-----------|--------------|
|1004|500347|t_auto|500145|1|
|1004|500348|t_not_auto|500145|0|

**Actual Behavior**

|tenant_id|table_id|table_name|database_id|auto_increment|
|---------|--------|----------|-----------|--------------|
|1004|500347|t_auto|500145|1|
|1004|500348|t_not_auto|500145|1|

**Additional context**

**Comment by meiq4096** [comment]
> ```sql
> ```sql
> CREATE TABLE t_not_auto(id BIGINT NOT NULL auto_increment PRIMARY KEY,c1 varchar(100));
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```
Sorry.
I made a mistake in the first part.You can remove the auto_increment column in t_not_auto.
But, you know, it's really easy to reproduce. It also exists in the latest version 4.2.0.

```sql

CREATE TABLE t_auto(id BIGINT NOT NULL auto_increment PRIMARY KEY,c1 varchar(100));
CREATE TABLE t_not_auto(id BIGINT NOT NULL  PRIMARY KEY,c1 varchar(100));

SELECT tenant_id,table_id,table_name,database_id,auto_increment
 from oceanbase.__all_virtual_table 
where 1=1 
  and tenant_id in (1004) 
  and table_name IN ('t_auto','t_not_auto');
```
![image](https://github.com/oceanbase/oceanbase/assets/33079488/f4e7edea-398e-4ba3-9339-a281344ddd8c)

**Comment by hnwyllmm** [comment]
I reproduced it, thanks.

**Comment by wyfanxiao** [comment]
The 'auto_increment' field in the '__all_virtual_table' table represents the initial value of the auto-increment column, rather than being used to signify whether it is auto-incrementing.

**Comment by wyfanxiao** [comment]
OceanBase(admin@test)>CREATE TABLE t_auto1(c1 varchar(100), id BIGINT NOT NULL auto_increment ) auto_increment=10;
Query OK, 0 rows affected (0.219 sec)

OceanBase(admin@test)>SELECT tenant_id,table_id,table_name,database_id,auto_increment  from oceanbase.__all_virtual_table  where table_name IN ('t_auto','t_auto1');
+-----------+----------+------------+-------------+----------------+
| tenant_id | table_id | table_name | database_id | auto_increment |
+-----------+----------+------------+-------------+----------------+
|      1004 |   500009 | t_auto     |      500001 |              1 |
|      1004 |   500010 | t_auto1    |      500001 |             10 |
+-----------+----------+------------+-------------+----------------+
2 rows in set (0.015 sec)
