### ISSUE TITLE
[Bug]: 执行 mysqldump 命令不能指定库备份

### ISSUE THREAD

**Issue by yupd** [oceanbase/oceanbase#1519]
**Describe the bug**

[root@bogon bin]# /usr/local/mysql/bin/mysqldump -h127.0.0.1 -uroot -pxxxxxx test > test.sql 
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't execute '/*!80000 SET SESSION information_schema_stats_expiry=0 */': Unknown system variable 'information_schema_stats_expiry' (1193)

mysqldump  Ver 8.0.30 for Linux on x86_64 (MySQL Community Server - GPL)

**Environment**

- OS Version and CPU Arch(`uname -a`): 
Linux bogon 3.10.0-693.el7.x86_64
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
oceanbase-all-in-one-4.1.0.2-100120230811172725.el7.x86_64

**Comment by ytk929** [comment]
您好，是如何解决的呢？我也遇到了这个问题。

**Comment by ytk929** [comment]
@yupd 您好，是如何解决的呢？我也遇到了这个问题。

**Comment by yupd** [comment]
> @yupd 您好，是如何解决的呢？我也遇到了这个问题。
oceanbase 自带了 mysqldump 命令，用自带的就可以了。
![使用oceanbase自带的命令](https://github.com/oceanbase/oceanbase/assets/9858627/478dbac5-a166-4bcc-bc46-d27cf59143e2)

**Comment by ytk929** [comment]
> > @yupd 您好，是如何解决的呢？我也遇到了这个问题。
> > oceanbase 自带了 mysqldump 命令，用自带的就可以了。
> > ![使用oceanbase自带的命令](https://user-images.githubusercontent.com/9858627/280236362-478dbac5-a166-4bcc-bc46-d27cf59143e2.jpg)

看到了看到了，谢谢啦
