### ISSUE TITLE
[Question]: datafile_next 和 datafile_maxsize 参数没有了？

### ISSUE THREAD

**Issue by yupd** [oceanbase/oceanbase#1527]
**Question**

按照文档 [配置磁盘数据文件的动态扩容](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000033620) 操作提示没有变量。

mysql> ALTER SYSTEM SET datafile_next='2G';
ERROR 5099 (42000): System config unknown

**Environment**

版本号是：4.1.0.2-100120230811172725

**Comment by hnwyllmm** [comment]
按照文档描述，这是4.2的功能，先升级一下集群试一试？

**Comment by yupd** [comment]
> 按照文档描述，这是4.2的功能，先升级一下集群试一试？

哦，好的，我试试，没注意看文档版本号，谢谢！
