### ISSUE TITLE
[Question]: Does Oceanbase have a GPU-accelerated version? 

### ISSUE THREAD

**Issue by qwebug** [oceanbase/oceanbase#1539]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**

Many databases have GPU-accelerated versions. Does Oceanbase have GPU-accelerated versions?

**Environment**

- OS Version and CPU Arch(`uname -a`):

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

**Comment by hnwyllmm** [comment]
Currently no
