### ISSUE TITLE
[Feature]: The Chinese and English versions of readme are not completely aligned

### ISSUE THREAD

**Issue by caicancai** [oceanbase/oceanbase#1550]
**Use Case**

The Chinese and English versions of readme are not completely aligned, whether to consider alignment

**Describe the solution you'd like**

May cause some trouble to users
**Describe alternatives you've considered**

The Chinese and English versions of the readme are aligned

**Additional context**

**Comment by caicancai** [comment]
I would like to contribute this pr

**Comment by hnwyllmm** [comment]
Welcome, thanks.
What's the difference?

**Comment by caicancai** [comment]
@hnwyllmm hello，For example, Continuous availability is here
<img width="463" alt="捕获" src="https://github.com/oceanbase/oceanbase/assets/77189278/2361e237-281f-4c75-94ab-898300d3c9a
<img width="636" alt="捕获1" src="https://github.com/oceanbase/oceanbase/assets/77189278/dedf7ee9-1d29-45c8-8f91-ea4921917641">
3">

**Comment by hnwyllmm** [comment]
Yeah, it's not difference between the two versions.
But it's difficult to make them aligned. For example, "满足金融行业6级容灾标准" is just used in China.
But for other tips, PR is welcome("三地无中心", "同城/异地容灾" etc)

**Comment by caicancai** [comment]
Thank you for your reply, I will submit a PR later

**Comment by hnwyllmm** [comment]
> @hnwyllmm Thank you for your reply. I will submit a PR later. I have another question. Is it mainly based on the Chinese version?

Sorry for late response but I have saw your PR and it's OK.
