### ISSUE TITLE
[Docs] Add contributing guide and development guide in Chinese

### ISSUE THREAD

**Issue by whhe** [oceanbase/oceanbase#1553]
Currently the contribution guide and development guide are only available in English, we need to provide Chinese version of these docs for Chinese developers.

**Comment by hnwyllmm** [comment]
As discuss a few months ago, we only keep the dev guide doc in English.
1. Doc in two languages takes more energy
2. Doc in difference languages always be fork
3. Developers can read doc in English.

**Comment by whhe** [comment]
> As discuss a few months ago, we only keep the dev guide doc in English.
> 
> 1. Doc in two languages takes more energy
> 2. Doc in difference languages always be fork
> 3. Developers can read doc in English.

OK, I understand.
