### ISSUE TITLE
[Enhancement]: `CURRENT_USER` statement compatibility

### ISSUE THREAD

**Issue by whhe** [oceanbase/oceanbase#1555]
When I read the `testcontainers-java` code, I found that they use the `select CURRENT_USER` statement to test various databases such as mysql and sqlserver.

https://github.com/testcontainers/testcontainers-java/blob/e8d737513cc0c7f16ea757a6f4f2eeea7a5e602e/modules/jdbc-test/src/main/java/org/testcontainers/jdbc/AbstractJDBCDriverTest.java#L112

When I tested the statement on OceanBase, I found that it supports `select CURRENT_USER()`, but it does not support  statement without parentheses, while mysql supports the statement without parentheses.

**Comment by caifeizhi** [comment]
@akaError please take a look, it seems to be easy to fix

**Comment by akaError** [comment]
https://github.com/akaError/oceanbase/commit/7198e18f7a9b99fed07b091104f402dca7c79ecc  already fix in this commit @caifeizhi @whhe
