### ISSUE TITLE
[Feature]: show column/index with extend keyword

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1563]
**Use Case**

MySQL 8 support show column/index with extend keyword

**Comment by Young-Cody** [comment]
Could I pick up this issue?

**Comment by hnwyllmm** [comment]
> Could I pick up this issue?

Thanks. But it is in progress now.

**Comment by Young-Cody** [comment]
> > Could I pick up this issue?
> 
> Thanks. But it is in progress now.

Is there any good first issues I can tackle? Thanks.

**Comment by hnwyllmm** [comment]
> > > Could I pick up this issue?
> > 
> > 
> > Thanks. But it is in progress now.
> 
> Is there any good first issues I can tackle? Thanks.

Please take a look at this:
https://github.com/oceanbase/oceanbase/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
