### ISSUE TITLE
[Feature]: Support for designing views that are compatible with Navicat

### ISSUE THREAD

**Issue by Oraing0** [oceanbase/oceanbase#1566]
支持兼容navicat的视图设计

**Comment by caifeizhi** [comment]
Thank you for your feedback, but I am currently unable to determine "What's the problem". Could you please provide more details about the compatibility problem and the error message? Additionally, it would be helpful to know the specific versions of OceanBase and Navicat. Without the above information, it is difficult for us to provide further assistance.

**Comment by caifeizhi** [comment]
This question seems to be mentioned in this post: https://ask.oceanbase.com/t/topic/35604532/5 , which we need to add function `load_file`

**Comment by Oraing0** [comment]
https://ask.oceanbase.com/t/topic/35604532/5这个问题就是我提交的，因为缺少load_file函数导致视图加载失败。在与 MySQL 兼容性对比-OceanBase 数据库 -OceanBase文档中心-分布式数据库使用文档社区文档中的OceanBase简介，与Mysql兼容性对比中有明确表示OceanBase的mysql模式不支持load_file函数。专栏 - 从抓包发现并解决 Navicat 编辑 TiDB 视图报错的问题 | TiDB 社区这是我搜索TIDB数据库解决此类问题的链接，不知道是否对你们有帮助


| |
zhangyu1620
|
|
***@***.***
|
---- Replied Message ----
| From | Feizhi ***@***.***> |
| Date | 9/11/2023 19:26 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [oceanbase/oceanbase] [Feature]: Support for designing views that are compatible with Navicat (Issue #1566) |

This question seems to be mentioned in this post: https://ask.oceanbase.com/t/topic/35604532/5 , which we need to add function load_file
