### ISSUE TITLE
[Enhancement]: Improve startup speed of standalone deployment

### ISSUE THREAD

**Issue by whhe** [oceanbase/oceanbase#1573]
**Enhancement**

Now it costs two or three minutes to start a standalone deployment of OceanBase, hope that the startup time can be less than one minute.

**Comment by caifeizhi** [comment]
Thank you for your suggestion. can you provide a few examples to supplement the specific benefits of doing this

**Comment by GITHUBear** [comment]
We are currently optimizing this part and can now reach a startup time of about 20 seconds. We will merge it after further improvement.

**Comment by whhe** [comment]
> Thank you for your suggestion. can you provide a few examples to supplement the specific benefits of doing this

There is no unacceptable disadvantage to have a long startup time, but since other databases, especially non-distributed databases, generally have a very short startup time, users will be confused if OceanBase's startup time is much longer, after all, it is just an standalone deployment.

In addition, improving the startup speed will make users to spend less time solving problems encountered during testing, which is more user-friendly.

**Comment by whhe** [comment]
The slim mode of oceanbase-ce Docker image can start in about 40 seconds. Closed.

https://github.com/oceanbase/docker-images/tree/main/oceanbase-ce
