### ISSUE TITLE
Is every query supposed to end with a `;`?

### ISSUE THREAD

**Issue by Amber1990Zhang** [oceanbase/oceanbase#158]
As title.
![image](https://user-images.githubusercontent.com/42762957/125900529-7c5bdcdb-46d4-41a0-9d63-9b9a9c015cba.png)
According to oblient, every query must end with a `;`, but I notice that `USE <database_name>` is an exception. Why?

**Comment by hnwyllmm** [comment]
The command `use xxx` does not care about the `;`
This command is keep up with the mariadb/mysql client
