### ISSUE TITLE
[Bug]: different join results when change calculate order

### ISSUE THREAD

**Issue by wengsy150943** [oceanbase/oceanbase#1590]
**Describe the bug**

When join columns with differnet FLOAT type, the results are influenced by the calculate order.

**Environment**

- OS Version and CPU Arch(`uname -a`):
```bash
Linux localhost.localdomain 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
- This command does not work:
```bash
bash: ./observer: No such file or directory
```
Get OB version in this way:
```mysql
MySQL [(none)]> select version();
+------------------------------+
| version()                    |
+------------------------------+
| 5.7.25-OceanBase_CE-v4.0.0.0 |
+------------------------------+
1 row in set (0.00 sec)
```

**Fast Reproduce Steps(Required)**

1. Init database with two tables:

```mysql
create table t0 (a decimal(5,3));
insert into t0 values(0.01);
create table t1 (a double);
insert into t1 values(0.1);
```

2. Join `t0` and `t1`:

```mysql
select * from t0,t1 where t0.a = t1.a - t1.a + t0.a; -- q1

select * from t0,t1 where t0.a = t0.a +  t1.a - t1.a; -- q2
```

**Expected behavior**

`q1` and `q2` return the same result as below, since their only differences are the calculate order.

```mysql
+-------+------+
| a     | a    |
+-------+------+
| 0.010 |  0.1 |
+-------+------+
1 row in set (0.03 sec)
```

**Actual Behavior**

They result different join results as below.

```mysql
MySQL [test]> select * from t0,t1 where t0.a = t1.a - t1.a + t0.a; -- q1
+-------+------+
| a     | a    |
+-------+------+
| 0.010 |  0.1 |
+-------+------+
1 row in set (0.01 sec)

MySQL [test]> select * from t0,t1 where t0.a = t0.a +  t1.a - t1.a; -- q2
Empty set (0.00 sec)
```

**Additional context**

We check the qurey plan and find that `t0.a` is casted as DOUBLE, which may cause float-point bias.
Though float-point bias is expected, some rewrite rules(e.g. reduce a-a) may cause unexpected results.

**Comment by hnwyllmm** [comment]
Thanks for your feedback. I'll check it.

**Comment by hnwyllmm** [comment]
We have check the sqls in mysql 5.7 and 8.0 and we got the same results with oceanbase, so we will not fix it event though it's a bug.

**Comment by hnwyllmm** [comment]
I close this issue. But if you have any questions, feel free to reopen it.
