### ISSUE TITLE
[Question]: nodejs 如何连接oracle 模式的 oceanbase呢

### ISSUE THREAD

**Issue by zeroHu** [oceanbase/oceanbase#1604]
线上数据oceanbase version: OceanBase 3.1.2

尝试使用了oracledb 连接，失败了。

请问现在官方是否可以支持nodejs连接使用呢?

[目前状况]: 老项目，是用nodejs写的，想迁移库从oracle迁到oceanbase 上来，迟迟找不到方案。求助!!!

**Comment by hnwyllmm** [comment]
可以直接找你们的企业版专业技术支持团队
