### ISSUE TITLE
[Enhancement]: there are too many error messages in copy.sh

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1607]
**Enhancement**
![image](https://github.com/oceanbase/oceanbase/assets/5187215/65336cf2-c9c2-49bd-96b7-7dad2a35d45b)

obd.sh use copy.sh to do the `prepare` before deploy developing cluster.
But we always get a lot of error messages and these are meaningless messages.
And another bug, copy.sh would choose a build directory randomly:
```bash
BUILD_DIR=$(find $PWD/../../ -maxdepth 1 -name 'build_*' -type d | grep -v 'build_ccls' | head -1)
```

**Comment by Young-Cody** [comment]
Could I pick up this issue?

**Comment by hnwyllmm** [comment]
Thanks, but please send us your solution before push the pr.

**Comment by Young-Cody** [comment]
As to the first issue, add an option in copy.sh to silence the unnecessary error messages.
![Screenshot from 2023-11-13 11-48-02](https://github.com/oceanbase/oceanbase/assets/63546852/30d1ebe2-eaea-4f52-985d-021de6b86608)
![Screenshot from 2023-11-13 11-49-21](https://github.com/oceanbase/oceanbase/assets/63546852/2aa98cfd-f3b7-4dcc-b395-b7bf8c0e59cd)
As to the second issue, either set an default build directory like build_debug or set it in an order of (build_debug, build_release, etc.).

**Comment by hnwyllmm** [comment]
As to the second issue, either set an default build directory like build_debug or set it in an order of (build_debug, build_release, etc.).

> And how about add an argument? That is, if no directory specific, then use `build_debug`, `build_release` and so on? Which is better?

**Comment by Young-Cody** [comment]
Yes.`copy.sh` is called by `obd.sh prepare`, we can add an argument in obd.sh like `obd.sh prepare -b|--build_path build_debug` to specify a build directory. If no build directory is specified, we set it in order.

> As to the second issue, either set an default build directory like build_debug or set it in an order of (build_debug, build_release, etc.).
> 
> > And how about add an argument? That is, if no directory specific, then use `build_debug`, `build_release` and so on? Which is better?

**Comment by hnwyllmm** [comment]
I agree with you. 
`copy.sh` already can access one argument as the build path.

**Comment by hnwyllmm** [comment]
close as fixed.
