### ISSUE TITLE
[Bug]: 设置自定义变量值为LAST_INSERT_ID()时不生效，【set @variable_name=LAST_INSERT_ID()】inoperative

### ISSUE THREAD

**Issue by cjlmu** [oceanbase/oceanbase#1618]
**Describe the bug**
插入一条数据后，设置变量值为 set @get_laster_id=LAST_INSERT_ID() 时不生效，使用 select @get_laster_id 无法查询出正确值，而MySQL是可以的。
尝试过 set @get_laster_id=now() 以及 set @get_laster_id=version() ，使用 select @get_laster_id 均可查询出正确值，唯独 set @get_laster_id=LAST_INSERT_ID() 不行。
目前解决是使用select la.laste_id into @get_laster_id from (select LAST_INSERT_ID() as laste_id) as la 才能生效，无法使用set。

**Environment**
OS：centos7.3
Version：5.7.25-OceanBase_CE-v4.0.0.0

**Comment by hnwyllmm** [comment]
I have tried to reproduce the scenario.
```sql
mysql> create table t1 (id int not null auto_increment, name char(20));
Query OK, 0 rows affected (0.03 sec)
mysql> insert into t1 (name) values('a');
Query OK, 1 row affected (0.01 sec)
mysql> select LAST_INSERT_ID();
+------------------+
| LAST_INSERT_ID() |
+------------------+
|                1 |
+------------------+
1 row in set (0.01 sec)
mysql> set @get_laster_id=LAST_INSERT_ID();
Query OK, 0 rows affected (0.00 sec)

mysql> select @get_laster_id;
+----------------+
| @get_laster_id |
+----------------+
|              1 |
+----------------+
1 row in set (0.00 sec)
```

It shows that `get_laster_id` would be the value of `LAST_INSERT_ID()`.
Did you mean `get_laster_id` should follow the value of `LAST_INSERT_ID()`?

**Comment by cjlmu** [comment]
> I have tried to reproduce the scenario.
> 
> ```sql
> mysql> create table t1 (id int not null auto_increment, name char(20));
> Query OK, 0 rows affected (0.03 sec)
> mysql> insert into t1 (name) values('a');
> Query OK, 1 row affected (0.01 sec)
> mysql> select LAST_INSERT_ID();
> +------------------+
> | LAST_INSERT_ID() |
> +------------------+
> |                1 |
> +------------------+
> 1 row in set (0.01 sec)
> mysql> set @get_laster_id=LAST_INSERT_ID();
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql> select @get_laster_id;
> +----------------+
> | @get_laster_id |
> +----------------+
> |              1 |
> +----------------+
> 1 row in set (0.00 sec)
> ```
> 
> It shows that `get_laster_id` would be the value of `LAST_INSERT_ID()`. Did you mean `get_laster_id` should follow the value of `LAST_INSERT_ID()`?


Why is my result like this? 
```

mysql> create table t1 (id int not null auto_increment, name char(20));
Query OK, 0 rows affected (0.61 sec)

mysql> insert into t1 (name) values('a');
Query OK, 1 row affected (0.08 sec)

mysql> select LAST_INSERT_ID();
+------------------+
| LAST_INSERT_ID() |
+------------------+
|                1 |
+------------------+
1 row in set (0.00 sec)

mysql> set @get_laster_id=LAST_INSERT_ID();
Query OK, 0 rows affected (0.00 sec)

mysql> select @get_laster_id;
+----------------+
| @get_laster_id |
+----------------+
|              0 |
+----------------+
1 row in set (0.00 sec)

```
Which configuration needs to be modified?

**Comment by hnwyllmm** [comment]
Nothing, I used the default configuration.
Can you try it on the latest OceanBase?
You can use `obd demo` command to try the latest version.

**Comment by cjlmu** [comment]
> Nothing, I used the default configuration. Can you try it on the latest OceanBase? You can use `obd demo` command to try the latest version.

I installed OceanBase 4.0.0 using the OBD tool in an offline environment. Is it the problem with this version? May I ask which version you are using?

**Comment by hnwyllmm** [comment]
The latest version.
And if you are testing the oceanbase, please upgrade it to the latest version as 4.0.0 is not a LTS version.

**Comment by cjlmu** [comment]
> The latest version. And if you are testing the oceanbase, please upgrade it to the latest version as 4.0.0 is not a LTS version.

Okay, I will upgrade before using it. Thank you
