### ISSUE TITLE
请问一下提测平台oceanbase这道题的这个找不到文件或目录是啥意思？

### ISSUE THREAD

**Issue by ShuquanWei** [oceanbase/oceanbase#1625]
**Question**
compile failed. command=['bash', '/data/test/players/source/oceanbase/build.sh', '-DOB_USE_CCACHE=ON', '--init', '--make', '-j2', '--silent']. bash: /data/test/players/source/oceanbase/build.sh: No such file or directory
错误信息如上
请问，我的仓库克隆下来是能编译部署的，为什么在提测平台上就不行了呢？

**Environment**
Ubuntu22.04

**Comment by hnwyllmm** [comment]
We couldn't find `build.sh` in your repo.
Check it?

**Comment by ShuquanWei** [comment]
i have this file in my repo，but it still couldn't work in the platform



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [oceanbase/oceanbase] 请问一下提测平台oceanbase这道题的这个找不到文件或目录是啥意思？ (Issue #1625)




 
We couldn't find build.sh in your repo.
 Check it?

**Comment by hnwyllmm** [comment]
Please write your repo here and let me have a look.

**Comment by ShuquanWei** [comment]
https://gitee.com/CutePigKk/ob.git，it is a private and i not sure if you can see it.if get any problem please email me



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 下午5:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [oceanbase/oceanbase] 请问一下提测平台oceanbase这道题的这个找不到文件或目录是啥意思？ (Issue #1625)




 
Please write your repo here and let me have a look.

**Comment by hnwyllmm** [comment]
I see that.
Your build.sh is under OB/oceanbase/, but it should be in the directory OB/.
You can move all file under OB/oceanbase/ to OB/ and try again.

**Comment by ShuquanWei** [comment]
thanks i will try it again later
