### ISSUE TITLE
[Feature]: 大哥们捞捞简历吧

### ISSUE THREAD

**Issue by wiskiy** [oceanbase/oceanbase#1633]
https://wiskiy.github.io/

大哥们捞一下简历吧，简历细节都在主页了

**Comment by caifeizhi** [comment]
Thank you very much for your interest and contribution to our project. 
We suggest that you concentrate on technical issues, bug reports, or feature requests in our project. If you are interested in our project and would like to join, you can visit this link: https://talent.antgroup.com/off-campus?search=OceanBase
