### ISSUE TITLE
[Question]: header file location

### ISSUE THREAD

**Issue by Young-Cody** [oceanbase/oceanbase#1638]
**Question**
In general, deps/oblib does not depend on src. But in [deps/oblib/src/lib/wide_integer/ob_wide_integer_helper.h](https://github.com/oceanbase/oceanbase/blob/master/deps/oblib/src/lib/wide_integer/ob_wide_integer_helper.h), it includes [src/sql/engine/ob_bit_vector.h](https://github.com/oceanbase/oceanbase/blob/d3d55f717fdbd3f96df0597f3a1e52fbb9756c4e/src/sql/engine/ob_bit_vector.h). Should we put ob_bit_vector.h in oblib?

**Comment by hnwyllmm** [comment]
No, please don't touch it.

**Comment by Young-Cody** [comment]
OK. Thanks.
