### ISSUE TITLE
[Bug]: Estimating the cardinality exceeds the table size

### ISSUE THREAD

**Issue by Freejww** [oceanbase/oceanbase#1671]
**Describe the bug**

**Environment**

- OS Version and CPU Arch(`uname -a`):
Linux/ Centos 7
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
Server version: 5.7.25 0ceanBase 4.2.0.0 (r101000032023091319-600ea4557d9847784acfa3e6b7a7d24595891c6) (Built Sep 13 2023 20:02:19)

**Fast Reproduce Steps(Required)**

Create table
Load data
Explain query
[error estimation.zip](https://github.com/oceanbase/oceanbase/files/13390454/error.estimation.zip)

**Expected behavior**
We have a query for which the cardinality of the result approaches the table size. The cardinality of the estimation should close to the actual cardinality.

**Actual Behavior**
But the cardinality of the estimation exceeds the table size.

**Additional context**
We encountered this issue while handling non-equality predicates and 'NOT IN' predicates.

**Comment by hnwyllmm** [comment]
Could you please upload the explain result on your system?

**Comment by Freejww** [comment]
mysql> select count(*) from table_1;
+----------+
| count(*) |
+----------+
|   100000 |
+----------+
1 row in set (0.04 sec)

mysql> select  count(*) as result from table_1 where table_1.col_2 != 25683;
+--------+
| result |
+--------+
|  98322 |
+--------+
1 row in set (0.05 sec)

mysql> explain select  count(*) as result from table_1 where table_1.col_2 != 25683;
+------------------------------------------------------------------------------------+
| Query Plan                                                                         |
+------------------------------------------------------------------------------------+
| ====================================================                               |
| |ID|OPERATOR         |NAME   |EST.ROWS|EST.TIME(us)|                               |
| ----------------------------------------------------                               |
| |0 |SCALAR GROUP BY  |       |1       |9358        |                               |
| |1 |└─TABLE FULL SCAN|table_1|103232  |7487        |                               |
| ====================================================                               |
| Outputs & filters:                                                                 |
| -------------------------------------                                              |
|   0 - output([T_FUN_COUNT_SUM(T_FUN_COUNT(*))]), filter(nil), rowset=256           |
|       group(nil), agg_func([T_FUN_COUNT_SUM(T_FUN_COUNT(*))])                      |
|   1 - output([T_FUN_COUNT(*)]), filter([table_1.col_2 != 25683]), rowset=256       |
|       access([table_1.col_2]), partitions(p0)                                      |
|       is_index_back=false, is_global_index=false, filter_before_indexback[false],  |
|       range_key([table_1.primaryKey]), range(MIN ; MAX)always true                 |
+------------------------------------------------------------------------------------+
14 rows in set (0.00 sec)

**Comment by hnwyllmm** [comment]
```
obclient> explain select  count(*) as result from table_0 where table_0.col_2 != 25683;
+------------------------------------------------------------------------------------+
| Query Plan                                                                         |
+------------------------------------------------------------------------------------+
| ====================================================                               |
| |ID|OPERATOR         |NAME   |EST.ROWS|EST.TIME(us)|                               |
| ----------------------------------------------------                               |
| |0 |SCALAR GROUP BY  |       |1       |8474        |                               |
| |1 |└─TABLE FULL SCAN|table_0|102962  |6608        |                               |
| ====================================================                               |
| Outputs & filters:                                                                 |
| -------------------------------------                                              |
|   0 - output([T_FUN_COUNT_SUM(T_FUN_COUNT(*))]), filter(nil), rowset=256           |
|       group(nil), agg_func([T_FUN_COUNT_SUM(T_FUN_COUNT(*))])                      |
|   1 - output([T_FUN_COUNT(*)]), filter([table_0.col_2 != 25683]), rowset=256       |
|       access([table_0.col_2]), partitions(p0)                                      |
|       is_index_back=false, is_global_index=false, filter_before_indexback[false],  |
|       range_key([table_0.primaryKey]), range(MIN ; MAX)always true,                |
|       pushdown_aggregation([T_FUN_COUNT(*)])                                       |
+------------------------------------------------------------------------------------+
15 rows in set (0.03 sec)
```
I reproduced

**Comment by Freejww** [comment]
In the statistic of TiDB, the total number of rows in a table is recorded. However, in the case of OceanBase, an estimate beyond the table size, I would like to know the reason.

**Comment by hnwyllmm** [comment]
The row number is estimated by the storage engine and if there are mini-sstable/minor-sstable exist, the row number estimated is not in accurately.
I have tested by the SQL below and it can make estimate result better.
```sql
alter system major freeze;
analyze table table_0 compute statistics for all columns size 1;
```

**Comment by Freejww** [comment]
thanks!
