### ISSUE TITLE
[Bug]: invalid log print in ob_memtable_context.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#1673]
**Describe the bug**

When print `char*` value in the log, it trait the value as a c-string.
We cannot print `buf` in fill_redo_log@ob_memtable_context.cpp as a c-string as it is a binary buffer.

Use `KP` is better.

**Comment by Dennis40816** [comment]
Could I work on this?

**Comment by hnwyllmm** [comment]
assigned
