### ISSUE TITLE
[Bug]:  docker oceanbase-ce observer crash on mac m2

### ISSUE THREAD

**Issue by xxaier** [oceanbase/oceanbase#1675]
see image as below 

![image](https://github.com/oceanbase/oceanbase/assets/130831741/60b54f53-9af5-4f4f-8d6c-18e7d6e63931)

- OS Version and CPU Arch(`uname -a`):
-Darwin zm2-7.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  docker Digest: sha256:b40b49a0619e16dfb0cd708ed16ab799f7c4d036436e92abd5181a997f50171c

**Comment by derecknowayback** [comment]
You should try 4.2.0.0 which has an arm version image.

**Comment by xxaier** [comment]
it works , thanks
