### ISSUE TITLE
[Bug]: Docker use '-v' argument boot failed.

### ISSUE THREAD

**Issue by derecknowayback** [oceanbase/oceanbase#1676]
**Describe the bug**
Use docker with -v argument failed on macos/arm with version 4.2.0.0 .

**Environment**
- OS Version and CPU Arch(`uname -a`):
macos / darwin arm64
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
 4.2.0.0 

**Fast Reproduce Steps(Required)**

```bash
docker run -p 2881:2881 --name oceanbase-ce-4.0 -e MINI_MODE='true' -v $PWD/ob/data:/root -d oceanbase/oceanbase-ce:4.0.0.0
```

**Expected behavior**
boot success.

**Actual Behavior**
2023-11-22 23:36:38 /bin/sh: _boot: command not found

**Comment by hnwyllmm** [comment]
```
docker run -d -p 2881:2881 -v $PWD/ob:/root/ob -v $PWD/obd:/root/.obd --name oceanbase oceanbase/oceanbase-ce
```

**Comment by derecknowayback** [comment]
> ```
> docker run -d -p 2881:2881 -v $PWD/ob:/root/ob -v $PWD/obd:/root/.obd --name oceanbase oceanbase/oceanbase-ce
> ```

Thanks !
