### ISSUE TITLE
Why can I use a non-existent database?

### ISSUE THREAD

**Issue by Amber1990Zhang** [oceanbase/oceanbase#169]
As title.
![image](https://user-images.githubusercontent.com/42762957/126439686-46d8e1a0-c6e0-4e31-9066-e3476dfb070a.png)
Isn't the database name supposed to be **CASE SENSITIVE**？

**Comment by Amber1990Zhang** [comment]
After some tests, I think the database name is case insensitive, which to me is kind of weird. Why?

**Comment by hnwyllmm** [comment]
Please refer 
https://mariadb.com/docs/reference/es/system-variables/lower_case_table_names/#:~:text=The%20lower_case_table_names%20system%20variable%20determines%20whether%20table%20names%2C,aliases%2C%20and%20database%20names%20are%20compared%20in%20
