### ISSUE TITLE
left/right join 的条件中存在子查询时不支持

### ISSUE THREAD

**Issue by TyphoonTai** [oceanbase/oceanbase#172]
oceanbase 中 left/right join 的条件中存在子查询时不支持

复现过程
**mysql5.6/5.7：**

表结构如下
CREATE TABLE `join_test` (
  `id` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

mysql> `insert into join_test values (1),(2),(3);`
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> `select * from join_test;`
+------+
| id   |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.00 sec)

mysql> `select * from join_test a left join join_test b on a.id in (select max(id) from join_test);`
+------+------+
| id   | id   |
+------+------+
|    3 |    1 |
|    3 |    2 |
|    3 |    3 |
|    1 | NULL |
|    2 | NULL |
+------+------+
5 rows in set (0.00 sec)

**oceanbase3.1.2：**

CREATE TABLE `join_test` (
  `id` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

mysql> `insert into join_test values (1),(2),(3);`
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> `select * from join_test;`
+------+
| id   |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.02 sec)

mysql> `select * from join_test a left join join_test b on a.id in (select max(id) from join_test);`
**ERROR 1235 (0A000): Not supported feature or function**

**Comment by liboyang0730** [comment]
谢谢你的回复。

这个 OB 暂时还不支持，如果在使用中发现报错是 Not supported feature 的时候，可以认为是 OB 已知的不支持的功能或特性，可以不需要再提出 issue 了。

再次感谢你对 OB 的关注！

**Comment by liboyang0730** [comment]
OB 已知的不支持的功能或特性。
