### ISSUE TITLE
聚合函数与别名使用问题

### ISSUE THREAD

**Issue by TyphoonTai** [oceanbase/oceanbase#173]
oceanbase中对某字段使用聚合函数后对结果设置成相同字段别名后，使用聚合结果排序必须使用别名，不能使用原来的聚合函数排序。
如：先使用` sum(data) as data` 再使用 `order by sum(data)` 会失败 

复现过程：
**mysql5.6/5.7：**

CREATE TABLE `test` (
  `id` int(10) DEFAULT NULL,
  `data` int(10) DEFAULT NULL,
  `tag` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

mysql> `insert into test values (1,1,'a'),(2,2,'a'),(3,3,'b');`

mysql> `select * from test;`
+------+------+------+
| id   | data | tag  |
+------+------+------+
|    1 |    1 | a    |
|    2 |    2 | a    |
|    3 |    3 | b    |
+------+------+------+
3 rows in set (0.00 sec)

mysql> `select tag,sum(data) as data from test group by tag order by sum(data);`
+------+------+
| tag  | data |
+------+------+
| a    |    3 |
| b    |    3 |
+------+------+
2 rows in set (0.00 sec)

**oceanbase3.1.2：**

CREATE TABLE `test` (
  `id` int(10) DEFAULT NULL,
  `data` int(10) DEFAULT NULL,
  `tag` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

mysql> `insert into test values (1,1,'a'),(2,2,'a'),(3,3,'b');`

mysql> `select * from test;`
+------+------+------+
| id   | data | tag  |
+------+------+------+
|    1 |    1 | a    |
|    2 |    2 | a    |
|    3 |    3 | b    |
+------+------+------+
3 rows in set (0.02 sec)

mysql> `select tag,sum(data) as data from test group by tag order by sum(data);`
**ERROR 1111 (HY000): Invalid use of group function**

**Comment by liboyang0730** [comment]
谢谢你的回复。

看上去是 OB 在解析 order by sum(data) 时将 data 当做是聚合函数的别名了，所以 order by sum(data) 就被解析成了 order by sum(sum(data))，此时会被检查出在聚集函数中含有同层级的聚集函数嵌套，所以报错了。

我们会尽快修复这个问题，再次感谢！

**Comment by liboyang0730** [comment]
问题已修复，下一个版本会带上。
