### ISSUE TITLE
[Feature]: Handle corrupted tables

### ISSUE THREAD

**Issue by liolay** [oceanbase/oceanbase#1735]
**Use Case**
When a server subsystem tries to access a corrupted table(caurse by unexpected power outage or anyother reasons), the server may crash. 

**Describe the solution you'd like**

We need a strategy to recovery our datas, currently, recovery from backups lost too many datas. 

**Describe alternatives you've considered**

Mysql's recovery mode or Percona's [innodb_corrupt_table_action ](https://docs.percona.com/percona-server/innovation-release/innodb-corrupt-table-action.html#interacting-with-the-innodb_force_recovery-variable) maybe a good solution while someone running OB only have single replication

**Additional context**

**Comment by hnwyllmm** [comment]
It's a very interesting question. I need to discuss with others first.

**Comment by hnwyllmm** [comment]
I think oceanbase don't have such issue.
OB use LSM-tree as the storage structure, and it uses WAL to ensure every modification can be redo.
For single machine, the data may be lost, but it shouldn't be in corruption status.

**Comment by hnwyllmm** [comment]
Hi @liolay , did you experience such a scenario about OB? That's a severe fault.

**Comment by liolay** [comment]
> Hi @liolay , did you experience such a scenario about OB? That's a severe fault.

Thanks for  your reply. Not yet, just considering in advance to avoid unsolvable problems in the production environment.

**Comment by hnwyllmm** [comment]
Thanks. This is an interesting issue.

**Comment by hnwyllmm** [comment]
I will close this issue but if you have any other questions, please feel free to reopen it.
