### ISSUE TITLE
"table_id" in __all_table_v2 is different from gv$partition

### ISSUE THREAD

**Issue by donghy-coredumped** [oceanbase/oceanbase#174]
I want to query the distribution of tables under the tenant I created，sql is
```
select t5.tenant_name, t3.database_name, t4.tablegroup_name, t1.table_name, t2.partition_id, t2.role, t2.zone, concat(t2.svr_ip, ':', t2.svr_port) observer, t2.`row_count`, round(t2.data_size/1024/1024) data_size_mb
from __all_table_v2 t1 join gv$partition t2 on (t1.tenant_id=t2.tenant_id and t1.table_id=t2.table_id)
    join gv$database t3 on (t1.tenant_id=t3.tenant_id and t1.database_id=t3.database_id)
    left join __all_tablegroup t4 on (t1.tenant_id=t4.tenant_id and t1.tablegroup_id=t4.tablegroup_id)
    join __all_tenant t5 on (t1.tenant_id=t5.tenant_id)
where t5.tenant_id=1012 and t2.role=1 and t1.table_name in ('dhytest','dhytest2','dhytest3')
order by t5.tenant_name, t3.database_name, t4.tablegroup_name, t2.partition_id, t2.zone, t2.svr_ip, t2.svr_port, t1.table_name,partition_id
;
```
But this SQL returns empty，reasons may be The "table_id" in __all_table_v2 is different from gv$partition :
```
MySQL [oceanbase]> select tenant_id, table_id , table_name from __all_table_v2 where table_name = 'dhytest2';
+-----------+----------+------------+
| tenant_id | table_id | table_name |
+-----------+----------+------------+
|         0 |    50002 | dhytest2   |
+-----------+----------+------------+
1 row in set (0.001 sec)

MySQL [oceanbase]> select * from gv$partition  where table_id = 50002;
ERROR 1210 (HY000): Invalid argument
MySQL [oceanbase]> select table_id  from gv$partition group by table_id limit 10 ;
+------------------+
| table_id         |
+------------------+
| 1100611139453778 |
| 1100611139453779 |
| 1100611139404029 |
| 1100611139404008 |
| 1100611139403941 |
| 1100611139404060 |
| 1100611139404035 |
| 1100611139403895 |
| 1100611139404014 |
| 1100611139403919 |
+------------------+
10 rows in set (0.037 sec)

```

**Comment by obpilot** [comment]
SELECT  t.tenant_id, a.tenant_name, t.table_name, d.database_name,  tg.tablegroup_name , t.part_num , t2.partition_id, t2.ZONE, t2.svr_ip , t2.data_size
	, a.primary_zone	  , IF(t.locality = '' OR t.locality IS NULL, a.locality, t.locality) AS locality	
FROM oceanbase.__all_tenant AS a  
	JOIN oceanbase.__all_virtual_database AS d ON ( a.tenant_id = d.tenant_id  ) 
	JOIN oceanbase.__all_virtual_table AS t  ON (t.tenant_id = d.tenant_id AND t.database_id = d.database_id)	
	JOIN oceanbase.__all_virtual_meta_table t2 ON (t.tenant_id = t2.tenant_id AND (t.table_id=t2.table_id OR t.tablegroup_id=t2.table_id)  AND t2.ROLE IN (1) )
	LEFT JOIN oceanbase.__all_virtual_tablegroup AS tg ON (t.tenant_id = tg.tenant_id and  t.tablegroup_id = tg.tablegroup_id) 
WHERE a.tenant_id IN (1012 ) AND  t.table_type IN (3)  
-- AND d.database_name = 'test' 
 and table_name in ('dhytest2','dhytest','dhytest3')
ORDER BY t.tenant_id, tg.tablegroup_name, d.database_name, t.table_name, t2.partition_id
;

**Comment by donghy-coredumped** [comment]
thanks
