### ISSUE TITLE
[Question]: Why bypass the batch insert plan cache optimization for the inner sql?

### ISSUE THREAD

**Issue by jscblack** [oceanbase/oceanbase#1743]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**

Currently the batch insert plan cache works well, though the requirement is a little bit tight. But why the inner_sql (usually very simple but cost much if always generate phy plan for them) cannot benefit from the insert plan cache optimization, especially in the bootstrap scenario.

Based on this, we tested the inner_sql do benefit from the batch insert plan cache optimization, and have no side-effect.

Maybe a manual force plan cache eviction can be introduced in to guarantee both the inner_sql performance and cache size/availability?

**Environment**

- OS Version and CPU Arch(`uname -a`):
Not related
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
Not related

**Comment by GITHUBear** [comment]
There may be two reasons for not enabling PC during Bootstrap: 
1. When there is no variable-length value list insertion optimization, the memory usage will be relatively large; 
2. After Bootstrap finishes refresh_schema, the schema version of the table will increase, causing the plan cache to be evicted. 
But there is indeed optimization for create_all_schema to enable plan cache.

**Comment by jscblack** [comment]
Thanks for your explanation. I will close it..
