### ISSUE TITLE
ob_error tool

### ISSUE THREAD

**Issue by a1iive** [oceanbase/oceanbase#176]
Both Oracle and MySQL have their own error tools, named **oerr** and **perror** respectively. 

The error tool can return the information, reason and solution corresponding to the error code according to the error code entered by the user. It saves the trouble of looking up documents.

such as:
```
$ oerr ora 600

ora-00600: internal error code, arguments: [%s], [%s], [%s], [%s], [%s], [%s], [%s], [%s]

 *Cause:  This is the generic internal error number for Oracle program

​     exceptions.  This indicates that a process has encountered an

​     exceptional condition.

 *Action: Report as a bug - the first argument is the internal error number
```
```
$ perror 1231

MySQL error code MY-001231 (ER_WRONG_VALUE_FOR_VAR): Variable '%-.64s'

can't be set to the value of '%-.200s'
```
But OceanBase doesn't have such a tool at present.

For ease of use, such a tool is needed, which named **ob_error**.

**Comment by LINxiansheng** [comment]
Good Idea.
