### ISSUE TITLE
[Bug]: Link errors from build.sh compiling

### ISSUE THREAD

**Issue by nayutah** [oceanbase/oceanbase#1765]
**Describe the bug**
[100%] Linking CXX shared library libobcdc.so
ld.lld: error: undefined symbol: Aws::AmazonWebServiceRequest::SetAdditionalCustomHeaderValue(std::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&, std::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&)
>>> referenced by ob_storage_s3_base.cpp:1166 (./deps/oblib/src/lib/restore/ob_storage_s3_base.cpp:1166)
>>>               ob_storage_s3_base.cpp.o:(oceanbase::common::ObStorageS3Reader::pread_(char*, long, long, long&)) in archive ../../deps/oblib/src/liboblib.a

ld.lld: error: undefined symbol: Aws::Utils::Crypto::CRC32::Calculate(std::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&)
>>> referenced by ob_storage_s3_base.cpp:2076 (./deps/oblib/src/lib/restore/ob_storage_s3_base.cpp:2076)
>>>               ob_storage_s3_base.cpp.o:(oceanbase::common::ObStorageS3MultiPartWriter::write_single_part_()) in archive ../../deps/oblib/src/liboblib.a

ld.lld: error: undefined symbol: Aws::Utils::HashingUtils::Base64Encode(Aws::Utils::Array<unsigned char> const&)
>>> referenced by ob_storage_s3_base.cpp:1994 (./deps/oblib/src/lib/restore/ob_storage_s3_base.cpp:1994)
>>>               ob_storage_s3_base.cpp.o:(oceanbase::common::ObStorageS3MultiPartWriter::close_()) in archive ../../deps/oblib/src/liboblib.a

ld.lld: error: undefined symbol: Aws::Endpoint::DefaultEndpointProvider<Aws::S3::S3ClientConfiguration, Aws::S3::Endpoint::S3BuiltInParameters, Aws::S3::Endpoint::S3ClientContextParameters>::OverrideEndpoint(std::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&)
>>> referenced by ob_storage_s3_base.cpp
>>>               ob_storage_s3_base.cpp.o:(vtable for Aws::S3::Endpoint::S3EndpointProvider) in archive ../../deps/oblib/src/liboblib.a

ld.lld: error: undefined symbol: EVP_MD_get_size
>>> referenced by ub_core.cpp
>>>               ub_core.cpp.o:(Aws::Utils::Crypto::MD5OpenSSLImpl::Calculate(std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&)) in archive /home/slc/oceanbase/deps/3rd/usr/local/oceanbase/deps/devel/lib64/libaws-cpp-sdk-core.a
>>> referenced by ub_core.cpp
>>>               ub_core.cpp.o:(Aws::Utils::Crypto::MD5OpenSSLImpl::Calculate(std::istream&)) in archive /home/slc/oceanbase/deps/3rd/usr/local/oceanbase/deps/devel/lib64/libaws-cpp-sdk-core.a
>>> referenced by ub_core.cpp
>>>               ub_core.cpp.o:(Aws::Utils::Crypto::MD5OpenSSLImpl::GetHash()) in archive /home/slc/oceanbase/deps/3rd/usr/local/oceanbase/deps/devel/lib64/libaws-cpp-sdk-core.a
>>> referenced 7 more times

**Environment**

Linux 6.2.0-1018-gcp \#20\~22.04.1-Ubuntu SMP Mon Oct 23 12:29:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
\~/oceanbase\$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1\~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1\~22.04)

OB from develop branch
   

**Fast Reproduce Steps(Required)**

1. ./build.sh debug --init --make

**Comment by hnwyllmm** [comment]
Please fetch the latest code and recompile again.

**Comment by nayutah** [comment]
solved in the latest version
