### ISSUE TITLE
[Enhancement]: [oblogminer] enhance usability.

### ISSUE THREAD

**Issue by nautaa** [oceanbase/oceanbase#1785]
**Enhancement**
[oblogminer] enhance usability. 

User-friendly error messages, progress displays.

for example:
Currently, oblogminer periodically prints the task progress on the command line, and the progress bar is currently a fixed-width display. It would be better to adjust the width of the progress bar to an adaptive length.

https://github.com/oceanbase/oceanbase/blob/51913c68f1aa19edc923123ee647f6092e994577/src/logservice/logminer/ob_log_miner_logger.h#L26

Possibly helpful header file: `sys/ioctl.h`

subtask of #1782

**Comment by zztaki** [comment]
I want to try it. :)

**Comment by nautaa** [comment]
@zztaki Thanks, Some contextual information is available: https://github.com/oceanbase/oceanbase/issues/1896#issuecomment-2028045377

**Comment by zztaki** [comment]
> @zztaki Thanks, Some contextual information is available: [#1896 (comment)](https://github.com/oceanbase/oceanbase/issues/1896#issuecomment-2028045377)

Thanks @nautaa, awesome information! :)
