### ISSUE TITLE
[Enhancement]: oceanbase process uses almost 100% single thread cpu all the time doing nothing.

### ISSUE THREAD

**Issue by sprappcom** [oceanbase/oceanbase#1788]
possible to let it sip cpu usage since it is doing nothing? it's like eating 100% cpu all the time. maybe set a mode where it is not so aggressively eating the CPU

**Comment by dimstars** [comment]
What version of OceanBase are you using? How many tenants are in the cluster? 
Since version 4.2, we have reduced the CPU overhead of a single tenant to less than 0.2 cores.

**Comment by sprappcom** [comment]
@dimstars was using the docker version, just upgraded and see it as 0.28 core. thx
