### ISSUE TITLE
[Question]: 请问如何禁止输出tracing日志来降低空载cpu消耗

### ISSUE THREAD

**Issue by i18n-now** [oceanbase/oceanbase#1809]
一个空的无负载的oceanbase数据库（创建了一个租户）
一个节点一直占用了70%的cpu，我看了一下日志，发现日志很多，而且其中有这个错误

```
[2024-01-23 22:29:53.341634] ERROR resize_ (ob_server_log_block_mgr.cpp:203) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=101][errcode=-4007] Not supported feature or function(possible reason="new log_disk_size is not enough to hold all tenants, please check the configuration about log disk", new log disk size(MB)=13312, min log disk size(MB)=14336)
```
请问应该如何修复

<img width="1727" alt="image" src="https://github.com/oceanbase/oceanbase/assets/145643935/900136f9-c1bd-4b70-9929-3af0248d1f6b">

请问如何解决这个错误
[2024-01-23 22:29:53.341634] ERROR resize_ (ob_server_log_block_mgr.cpp:203) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=101][errcode=-4007] Not supported feature or function(possible reason="new log_disk_size is not enough to hold all tenants, please check the configuration about log disk", new log disk size(MB)=13312, min log disk size(MB)=14336)
[2024-01-23 22:29:53.341661] ERROR issue_dba_error (ob_log.cpp:1853) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=24][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4007, file="ob_server_log_block_mgr.cpp", line_no=783, info="ObServerLogBlockMGR resize failed")

```
97440,size=265,type=2,seq=0), type:"MAJOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:0, v:0}, end_scn:{val:1, v:0}}, snapshot_version:1, max_merge_version:1}}, minor_tables:{{i:0, addr:[18874-901-0-2305843887536103689-0](offset=1597705,size=818,type=2,seq=0), type:"MINOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:1, v:0}, end_scn:{val:1706020188329356108, v:0}}, contain_uncommitted_row:"no", max_merge_version:4096, upper_trans_version:4096}}, ddl_sstables:{null}, ddl_mem_sstables:{null}, meta_major_tables:{null}, memtables_:{{i:0, memtable:{ObITable:{this:0x7fdadbc52080, key:{tablet_id:{id:49402}, column_group_idx:0, table_type:"TX_DATA_MEMTABLE", scn_range:{start_scn:{val:1706020188329356108, v:0}, end_scn:{val:1706020191841971753, v:0}}}, ref_cnt:4, upper_trans_version:-4007, timestamp:0}, is_inited:true, is_iterating:false, pre_process_done:true, construct_list_done:true, min_tx_scn:{val:1706020191572845809, v:0}, max_tx_scn:{val:1706020191841971753, v:0}, min_start_scn:{val:1706020191572845809, v:0}, snapshot_version:{val:1706020191572845809, v:0}, inserted_cnt:4, deleted_cnt:0, write_ref:0, occupied_size:0, state:2, stat_change_ts:{frozen_time:1706020192172315, ready_for_flush_time:1706020192172367, create_flush_dag_time:1706020192172458, release_time:0}, tx_data_map:0x7fdadff50060, memtable_mgr:0x7fdae1d5c1b0, commit_versions_serialize_size:0, row_key_array:[], tx_id_2_range:[]}}}}}, addr:[18874-901-0-2305843316305457152-0](offset=1601536,size=286,type=2,seq=0)}, storage_schema_addr:{ptr:null, addr:[18874-901-0-2305843162760376606-0](offset=1601822,size=143,type=2,seq=0)}, mds_data:{is_inited:true, tablet_status:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:(nil), addr:[18874-901-0-2305843270134559149-0](offset=1601965,size=243,type=2,seq=0)}}, aux_tablet_info:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}}, extra_medium_info:{info:1, compat:1, last_compaction_type:0, wait_check_flag:0, last_medium_scn:0}, medium_info_list:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, auto_inc_seq:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, tablet_status_cache:{tablet_status:{val:1, str:"NORMAL"}, transfer_scn:{val:18446744073709551615, v:3}, transfer_ls_id:{id:-1}, data_type:1, create_commit_scn:{val:18446744073709551615, v:3}, create_commit_version:-1, delete_commit_scn:{val:18446744073709551615, v:3}, delete_commit_version:-1, transfer_out_commit_version:-1}}, ddl_kvs:null, ddl_kv_count:0, memtables:[0x7fdadbc52080, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], memtable_count:1}, this={this:0x7fda95d6c060, is_inited:true, wash_score:-9223372036854775808, hold_ref_cnt:true, ref_cnt:1, version:2, length:0, tablet_addr:[0-0-0-3458765810900664320-0](offset=0,size=1208,type=3,seq=0), allocator:0x7fdae3056650, tablet_meta:{version:1, ls_id:{id:1}, tablet_id:{id:49402}, data_tablet_id:{id:49402}, ref_tablet_id:{id:0}, has_next_tablet:false, create_scn:{val:1, v:0}, start_scn:{val:1, v:0}, clog_checkpoint_scn:{val:1706020191841971753, v:0}, ddl_checkpoint_scn:{val:1, v:0}, snapshot_version:1706020191572845809, multi_version_start:1, compat_mode:0, ha_status:{restore_status:0, data_status:0, expected_status:0, reserved:0}, report_status:{merge_snapshot_version:1, cur_report_version:1, data_checksum:0, row_count:0}, table_store_flag:{with_major_sstable:1}, ddl_start_scn:{val:0, v:0}, ddl_snapshot_version:0, max_sync_storage_schema_version:0, max_serialized_medium_scn:0, ddl_execution_id:-1, ddl_data_format_version:0, ddl_commit_scn:{val:0, v:0}, mds_checkpoint_scn:{val:1, v:0}, transfer_info:{ls_id:{id:0}, transfer_start_scn:{val:0, v:0}, transfer_seq:0, has_transfer_table:false}, create_schema_version:1}, table_store_addr:{ptr:{this:0x7fda95d6c660, version:257, major_tables:{cnt:1, is_inited:true}, minor_tables:{cnt:2, is_inited:true}, ddl_sstables:{cnt:0, is_inited:false}, meta_major_tables:{cnt:0, is_inited:false}, memtables:{count:1}, is_ready_for_read:true, sstable_arrays:{major_tables:{{i:0, addr:[18874-901-0-2305843293756874752-0](offset=1597440,size=265,type=2,seq=0), type:"MAJOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:0, v:0}, end_scn:{val:1, v:0}}, snapshot_version:1, max_merge_version:1}}, minor_tables:{{i:0, addr:[18874-901-0-2305843887536103689-0](offset=1597705,size=818,type=2,seq=0), type:"MINOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:1, v:0}, end_scn:{val:1706020188329356108, v:0}}, contain_uncommitted_row:"no", max_merge_version:4096, upper_trans_version:4096}, {i:1, addr:[0-0-0-3458764685619232768-0](offset=0,size=160,type=3,seq=0), type:"MINI", tablet_id:{id:49402}, scn_range:{start_scn:{val:1706020188329356108, v:0}, end_scn:{val:1706020191841971753, v:0}}, contain_uncommitted_row:"no", max_merge_version:4096, upper_trans_version:4096}}, ddl_sstables:{null}, ddl_mem_sstables:{null}, meta_major_tables:{null}, memtables_:{{i:0, memtable:{ObITable:{this:0x7fdadbc54cc0, key:{tablet_id:{id:49402}, column_group_idx:0, table_type:"TX_DATA_MEMTABLE", scn_range:{start_scn:{val:1706020191841971753, v:0}, end_scn:{val:4611686018427387903, v:0}}}, ref_cnt:3, upper_trans_version:-4007, timestamp:0}, is_inited:true, is_iterating:false, pre_process_done:false, construct_list_done:false, min_tx_scn:{val:4611686018427387903, v:0}, max_tx_scn:{val:0, v:0}, min_start_scn:{val:4611686018427387903, v:0}, snapshot_version:{val:1706020186482697896, v:0}, inserted_cnt:0, deleted_cnt:0, write_ref:0, occupied_size:0, state:0, stat_change_ts:{frozen_time:0, ready_for_flush_time:0, create_flush_dag_time:0, release_time:0}, tx_data_map:0x7fdadff5c060, memtable_mgr:0x7fdae1d5c1b0, commit_versions_serialize_size:0, row_key_array:[], tx_id_2_range:[]}}}}}, addr:[0-0-0-3458764857417924608-0](offset=0,size=320,type=3,seq=0)}, storage_schema_addr:{ptr:{this:0x7fda95d6c520, storage_schema_version:2, version:0, is_use_bloomfilter:0, column_info_simplified:1, compat_mode:0, table_type:3, index_type:0, index_status:1, row_store_type:1, schema_version:1, column_cnt:5, store_column_cnt:5, tablet_size:134217728, pctfree:10, block_size:16384, progressive_merge_round:0, master_key_id:18446744073709551615, compressor_type:1, encryption:"", encrypt_key:"", rowkey_cnt:2, rowkey_array:[{column_idx:16, meta_type:{type:"BIGINT", collation:"binary", coercibility:"NUMERIC"}, order:0}, {column_idx:17, meta_type:{type:"BIGINT", collation:"binary", coercibility:"NUMERIC"}, order:0}], column_array:[]}, addr:[0-0-0-3458764814468251648-0](offset=0,size=280,type=3,seq=0)}, mds_data:{is_inited:true, tablet_status:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:0x7fda95d6d720, dump_node:{status:UNKNOWN|UNKNOWN|INIT|False, user_data:ERROR:table_id not in tuple(255)}, addr:[0-0-0-3458764634079625216-0](offset=0,size=112,type=3,seq=0)}}, aux_tablet_info:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}}, extra_medium_info:{info:1, compat:1, last_compaction_type:0, wait_check_flag:0, last_medium_scn:0}, medium_info_list:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, auto_inc_seq:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, tablet_status_cache:{tablet_status:{val:1, str:"NORMAL"}, transfer_scn:{val:18446744073709551615, v:3}, transfer_ls_id:{id:-1}, data_type:1, create_commit_scn:{val:18446744073709551615, v:3}, create_commit_version:-1, delete_commit_scn:{val:18446744073709551615, v:3}, delete_commit_version:-1, transfer_out_commit_version:-1}}, ddl_kvs:null, ddl_kv_count:0, memtables:[0x7fdadbc54cc0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], memtable_count:1})
[2024-01-23 22:29:53.341634] ERROR resize_ (ob_server_log_block_mgr.cpp:203) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=101][errcode=-4007] Not supported feature or function(possible reason="new log_disk_size is not enough to hold all tenants, please check the configuration about log disk", new log disk size(MB)=13312, min log disk size(MB)=14336)
[2024-01-23 22:29:53.341661] ERROR issue_dba_error (ob_log.cpp:1853) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=24][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4007, file="ob_server_log_block_mgr.cpp", line_no=783, info="ObServerLogBlockMGR resize failed")
```

**Comment by i18n-now** [comment]
截图如下，我什么数据也没写，磁盘就用了5%，cpu用了41.7%
不知道这正常吗？
cpu 一直负载很高
<img width="639" alt="image" src="https://github.com/oceanbase/oceanbase/assets/145643935/94823745-9e9a-44bd-86b3-26a7f3c93751">

<img width="1716" alt="image" src="https://github.com/oceanbase/oceanbase/assets/145643935/8983aefb-0679-409d-a3ce-4fede227136c">

**Comment by i18n-now** [comment]
这个问题已经解决，原因是
创建租户的时候显示磁盘不够，然后我就
ALTER SYSTEM SET log_disk_size='30G'
但是重启后这个会被配置文件中的数据覆盖，
是修改 ~/.obd/cluster 下面的配置文件

现在剩下的问题就是如何屏蔽TRACE日志，这个感觉特别多

> 一个空的无负载的oceanbase数据库（创建了一个租户） 一个节点一直占用了70%的cpu，我看了一下日志，发现日志很多，而且其中有这个错误
> 
> ```
> [2024-01-23 22:29:53.341634] ERROR resize_ (ob_server_log_block_mgr.cpp:203) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=101][errcode=-4007] Not supported feature or function(possible reason="new log_disk_size is not enough to hold all tenants, please check the configuration about log disk", new log disk size(MB)=13312, min log disk size(MB)=14336)
> ```
> 
> 请问应该如何修复
> 
> <img alt="image" width="1727" src="https://private-user-images.githubusercontent.com/145643935/298974363-900136f9-c1bd-4b70-9929-3af0248d1f6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjI1NjQsIm5iZiI6MTcwNjAyMjI2NCwicGF0aCI6Ii8xNDU2NDM5MzUvMjk4OTc0MzYzLTkwMDEzNmY5LWMxYmQtNGI3MC05OTI5LTNhZjAyNDhkMWY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNTA0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjRhN2Y3OWYwM2FmZGE3NjZiNThiMGY1MWEyYjg3MjE2NTc3N2RiMTEzNzkwMWQ5OWE5MzBlYzRkZGU4MGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LIiO4z5QyGBBbNIpFl-ljSNUI_z7kPeHy2_-sscwxt0">
> 请问如何解决这个错误 [2024-01-23 22:29:53.341634] ERROR resize_ (ob_server_log_block_mgr.cpp:203) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=101][errcode=-4007] Not supported feature or function(possible reason="new log_disk_size is not enough to hold all tenants, please check the configuration about log disk", new log disk size(MB)=13312, min log disk size(MB)=14336) [2024-01-23 22：29：53.341634]错误resize_（ob_server_log_block_mgr.cpp：203）[1352] [OmtNodeBalancer] [T0] [YB42B8AE247A-00060F989A3053BE-0-0] [lt = 101] [errcode = -4007]不支持的特性或功能（可能原因=“新的log_disk_size不足以容纳所有租户，请检查日志磁盘的配置”，新日志磁盘大小（MB）= 13312，最小日志磁盘大小（MB）= 14336） [2024-01-23 22:29:53.341661] ERROR issue_dba_error (ob_log.cpp:1853) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=24][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4007, file="ob_server_log_block_mgr.cpp", line_no=783, info="ObServerLogBlockMGR resize failed")[2024-01-23 22：29：53.341661]错误issue_dba_error（ob_log.cpp：1853）[1352] [OmtNodeBalancer] [T0] [YB42B8AE247A-00060F989A3053BE-0-0] [lt = 24] [errcode = -4388]发生意外的内部错误，请检查内部错误代码(errcode=-4007, file="ob_server_log_block_mgr.cpp", line_no=783, info="ObServerLogBlockMGR resize failed")
> 
> ```
> 97440,size=265,type=2,seq=0), type:"MAJOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:0, v:0}, end_scn:{val:1, v:0}}, snapshot_version:1, max_merge_version:1}}, minor_tables:{{i:0, addr:[18874-901-0-2305843887536103689-0](offset=1597705,size=818,type=2,seq=0), type:"MINOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:1, v:0}, end_scn:{val:1706020188329356108, v:0}}, contain_uncommitted_row:"no", max_merge_version:4096, upper_trans_version:4096}}, ddl_sstables:{null}, ddl_mem_sstables:{null}, meta_major_tables:{null}, memtables_:{{i:0, memtable:{ObITable:{this:0x7fdadbc52080, key:{tablet_id:{id:49402}, column_group_idx:0, table_type:"TX_DATA_MEMTABLE", scn_range:{start_scn:{val:1706020188329356108, v:0}, end_scn:{val:1706020191841971753, v:0}}}, ref_cnt:4, upper_trans_version:-4007, timestamp:0}, is_inited:true, is_iterating:false, pre_process_done:true, construct_list_done:true, min_tx_scn:{val:1706020191572845809, v:0}, max_tx_scn:{val:1706020191841971753, v:0}, min_start_scn:{val:1706020191572845809, v:0}, snapshot_version:{val:1706020191572845809, v:0}, inserted_cnt:4, deleted_cnt:0, write_ref:0, occupied_size:0, state:2, stat_change_ts:{frozen_time:1706020192172315, ready_for_flush_time:1706020192172367, create_flush_dag_time:1706020192172458, release_time:0}, tx_data_map:0x7fdadff50060, memtable_mgr:0x7fdae1d5c1b0, commit_versions_serialize_size:0, row_key_array:[], tx_id_2_range:[]}}}}}, addr:[18874-901-0-2305843316305457152-0](offset=1601536,size=286,type=2,seq=0)}, storage_schema_addr:{ptr:null, addr:[18874-901-0-2305843162760376606-0](offset=1601822,size=143,type=2,seq=0)}, mds_data:{is_inited:true, tablet_status:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:(nil), addr:[18874-901-0-2305843270134559149-0](offset=1601965,size=243,type=2,seq=0)}}, aux_tablet_info:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}}, extra_medium_info:{info:1, compat:1, last_compaction_type:0, wait_check_flag:0, last_medium_scn:0}, medium_info_list:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, auto_inc_seq:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, tablet_status_cache:{tablet_status:{val:1, str:"NORMAL"}, transfer_scn:{val:18446744073709551615, v:3}, transfer_ls_id:{id:-1}, data_type:1, create_commit_scn:{val:18446744073709551615, v:3}, create_commit_version:-1, delete_commit_scn:{val:18446744073709551615, v:3}, delete_commit_version:-1, transfer_out_commit_version:-1}}, ddl_kvs:null, ddl_kv_count:0, memtables:[0x7fdadbc52080, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], memtable_count:1}, this={this:0x7fda95d6c060, is_inited:true, wash_score:-9223372036854775808, hold_ref_cnt:true, ref_cnt:1, version:2, length:0, tablet_addr:[0-0-0-3458765810900664320-0](offset=0,size=1208,type=3,seq=0), allocator:0x7fdae3056650, tablet_meta:{version:1, ls_id:{id:1}, tablet_id:{id:49402}, data_tablet_id:{id:49402}, ref_tablet_id:{id:0}, has_next_tablet:false, create_scn:{val:1, v:0}, start_scn:{val:1, v:0}, clog_checkpoint_scn:{val:1706020191841971753, v:0}, ddl_checkpoint_scn:{val:1, v:0}, snapshot_version:1706020191572845809, multi_version_start:1, compat_mode:0, ha_status:{restore_status:0, data_status:0, expected_status:0, reserved:0}, report_status:{merge_snapshot_version:1, cur_report_version:1, data_checksum:0, row_count:0}, table_store_flag:{with_major_sstable:1}, ddl_start_scn:{val:0, v:0}, ddl_snapshot_version:0, max_sync_storage_schema_version:0, max_serialized_medium_scn:0, ddl_execution_id:-1, ddl_data_format_version:0, ddl_commit_scn:{val:0, v:0}, mds_checkpoint_scn:{val:1, v:0}, transfer_info:{ls_id:{id:0}, transfer_start_scn:{val:0, v:0}, transfer_seq:0, has_transfer_table:false}, create_schema_version:1}, table_store_addr:{ptr:{this:0x7fda95d6c660, version:257, major_tables:{cnt:1, is_inited:true}, minor_tables:{cnt:2, is_inited:true}, ddl_sstables:{cnt:0, is_inited:false}, meta_major_tables:{cnt:0, is_inited:false}, memtables:{count:1}, is_ready_for_read:true, sstable_arrays:{major_tables:{{i:0, addr:[18874-901-0-2305843293756874752-0](offset=1597440,size=265,type=2,seq=0), type:"MAJOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:0, v:0}, end_scn:{val:1, v:0}}, snapshot_version:1, max_merge_version:1}}, minor_tables:{{i:0, addr:[18874-901-0-2305843887536103689-0](offset=1597705,size=818,type=2,seq=0), type:"MINOR", tablet_id:{id:49402}, scn_range:{start_scn:{val:1, v:0}, end_scn:{val:1706020188329356108, v:0}}, contain_uncommitted_row:"no", max_merge_version:4096, upper_trans_version:4096}, {i:1, addr:[0-0-0-3458764685619232768-0](offset=0,size=160,type=3,seq=0), type:"MINI", tablet_id:{id:49402}, scn_range:{start_scn:{val:1706020188329356108, v:0}, end_scn:{val:1706020191841971753, v:0}}, contain_uncommitted_row:"no", max_merge_version:4096, upper_trans_version:4096}}, ddl_sstables:{null}, ddl_mem_sstables:{null}, meta_major_tables:{null}, memtables_:{{i:0, memtable:{ObITable:{this:0x7fdadbc54cc0, key:{tablet_id:{id:49402}, column_group_idx:0, table_type:"TX_DATA_MEMTABLE", scn_range:{start_scn:{val:1706020191841971753, v:0}, end_scn:{val:4611686018427387903, v:0}}}, ref_cnt:3, upper_trans_version:-4007, timestamp:0}, is_inited:true, is_iterating:false, pre_process_done:false, construct_list_done:false, min_tx_scn:{val:4611686018427387903, v:0}, max_tx_scn:{val:0, v:0}, min_start_scn:{val:4611686018427387903, v:0}, snapshot_version:{val:1706020186482697896, v:0}, inserted_cnt:0, deleted_cnt:0, write_ref:0, occupied_size:0, state:0, stat_change_ts:{frozen_time:0, ready_for_flush_time:0, create_flush_dag_time:0, release_time:0}, tx_data_map:0x7fdadff5c060, memtable_mgr:0x7fdae1d5c1b0, commit_versions_serialize_size:0, row_key_array:[], tx_id_2_range:[]}}}}}, addr:[0-0-0-3458764857417924608-0](offset=0,size=320,type=3,seq=0)}, storage_schema_addr:{ptr:{this:0x7fda95d6c520, storage_schema_version:2, version:0, is_use_bloomfilter:0, column_info_simplified:1, compat_mode:0, table_type:3, index_type:0, index_status:1, row_store_type:1, schema_version:1, column_cnt:5, store_column_cnt:5, tablet_size:134217728, pctfree:10, block_size:16384, progressive_merge_round:0, master_key_id:18446744073709551615, compressor_type:1, encryption:"", encrypt_key:"", rowkey_cnt:2, rowkey_array:[{column_idx:16, meta_type:{type:"BIGINT", collation:"binary", coercibility:"NUMERIC"}, order:0}, {column_idx:17, meta_type:{type:"BIGINT", collation:"binary", coercibility:"NUMERIC"}, order:0}], column_array:[]}, addr:[0-0-0-3458764814468251648-0](offset=0,size=280,type=3,seq=0)}, mds_data:{is_inited:true, tablet_status:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:0x7fda95d6d720, dump_node:{status:UNKNOWN|UNKNOWN|INIT|False, user_data:ERROR:table_id not in tuple(255)}, addr:[0-0-0-3458764634079625216-0](offset=0,size=112,type=3,seq=0)}}, aux_tablet_info:{uncommitted_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, committed_kv:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}}, extra_medium_info:{info:1, compat:1, last_compaction_type:0, wait_check_flag:0, last_medium_scn:0}, medium_info_list:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, auto_inc_seq:{ptr:(nil), addr:[0-0-0-0-0](offset=0,size=0,type=0,seq=0)}, tablet_status_cache:{tablet_status:{val:1, str:"NORMAL"}, transfer_scn:{val:18446744073709551615, v:3}, transfer_ls_id:{id:-1}, data_type:1, create_commit_scn:{val:18446744073709551615, v:3}, create_commit_version:-1, delete_commit_scn:{val:18446744073709551615, v:3}, delete_commit_version:-1, transfer_out_commit_version:-1}}, ddl_kvs:null, ddl_kv_count:0, memtables:[0x7fdadbc54cc0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], memtable_count:1})
> [2024-01-23 22:29:53.341634] ERROR resize_ (ob_server_log_block_mgr.cpp:203) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=101][errcode=-4007] Not supported feature or function(possible reason="new log_disk_size is not enough to hold all tenants, please check the configuration about log disk", new log disk size(MB)=13312, min log disk size(MB)=14336)
> [2024-01-23 22:29:53.341661] ERROR issue_dba_error (ob_log.cpp:1853) [1352][OmtNodeBalancer][T0][YB42B8AE247A-00060F989A3053BE-0-0] [lt=24][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4007, file="ob_server_log_block_mgr.cpp", line_no=783, info="ObServerLogBlockMGR resize failed")
> ```

**Comment by hnwyllmm** [comment]
The `trace log` is slow query log and it is forced to flush to log file.
Please find the reason the query is slow.

**Comment by i18n-now** [comment]
我没有进行任何查询
就只是搭建了一个空的oeacnbase
创建了一个租户
其他什么也没做

**Comment by i18n-now** [comment]
https://cowtransfer.com/s/f4f49cc61ef545 点击链接查看 [ log.tar.bz2 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 u7pbg2 

我把日志传到这里了，现在闲置无数据，一个租户的情况下，负载如下下图（这是其中一台服务器，一共3台服务器）

![image](https://github.com/oceanbase/oceanbase/assets/145643935/f73e18eb-2689-44ee-9f03-073243d8be78)

![image](https://github.com/oceanbase/oceanbase/assets/145643935/42878fc6-4a86-4870-bb6a-b57346186d5e)

**Comment by hnwyllmm** [comment]
oceanbase cost too much CPU and print lots of logs. We're working on it, but we don't get a good result now.
