### ISSUE TITLE
observer启动时传参包含unicode字符无法处理时应该报错

### ISSUE THREAD

**Issue by gaodg** [oceanbase/oceanbase#181]
您好，

问题描述：
企业版Ocean Base，启动observer时，发现若传参包含unicode字符，如附件例子中（-P 5022）执行时命令成功，但rpc以默认端口2055启动，而非传递的5022。导致后续步骤报错（rpc无法连接），排障起来不方便。类似场景参数，如果是mysql客户端，则不会执行，会显示命令用法，更容易排查。

版本：observer (OceanBase CE 3.1.0)
OS：centos 7
执行命令：
bin/observer -r '1.1.1.1:5022:2883;2.2.2.2:5022:2883;3.3.3.3:5022:2883' -o datafile_size=16G,memory_limit=8G,system_memory=4G,stack_size=512K,cpu_count=8,cache_wash_threshold=1G,workers_per_cpu_quota=10,schema_history_expire_time=1d,net_thread_count=4,major_freeze_duty_time=Disable,minor_freeze_times=10,enable_separate_sys_clog=0,enable_merge_by_turn=False,datafile_disk_percentage=20,idc='idc1' -z 'zone1' -p 2883 –P5022 -c 11 -d /data/observer/store -i eth0 –n myapp –l ERROR

具体命令参见附件：
[observer_cmd_unicode.txt](https://github.com/oceanbase/oceanbase/files/6886008/observer_cmd_unicode.txt)

可能也不算是bug，只是这个场景执行时直接提示或报错会更好排错。谢谢。

**Comment by longdafeng** [comment]
We will try to reproduce this issue firstly, later we will give you some feedback.

**Comment by longdafeng** [comment]
Why exist unicode character? 
In normal case, observer will be started by other program, it is hard to set unicode in the parameter list.

**Comment by gaodg** [comment]
> Why exist unicode character?
> In normal case, observer will be started by other program, it is hard to set unicode in the parameter list.

是安装测试时拷贝别人的命令导致的，应该是保存时带格式了，正常是不会出现的。
