### ISSUE TITLE
ob_ilog_storage.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#182]
下面的代码中，这里的pruge 应该是purge .
/code/oceanbase/src/clog/ob_ilog_storage.cpp : 691
CSR_LOG(TRACE, "ilog_storage_timer pruge_stale_file success");

下面的注释中，这里的 betweent 应该是betweend .
/code/oceanbase/src/clog/ob_ilog_storage.cpp : 846
// handle logs betweent ilog_store and memstore.

**Comment by LINxiansheng** [comment]
#250 Done
