### ISSUE TITLE
ob_log_archive_and_restore_driver.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#183]
下面的代码中，这里的archvie 应该是archie .
/code/oceanbase/src/clog/ob_log_archive_and_restore_driver.cpp : 85
CLOG_LOG(INFO, "ob_log_archvie_and_restore_driver will stop");

**Comment by LINxiansheng** [comment]
Thanks for your contribution and it is 'archive'.

**Comment by LINxiansheng** [comment]
#250 Done
