### ISSUE TITLE
[Question]:  [CP] in some commits, what is the meaning about it

### ISSUE THREAD

**Issue by andyli029** [oceanbase/oceanbase#1840]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
 [CP] in some commits, what is the meaning about it
```

```
**Environment**

- OS Version and CPU Arch(`uname -a`):

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

**Comment by hnwyllmm** [comment]
CP is for Cherry Pick.
It means the commit is pick from other branch.

**Comment by andyli029** [comment]
> CP is for Cherry Pick. It means the commit is pick from other branch.
Thanks 

[[CP] [to #54607752]fix mysqlTest, use das force for skip locked cursor in PL]
(https://github.com/oceanbase/oceanbase/commit/ee68ee57757aee6471036c6fc24bd140ccde657a)

What is about `#54607752`

**Comment by hnwyllmm** [comment]
Sorry for confusing.
54607752 is an issue id.

**Comment by andyli029** [comment]
> Sorry for confusing. 54607752 is an issue id.
where is the link? if I want to know the issue

**Comment by hnwyllmm** [comment]
Sorry it is internal in oceanbase.
If you want to report some bugs, you can report it through github issue.

**Comment by andyli029** [comment]
> Sorry it is internal in oceanbase. If you want to report some bugs, you can report it through github issue.
Open is better?

**Comment by hnwyllmm** [comment]
We're not able to do this right now.
Do you have any other questions about this issue?
