### ISSUE TITLE
[Enhancement]: driver for node.js

### ISSUE THREAD

**Issue by Cooper-dang** [oceanbase/oceanbase#1843]
**Enhancement**

**Comment by deskau** [comment]
The MySQL driver using node.js can connect to Oceanbase, and the compatibility should be over 95%
https://github.com/mysqljs/mysql

**Comment by longdafeng** [comment]
Please directly use MySQL's node.js driver, if you meet problem with MySQL node.js driver, please feel free to ask.

**Comment by moc4097** [comment]
Can MySQL's node.js driver connect to the Oracle mode of OceanBase?
