### ISSUE TITLE
[Bug]: The extractvalue function in ob for mysql is not compatible with the native MySQL function

### ISSUE THREAD

**Issue by PanternBao** [oceanbase/oceanbase#1851]
**Describe the bug**
ob mysql 模式下 extractvalue 函数如果有多个元素匹配的话，只会返回第一个，与mysql行为不兼容
![image](https://github.com/oceanbase/oceanbase/assets/21034841/abb1a938-32a7-4b99-8442-9d6e77ddef04)

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
release v4.2.2.0  

**Fast Reproduce Steps(Required)**

`set @x='<a><b id="0"><it v="00">00</it><it v="01">01</it></b><b id="1"><it v="10">10</it><it v="11">1</it></b></a>';
select @x,extractvalue(@x,"/a/b[@id=1]/it/@v");`

**Expected behavior**

**Actual Behavior**

**Additional context**

**Comment by hnwyllmm** [comment]
感谢你的信息，已经重现。

**Comment by PanternBao** [comment]
好的，请问下4.2.3预计什么时候发布，因为项目使用到这个功能比较急，想问下时间。

**Comment by hnwyllmm** [comment]
预计是4月中旬。

**Comment by hnwyllmm** [comment]
https://github.com/oceanbase/oceanbase/milestone/14
已经放在这里了，会不定时更新进展。

**Comment by hnwyllmm** [comment]
The code is merged.

**Comment by PanternBao** [comment]
I find other problems about extractvalue function, can you provide commit and I build ob to test again.

**Comment by hnwyllmm** [comment]
> I find other problems about extractvalue function, can you provide commit and I build ob to test again.

Please take a look at :
https://github.com/oceanbase/oceanbase/commit/04ac822b916803791d7adb6f69cbca7b1b804efa

**Comment by PanternBao** [comment]
thanks, i test the following case, but it isn't fixed.
in ob for mysql:
![image](https://github.com/oceanbase/oceanbase/assets/21034841/a13763c1-867a-4d08-9ac1-44518af2a802)

in mysql:
![image](https://github.com/oceanbase/oceanbase/assets/21034841/ad13ff19-a08d-4301-8c54-a0d8ff456bc7)

**Comment by hnwyllmm** [comment]
Fixed on branch 42x. Did you use the right branch?

**Comment by PanternBao** [comment]
the old case is fixed, the new case isn't fixed.
`
select extractvalue('<a><b id="0"><it v="00">00</it><it v="01">01</it></b><b id="1"><it v="10">10</it><it v="11">11</it></b></a>',"/a/b/it[2]");
`
result is as previously shown.

**Comment by hnwyllmm** [comment]
OK. got it.

**Comment by hnwyllmm** [comment]
thanks very much.

**Comment by hnwyllmm** [comment]
> the old case is fixed, the new case isn't fixed. `select extractvalue('<a><b id="0"><it v="00">00</it><it v="01">01</it></b><b id="1"><it v="10">10</it><it v="11">11</it></b></a>',"/a/b/it[2]");` result is as previously shown.

Sorry for that we can't fix in short term.

**Comment by PanternBao** [comment]
> > the old case is fixed, the new case isn't fixed. `select extractvalue('<a><b id="0"><it v="00">00</it><it v="01">01</it></b><b id="1"><it v="10">10</it><it v="11">11</it></b></a>',"/a/b/it[2]");` result is as previously shown.
> 
> Sorry for that we can't fix in short term.

ok, by the way, the case goes against the current design and need refactor code?

**Comment by hnwyllmm** [comment]
I can't say it. But there is a lot of work to do to fix this.

**Comment by PanternBao** [comment]
ok, thanks very much.
