### ISSUE TITLE
[Question]: ERROR 1227 (42501): Access denied during load data

### ISSUE THREAD

**Issue by shaun-kee** [oceanbase/oceanbase#1854]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
How do I load data from my own bind volume into oceanbase?
I am using docker container to test oceanbase-ce but encountered this problem when trying to load csv from bind volume mount.
I am following the instructions in here.
https://www.oceanbase.com/docs/enterprise-oceanbase-database-cn-10000000000358964

But when setting `obclient> SET GLOBAL secure_file_priv = ""` I got this error:
`ERROR 1235 (0A000): modify SECURE_FILE_PRIV not by unix socket connection not supported`

and when trying to load data I got permission denied error.

**Environment**
Local machine (MacOS) using docker image with docker-compose up command

```
# docker-compose.yml
version: '3.8'
services:

  oceanbase:
    container_name: oceanbase-container
    image: oceanbase/oceanbase-ce:latest
    restart: always
    ports:
      - "2881:2881"
    volumes:
      - ob:/root/ob
      - obd:/root/.obd
      - /user/path/to/oceanbase/data:/home/data

volumes:
  ob:
  obd:
```

- OS Version and CPU Arch(`uname -a`):

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

**Comment by hnwyllmm** [comment]
Sorry, you should follow the doc below:
https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000511007

You should connect to oceanbase-ce by unix socket:
obclient -uroot@`your tenant name` -S `oceanbase unix socket path`

And then set the variable:
SET GLOBAL secure_file_priv = "/";

The variable should be "/" not "" in the latest version.

Where is the `oceanbase unix socket path`?
You can find the `observer` binary path first like this:
`ps -ef | grep observer`
You may got this:
```
wangyun+  71639      1 17 Mar12 ?        11:09:34 /home/wangyunlai.wyl/oceanbase-ce/bin/observer -r 127.0.0.1:2882:2881 -p 2881 ...
```

Here is the observer binary path:
```
/home/wangyunlai.wyl/oceanbase-ce/bin/observer
```
The unix socket path is 
```
/home/wangyunlai.wyl/oceanbase-ce/run/sql.sock
```

**Comment by shaun-kee** [comment]
I have done the following settings

`obclient [(none)]> set global secure_file_priv="/";
Query OK, 0 rows affected (0.035 sec)
obclient [oceanbase]> set global local_infile=1;
Query OK, 0 rows affected (0.006 sec)
`

however I am getting this error when I'm trying to load a csv from a bind docker volume
`obclient [oceanbase]> load data local infile '/home/data/draw0010.csv' into table betdraw;
ERROR 3948 (42000): Loading local data is disabled; this must be enabled on both the client and server sides
`

**Comment by hnwyllmm** [comment]
Please take a look at https://ask.oceanbase.com/t/topic/35606653/2 (in Chinese).

How did you search document about observer 3.1.2?

**Comment by hnwyllmm** [comment]
如果需要使用load data local功能，需要保证：

obclient 版本不低于 2.2.4;
obproxy 版本不低于 3.2.4(直连observer无此要求);
objdbc 版本不低于 2.4.8 (如果使用Java + objdbc）；

另外，可以直接使用mysql或mariadb原生客户端，对版本没有特殊要求。
但是MySQL客户端需要增加 --local-infile 参数。

如果版本没有问题，需要设置变量 local_infile 为ON：

``` sql
-- 开启变量
set @@local_infile=1;
-- 检查变量
show variables like 'local_infile';
```

关于 SECURE_FILE_PRIV 变量，此变量是控制observer能访问服务端机器上的权限，所以此变量对load local功能无影响，不需要做设置。

---

If you need to use `load data local`, you need to ensure:

- obclient version is not lower than 2.2.4;
- The obproxy version is no less than 3.2.4 (there is no such requirement for direct connection to the observer);
- objdbc version is not lower than 2.4.8 (if using Java + objdbc);

In addition, you can use mysql or mariadb native client directly, and there are no special requirements for the version.

You should start mysql client with `--local-infile` argument like this:
```shell
mysql --local-infile -h127.0.0.1 -uroot -P 2881
```

If there is no problem with the version, you need to set the variable local_infile to ON:

```sql
-- Open variables
set @@local_infile=1;
-- Check variables
show variables like 'local_infile';
```

Regarding the SECURE_FILE_PRIV variable, this variable controls the observer's access to the server machine, so this variable has no impact on the load local function and does not need to be set.

**Comment by hnwyllmm** [comment]
如果需要使用load data local功能，需要保证：

obclient 版本不低于 2.2.4;
obproxy 版本不低于 3.2.4(直连observer无此要求);
objdbc 版本不低于 2.4.8 (如果使用Java + objdbc）；

另外，可以直接使用mysql或mariadb原生客户端，对版本没有特殊要求。
但是MySQL客户端需要增加 --local-infile 参数。

如果版本没有问题，需要设置变量 local_infile 为ON：

``` sql
-- 开启变量
set @@local_infile=1;
-- 检查变量
show variables like 'local_infile';
```

关于 SECURE_FILE_PRIV 变量，此变量是控制observer能访问服务端机器上的权限，所以此变量对load local功能无影响，不需要做设置。

---

If you need to use `load data local`, you need to ensure:

- obclient version is not lower than 2.2.4;
- The obproxy version is no less than 3.2.4 (there is no such requirement for direct connection to the observer);
- objdbc version is not lower than 2.4.8 (if using Java + objdbc);

In addition, you can use mysql or mariadb native client directly, and there are no special requirements for the version.

You should start mysql client with `--local-infile` argument like this:
```shell
mysql --local-infile -h127.0.0.1 -uroot -P 2881
```

If there is no problem with the version, you need to set the variable local_infile to ON:

```sql
-- Open variables
set @@local_infile=1;
-- Check variables
show variables like 'local_infile';
```

Regarding the SECURE_FILE_PRIV variable, this variable controls the observer's access to the server machine, so this variable has no impact on the load local function and does not need to be set.

**Comment by shaun-kee** [comment]
I removed local option from load infile syntax.
It is working now. 
Thanks for the clarification

**Comment by hnwyllmm** [comment]
I close this issue as it fixed.
