### ISSUE TITLE
[Question]: 表定义外键后添加数据失败

### ISSUE THREAD

**Issue by EayonLee** [oceanbase/oceanbase#1857]
版本为: v3.1.5 all-in-one

按照官网demo，创建了两张表如下：
`
CREATE TABLE parent (
 id INT NOT NULL,
 PRIMARY KEY (id)
);
​
CREATE TABLE child (
 id INT,
 parent_id INT,
 INDEX par_ind(parent_id),
 FOREIGN KEY (parent_id) REFERENCES parent (id) ON DELETE CASCADE
);
`

先给`parent`表插入了一条数据
`
obclient [soc]> insert into parent (`id`) VALUE (1);
Query OK, 1 row affected (0.007 sec)

obclient [soc]> select * from parent;
+----+
| id |
+----+
|  1 |
+----+
1 row in set (0.007 sec)
`

随后向`child`表插入数据失败
`
obclient [soc]> insert into child (`id`, `parent_id`) VALUE (1,1);
ERROR 1235 (0A000): Not supported feature or function
`

请问是什么原因？

**Comment by hnwyllmm** [comment]
3.1.5 当前已经不在维护，能否升级到4.2.2？

**Comment by EayonLee** [comment]
> 3.1.5 当前已经不在维护，能否升级到4.2.2？

是3.1.5版本问题导致的吗？如果是的话可以升级一下，不是的话我这边需要找到问题😥

**Comment by hnwyllmm** [comment]
<img width="831" alt="image" src="https://github.com/oceanbase/oceanbase/assets/5187215/ba85104c-a68d-45fe-a80c-090355050b0b">

4.2.2 版本没有此问题。

**Comment by EayonLee** [comment]
> <img alt="image" width="831" src="https://private-user-images.githubusercontent.com/5187215/313646426-ba85104c-a68d-45fe-a80c-090355050b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTIyNjIsIm5iZiI6MTcxMDgxMTk2MiwicGF0aCI6Ii81MTg3MjE1LzMxMzY0NjQyNi1iYTg1MTA0Yy1hNjhkLTQ1ZmUtYTgwYy0wOTAzNTUwNTBiMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDEzMjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg4MzJjOGJiNWNjMzk5MjlkODYwMzM4ZmVmMmM3YjNhZTNkNzNlNzY0NGY3YzU5MmY5MTE2MmM2NDBlMTg2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IRUzv4OAhhVdHvJBFxKHalBZ2-eH7NFb9rl93mxBmJQ">
> 4.2.2 版本没有此问题。

感谢
