### ISSUE TITLE
ob_log_membership_task_mgr.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#186]
ob_log_membership_task_mgr.cpp文件中多出cascad单词拼写错误，应更正为cascade.

下面的注释中，这里的leadera 应该是leaders .
/code/oceanbase/src/clog/ob_log_membership_task_mgr.cpp : 489
// standby_leadera will retry,

**Comment by LINxiansheng** [comment]
I think the "cascad' appear with 'ing' and 'ed' is not wrong.
