### ISSUE TITLE
[Question]: No such package name: oceanbase-libs

### ISSUE THREAD

**Issue by EayonLee** [oceanbase/oceanbase#1862]
安装的oceanbase包是：`oceanbase-3.2.3.3-110080012024022713.el7.x86_64.rpm`
本地镜像列表如下：
![Uploading WX20240320-183703@2x.png…]()

构建集群时报错如下
[root@docker02v lib]# obd cluster deploy ob-test -c /opt/db/mini-local-example.yaml
+------------------------------------------------------------------------------------------+
|                                         Packages                                         |
+------------+---------+------------------------+------------------------------------------+
| Repository | Version | Release                | Md5                                      |
+------------+---------+------------------------+------------------------------------------+
| oceanbase  | 3.2.3.3 | 110080012024022713.el7 | 4c5c9b65b749e6ee98e48e11293095d1f3844e69 |
+------------+---------+------------------------+------------------------------------------+
Repository integrity check ok
Parameter check ok
Cluster status check ok
Initializes observer work home ok
Remote oceanbase-3.2.3.3-110080012024022713.el7-4c5c9b65b749e6ee98e48e11293095d1f3844e69 repository install ok
Remote oceanbase-3.2.3.3-110080012024022713.el7-4c5c9b65b749e6ee98e48e11293095d1f3844e69 repository lib check !!
Try to get lib-repository
[ERROR] No such package name: oceanbase-libs.
[ERROR] Failed to install lib package for local

如何在`mini-local-example.yaml`配置中指定他使用`oceanbase-ce-libs-4.0.0.0-103000022023011215.el7.x86_64.rpm`这个lib?

**Comment by EayonLee** [comment]
图片加载上来，镜像列表如下：
[root@docker02v lib]# obd mirror list local
+----------------------------------------------------------------------------------------------------------+
|                                            local Package List                                            |
+-------------------+---------+------------------------+--------+------------------------------------------+
| name              | version | release                | arch   | md5                                      |
+-------------------+---------+------------------------+--------+------------------------------------------+
| ob-deploy         | 2.6.1   | 6.el7                  | x86_64 | e9a0a7af5ecedd7a267ccef44e64b6323ea568c2 |
| oceanbase-ce      | 4.2.2.0 | 100010012024022719.el7 | x86_64 | 60fe842818ef64631dd3bb6f90bf4cab0e737195 |
| oceanbase-ce-libs | 4.2.2.0 | 100010012024022719.el7 | x86_64 | 756bc0a7949701b0a6c707a29cf623f7fb966bb7 |
| libobclient       | 2.2.3   | 1.el7                  | x86_64 | 841949aa594173e1751dfbe9730b2787410e6f01 |
| obclient          | 2.2.3   | 1.el7                  | x86_64 | a983aa8564d4c47a7afce933e9659c7fc60c4d29 |
| ob-deploy         | 2.2.0   | 2.el7                  | x86_64 | 3a00baa833f492faad616eafc5ac6a5e960bf919 |
| oceanbase         | 3.2.3.3 | 110080012024022713.el7 | x86_64 | 4c5c9b65b749e6ee98e48e11293095d1f3844e69 |
| oceanbase-ce-libs | 4.0.0.0 | 103000022023011215.el7 | x86_64 | ef48cff7633e3dbc39f5c0abdcd72348213e09a2 |
+-------------------+---------+------------------------+--------+------------------------------------------+

**Comment by hnwyllmm** [comment]
obd 不能部署oceanbase 3.2.3版本，你可以部署3.1.x和4.x版本。

**Comment by EayonLee** [comment]
> obd 不能部署oceanbase 3.2.3版本，你可以部署3.1.x和4.x版本。

那我这个3.2.3.3版本该如何部署？有没有相关文档

**Comment by hnwyllmm** [comment]
3.2.3 属于企业版，需要技术支持人员安装部署相关的依赖。
