### ISSUE TITLE
[Enhancement] ObLogMiner: optimize ObLogMinerBRFilter

### ISSUE THREAD

**Issue by nautaa** [oceanbase/oceanbase#1883]
**Enhancement**

Currently, in `ObLogMinerBRFilter`, we filter records by iterating over `filter_pipeline_`, and still need to iterate over `filter_pipeline_` for cases where no filter related parameters are specified. It is necessary to recognize if meaningless filter parameters are specified, e.g.: `--operation "insert|delete|update"`.

target branch:
oblogminer_dev

relate file:
src/logservice/logminer/ob_log_miner_br_filter.cpp

**Comment by zztaki** [comment]
hi, @nautaa,
I am a beginner in oceanbase, I want to try this issue and make more contributions to oceanbase step by step. :)

**Comment by nautaa** [comment]
@zztaki Thanks for your interest. However this issue is currently being worked on by another contributor @qiuyg3 , and if there are no progress updates for a long time, you can still submit a PR for this issue. you can also prioritize other issues. If you are interested in other good first issues or appreciate certain modules, please let us know.

**Comment by nautaa** [comment]
> @zztaki Thanks for your interest. However this issue is currently being worked on by another contributor @qiuyg3 , and if there are no progress updates for a long time, you can still submit a PR for this issue. you can also prioritize other issues. If you are interested in other good first issues or appreciate certain modules, please let us know.

@zztaki for example, you could take a look at #1785

**Comment by zztaki** [comment]
> > @zztaki Thanks for your interest. However this issue is currently being worked on by another contributor @qiuyg3 , and if there are no progress updates for a long time, you can still submit a PR for this issue. you can also prioritize other issues. If you are interested in other good first issues or appreciate certain modules, please let us know.
> 
> @zztaki for example, you could take a look at #1785

Thank you for your kind suggestion, I want to try it!
