### ISSUE TITLE
[Question]: 编译完成Oceanbase，使用./obd.sh启动集群后，使用sysbench压测，但是CPU一直上不去

### ISSUE THREAD

**Issue by yujiabin123** [oceanbase/oceanbase#1884]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
我基于社区版本，编译完成了OB 4.2.1 ，使用./obd.sh启动后，使用sysbench进行压测，但是性能一直上不去，使用TOP查看CPU使用率，非常低

我创建的租户：
create resource unit sysbench_unit memory_size='200g',log_disk_size='120g',min_cpu=122,max_cpu=122,max_iops=102400,min_iops=102400;

create resource pool sysbench_pool unit = 'sysbench_unit', unit_num = 1, zone_list=('zone1','zone2','zone3');
create tenant sysbench_tenant resource_pool_list=('sysbench_pool'), charset=utf8mb4, replica_num=3, zone_list('zone1', 'zone2', 'zone3'), primary_zone=RANDOM, locality='F@zone1,F@zone2,F@zone3' set variables ob_compatibility_mode='mysql', ob_tcp_invited_nodes='%';

**Environment**
![image](https://github.com/oceanbase/oceanbase/assets/28921999/df6b0e36-b207-469c-80db-f4885685fd64)

- OS Version and CPU Arch(`uname -a`):
![image](https://github.com/oceanbase/oceanbase/assets/28921999/45a007aa-2f11-4f72-9076-aa69435a0768)

CPU为128核

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
OB为社区版4.2.1.5（编译release）

请问是否是需要调某些参数？看起来OB没有使用我的机器物理资源

**Comment by yujiabin123** [comment]
当我运行point_select时，
[root@localhost lua]# sysbench /usr/local/share/sysbench/oltp_point_select.lua --mysql-host=127.0.0.1 --mysql-port=10006 --mysql-user=root@sysbench_tenant --mysql-db=sbtest --tables=64 --table_size=1000000 --threads=216 --time=500 --rand-type=uniform  --report-interval=2 --db-ps-mode=disable --mysql-ignore-errors=1062,1213,6002  run
sysbench 1.0.20 (using bundled LuaJIT 2.1.1697887905)

Running the test with following options:
Number of threads: 216
Report intermediate results every 2 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 2s ] thds: 216 tps: 1345.69 qps: 1345.69 (r/w/o: 1345.69/0.00/0.00) lat (ms,95%): 331.91 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 216 tps: 1474.50 qps: 1474.50 (r/w/o: 1474.50/0.00/0.00) lat (ms,95%): 320.17 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 216 tps: 1484.04 qps: 1484.04 (r/w/o: 1484.04/0.00/0.00) lat (ms,95%): 314.45 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 216 tps: 1484.00 qps: 1484.00 (r/w/o: 1484.00/0.00/0.00) lat (ms,95%): 303.33 err/s: 0.00 reconn/s: 0.00
[ 10s ] thds: 216 tps: 1470.98 qps: 1470.98 (r/w/o: 1470.98/0.00/0.00) lat (ms,95%): 320.17 err/s: 0.00 reconn/s: 0.00
[ 12s ] thds: 216 tps: 1207.50 qps: 1207.50 (r/w/o: 1207.50/0.00/0.00) lat (ms,95%): 419.45 err/s: 0.00 reconn/s: 0.00
[ 14s ] thds: 216 tps: 1320.55 qps: 1320.55 (r/w/o: 1320.55/0.00/0.00) lat (ms,95%): 376.49 err/s: 0.00 reconn/s: 0.00
[ 16s ] thds: 216 tps: 1401.50 qps: 1401.50 (r/w/o: 1401.50/0.00/0.00) lat (ms,95%): 363.18 err/s: 0.00 reconn/s: 0.00
[ 18s ] thds: 216 tps: 1363.89 qps: 1363.89 (r/w/o: 1363.89/0.00/0.00) lat (ms,95%): 369.77 err/s: 0.00 reconn/s: 0.00
[ 20s ] thds: 216 tps: 1148.51 qps: 1148.51 (r/w/o: 1148.51/0.00/0.00) lat (ms,95%): 467.30 err/s: 0.00 reconn/s: 0.00
[ 22s ] thds: 216 tps: 1146.55 qps: 1146.55 (r/w/o: 1146.55/0.00/0.00) lat (ms,95%): 484.44 err/s: 0.00 reconn/s: 0.00
[ 24s ] thds: 216 tps: 1578.02 qps: 1578.02 (r/w/o: 1578.02/0.00/0.00) lat (ms,95%): 297.92 err/s: 0.00 reconn/s: 0.00
[ 26s ] thds: 216 tps: 1592.97 qps: 1592.97 (r/w/o: 1592.97/0.00/0.00) lat (ms,95%): 297.92 err/s: 0.00 reconn/s: 0.00
[ 28s ] thds: 216 tps: 1596.01 qps: 1596.01 (r/w/o: 1596.01/0.00/0.00) lat (ms,95%): 303.33 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 216 tps: 285.01 qps: 285.01 (r/w/o: 285.01/0.00/0.00) lat (ms,95%): 1170.65 err/s: 0.00 reconn/s: 0.00
FATAL: mysql_drv_query() returned error 2013 (Lost connection to MySQL server during query) for query 'SELECT c FROM sbtest43 WHERE id=76780'
FATAL: `thread_run' function failed: ./oltp_common.lua:419: SQL error, errno = 2013, state = 'HY000': Lost connection to MySQL server during query
[ 32s ] thds: 216 tps: 84.50 qps: 84.50 (r/w/o: 84.50/0.00/0.00) lat (ms,95%): 3326.55 err/s: 0.50 reconn/s: 0.00
[ 34s ] thds: 216 tps: 58.50 qps: 58.50 (r/w/o: 58.50/0.00/0.00) lat (ms,95%): 5124.81 err/s: 0.00 reconn/s: 0.00
[ 36s ] thds: 215 tps: 18.00 qps: 18.00 (r/w/o: 18.00/0.00/0.00) lat (ms,95%): 6476.48 err/s: 0.00 reconn/s: 0.00


性能远低于预期，
且

CPU
![image](https://github.com/oceanbase/oceanbase/assets/28921999/6c68c4b9-a91b-4eb1-a718-4a77283b7ba0)
只吃了3-4个核

**Comment by hnwyllmm** [comment]
建议直接使用obd来部署和测试sysbench吧。obd 会根据实际情况做参数的调整和优化。

**Comment by yujiabin123** [comment]
我之前使用obd来进行部署过，但它是否只支持官网上的ob包呢？  我该如何用obd来启动我自己编译出来的OB？

**Comment by yujiabin123** [comment]
我试过先用obd部署集群，然后把observer的二进制文件替换成我编译出来的observer，但会报错，是否是因为版本没适配对？

**Comment by hnwyllmm** [comment]
直接替换二进制文件确实有可能兼容问题，建议下载跟自己版本一样的二进制文件安装。

**Comment by hnwyllmm** [comment]
编译的时候还需要编译 perf 版本，或者 release版本。

**Comment by yujiabin123** [comment]
我编译的就是release版本，二进制有2.6G

**Comment by yujiabin123** [comment]
> 直接替换二进制文件确实有可能兼容问题，建议下载跟自己版本一样的二进制文件安装。

您指的是下载对应版本的OBD？还是对应版本的OBPROXY

**Comment by yujiabin123** [comment]
我现在使用./obd.sh，但是集群不使用obproxy，CPU可以使用到20-30个核，虽然有所提升，但还是无法吃满。

**Comment by hnwyllmm** [comment]
不走obproxy 可能就白白消耗了CPU但是没有干实际有效的活，本来obproxy做的事情，变到observer内部自己做了

**Comment by yujiabin123** [comment]
是这样的，但我目前还没想到如何使用proxy。用./obd.sh自动部署的proxy出现压力一直起不来的情况

**Comment by hnwyllmm** [comment]
obd.sh 通常是为开发者准备的，有些参数设置可能不到位。
你可以使用OBD版本部署一个4.2.1集群，然后把你的二进制文件替换上去再重启。之前替换失败很可能是由于版本不兼容导致的。

**Comment by yujiabin123** [comment]
好的，我可以去试试

**Comment by hnwyllmm** [comment]
后面有新的进展吗？

**Comment by yujiabin123** [comment]
谢谢您的关心，我后续适配了obd的版本，然后跑起来了。

**Comment by hnwyllmm** [comment]
issue 先关掉了，后面有问题再开。
