### ISSUE TITLE
[Enhancement] ObLogMiner: ObLogMinerAnalyzer continuous checking time interval

### ISSUE THREAD

**Issue by nautaa** [oceanbase/oceanbase#1896]
**Enhancement**

ObLogMinerAnalyzer continuous checking time interval, will  causes ineffective cpu-usage.

target branch:
oblogminer_dev

ref:
https://github.com/oceanbase/oceanbase/blob/cdc4f32ef0da858c3416823677faedb897b18fb3/src/logservice/logminer/ob_log_miner_analyzer.cpp#L212-L230

Solution Description:
You should add `ob_usleep()` to avoid ObLogMinerAnalyzer continuous checking time interval. You can refer to other threads that deal with this, for example:

https://github.com/oceanbase/oceanbase/blob/cdc4f32ef0da858c3416823677faedb897b18fb3/src/logservice/logminer/ob_log_miner_data_manager.cpp#L264-L271

**Comment by nautaa** [comment]
@C-ld Thanks for your interest, I've assigned this issue to you. Any doubt can be commented below. You can choose the `oblogminer_dev` branch as the target branch to submit your PR, and how to build and run `oblogminer` can be found at [build-and-run](https://github.com/oceanbase/oceanbase/blob/develop/docs/build-and-run.md) and  [chinese yuque documentation](https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16)

**Comment by C-ld** [comment]
@nautaa  Sorry for the late reply, I have submitted PR and you can check it whenever you are spare.
