### ISSUE TITLE
Failed to connect oceanbase-ce

### ISSUE THREAD

**Issue by coding01000** [oceanbase/oceanbase#19]
when i executed "obd cluster start lo",  an error occured "[ERROR] Failed to connect oceanbase-ce"

> obd cluster start lo 
Get local repositories and plugins ok
[WARN] (127.0.0.1) fs.aio-max-nr must not be less than 1048576 (Current value: 65536)
[WARN] (127.0.0.1) open files number must not be less than 655350 (Current value: 1024)
Start observer ok
observer program health check ok
Connect to observer x
[ERROR] Failed to connect oceanbase-ce

error displayed in log file is 
ERROR [SERVER] init_io (ob_server.cpp:1062) [6994][0][Y0-0000000000000000] [lt=4] [dc=0] init io benchmark fail, (ret=-4027) BACKTRACE:0x90a107e 0x90090c1 0x24c1b14 0x24c176b 0x24c1583 0x24c04f6 0x870573a 0x86fe5c4 0x24be805 0x7f36ec88c555 0x24bd4e9
ERROR [SERVER] init_multi_tenant (ob_server.cpp:1247) [6994][0][Y0-0000000000000000] [lt=19] [dc=0] Fail to set tenant mem limit(ret=-4002) BACKTRACE:0x90a107e 0x90090c1 0x24c1b14 0x24c176b 0x24c1583 0x24c04f6 0x8709feb 0x86fea10 0x24be805 0x7f36ec88c555 0x24bd4e9
ERROR [SERVER] init (ob_server.cpp:298) [6994][0][Y0-0000000000000000] [lt=49] [dc=0] init multi tenant fail(ret=-4002) BACKTRACE:0x90a107e 0x90090c1 0x24c1b14 0x24c176b 0x24c1583 0x24c04f6 0x8700741 0x24be805 0x7f36ec88c555 0x24bd4e9
ERROR [LIB] ob_malloc (ob_malloc.h:38) [7351][704][YB427F000001-0005C3AD4E9BEA99] [lt=3] [dc=0] allocate memory fail(attr=tenant_id=1, label=MysqlRequesReco, ctx_id=0, prio=0, nbyte=2088960) BACKTRACE:0x90a107e 0x90090c1 0x24d1eef 0x24d1b3b 0x24d1900 0x24d1552 0x24d130f 0x24dfe00 0x8692c6a 0x49ae651 0x86d10dd 0x86d2fd9 0x86d9194 0x8f8f342 0x6402731 0x68a72db 0x68a6dfc 0x6886091 0x4ff14ed 0x4ff3609 0x5004638 0x5005acd 0x5007e30 0x500993f 0x8725d90 0x8727cce 0x8727196 0x8726dc7 0x872798d 0x41b49f4 0x2a55b14 0x8ebc475 0x8eb9e4e 0x8eb46ef
**ERROR [SQL.ENG] create_physical_plan_ctx (ob_exec_context.cpp:611) [7103][214][YB427F000001-0005C3AD4EBBEA98] [lt=2] [dc=0] no more memory to create physical_plan_ctx BACKTRACE:0x90a107e 0x90090c1 0x8fffccf 0x24c0127 0x24bd7a5 0x3c01649 0x4a359c5 0x4a1639f 0x4a12e73
**

**Comment by raywill** [comment]
what's your memory configuration?  please execute `free -m`

**Comment by frf12** [comment]
Your configuration may be wrong. Please provide your configuration. Execute `obd cluster edit config lo` show your configuration

**Comment by coding01000** [comment]
> Your configuration may be wrong. Please provide your configuration. Execute `obd cluster edit-config lo` show your configuration

>oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
    - 127.0.0.1
  global:
    home_path: /root/observer
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: lo
    mysql_port: 2883
    rpc_port: 2882
    zone: zone1
    # if current hardware's memory capacity is smaller than 50G, please use the setting of "mini-single-example.yaml" and do a small adjustment.
    memory_limit: 64G
    datafile_disk_percentage: 20
    cluster_id: 1

The memory of the machine is 128G
I think there was an error when executing io benchmark

**Comment by coding01000** [comment]
The problem is solved, you need to set the maximum number of open files in the OS，
>vm.max_map_count=655360" >> /etc/sysctl.conf
sysctl -p

echo "* soft nofile 655360
* hard nofile 655360
* soft nproc 655360
* hard nproc 655360
* hard core unlimited
* soft core unlimited
* hard stack 10240
* soft stack 10240
* hard cpu unlimited
* soft cpu unlimited" >> /etc/security/limits.conf
ulimit -s 10240; ulimit -c unlimited;

**Comment by SilvaXiang** [comment]
> The problem is solved, you need to set the maximum number of open files in the OS，
> 
> > vm.max_map_count=655360" >> /etc/sysctl.conf
> > sysctl -p echo "* soft nofile 655360 * hard nofile 655360 * soft nproc 655360 * hard nproc 655360 * hard core unlimited * soft core unlimited * hard stack 10240 * soft stack 10240 * hard cpu unlimited * soft cpu unlimited" >> /etc/security/limits.conf
> > ulimit -s 10240; ulimit -c unlimited;

So, how to set the max number of open files? Can you paste the command clearly? Thank you

**Comment by frf12** [comment]
> > The problem is solved, you need to set the maximum number of open files in the OS，
> > > vm.max_map_count=655360" >> /etc/sysctl.conf
> > > sysctl -p echo "* soft nofile 655360 * hard nofile 655360 * soft nproc 655360 * hard nproc 655360 * hard core unlimited * soft core unlimited * hard stack 10240 * soft stack 10240 * hard cpu unlimited * soft cpu unlimited" >> /etc/security/limits.conf
> > > ulimit -s 10240; ulimit -c unlimited;
> 
> So, how to set the max number of open files? Can you paste the command clearly? Thank you

see oceanbase/obdeploy#4
