### ISSUE TITLE
[Bug]: initialize a variable of type `char *` using `strrchr (const char *, int)`

### ISSUE THREAD

**Issue by zztaki** [oceanbase/oceanbase#1911]
**Describe the bug**

Initialize a variable of type `char *` using `strrchr (const char *, int)` in `ob_pl_package_manager.cpp`. This may be correct when using [the C language compilation method](https://en.cppreference.com/w/c/string/byte/strrchr), but in C++, [this function will return `const char *`](https://en.cppreference.com/w/cpp/string/byte/strrchr). It will fail when I compile using `bash build.sh debug --init --make` in branch `oblogminer_dev`, as we initialize last_slash as a variable of type `char *`.

If you think this makes sense, I will commit a fix with [this Enhancement](https://github.com/oceanbase/oceanbase/issues/1785) in a PR. :)

**Environment**

- OS Version and CPU Arch(`uname -a`): Linux server 5.4.0-131-generic Ubuntu 20.04.5 LTS
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
- Repo branch: `oblogminer_dev`
  

**Fast Reproduce Steps(Required)**

Steps to reproduce the behavior: compile using `bash build.sh debug --init --make` in branch `oblogminer_dev`.

**Expected behavior**

**Actual Behavior**

**Additional context**

![image](https://github.com/oceanbase/oceanbase/assets/50295684/3e8d3264-411c-4e0a-9cd2-d56dbe472c73)

**Comment by nautaa** [comment]
Thanks for the feedback and fix, I was able to reproduce it on ubuntu 20.04(ref: https://github.com/nautaa/oceanbase/actions/runs/8580887461/job/23517789556), but it compiles fine here on centos7(ref: https://github.com/nautaa/oceanbase/actions/runs/8581083276/job/23517808137).

Can you submit a separate PR for this issue? The target branch is selected as `4.2.x`. Actually `oblogminer_dev` is a mirrored branch for `4.2.x`.

**Comment by zztaki** [comment]
> Thanks for the feedback and fix, I was able to reproduce it on ubuntu 20.04(ref: https://github.com/nautaa/oceanbase/actions/runs/8580887461/job/23517789556), but it compiles fine here on centos7(ref: https://github.com/nautaa/oceanbase/actions/runs/8581083276/job/23517808137).
> 
> Can you submit a separate PR for this issue? The target branch is selected as `4.2.x`. Actually `oblogminer_dev` is a mirrored branch for `4.2.x`.

Thank you for your review. I will submit a separate PR for this in 4.2.x tomorrow. :)
Does it mean that this enhancement #1912 is also above 4.2.x?

**Comment by nautaa** [comment]
> > Thanks for the feedback and fix, I was able to reproduce it on ubuntu 20.04(ref: https://github.com/nautaa/oceanbase/actions/runs/8580887461/job/23517789556), but it compiles fine here on centos7(ref: https://github.com/nautaa/oceanbase/actions/runs/8581083276/job/23517808137).
> > Can you submit a separate PR for this issue? The target branch is selected as `4.2.x`. Actually `oblogminer_dev` is a mirrored branch for `4.2.x`.
> 
> Thank you for your review. I will submit a separate PR for this in 4.2.x tomorrow. :) Does it mean that this enhancement #1912 is also above 4.2.x?

yep. These PRs will eventually try to merge in the internal branch.

**Comment by zztaki** [comment]
> > > Thanks for the feedback and fix, I was able to reproduce it on ubuntu 20.04(ref: https://github.com/nautaa/oceanbase/actions/runs/8580887461/job/23517789556), but it compiles fine here on centos7(ref: https://github.com/nautaa/oceanbase/actions/runs/8581083276/job/23517808137).
> > > Can you submit a separate PR for this issue? The target branch is selected as `4.2.x`. Actually `oblogminer_dev` is a mirrored branch for `4.2.x`.
> > 
> > 
> > Thank you for your review. I will submit a separate PR for this in 4.2.x tomorrow. :) Does it mean that this enhancement #1912 is also above 4.2.x?
> 
> yep. These PRs will eventually try to merge in the internal branch.

I get it! Have a good night~
