### ISSUE TITLE
[Bug]: Ubuntu 20.04 build error

### ISSUE THREAD

**Issue by zztaki** [oceanbase/oceanbase#1913]
**Describe the bug**

There is an error when I build oceanbase in ubuntu 20.04. It seems that we need publish a new apr library in the repo for ubuntu 20.04. Related issue #1112.

**Environment**

- OS Version and CPU Arch: Ubuntu 20.04.5 LTS x86_64
- g++: 11.4.0
- glibc: ldd (Ubuntu GLIBC 2.35-0ubuntu3.4) 2.35
  

**Fast Reproduce Steps(Required)**

Steps to reproduce the behavior: `bash build.sh debug --init --make`

**Expected behavior**

**Actual Behavior**

**Additional context**

```cpp
[ 96%] Built target obcdc_static
ld.lld: error: undefined symbol: pthread_mutexattr_setrobust_np
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_create) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> did you mean: pthread_mutexattr_setrobust_np@GLIBC_2.4
>>> defined in: /lib/x86_64-linux-gnu/libc.so.6

ld.lld: error: undefined symbol: pthread_mutex_consistent_np
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_acquire) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> referenced by proc_mutex.c
>>>               proc_mutex.o:(proc_mutex_pthread_tryacquire) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
>>> did you mean: pthread_mutex_consistent_np@GLIBC_2.4
>>> defined in: /lib/x86_64-linux-gnu/libc.so.6

ld.lld: error: undefined symbol: sys_siglist
>>> referenced by signals.c
>>>               signals.o:(apr_signal_description_get) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a

ld.lld: error: undefined symbol: pthread_yield
>>> referenced by thread.c
>>>               thread.o:(apr_thread_yield) in archive ../../../deps/3rd/usr/local/oceanbase/deps/devel/lib/libapr-1.a
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/observer/CMakeFiles/observer.dir/build.make:165: src/observer/observer] Error 1
make[1]: *** [CMakeFiles/Makefile2:11680: src/observer/CMakeFiles/observer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Built target obcdc
make: *** [Makefile:166: all] Error 2

**Comment by nautaa** [comment]
I try to build `4.2.x` branch on ubuntu 20.04, it's ok for github action. afer #1914  ref: https://github.com/nautaa/oceanbase/actions/runs/8585365978/job/23526687238.
Are you using another branch?

**Comment by zztaki** [comment]
> I try to build `4.2.x` branch on ubuntu 20.04, it's ok for github action. afer #1914 ref: https://github.com/nautaa/oceanbase/actions/runs/8585365978/job/23526687238. Are you using another branch?

Yes, let me try to build `4.2.x` on my machine.

**Comment by zztaki** [comment]
> I try to build `4.2.x` branch on ubuntu 20.04, it's ok for github action. afer #1914 ref: https://github.com/nautaa/oceanbase/actions/runs/8585365978/job/23526687238. Are you using another branch?

This problem still exists in `4.2.x`. :(

**Comment by nautaa** [comment]
Is it because you upgraded the version of glibc or ldd? ubuntu 20.04 default glibc is 2.31 ref:
https://gist.github.com/richardlau/6a01d7829cc33ddab35269dacc127680

**Comment by zztaki** [comment]
> Is it because you upgraded the version of glibc or ldd? ubuntu 20.04 default glibc is 2.31 ref: https://gist.github.com/richardlau/6a01d7829cc33ddab35269dacc127680

You are right! It should be that.

**Comment by nautaa** [comment]
> > Is it because you upgraded the version of glibc or ldd? ubuntu 20.04 default glibc is 2.31 ref: https://gist.github.com/richardlau/6a01d7829cc33ddab35269dacc127680
> 
> You are right! It should be that.

ok, you can downgrade glic version,  or try to use apr el9 rpm package  as a replacement. ref: https://mirrors.aliyun.com/oceanbase/development-kit/el/9/x86_64/devdeps-apr-1.6.5-232023090616.el9.x86_64.rpm
