### ISSUE TITLE
[Bug]: 当表中有blob类型的列时，主节点执行delete操作，cdc拿到的数据中blob类型的这列的值为NULL，导致从节点复制失败

### ISSUE THREAD

**Issue by ZhuKaley** [oceanbase/oceanbase#1927]
**Describe the bug**

当表中有blob类型的列时，主节点执行delete操作，cdc拿到的数据中blob类型的这列的值为NULL。
例如：
CREATE TABLE t_blob_text(id1 BLOB,id2 TEXT);
insert into t_blob_text values(repeat('😂',16383),repeat('犇',300));
delete from t_blob_text;
执行完delete语句后，cdc拿到的数据中，id1对应的数据是NULL，id2对应的数据是300个犇，导致从节点复制失败。
**Environment**

- OS Version and CPU Arch(`uname -a`):
  Linux 26c976bc03c6 4.15.0-197-generic 208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  observer (OceanBase_CE 4.3.1.0)

REVISION: 1-292a72f4b39a12e5e055751334c4cf35afd723ac
BUILD_BRANCH: develop
BUILD_TIME: Apr 15 2024 05:52:07
BUILD_FLAGS: Debug
BUILD_INFO: 

Copyright (c) 2011-present OceanBase Inc.

**Fast Reproduce Steps(Required)**

CREATE TABLE t_blob_text(id1 BLOB,id2 TEXT);
insert into t_blob_text values(repeat('😂',16383),repeat('犇',300));
delete from t_blob_text;

**Expected behavior**

期望cdc拿到的数据中，id1的值为16383个😂
**Actual Behavior**

![image](https://github.com/oceanbase/oceanbase/assets/45195840/4e4f2c7d-6db6-4fc7-b7f8-8af0a68e72cd)

**Additional context**

**Comment by nautaa** [comment]
currently, when LOB type(including blob, text, etc) is stored out-of-row, the previous value is not supported to output, which will output `NULL`

**Comment by ZhuKaley** [comment]
如果输出NULL的话，那么，在observer上执行delete操作后，cdc拿到的变更数据在从节点上执行会失败。请问这个问题会修复吗？

**Comment by nautaa** [comment]
> 如果输出NULL的话，那么，在observer上执行delete操作后，cdc拿到的变更数据在从节点上执行会失败。请问这个问题会修复吗？

近期不会修复，请问是通过什么方式使用 CDC 然后在从节点复制的呢？ 可以通过加一个主键/唯一键的方式避免这个问题吗？比如，删除某一行时，仅指定主键/唯一键。

**Comment by ZhuKaley** [comment]
通过cdc拿到变更数据，然后转成binlog，在从节点上回放；
通过主键可以避免这个问题，唯一键依然有这个问题。

**Comment by nautaa** [comment]
> 通过cdc拿到变更数据，然后转成binlog，在从节点上回放； 通过主键可以避免这个问题，唯一键依然有这个问题。

是通过 oblogproxy 转成binlog 的吗，还是基于 OBCDC 自己实现的？回放是通过什么方式实现的呢？

**Comment by ZhuKaley** [comment]
基于OBCDC自己实现的，回放就是用的MySQL自己的方式。

**Comment by ZhuKaley** [comment]
通过 oblogproxy 转成binlog这种方式有处理这种情况吗？

**Comment by nautaa** [comment]
> 通过 oblogproxy 转成binlog这种方式有处理这种情况吗？

oblogproxy 也是基于cdc实现的，目前CDC不支持输出行外存储的lob类型的前镜像。建议通过指定主键的方式避免。

**Comment by ZhuKaley** [comment]
请问如果修复这个问题的话，修复成本大吗？

**Comment by nautaa** [comment]
> 请问如果修复这个问题的话，修复成本大吗？您这边可以预估下修复成本吗？

涉及改动比较大，近期暂时还没有计划支持。

**Comment by ZhuKaley** [comment]
好的，谢谢您。
