### ISSUE TITLE
[Bug]: OceanBase 安装成功，通过 OBProxy 连接数据库提示：ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 11

### ISSUE THREAD

**Issue by CodePlayer** [oceanbase/oceanbase#1933]
**Describe the bug**
使用 OceanBase 官方提供的社区版一键安装包，在本地使用白屏部署（`obd web`）方式，以最小化占用的形式安装了一个3节点的集群（非容器方式）。
所有参数均按照官方的提示调整为了推荐值。
![image](https://github.com/oceanbase/oceanbase/assets/3793502/1a8ca6f6-d91f-4613-b9e0-802f62103c1b)

使用最新版的 Navicat 直连 节点2（192.168.0.71）的 OBServer  创建了一个 `t_user` 表。
```sql
CREATE TABLE `t_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(20) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4;
```

直连其他 2个 OBServer 节点，确认数据也是正常同步的。

不过当我们使用 OBProxy 方式连接数据库时，却发现所有SQL命令均无法按照预期正确返回。

- 执行 `show tables` 返回的配置参数列表
- 执行 `select * from t_user` 返回 `ERROR 4016 (HY000): Internal error`;
- 执行 `desc t_user` 返回 `ERROR 5010 (21000): Unknown operator, bad internal cmd`;
- 想执行 `SHOW TRACE` 命令跟踪一下错误日志，结果也返回 `ERROR 2013 (HY000): Lost connection to MySQL server during query`。

整个 OBProxy ，除了能够成功登录，但几乎所有命令功能几乎都处于一个不可用的状态。

不管是安装最新的 `4.3.0.1` 还是 `4.2.2` 版本，不管是CentOS 7.9 还是 CentOS 8.2，不管是最大化占用，还是最小化占用，均是如此，每次都是 **必现** 的。 

![lQLPJwI4SE_ddgXM7M0DXbC5W-TyL-0nlwYPGmQh7PYA_861_236](https://github.com/oceanbase/oceanbase/assets/3793502/a3cbf7e1-b556-4715-9c4f-5a3588753d25)

**Environment**

- `CentOS 7.9 x86_64`，内核版本是 `Linux k8s-node02 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

`CentOS 8.2 x86_64` 也试过，内核版本是 `4.18.0-193.28.1.el8_2.x86_64`

  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`): 社区版 `4.3.0.1` 或 `4.2.2.0`

  

**Fast Reproduce Steps(Required)**

**Expected behavior**
希望连接 OBProxy 能够像连接 OBServer 一样返回正确的结果。

**Actual Behavior**
以下是执行的完整命令行及输出。
```
[k8s-user@k8s-node02 ~]$ obclient -h192.168.0.66 -P2883 -uroot@proxysys -p'password' -Dtest -A
Welcome to the OceanBase.  Commands end with ; or \g.
Your OceanBase connection id is 1950875668
Server version: 5.6.25

Copyright (c) 2000, 2018, OceanBase and/or its affiliates. All rights reserved.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

obclient [test]> show tables;
+--------------------------+-------------------+
| Variable_name            | Value             |
+--------------------------+-------------------+
| tx_isolation             | READ-COMMITTED    |
| system_time_zone         | +08:00            |
| time_zone                | +08:00            |
| character_set_server     | utf8mb4           |
| character_set_client     | utf8mb4           |
| interactive_timeout      | 28800             |
| query_cache_size         | 1048576           |
| character_set_results    | utf8mb4           |
| max_allowed_packet       | 4194304           |
| sql_mode                 | STRICT_ALL_TABLES |
| net_buffer_length        | 16384             |
| wait_timeout             | 28800             |
| lower_case_table_names   | 2                 |
| query_cache_type         | OFF               |
| init_connect             |                   |
| transaction_isolation    | READ              |
| character_set_connection | utf8mb4           |
| net_write_timeout        | 60                |
+--------------------------+-------------------+
18 rows in set (0.001 sec)

obclient [test]> select * from t_user;
ERROR 4016 (HY000): Internal error
obclient [test]> desc t_user;
ERROR 5010 (21000): Unknown operator, bad internal cmd
obclient [test]> SHOW TRACE;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

**Comment by CodePlayer** [comment]
连接 OBProxy，**不能** 使用系统提供的连接，也就是用 `@proxysys` 租户进行登录，而应该用对应的数据业务租户进行连接。
要通过 OBProxy 访问数据库，应该使用
```bash
obclient -h主机IP -P2883 -u用户名@租户名#集群名称 -p'PASSWORD' -D数据库名称 -A
```

来访问，例如：
```bash
obclient -h192.168.0.66 -P2883 -uroot@sys#local -p'PASSWORD' -Dtest -A
```

如果只有一个集群名称，`#集群名称` 貌似是可以省略的。我在本地环境已经测试连接OK了。

不过，当我在 测试环境 使用 OBProxy 访问数据库的时候： 

```
obclient -h10.0.0.3 -P2883 -uroot@sys#obcluster -p'PASSWORD' -Dtest -A
```

却提示错误：
```
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 11
```

有人遇到过这种情况吗 ？感谢对本问题的关注与回复！

**Comment by hnwyllmm** [comment]
使用 @proxysys 连接的是obporxy本身，而不是 observer集群。不够这个问题楼主已经解决。
使用obclient连接收到 "Lost connection"的错误看起来是ob集群还没有初始化完成。

**Comment by CodePlayer** [comment]
> 使用 @proxysys 连接的是obporxy本身，而不是 observer集群。不够这个问题楼主已经解决。 使用obclient连接收到 "Lost connection"的错误看起来是ob集群还没有初始化完成。

你好，OBServer 一定需要至少3个节点吗 ？两个可以吗 ？

**Comment by hnwyllmm** [comment]
用几个节点，集群中部署几个zone，通常按照你们业务需求中对高可用和容灾的需求，oceanbase本身对此并没有要求。
不过部署两个节点，通常意义不大，并不能提高系统的可用性，只要一个节点宕机，系统就不能提供服务了。

**Comment by CodePlayer** [comment]
> 用几个节点，集群中部署几个zone，通常按照你们业务需求中对高可用和容灾的需求，oceanbase本身对此并没有要求。 不过部署两个节点，通常意义不大，并不能提高系统的可用性，只要一个节点宕机，系统就不能提供服务了。

好的，感谢你的热心回复。我们只是测试环境，物理节点不多，只要能确认不是因为2个节点导致集群无法初始化就好。
再次感谢！

**Comment by hnwyllmm** [comment]
测试环境数据不重要的话，配置单个节点也可以的。

**Comment by CodePlayer** [comment]
> 测试环境数据不重要的话，配置单个节点也可以的。

是的，我们配置两个，主要是想观察一下两个节点之间的数据互联同步情况。

**Comment by CodePlayer** [comment]
删除干净后再重装，该问题已解决，谢谢！
