### ISSUE TITLE
[Bug]: 刚刚新安装的OceanBase集群，没有业务数据，CPU占用非常高

### ISSUE THREAD

**Issue by CodePlayer** [oceanbase/oceanbase#1938]
**Describe the bug**
我从官网下载了 OceanBase 4.2.2 最新社区版（ `oceanbase-all-in-one-4.2.2.0-100010012024022719.el8.x86_64.tar.gz` ），只是创建了一个业务租户，分配了资源池，还 **没有** 导入任何数据。
但是，结果发现每个节点的CPU占用都非常高，CPU占用达到了 600~700+%，看起来有点吓人。

后来，我把新建的业务租户删除掉，以保持系统安装的默认租户现状，结果 CPU 占用还是高达 400+% 。

在此之前，我把该问题发帖反馈到了 OceanBase 社区，在各位热心朋友的帮助下，也采集了不少的诊断数据（包括但不限于 `observer.log` 日志、线程占用、最耗CPU的部分SQL、`obdiag`），完整的过程和数据可以参见 [https://ask.oceanbase.com/t/topic/35607662/17](https://ask.oceanbase.com/t/topic/35607662/17)，在此不再赘述 。

最后，在好心人的帮助下，通过 ``perf top -p `pidof observer` `` 采集到 OBServer 的 CPU 占用的函数调用分布，发现 CPU占用过高 的 原因大概率是因为内核调用 `read_hpet` 占用了过多的 CPU 所致 。

![perf数据](https://github.com/oceanbase/oceanbase/assets/3793502/4c278291-63f7-4562-8c7b-fe1a046c3dd7)

**Environment**

- CentOS 8.2 x86_64： `Linux test02 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- CPU：`Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz` 
- OceanBase：4.2.2.0 社区版
  

**Fast Reproduce Steps(Required)**

**Expected behavior**
我们在本地环境，采用相同的方式，部署了另一个集群，在没有业务数据的情况下，每个节点正常的CPU占用只有 15% 左右。
希望该问题集群的CPU占用能够恢复正常。

**Actual Behavior**
实际的CPU占用高达 600~700%
![cpu_load](https://github.com/oceanbase/oceanbase/assets/3793502/7b009acc-fcc4-4e10-9d23-da703704dbc7)

**Additional context**
删除 新建的业务租户后（实际并没有业务数据），CPU占用有所降低，但还是有 400+%
![cpu_load_default](https://github.com/oceanbase/oceanbase/assets/3793502/8741c9fc-61a5-4a00-b4f7-c81b34468e4b)

以下是CPU占用表现正常的另一个集群
> 该集群的 perf 采集数据没有发现 `read_hpet` CPU 占用过高。
> 不同的是该集群系统为 CentOS 7.9（ `Linux k8s-master 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux` ） ，CPU是 `13th Gen Intel(R) Core(TM) i7-13700K`）。

![local_cpu_load](https://github.com/oceanbase/oceanbase/assets/3793502/b8f4fc9f-3a24-4b40-9e65-0c0003948fc2)

**Comment by Teingi** [comment]
已确认，当 OBServer 服务器使用 hpet 作为时钟源类型时，获取系统时间的开销会比较大，进而可能导致内核态 CPU 使用率高。

规避的方法是将时钟源修改为tsc,

echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource

**Comment by CodePlayer** [comment]
我在启用了 `tsc` 时钟源后，重启了系统 以及 OceanBase 集群，目前观察到 CPU 的占用只有 60+% 了。

![tsc_cpu_load](https://github.com/oceanbase/oceanbase/assets/3793502/13b5eeb1-ae01-457c-bda8-2cb6db2b5ed5)

不过，整个历程还是挺折腾的，建议官方能够在文档中，或者 安装工具中 给予较为明确的提示，以便后来者不再重复踩坑！
感谢整个过程中，所有不知名的朋友给予的热心回复+耐心帮助 ~！

**Comment by hnwyllmm** [comment]
官网文档往往会滞后，如果楼主方便的话，可以把问题排查过程，发个博客出来，大家也可以搜到。
其实时钟源的问题，不仅仅是数据库，其它应用也会有类似的问题。

**Comment by Teingi** [comment]
> 我在启用了 `tsc` 时钟源后，重启了系统 以及 OceanBase 集群，目前观察到 CPU 的占用只有 60+% 了。
> 
> ![tsc_cpu_load](https://private-user-images.githubusercontent.com/3793502/325151561-13b5eeb1-ae01-457c-bda8-2cb6db2b5ed5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTA4OTgsIm5iZiI6MTcxMzk1MDU5OCwicGF0aCI6Ii8zNzkzNTAyLzMyNTE1MTU2MS0xM2I1ZWViMS1hZTAxLTQ1N2MtYmRhOC0yY2I2ZGIyYjVlZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDkyMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI0YjQxMTE3ODBkYzcwZDYzYWRlMTM1MTczZjM5NmQyZjQyZDg5NDk3YjVlMDQ2Yzk3M2ZhMGI5Yjc4MjU5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xn--FEEbT2deF1g5LgfCVSNfOs96YiI-RsK1bRXetIs)
> 
> 不过，整个历程还是挺折腾的，建议官方能够在文档中，或者 安装工具中 给予较为明确的提示，以便后来者不再重复踩坑！ 感谢整个过程中，所有不知名的朋友给予的热心回复+耐心帮助 ~！

敏捷诊断工具obdiag 的巡检中已经记录了需求了，预计5月初发布的obdiag 2.1.0就会支持这个巡检项。https://github.com/oceanbase/oceanbase-diagnostic-tool/issues/179

**Comment by CodePlayer** [comment]
> 官网文档往往会滞后，如果楼主方便的话，可以把问题排查过程，发个博客出来，大家也可以搜到。 其实时钟源的问题，不仅仅是数据库，其它应用也会有类似的问题。

OceanBase 官方社区已包含整个过程，也补充完善了 **如何切换时钟源** 的[相关教程](https://ask.oceanbase.com/t/topic/35607662/44)，大家如果有需要，可以自行点击查看。
