### ISSUE TITLE
[Bug]: latest master branch(2abb0b0) compiles with an error

### ISSUE THREAD

**Issue by Dragonliu2018** [oceanbase/oceanbase#1942]
**Describe the bug**

The latest master branch(2abb0b075ebce4886af4db536da56cd6ae1b6161) compiles with an error.

```shell
/home/runner/work/oceanbase/oceanbase/src/logservice/libobcdc/src/ob_log_instance.cpp:1708:87: error: use of undeclared identifier 'EPUT'
    if (EINSERT == record_type || EUPDATE == record_type || EDELETE == record_type || EPUT == record_type) {
```
**Environment**

- OS Version and CPU Arch(`uname -a`): Linux  4.9.151-015.ali3000.alios7.x86_64  SMP Tue Mar 12 19:10:26 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`): latest master branch(2abb0b075ebce4886af4db536da56cd6ae1b6161)
  

**Fast Reproduce Steps(Required)**

compile OB

**Expected behavior**

**Actual Behavior**

compile failed, can see https://github.com/oceanbase/oceanbase/actions/runs/8842989372/job/24282520452

**Additional context**

**Comment by qiuyg3** [comment]
I think it's an undefined error in EPUT

**Comment by hnwyllmm** [comment]
closed by https://github.com/oceanbase/oceanbase/commit/db22f4f1b10c9a9b9f93a094ac9d305dcaec6790
