### ISSUE TITLE
[Question]: DISTRIBUTED TABLE GET = 1 or TABLE GET = 1 可能会对优化器选择物理计划造成影响？

### ISSUE THREAD

**Issue by Freejww** [oceanbase/oceanbase#1943]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
在执行一条查询时，查看物理计划（figure 1）发现，如果对于表的扫描算子是DISTRIBUTED TABLE GET OR TABLE GET，给出的预估基数为1，但实际上可以看到表的真实基数与1相差非常大，通过几条类似的查询发现只要是DISTRIBUTED TABLE GET = 1 or TABLE GET = 1 ，在join时选择物理算子时会优先选择NLJ，我通过改变join order(figure2)使得规避对于表的扫描有DISTRIBUTED TABLE GET = 1 or TABLE GET = 1 ，表的连接会转为HJ，从而执行时间变快了。

不知道这里对于DISTRIBUTED TABLE GET OR TABLE GET的预估基数设置为1使得选择物理算子时会选择NLJ 是否合理？

figure 1<img width="602" alt="image" src="https://github.com/oceanbase/oceanbase/assets/103876282/a79bcdf1-aad5-46a0-b1ee-e742c9dbd069">

figure 2<img width="538" alt="image" src="https://github.com/oceanbase/oceanbase/assets/103876282/adaf0578-7e6b-49c7-9b55-e7bca7200158">

**Environment**

- OS Version and CPU Arch(`uname -a`):

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

**Comment by hnwyllmm** [comment]
observer版本是多少？

**Comment by Freejww** [comment]
> observer版本是多少？

Server version: 5.6.25 OceanBase_CE 4.3.0.1

**Comment by akaError** [comment]
> > observer版本是多少？
> 
> Server version: 5.6.25 OceanBase_CE 4.3.0.1

逻辑弄返了，计划选择是一个代价竞争的过程，对于DISTRIBUTED TABLE GET OR TABLE GET的预估基数设置为1使得选择物理算子时会选择NLJ这种说法是规则化的， 你的问题应该是需要弄清楚为什么在你的查询中会预估一行，是不是没收集统计信息或有一些特殊的谓词无法估计，当然也不排队oceanbase的估行没有cover到你的case，具体的排查需要提供下你的相关的schema，explain extended计划等，这种问题麻烦去我们的论坛ask.oceanbase.com发贴提问吧

**Comment by Freejww** [comment]
> > > observer版本是多少？
> > 
> > 
> > Server version: 5.6.25 OceanBase_CE 4.3.0.1
> 
> 逻辑弄返了，计划选择是一个代价竞争的过程，对于DISTRIBUTED TABLE GET OR TABLE GET的预估基数设置为1使得选择物理算子时会选择NLJ这种说法是规则化的， 你的问题应该是需要弄清楚为什么在你的查询中会预估一行，是不是没收集统计信息或有一些特殊的谓词无法估计，当然也不排队oceanbase的估行没有cover到你的case，具体的排查需要提供下你的相关的schema，explain extended计划等，这种问题麻烦去我们的论坛ask.oceanbase.com发贴提问吧

thanks
