### ISSUE TITLE
迪聚海思手术麻醉信息系统

### ISSUE THREAD

**Issue by worldpeacelove** [oceanbase/oceanbase#1966]
公司: 深圳迪聚海思科技有限公司
地点: 中国, 深圳
联系方式: [yanfabu@digihealth.net]
业务场景: 医疗手术麻醉管理
额外信息(可选): 公司秉承“科技健康未来”的企业使命，凭借十多年的医疗行业经验和先进IT技术经验，面向全球市场，为医院提供具有核心知识产权的重症监护临床信息系统（DIGI-ICIS），急诊急救临床信息系统(DIGI-ECIS)，手术室麻醉临床信息系统(DIGI-AIMS)，移动医疗和移动护理等医疗信息化解决方案。

**Comment by hnwyllmm** [comment]
你应该在这里增加一个评论：https://github.com/oceanbase/oceanbase/issues/1301
