### ISSUE TITLE
[Feature]: skyingworking的使用

### ISSUE THREAD

**Issue by zhuhuaiyu-nn** [oceanbase/oceanbase#1969]
请问OceanBase有支持skyworking插件的计划么

**Comment by zhuhuaiyu-nn** [comment]
apache/skywalking

**Comment by hnwyllmm** [comment]
现在的obagent支持普罗米修斯，是不是可以直接对接skywalking?

**Comment by caifeizhi** [comment]
可以具体描述一下你的想法么？在哪些场景，遇到了什么问题，希望引入Apache Skywalking？

**Comment by zhuhuaiyu-nn** [comment]
打算引入Apache Skywalking进行链路分析，目前看没有采集到ob的sql信息，查看了一些资料表示需要一个【apm-oceanbase的plugin包】,不知道大佬们有啥好办法不

**Comment by zhuhuaiyu-nn** [comment]
> 现在的obagent支持普罗米修斯，是不是可以直接对接skywalking?

您是说 普罗米修斯可以从ob agent采集到具体的执行sql信息么

**Comment by hnwyllmm** [comment]
> > 现在的obagent支持普罗米修斯，是不是可以直接对接skywalking?
> 
> 您是说 普罗米修斯可以从ob agent采集到具体的执行sql信息么

obgent就是与oceanbase配套的，采集了一些OceanBase的指标数据。他可以支持普罗米修斯，理论上可以直接对接skywalking。但是你要求的更具体的统计信息，要具体分析。
不用那么客气，不用称呼您。

**Comment by hnwyllmm** [comment]
如果需要采集SQL执行的信息，需要考虑sql_audit数据。
不过还是先看下你们具体的业务场景吧

**Comment by zhuhuaiyu-nn** [comment]
> > > 现在的obagent支持普罗米修斯，是不是可以直接对接skywalking?
> > 
> > 
> > 您是说 普罗米修斯可以从ob agent采集到具体的执行sql信息么
> 
> obgent就是与oceanbase配套的，采集了一些OceanBase的指标数据。他可以支持普罗米修斯，理论上可以直接对接skywalking。但是你要求的更具体的统计信息，要具体分析。 不用那么客气，不用称呼您。

obagent我理解主要是负责路由数据库的请求，向业务层屏蔽ob的分片逻辑和路由规则。skywalking可以直接对接么。

【场景】我们计划使用skywalking做链路追踪，同时实现controller的下钻一直到sql这样可以做性能分析

**Comment by hnwyllmm** [comment]
你说的不是obagent是obproxy。obagent是采集OceanBase和主机运行指标数据的，做监控用的。
但是obagent无法做具体的SQL性能分析。OCP 是一个OceanBase 运维、监控一体的管控平台，应该是可以满足你的需求的。

**Comment by zhuhuaiyu-nn** [comment]
嗯嗯 明白您的意思了OCP 确实是个不错的平台 这是数据库层面的统一分析平台。
其实我这不知道 obagent的监控信息不知道能不能整合到调用链路。

> 你说的不是obagent是obproxy。obagent是采集OceanBase和主机运行指标数据的，做监控用的。 但是obagent无法做具体的SQL性能分析。OCP 是一个OceanBase 运维、监控一体的管控平台，应该是可以满足你的需求的。

**Comment by hnwyllmm** [comment]
数据库的性能问题，SQL运行慢是一个方面，还有整体的性能问题。
OB提供了ASH和WR功能，帮助诊断性能问题，在4.2.2版本上可用：

**Comment by zhuhuaiyu-nn** [comment]
> 数据库的性能问题，SQL运行慢是一个方面，还有整体的性能问题。 OB提供了ASH和WR功能，帮助诊断性能问题，在4.2.2版本上可用： https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749938 https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749935

感谢大佬的回复。我这看下来这个主要是数据库整体层面的性能分析，没法通过traceid在skywalking的调用链路显示具体某个请求的sql，这样理解是对的不

**Comment by hnwyllmm** [comment]
是的，只是给你介绍另一个工具

**Comment by hnwyllmm** [comment]
https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749332
OB本身也是有全链路跟踪的，可以看这个

**Comment by zhuhuaiyu-nn** [comment]
> https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749332 OB本身也是有全链路跟踪的，可以看这个

这个看下来是针对从开始obproxy往后到OBServer的数据库内部的trace是不。这样还是没法和skywalking这样的应用apm工具进行联动，我这样理解对不

**Comment by zhuhuaiyu-nn** [comment]
> https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749332 OB本身也是有全链路跟踪的，可以看这个

再次感谢大佬，我们研究一下这个。

**Comment by hnwyllmm** [comment]
我把 issue 关掉了，后面有新的问题，随时开issue讨论。
