### ISSUE TITLE
ob_batch_submit_task.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#197]
下面的代码中，这里的dtask 应该是task .
/code/oceanbase/src/clog/ob_batch_submit_task.cpp : 189,197
ret_val = alloc_mgr->alloc_batch_submit_dtask();
ob_slice_free_batch_submit_dtask(task);

**Comment by LINxiansheng** [comment]
Thanks for your contribution, but I think the 'dtask' maybe mean dxx task.
After I ask the developer I reply the answer here.
