### ISSUE TITLE
[Enhancement]: oblogminer optimization || [Enhancement]: ologminer optimization

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#2017]
**Enhancement**
当前 oblogminer 无法判断obcdc 输出的结果是否可信，因此对于所有可能不正确的SQL 标记 `/* POTENTIALLY INACCURATE */`。在obcdc 4.3.1 版本支持标记输出的列值是否可信。因此oblogminer 可以将obcdc 标记可信的列值正常输出，无需标记`/* POTENTIALLY INACCURATE */`。如果对更多细节有疑问，可参考[oblogminer 文档](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749609)，或在本 issue 下评论。

参考信息:

列值不可信的场景：行外存储的Lob 类型在更新或删除操作时，前镜像值可能会输出为不可信的 NULL 值。可参考 #1927 

如何判断列值是否可信：
oblogmsg 库中`ValueOrigin.h`中的enum类型`VALUE_ORIGIN`代表了列值来源，`VALUE_ORIGIN::REDO`代表列值来源于日志，说明该列为可信的，`VALUE_ORIGIN::PADDING`代表列值来源于OBCDC自己生成的，不代表真实列值。

---
**Enhancement**
Currently oblogminer cannot judge whether the results output by obcdc are trustworthy, so for all possible incorrect SQL tags `/* POTENTIALLY INACCURATE */`. In obcdc version 4.3.1, it is supported to mark whether the output column value is trustworthy. Therefore, oblogminer can output obcdc-marked trusted column values ​​normally without marking `/* POTENTIALLY INACCURATE */`. If you have questions about more details, you can refer to the [oblogminer documentation](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000749609), or leave a comment under this issue.

Reference Information:

Scenarios where column values ​​are untrustworthy: During an update or delete operation for a Lob type stored outside the row, the pre-mirror value may be output as an untrusted NULL value. Please refer to #1927

How to determine whether a column value is trustworthy:
The enum type `VALUE_ORIGIN` in `ValueOrigin.h` in the oblogmsg library represents the source of the column value, `VALUE_ORIGIN::REDO` represents the column value from the log, indicating that the column is trusted, `VALUE_ORIGIN::PADDING` represents the column The values ​​are generated by OBCDC itself and do not represent the real column values.

**Comment by nautaa** [comment]
@hnwyllmm 看起来 translate bot 有点问题，对于纯英文的title 也会翻译。`[Enhancement]: oblogminer optimization`-> `[Enhancement]: oblogminer optimization || [Enhancement]: ologminer optimization`

**Comment by hnwyllmm** [comment]
语言探测的结果不是完全准确的，好在这个软件大部分情况下是可以正确工作的。

**Comment by 2549141519** [comment]
您好！我修改了log_minner_record.cpp的源代码，我的理解是无法让cdc捕获的数据变得正确（ https://github.com/oceanbase/oceanbase/issues/1927），但是可以判断出数据本来就是NULL还是cdc修改成了NULL，从而达到是否标记/* POTENTIALLY INACCURATE */的目的。

**Comment by 2549141519** [comment]
您好！我修改了log_miner_record.cpp的源代码，我的理解是无法让cdc本身捕获的lob数据变得正确（ 您提到的issue），但是logminer可以判断这个lob类型的NULL是真实的操作，还是cdc修改的错误的操作，从而达到是否追加/* POTENTIALLY INACCURATE */的目的。

用户命令：
insert into t_blob_text values(repeat('😂',16383),repeat('犇',300));
delete from t_blob_text;
insert into t_blob_text values(NULL,repeat('犇',300));
delete from t_blob_text;

logminner运行结果： 
![image](https://github.com/user-attachments/assets/c84d7d5c-e134-4b03-ba93-37e42e91c6dd)
![image](https://github.com/user-attachments/assets/3104b587-dc05-4e56-b082-c8a1f1f5f84f)

请问这个思路目前是对的吗 抱歉打扰

**Comment by nautaa** [comment]
@2549141519 对的
