### ISSUE TITLE
审计代码没有开源吗，为什么没有看见check_allow_stmt_operation类似实现的地方 || Is the audit code not open source? Why don’t you see similar implementations of check_allow_stmt_operation?

### ISSUE THREAD

**Issue by 1412904892** [oceanbase/oceanbase#2067]
https://github.com/oceanbase/oceanbase/blob/1af450cb550012cb8d4ad0e0afa1defff1e6e275/src/sql/monitor/ob_security_audit_utils.h#L267C14-L267C40

**Comment by hnwyllmm** [comment]
是的，audit代码没有开源。
