### ISSUE TITLE
[Question]: ob-mysql cannot be found when configuring oceanbase in docker

### ISSUE THREAD

**Issue by DBMSTesting** [oceanbase/oceanbase#2073]
Follow the installation steps in the user guide and enter the container:
docker exec -it obstandalone ob-mysql sys
But the ob-mysql file cannot be found:
OCI runtime exec failed: exec failed: unable to start container process: exec: “ob-mysql”: executable file not found in $PATH: unknown

Is there any configuration error?

Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-150-generic x86_64)

**Comment by whhe** [comment]
`ob-mysql` was removed in the latest `oceanbase/oceanbase-ce` Docker image. You can check it at https://github.com/oceanbase/docker-images/tree/main/oceanbase-ce
