### ISSUE TITLE
[Bug]: obcdc配置config_fpath选项无效 || [Bug]: obcdc configuration config_fpath option is invalid

### ISSUE THREAD

**Issue by guziqiu** [oceanbase/oceanbase#2075]
**Describe the bug**

libobcdc配置了config_fpath选项，配置无效，只能将配置选项的文件放置在程序启动路径下。
配置后启动obcdc报错load_from_file fail。。。
**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  均有此问题， 4.2.3

**Fast Reproduce Steps(Required)**

**Expected behavior**

**Actual Behavior**

**Additional context**

ob源码 4.2.3分支中2370行一直使用默认路径读取配置文件
oceanbase/src/logservice/libobcdc/src/ob_log_instance.cpp

---
**Describe the bug**

libobcdc is configured with the config_fpath option, but the configuration is invalid. You can only place the configuration option file in the program startup path.
After configuration, the error load_from_file fail is reported when starting obcdc. . .
**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  All have this problem, 4.2.3

**Fast Reproduce Steps(Required)**

**Expected behavior**

**Actual Behavior**

**Additional context**

Line 2370 in the ob source code 4.2.3 branch always uses the default path to read the configuration file.
oceanbase/src/logservice/libobcdc/src/ob_log_instance.cpp

**Comment by nautaa** [comment]
感谢反馈，请问是否有兴趣帮忙提交PR修复下呢？ @guziqiu

**Comment by nautaa** [comment]
我发现这个问题已经被你修复过了，https://github.com/oceanbase/oceanbase/pull/1760，后续我把这个patch 到4.2.x 分支。
