### ISSUE TITLE
[Question]: load data local infile '' 中的 '' 在OB中不能为空，而MySQL数据库可以为空 || [Question]: The '' in load data local infile '' cannot be empty in OB, but the MySQL database can be empty.

### ISSUE THREAD

**Issue by ZhuKaley** [oceanbase/oceanbase#2078]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
load data local infile '' 中的 '' 在OB中不能为空，而在MySQL数据库中可以为空；
使用JDBC分别去连OB和MySQL，然后，执行load data local infile ''，OB会报文件不存在的错误，MySQL插入数据成功；
请问对于这个问题，OB这边会兼容MySQL吗？

java代码如下：
`package org.example;

import com.oceanbase.jdbc.OceanBaseStatement;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.*;

public class Main {

    static String createTable = "create table if not exists test_stream_load ("
            + " ID_ varchar(20) binary,"
            + " NAME_ varchar(20) binary,"
            + " SAL_ decimal(18,2),"
            + " CNT_ bigint,"
            + " DATE_ date,"
            + " DATETIME_ datetime(3) null default null)";

    static String loadData = "load data local infile '' replace into table test_stream_load character set utf8mb4 fields terminated by ',' enclosed by '\"' escaped by '\"' lines terminated by '\\n' "
            + "(@id,@name,@sal,@cnt,@date,@datetime) set ID_=nullif(@id,''),NAME_=nullif(@name,''),SAL_=nullif(@sal,''),CNT_=nullif(@cnt,''),DATE_=nullif(@date,''),DATETIME_=nullif(@datetime,'')";

    static String data = "0006,北京,0.15,11,2016-08-17,2017-08-18 15:22:34\n0007,上海,3455.33,22,2016-08-18,2016-08-18 13:23:33";

    static String obConnUrl = "jdbc:oceanbase://xxx:xxx/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowLoadLocalInfile=true";
    static String obUser = "xxx";
    static String obPwd = "xxx";

    static String myConnUrl = "jdbc:mysql://xxx:xxx/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowLoadLocalInfile=true&allowPublicKeyRetrieval=true";
    static String myUser = "xxx";
    static String myPwd = "xxx";

    public static void main(String[] args) {
        // testMySQL();
        testOB();
    }

    public static void testOB() {
        try {
            InputStream in = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
            try (Connection conn = DriverManager.getConnection(obConnUrl, obUser, obPwd)) {
                conn.setAutoCommit(true);
                try (Statement stat = conn.createStatement()) {
                    stat.execute(createTable);
                    OceanBaseStatement mysqlStmt = stat.unwrap(OceanBaseStatement.class);
                    mysqlStmt.setLocalInfileInputStream(in);
                    stat.execute(loadData);

                    stat.execute("select * from test_stream_load");
                    try (ResultSet rs = stat.getResultSet()) {
                        while (rs.next()) {
                            System.out.println(rs.getString(1) + "," + rs.getString(2) + "," + rs.getString(3));
                        }
                    }
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public static void testMySQL() {
        try {
            InputStream in = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
            try (Connection conn = DriverManager.getConnection(myConnUrl, myUser, myPwd)) {
                try (Statement stat = conn.createStatement()) {
                    stat.execute(createTable);
                    com.mysql.cj.jdbc.StatementImpl mysqlStmt = (com.mysql.cj.jdbc.StatementImpl) stat;
                    mysqlStmt.setLocalInfileInputStream(in);
                    stat.execute(loadData);

                    stat.execute("select * from test_stream_load");
                    try (ResultSet rs = stat.getResultSet()) {
                        while (rs.next()) {
                            System.out.println(rs.getString(1) + "," + rs.getString(2) + "," + rs.getString(3));
                        }
                    }
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}`

**Environment**

- OS Version and CPU Arch(`uname -a`):
Linux ab49610813b4 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
observer (OceanBase_CE 4.3.1.0)

REVISION: 1-292a72f4b39a12e5e055751334c4cf35afd723ac
BUILD_BRANCH: develop
BUILD_TIME: Apr 15 2024 05:52:07
BUILD_FLAGS: Debug
BUILD_INFO: 

Copyright (c) 2011-present OceanBase Inc.

---
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
The '' in load data local infile '' cannot be empty in the OB, but can be empty in the MySQL database;
Use JDBC to connect to OB and MySQL respectively, and then execute load data local infile ''. OB will report an error that the file does not exist, and MySQL inserts data successfully;
Regarding this issue, will OB be compatible with MySQL?

The java code is as follows:
`package org.example;

import com.oceanbase.jdbc.OceanBaseStatement;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.*;

public class Main {

    static String createTable = "create table if not exists test_stream_load ("
            + "ID_ varchar(20) binary,"
            + "NAME_ varchar(20) binary,"
            + " SAL_ decimal(18,2),"
            + " CNT_ bigint,"
            + "DATE_ date,"
            + "DATETIME_ datetime(3) null default null)";

    static String loadData = "load data local infile '' replace into table test_stream_load character set utf8mb4 fields terminated by ',' enclosed by '\"' escaped by '\"' lines terminated by '\\n' "
            + "(@id,@name,@sal,@cnt,@date,@datetime) set ID_=nullif(@id,''),NAME_=nullif(@name,''),SAL_=nullif(@sal ,''),CNT_=nullif(@cnt,''),DATE_=nullif(@date,''),DATETIME_=nullif(@datetime,'')";

    static String data = "0006,Beijing,0.15,11,2016-08-17,2017-08-18 15:22:34\n0007,Shanghai,3455.33,22,2016-08-18,2016-08-18 13 :23:33";

    static String obConnUrl = "jdbc:oceanbase://xxx:xxx/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowLoadLocalInfile=true";
    static String obUser = "xxx";
    static String obPwd = "xxx";

    static String myConnUrl = "jdbc:mysql://xxx:xxx/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowLoadLocalInfile=true&allowPublicKeyRetrieval=true";
    static String myUser = "xxx";
    static String myPwd = "xxx";

    public static void main(String[] args) {
        // testMySQL();
        testOB();
    }

    public static void testOB() {
        try {
            InputStream in = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
            try (Connection conn = DriverManager.getConnection(obConnUrl, obUser, obPwd)) {
                conn.setAutoCommit(true);
                try (Statement stat = conn.createStatement()) {
                    stat.execute(createTable);
                    OceanBaseStatement mysqlStmt = stat.unwrap(OceanBaseStatement.class);
                    mysqlStmt.setLocalInfileInputStream(in);
                    stat.execute(loadData);

                    stat.execute("select * from test_stream_load");
                    try (ResultSet rs = stat.getResultSet()) {
                        while (rs.next()) {
                            System.out.println(rs.getString(1) + "," + rs.getString(2) + "," + rs.getString(3));
                        }
                    }
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public static void testMySQL() {
        try {
            InputStream in = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
            try (Connection conn = DriverManager.getConnection(myConnUrl, myUser, myPwd)) {
                try (Statement stat = conn.createStatement()) {
                    stat.execute(createTable);
                    com.mysql.cj.jdbc.StatementImpl mysqlStmt = (com.mysql.cj.jdbc.StatementImpl) stat;
                    mysqlStmt.setLocalInfileInputStream(in);
                    stat.execute(loadData);

                    stat.execute("select * from test_stream_load");
                    try (ResultSet rs = stat.getResultSet()) {
                        while (rs.next()) {
                            System.out.println(rs.getString(1) + "," + rs.getString(2) + "," + rs.getString(3));
                        }
                    }
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}`

**Environment**

- OS Version and CPU Arch(`uname -a`):
Linux ab49610813b4 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
observer (OceanBase_CE 4.3.1.0)

REVISION: 1-292a72f4b39a12e5e055751334c4cf35afd723ac
BUILD_BRANCH: develop
BUILD_TIME: Apr 15 2024 05:52:07
BUILD_FLAGS: Debug
BUILD_INFO:

Copyright (c) 2011-present OceanBase Inc.

**Comment by ZhuKaley** [comment]
在OB的resolve阶段，会判断文件名是否为空，如果为空，就报文件不存在的错误；
MySQL的代码中，没有去判断文件名是否为空，因此，没有报错；

**Comment by hnwyllmm** [comment]
你说得对，可以帮忙提个PR吗？检测LOCAL模式下空文件不报错？

**Comment by ZhuKaley** [comment]
可以的

**Comment by hnwyllmm** [comment]
多谢，我把issue assign给你

**Comment by ZhuKaley** [comment]
好的，请问我提到哪个分支上呢？

**Comment by hnwyllmm** [comment]
提交到master吧。
我会同步到其它分支。
