### ISSUE TITLE
[Bug]: Compile Error: 'sanity/sanity.h' file not found

### ISSUE THREAD

**Issue by Young-Cody** [oceanbase/oceanbase#2111]
**Describe the bug**

![image](https://github.com/user-attachments/assets/fe52a70c-16d8-465a-9489-7ff4715234a2)
When I compile the 4.2.x branch, I get the error: 'sanity/sanity.h' file not found. Is this my fault?
**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  

**Fast Reproduce Steps(Required)**
Compile in branch 4.2.x

**Expected behavior**

**Actual Behavior**

**Additional context**

**Comment by hnwyllmm** [comment]
What command did you executed?

**Comment by Young-Cody** [comment]
bash build.sh release --init --make -j16

**Comment by hnwyllmm** [comment]
Working on it.

**Comment by PanternBao** [comment]
@hnwyllmm I want to compile observer with sanity, but I encounter the same problem, how to reslove it?
