### ISSUE TITLE
[Bug]: Although the CASE WHEN clause returns the same value as the direct concatenation, FIELD yields different results in each case.

### ISSUE THREAD

**Issue by akuluasan** [oceanbase/oceanbase#2141]
**Describe the bug**
```sql
select FIELD((case when true then ('i' || 'o') else '0' end), 'c') as c0;
+------+
| c0   |
+------+
|    0 |
+------+
1 row in set, 2 warnings (0.001 sec)

select FIELD(('i' || 'o'), 'c') as c0;
+------+
| c0   |
+------+
|    1 |
+------+
1 row in set, 3 warnings (0.001 sec)

```
The condition for CASE WHEN is TRUE, so this clause should return the result of ('i' || 'o'). This statement should return the same value as select FIELD(('i' || 'o'), 'c') as c0;, but the actual result is not the same.

**Environment**

- OS Version and CPU Arch(`uname -a`):

 ```
  Linux ubuntu 5.15.0-122-generic #132~20.04.1-Ubuntu SMP Fri Aug 30 15:50:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):

 ```
 5.7.25-OceanBase_CE-v4.2.1.7 
```

**Fast Reproduce Steps(Required)**

```sql
select FIELD((case when true then ('i' || 'o') else '0' end), 'c') as c0;
select FIELD(('i' || 'o'), 'c') as c0;

```
**Expected behavior**

They return the same result
**Actual Behavior**

They return different results
**Additional context**

**Comment by hnwyllmm** [comment]
This is the same issue with https://github.com/oceanbase/oceanbase/issues/2140.
`(case when true then ('i' || 'o') else '0' end)` is a `varchar` and 'c' is 'varchar' too.
`('i' || 'o')` is a number so 'c' should be cast to a number.

**Comment by hnwyllmm** [comment]
Feel free to reopen the issue if you have more information.
