### ISSUE TITLE
[Bug]: 修改参数时 SCOPE = SPFILE 把内存值也修改了 || [Bug]: When modifying parameters, SCOPE = SPFILE also modifies the memory value.

### ISSUE THREAD

**Issue by lxc-19092808** [oceanbase/oceanbase#2142]
**Describe the bug**

执行 ALTER SYSTEM SET 语句添加 SCOPE = SPFILE 选项计划只修改内存中参数时，发现同时对内存和文件的参数进行了修改。

**Environment**

- OS Version and CPU Arch(`uname -a`):
  centos 7.3
  Linux rhel7304 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  observer (OceanBase 4.2.1.8)

REVISION: 108010012024082314-17a07c4b17c6382a6fdb8b47fd1e525de5d4f018
BUILD_BRANCH: HEAD
BUILD_TIME: Aug 23 2024 14:26:02
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

**Fast Reproduce Steps(Required)**
SHOW PARAMETERS LIKE '%syslog_level%'\G
ALTER SYSTEM SET syslog_level='ERROR' SCOPE = SPFILE;
SHOW PARAMETERS LIKE '%syslog_level%'\G

**Expected behavior**

执行 ALTER SYSTEM SET 语句添加 SCOPE = SPFILE 只修改文件中参数。

**Actual Behavior**

**Additional context**

---
**Describe the bug**

When executing the ALTER SYSTEM SET statement to add the SCOPE = SPFILE option and planning to modify only the parameters in memory, it was found that the parameters in memory and files were modified at the same time.

**Environment**

- OS Version and CPU Arch(`uname -a`):
  centos 7.3
  Linux rhel7304 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  observer (OceanBase 4.2.1.8)

REVISION: 108010012024082314-17a07c4b17c6382a6fdb8b47fd1e525de5d4f018
BUILD_BRANCH: HEAD
BUILD_TIME: Aug 23 2024 14:26:02
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO:

**Fast Reproduce Steps(Required)**
SHOW PARAMETERS LIKE '%syslog_level%'\G
ALTER SYSTEM SET syslog_level='ERROR' SCOPE = SPFILE;
SHOW PARAMETERS LIKE '%syslog_level%'\G

**Expected behavior**

Execute the ALTER SYSTEM SET statement to add SCOPE = SPFILE to only modify the parameters in the file.

**Actual Behavior**

**Additional context**

**Comment by hnwyllmm** [comment]
看起来是一个为了兼容旧功能保留的一个关键字，实际上已经不生效了。可以看下下面两个文档。

[3.x doc](https://www.oceanbase.com/docs/community-observer-cn-10000000000016743)
[4.x doc](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000001433162)
