### ISSUE TITLE
[Bug]: Update with subquery cannot fetch correct snapshot in RR isolation level

### ISSUE THREAD

**Issue by wengsy150943** [oceanbase/oceanbase#2145]
**Describe the bug**

When using an update with subquery in repeatable read isolation level, it does not get current committed data, following the CURRENT READ requirement. Instead, it returns a stale snapshot data version.

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
 ```mysql
select version();
+------------------------------+
| version()                    |
+------------------------------+
| 5.7.25-OceanBase_CE-v4.3.1.0 |
+------------------------------+
1 row in set (0.00 sec)
```

**Fast Reproduce Steps(Required)**

1. set isolation level to RR.
```mysql
 select @@transaction_isolation;
+-------------------------+
| @@transaction_isolation |
+-------------------------+
| REPEATABLE-READ         |
+-------------------------+
1 row in set (0.00 sec)
```
2. create tables.
```sql
create table t(k int, v int);
create table t1(k int, v int);
insert into t values(1,1);
insert into t1 values(1,1);
```
3. execute the following statements in two session.

| session1                                                     | session2                     | MySQL result | OB result |
| ------------------------------------------------------------ | ---------------------------- | ------------ | --------- |
| begin;                                                       |                              | ok           | ok        |
| select * from t;                                             |                              | <1, 1>       | <1, 1>    |
|                                                              | update t1 set v=2 where k=1; | ok           | ok        |
| update t set t.v=2 where t.v+1=(select v from t1 where v=2); |                              | ok           | ok        |
| commit;                                                      |                              | ok           | ok        |
| select * from t;                                             |                              | <1, 2>       | <1, 1>    |

**Expected behavior**

MySQL's update can fetch the newer data updated in session 2, so the update in session1 affects rows, results in <1,2>.
But OB's update cannot see the newer data, so the update affects 0 row. 

**Additional context**

This issue is similar with TiDB's [issue 45677](https://github.com/pingcap/tidb/issues/45677).
But TiDB's SELECT FOR UPDATE can fetch current committed data as CURRENT READ, while OB cannot.
So it might be harder to fix this issue in OB.

**Comment by hnwyllmm** [comment]
Thanks. We'll discuss the issue.

**Comment by hnwyllmm** [comment]
We reproduced the scenario but we won't fix the issue.
The result of OceanBase is the same as Oracle but difference with MySQL.
In MySQL, the isolation level is Repeatable Read but it can read the committed data or newer version data in the `update` statement. So we think this is a bug of MySQL and we can't make a good compatible.

**Comment by wengsy150943** [comment]
Thanks for your reply! 

But it is still confuzing because Oracle does not have RR Isolation Level(IL). 
It seems that, in Oracle's SR IL, the tranasction gets the snapshot at the beginning of tranasction, but OB does not. In Oracle's RC IL, operations always get the current snapshot.

May I ask for the detailed behaviors of OB's RR IL? In other word, OB's RR IL matches which IL of Oracle?
