### ISSUE TITLE
[Question]: failed to enable vector search, ERROR 5099 (42000): System config unknown

### ISSUE THREAD

**Issue by lizzy-0323** [oceanbase/oceanbase#2153]
If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw)

**Question**
I can't use vector search of ob on my computer, according to the docs, i want to change the variable to enable the vector search module, and after i run 
```sql
ALTER SYSTEM SET ob_vector_memeory_limit_percentage = 30;
```
I got `system config unknown` like this:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/9916dba2-eb9d-42d4-99e1-f15adb13aa49">

**Environment**

- OS Version and CPU Arch(`uname -a`): 
```
Linux ubun 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
```
observer (OceanBase_CE 4.3.3.0)

REVISION: 1-0723f9774e5f77a1253149261ba75a94414625d0
BUILD_BRANCH: vector-demo
BUILD_TIME: Oct 22 2024 22:27:37
BUILD_FLAGS: Debug
BUILD_INFO: 

Copyright (c) 2011-present OceanBase Inc.
```
By the way, BUILD_BRANCH `vector-demo` is my local branch, I checkout from tag `4.3.3_CE `, as you can see below:
<img width="786" alt="image" src="https://github.com/user-attachments/assets/f3260887-dc1b-47a7-a358-45be796fac75">

**Comment by a1iive** [comment]
plz check the `ob_vector_memory_limit_percentage` in `ob_parameter_seed.ipp`

**Comment by a1iive** [comment]
there is a typo : ob_vector_memeory_limit_percentage -> ob_vector_memory_limit_percentage

**Comment by lizzy-0323** [comment]
> there is a typo : ob_vector_memeory_limit_percentage -> ob_vector_memory_limit_percentage

😭Ok，Thank you very much for helping me, and feel sorry to bother you ~
