### ISSUE TITLE
[Feature]: oceanbase

### ISSUE THREAD

**Issue by 329009099** [oceanbase/oceanbase#2157]
Company: Zhiqi Cloud Nanjing Information Technology Co., Ltd.
Location: Nanjing, China
Contact Information:
Business Scenarios: Data analysis for public security, procuratorate, and courts; financial business scenarios; anti-money laundering; and anti-fraud analysis scenarios;

公司: 智器云南京信息科技有限公司
地点: 中国，南京
联系方式:
业务场景: 公检法数据分析、金融业务场景、反洗钱、反欺诈分析场景;

---
Company: Zhiqi Cloud Nanjing Information Technology Co., Ltd.
Location: Nanjing, China
Contact Information:
Business Scenarios: Data analysis for public security, procuratorate, and courts; financial business scenarios; anti-money laundering; and anti-fraud analysis scenarios;

Company: Zhiqiyun Nanjing Information Technology Co., Ltd.
Location: Nanjing, China
Contact information:
Business scenarios: Public security law data analysis, financial business scenarios, anti-money laundering, anti-fraud analysis scenarios;

**Comment by hnwyllmm** [comment]
信息在 https://github.com/oceanbase/oceanbase/issues/1301#issuecomment-2441050489
