### ISSUE TITLE
[Bug]: Issues with NULLIF function

### ISSUE THREAD

**Issue by LLuopeiqi** [oceanbase/oceanbase#2168]
# BugReport: Issues with NULLIF function
## version
4.2.1
## Original sql
```
SELECT DISTINCT o_orderpriority
from orders
WHERE o_comment > IFNULL(3855411377,NULL);
```
return 0 rows

## Rewritten sql
```
SELECT DISTINCT o_orderpriority
FROM orders
WHERE o_comment >
    IFNULL(3855411377, NULLIF(o_orderdate,NULL));
```
return 5 row

## Analysis

The rewritten SQL replaces IFNULL(3855411377, NULL) with IFNULL(3855411377, NULLIF(o_orderdate, NULL)). The result remains unchanged because NULLIF(o_orderdate, NULL) will return either o_orderdate or NULL, but since 3855411377 is non-null, IFNULL(3855411377, NULLIF(o_orderdate, NULL)) will always return 3855411377. Therefore, the filtering condition in both queries (o_comment > 3855411377) remains the same.

However, the number of returned rows is different, indicating the presence of a bug.

## How to repeat
The exported file for the database is in the attachment. : 
https://github.com/LLuopeiqi/newtpcd/blob/main/oceanbase/tpcd.sql

**Comment by hnwyllmm** [comment]
It looks it is the same issue with https://github.com/oceanbase/oceanbase/issues/2167.
Please check it with `explain` and pay attention to the `filter` statement.

**Comment by hnwyllmm** [comment]
I'll close the issue.
Please feel free to reopen the issue if you have further information.
