### ISSUE TITLE
[Bug]: Issues with CAST function

### ISSUE THREAD

**Issue by LLuopeiqi** [oceanbase/oceanbase#2169]
# BugReport: Issues with CAST function
## version
4.2.1
## Original sql
```
select distinct lineitem.l_receiptdate, lineitem.l_returnflag from lineitem 
where ((not (lineitem.l_shipmode not in 
             (781812915, lineitem.l_commitdate, -1313533185)))) is not false ;
```
return 0 row

## Rewritten sql
```
SELECT distinct l_receiptdate, l_returnflag FROM lineitem 
WHERE ( l_shipmode = 781812915 OR
       CAST(l_shipmode AS DATE) = l_commitdate OR 
       l_shipmode = -1313533185 ) is not false ;
```
return 2868 rows

## Analysis
The rewritten SQL replaces the condition NOT (lineitem.l_shipmode NOT IN (781812915, lineitem.l_commitdate, -1313533185)) with (l_shipmode = 781812915 OR CAST(l_shipmode AS DATE) = l_commitdate OR l_shipmode = -1313533185). The result remains unchanged because the rewritten query explicitly expands the NOT IN logic into equivalent OR conditions. Each element of the NOT IN set is checked against l_shipmode, and the conditions remain logically identical. Therefore, the filtering condition in both queries is the same, and the results will be identical.

However, the number of returned rows is different, indicating the presence of a bug.

## How to repeat
The exported file for the database is in the attachment. : 
https://github.com/LLuopeiqi/newtpcd/blob/main/oceanbase/tpcd.sql

**Comment by hnwyllmm** [comment]
This is maybe the same issue with https://github.com/oceanbase/oceanbase/issues/2167.
If not, please feel free to comment below.

**Comment by hnwyllmm** [comment]
I'll close the issue.
Please feel free to reopen the issue if you have further information.
