### ISSUE TITLE
[Bug]: BugReport: Issues with EXISTS function

### ISSUE THREAD

**Issue by LLuopeiqi** [oceanbase/oceanbase#2170]
# BugReport: Issues with EXISTS function
## version
4.2.1
## Original sql
```
SELECT l_extendedprice
FROM lineitem
WHERE (l_comment IN ( COALESCE(1198529099, lineitem.l_discount) )  ) 
	= 0.05420610582877583
GROUP BY l_extendedprice;
```
return 0 row

## Rewritten sql
```
SELECT l_extendedprice
FROM lineitem
WHERE NOT EXISTS (
    SELECT 1
    WHERE l_comment <> 1198529099 OR l_comment IS NULL
) = 0.05420610582877583
GROUP BY l_extendedprice;
```
return 4525 rows

## Analysis
The rewritten SQL replaces the condition (l_comment IN (COALESCE(1198529099, lineitem.l_discount))) with NOT EXISTS (SELECT 1 WHERE l_comment <> 1198529099 OR l_comment IS NULL). The result remains unchanged because both queries evaluate the same logical condition.

Original Query:
+ The COALESCE function returns the first non-NULL value, which is 1198529099 in this case because it is a constant and not NULL.
+ The IN condition checks if l_comment equals 1198529099. This is equivalent to a simple equality comparison.
+ The condition (l_comment IN (1198529099)) = 0.05420610582877583 evaluates whether the comparison result matches 0.05420610582877583.

Rewritten Query:
+ The rewritten query uses a NOT EXISTS subquery instead of IN.
+ The subquery SELECT 1 WHERE l_comment <> 1198529099 OR l_comment IS NULL evaluates whether there are any l_comment values not equal to 1198529099 or that are NULL.
+ The NOT EXISTS ensures that no such rows exist, which is logically equivalent to l_comment = 1198529099.
+ The condition NOT EXISTS (...) = 0.05420610582877583 then compares the result of NOT EXISTS with 0.05420610582877583.

Despite the syntactic difference, both queries perform the same logical check and produce the same result. However, the number of returned rows is different, indicating the presence of a bug.

## How to repeat
The exported file for the database is in the attachment. : 
https://github.com/LLuopeiqi/newtpcd/blob/main/oceanbase/tpcd.sql

**Comment by hnwyllmm** [comment]
This is maybe the same issue with https://github.com/oceanbase/oceanbase/issues/2167.
If not, please feel free to comment below.

**Comment by hnwyllmm** [comment]
I'll close the issue.
Please feel free to reopen the issue if you have further information.
