### ISSUE TITLE
[Question]: 链接mysql.user超时，Statement is timeout应该怎么解决 || [Question]: The link mysql.user times out and Statement is timeout. How to solve it?

### ISSUE THREAD

**Issue by hank997997** [oceanbase/oceanbase#2201]
**链接mysql.user超时，Statement is timeout**

```
obclient [(none)]> use mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
obclient [mysql]> select * from mysql.user;
ERROR 4012 (HY000): Statement is timeout
```

操作步骤
  1. 正常安装oceanbase-ce，运行一切正常。
  2. 使用 `date -s`修改时间 到下个月，进行使用，就已经报错异常
  3. 再次把时间调整回来，还是登录失败。
请问，这个原因是什么，怎么解决？

---
**The link mysql.user timed out, Statement is timeout**

```
obclient [(none)]> use mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
obclient [mysql]> select * from mysql.user;
ERROR 4012 (HY000): Statement is timeout
```

Operation steps
  1. Install oceanbase-ce normally and everything runs normally.
  2. Use `date -s` to modify the time until next month, and an error will be reported if you use it.
  3. Adjust the time back again, but the login still fails.
Please tell me what is the reason and how to solve it?

**Comment by hank997997** [comment]
刚才又自测了一下，时间往后调没问题，如果往前调就会出现问题

```
obclient [(none)]> select * from mysql.user;
ERROR 4012 (HY000): Timeout, query has reached the maximum query timeout: 30000000(us), maybe you can adjust the session variable ob_query_timeout or query_timeout hint, and try again.
```

**Comment by wpleonardo** [comment]
Please wait for a while, we will investigate this issue promptly.

**Comment by wpleonardo** [comment]
Currently, modifying the time OB in this way will cause problems, which will be fixed in Version 425bp2.
Please pay attention to the OB new version release.
