### ISSUE TITLE
[Bug]: gitpod source  build failed 

### ISSUE THREAD

**Issue by watchpoints** [oceanbase/oceanbase#2212]
**Describe the bug**

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
uname -a
Linux watchpoints-oceanbase-5zrb0jeppx3 6.1.91-060191-generic #202407021948 SMP PREEMPT_DYNAMIC Tue Jul  2 20:28:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"

- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  

**Fast Reproduce Steps(Required)**

gipod:
https://oceanbase.github.io/oceanbase/toolchain/
git clone https://github.com/oceanbase/oceanbase.git

**Expected behavior**

build success
github is ok

**Actual Behavior**

~~~
build.sh debug --init --make -j8
[dep_create.sh] [NOTICE] 'Ubuntu 22.04.5 LTS (x86_64)' is compatible with CentOS 9, use el9 dependencies list
[dep_create.sh] oceanbase.el9.x86_64.deps has been not initialized, due to /workspace/oceanbase/deps/3rd/e9982c3dd04198e4728809c2bf18f7c5 not exists
[dep_create.sh] disable share dep cache due to env DEP_CACHE_DIR not set
[dep_create.sh] check dependencies profile for oceanbase.el9.x86_64.deps... FOUND
[dep_create.sh] check repository address in profile...
[dep_create.sh] target: default, repo: http://mirrors.aliyun.com/oceanbase/development-kit/el/8/x86_64/
[dep_create.sh] target: community, repo: http://mirrors.aliyun.com/oceanbase/community/stable/el/8/x86_64/
[dep_create.sh] target: el9, repo: http://mirrors.aliyun.com/oceanbase/development-kit/el/9/x86_64/
[dep_create.sh] start to download dependencies...
[dep_create.sh] downloading package <devdeps-gtest-1.8.0-132022101316.el8.x86_64.rpm>
[dep_create.sh] unpack package <devdeps-gtest-1.8.0-132022101316.el8.x86_64.rpm>... dep_create.sh: line 329: rpm2cpio: command not found
dep_create.sh: line 329: cpio: command not found
FAILED
~~~

**Additional context**

github is ok

![image](https://github.com/user-attachments/assets/36e0a5eb-4c9a-4e6c-82b4-965ee95ab9e4)

gitpod is failed
![image](https://github.com/user-attachments/assets/b25463d1-0ef0-44d8-b908-7ecf5ea48f27)

**Comment by watchpoints** [comment]
sudo apt-get update
sudo apt-get install rpm
sudo apt install cpio

**Comment by wpleonardo** [comment]
Thanks for choosing OceanBase. Feel free to ask any question.
