### ISSUE TITLE
ob_log_line_cache.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#229]
/code/oceanbase/src/clog/ob_log_line_cache.cpp
 conflct (suggestion: conflict)
 fortuned (suggestion: fortunes)
 uccessfully (suggestion: successfully)

**Comment by LINxiansheng** [comment]
Thanks for your contribution.
I think 'fortuned' is not wrong.

**Comment by LINxiansheng** [comment]
#250 Done
