### ISSUE TITLE
ob_file_id_cache.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#235]
/code/oceanbase/src/clog/ob_file_id_cache.cpp
 cachel (suggestion: rachel)
 rguard (suggestion: guard)
 partiiton (suggestion: parititon)
 inito (suggestion: finito)
 cahce (suggestion: cace)
 fliter (suggestion: filter)
 measn (suggestion: meas)
 retrym (suggestion: retrim)

**Comment by LINxiansheng** [comment]
#250  Done
