### ISSUE TITLE
ob_log_sliding_window.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#244]
/code/oceanbase/src/clog/ob_log_sliding_window.cpp
 submnit (suggestion: subunit)
 slided (suggestion: slides)
 stadnby (suggestion: standby)
 allcating (suggestion: allocating)
 folloer (suggestion: follower)
 cascad (suggestion: cascade)
 woring (suggestion: wooing)
 invalue (suggestion: intvalue)
 argumetns (suggestion: arguments)
 freee (suggestion: freex)
 leadre (suggestion: leader)

**Comment by LINxiansheng** [comment]
#250 Done
