### ISSUE TITLE
ob_log_state_mgr.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#245]
/code/oceanbase/src/clog/ob_log_state_mgr.cpp
 swtich (suggestion: switch)
 cascad (suggestion: cascade)
 chagne (suggestion: channe)
 priamry (suggestion: primary)
 replcia (suggestion: replica)
 clulster (suggestion: cluster)
 phsyical (suggestion: phsical)
 swith (suggestion: swish)
 whill (suggestion: whirl)

**Comment by LINxiansheng** [comment]
#250 Done
