### ISSUE TITLE
创建oracle类型的租户时，报错重复

### ISSUE THREAD

**Issue by iwen-nie** [oceanbase/oceanbase#249]
在创建oracle租户时，报错提示有重复

MySQL [oceanbase]> CREATE TENANT oracle_tenant
    -> RESOURCE_POOL_LIST = ('pool1'),
    -> primary_zone = 'RANDOM'
    -> set ob_tcp_invited_nodes = '%', ob_compatibility_mode = 'oracle';
ERROR 1235 (0A000): Not support oracle mode not supported

提示要么应该是Not support oracle mode
要么应该是Oracle mode not supported
不应该是Not support oracle mode not supported

**Comment by icefery** [comment]
请问怎么解决啊？

**Comment by akaError** [comment]
Already fixed, commit id:709ca16d814fdd5cbe7dccd62f5dc7c41715587d
