### ISSUE TITLE
No Docker version for OceanBase?

### ISSUE THREAD

**Issue by JasonkayZK** [oceanbase/oceanbase#25]
I’ve already read the deploy doc for OceanBase which is helpful.
Good for OceanBase! 👍🎉 

But i was wondering if there has a `Docker version` of OceanBase for a quick start?
Or if there has any projects for supporting OceanBase official mirror?

**Comment by yangzhifeng** [comment]
Yes, there was a docker image for OceanBase v2.2, See https://hub.docker.com/repository/docker/oceanbase/oceanbase-xe .

**Comment by JasonkayZK** [comment]
OK, i saw it. But the latest image is `Updated 10 months ago`.
Will official documents be added later? (Since i did not even know what environment params should i pass 😢)

Here is TiDB's document for `test-deployment-using-docker`:
- https://docs.pingcap.com/tidb/stable/test-deployment-using-docker

**Comment by longdafeng** [comment]
@LINxiansheng  please take a look at this issue, we can release one docker image for user and  writing one document to show how to use it.

**Comment by JasonkayZK** [comment]
thanks a lot!

**Comment by LINxiansheng** [comment]
Please refer it:
https://hub.docker.com/r/oceanbase/obce-mini
This is the OceanBase-ce offical docker image.

**Comment by JasonkayZK** [comment]
That's great! I've already tried this mirror during my noon break, and it worked just fine!

![image](https://user-images.githubusercontent.com/40811521/131294913-b53a7bee-5c1a-45fc-bbbf-bccdaafa055b.png)

I heard that OB already support OLAP, i gonna try it with cluster mode(maybe sometime? 😄)

BTW, thanks a lot! ❤️
