### ISSUE TITLE
套壳TiDB?

### ISSUE THREAD

**Issue by UnknowName** [oceanbase/oceanbase#26]
![image](https://user-images.githubusercontent.com/12406399/120274454-72d6a880-c2e2-11eb-9101-de1f1351f73c.png)

**Comment by pinylin** [comment]
不至于，TIDB社区模式很不错，应该是借鉴一下文档而已

**Comment by jzdayz** [comment]
有点吊。。

**Comment by hnwyllmm** [comment]
这就是一个CLA签名吧，就是开源社区提交代码的时候，必须签名CLA，才能提交。就相当于签署一个协议，防止提交了代码后面又反悔。与系统本身无关。

**Comment by MizuhaHimuraki** [comment]
感谢反馈，

此处仅为CLA示例，在做开源方面OceanBase还是个新手，还有很多需要和前辈们学习的，感谢TiDB的CLA样例。
