### ISSUE TITLE
疑问：clog的写入似乎没有调用fsync？

### ISSUE THREAD

**Issue by Yriuns** [oceanbase/oceanbase#275]
调用链大概是
```
ObLogFileStore::write(void* buf, int64_t count, int64_t offset)
  process_io_submit()
  process_io_getevents()
```
然后就认为写入成功了。
请问这里不需要调用`fsync`吗？还是我漏了什么地方？

**Comment by simonjoylet** [comment]
in a word, we open files with O_SYNC.
see:

ObLogFileStore::open
ObLogFileStore::inner_open
ObLogFileDescriptor::sync(const int64_t offset)
ObLogDiskManager::sync_system_fd
static const int OPEN_FLAG_WRITE = O_WRONLY | O_DIRECT | O_SYNC | O_CREAT;
