### ISSUE TITLE
select max,min primary key together hit a slow plan

### ISSUE THREAD

**Issue by boysxw8755773** [oceanbase/oceanbase#277]
**Describe the bug (__must be provided__)**
#column id is primary key ，but follow execute_plan always table scan
select max(id) max_id,min(id) min_id from test_table;

**Your Environments (__must be provided__)**

* OS: 3.10.0-957.21.2.el7.x86_64
* Compliler:g++ (GCC) 4.8.5 20150623 
* CPU: x86_64
* Commit id (fa0c4c8a389)

1.CREATE TABLE `test_table` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '空',
  `Name` varchar(100) DEFAULT '',
  PRIMARY KEY (`ID`)
) ;
2. insert demo data for 1 million 
insert into test_table(name) select now() from oceanbase.__all_ddl_operation a join oceanbase.__all_ddl_operation b on 1=1 limit 1000000;

3. mysql> select max(id) max_id,min(id) min_id from test_table;
+---------+--------+
| max_id  | min_id |
+---------+--------+
| 6048560 |   4001 |
+---------+--------+
1 row in set (3.44 sec)

> desc select max(id) max_id,min(id) min_id from test_table;
|ID|OPERATOR            |NAME      |EST. ROWS|COST   |
------------------------------------------------------
|0 |EXCHANGE IN REMOTE  |          |1        |2830864|
|1 | EXCHANGE OUT REMOTE|          |1        |2830864|
|2 |  SCALAR GROUP BY   |          |1        |2830864|
|3 |   TABLE SCAN       |test_table|1970153  |2350141|

Outputs & filters: 
-------------------------------------
  0 - output([T_FUN_MAX(test_table.ID)], [T_FUN_MIN(test_table.ID)]), filter(nil)
  1 - output([T_FUN_MAX(test_table.ID)], [T_FUN_MIN(test_table.ID)]), filter(nil)
  2 - output([T_FUN_MAX(test_table.ID)], [T_FUN_MIN(test_table.ID)]), filter(nil), 
      group(nil), agg_func([T_FUN_MAX(test_table.ID)], [T_FUN_MIN(test_table.ID)])
  3 - output([test_table.ID]), filter(nil), 
      access([test_table.ID]), partitions(p0)

**Expected behavior**

Mysql execute plan is more fast than ob, execute_plan may be something wrong

**Comment by longdafeng** [comment]
Table size of 1 million is small for OceanBase, 

Suggest you insert 100 million data into OceanBase, and query with parallel . https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/execution-of-parallel-query-2
