### ISSUE TITLE
社区版obproxy-3.1.0 帮助中--rs_list sql_prot 应该是sql_port

### ISSUE THREAD

**Issue by gaodg** [oceanbase/oceanbase#279]
猜测  root server list(format ip:sql_prot) 中ip:sql_prot 应该是 ip:sql_port

obproxy [OPTIONS]
  -h,--help                              print this help
  -p,--listen_port         LPORT         obproxy listen port
  -l,--promethues_listen_port  PLPORT    obproxy prometheus listen port
  -o,--optstr              OPTSTR        extra options string
  -n,--appname             APPNAME       application name
  -r,--rs_list             RS_LIST       root server list(format ip:sql_prot)

在打出的日志里面也是错的。

**Comment by gaodg** [comment]
企业版obproxy-3.1.0.1 也是一样的。

**Comment by longdafeng** [comment]
Could you please directly propose one pull request to fix it ?

If you doesn't know how to resolve it, we will handle it.

**Comment by gaodg** [comment]
谢谢您的回复。
我可能没有描述清楚我的意思。我的意思是obproxy 帮助里面 -r 参数 最后sql_prot 应该是写错了，应该是sql_port。

**Comment by hongrubb** [comment]
Hi, I'd like to help fix this issue. @longdafeng

**Comment by hongrubb** [comment]
After looking at the code in OBProxy. I found the [source code](https://github.com/oceanbase/obproxy/blob/master/src/obproxy/ob_proxy_main.cpp#L139) is correct. 
Maybe this issue could only be reproduced in the specific installation package.

**Comment by gaodg** [comment]
谢谢。
