### ISSUE TITLE
Segmentation fault during cpack rpm build stage

### ISSUE THREAD

**Issue by anysql** [oceanbase/oceanbase#28]
$cpack
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: OceanBase CE
CPack: - Install project: OceanBase CE
CPack: -   Install component: libs
CPack: -   Install component: server
CPack: -   Install component: sql-parser
CPack: Create package
CPackRPM: Will use GENERATED spec file: ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/SPECS/oceanbase-ce-libs.spec
CPackRPM: Will use GENERATED spec file: ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/SPECS/oceanbase-ce-sql-parser.spec
CPackRPM:Debug: You may consult rpmbuild logs in:
CPackRPM:Debug:    - ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/rpmbuildoceanbase-ce-sql-parser.err
CPackRPM:Debug: *** + umask 022
+ cd ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/BUILD
+ mv ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/tmpBBroot
+ exit 0
+ umask 022
+ cd ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/BUILD
+ '[' ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser '!=' / ']'
+ rm -rf ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser
++ dirname ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser
+ mkdir -p ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux
+ mkdir ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser
+ '[' -e ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser ']'
+ rm -rf ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser
+ mv ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/tmpBBroot ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/oceanbase-ce-3.1.0-Linux/sql-parser
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
/usr/lib/rpm/redhat/brp-strip-static-archive: line 11: 18174 Segmentation fault      $STRIP -g "$f"
error: Bad exit status from /var/tmp/rpm-tmp.IbNHwk (%install)
    Bad exit status from /var/tmp/rpm-tmp.IbNHwk (%install)
 ***
CPackRPM:Debug:    - ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/rpmbuildoceanbase-ce-sql-parser.out
CPackRPM:Debug: *** Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.4TKeaI
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.IbNHwk

RPM build errors:
 ***
CPackRPM: Will use GENERATED spec file: ./oceanbase/build_rpm/_CPack_Packages/Linux/RPM/SPECS/oceanbase-ce.spec
CPack: - package: ./oceanbase/build_rpm/oceanbase-ce-3.1.0-1.alios7.x86_64.rpm generated.
CPack: - package: ./oceanbase/build_rpm/oceanbase-ce-libs-3.1.0-1.alios7.x86_64.rpm generated.

**Comment by MizuhaHimuraki** [comment]
> * /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
>   /usr/lib/rpm/redhat/brp-strip-static-archive: line 11: 18174 Segmentation fault      $STRIP -g "$f"

Looks like bugs of Binutils. Can you show me the version of the binary 'strip'?
Btw, you can also try to update the binutils to workaround, since binutils-2.27-41.base.2.alios7.1.x86_64 works for me.

**Comment by anysql** [comment]
Why do we need to call strip?

**Comment by MizuhaHimuraki** [comment]
Just to control the size of the rpm package.

We recommend users to use ob-deploy for deployment (refer to this [QuickStart](https://open.oceanbase.com/quickStart).
The package is distributed based on network, and its size will affect the experience.
