### ISSUE TITLE
alter system archivelog--ERROR 4114 (08S01): In STOP state

### ISSUE THREAD

**Issue by landnow** [oceanbase/oceanbase#281]
Server version: 5.6.25 OceanBase 3.1.0。

execute “alter system archivelog;” ，show error:
MySQL [oceanbase]>  alter system archivelog;
ERROR 4114 (08S01): In STOP state

picture detail:
![image](https://user-images.githubusercontent.com/71339209/127798856-5c7fe6e0-699b-4905-b888-ffa0ee509c57.png)

**Comment by simonjoylet** [comment]
currently, the "backup and restore" feature of oceanbase community edition is not available. please wait the update at September.
