### ISSUE TITLE
Transaction is killed when creating tablegroup

### ISSUE THREAD

**Issue by Amber1990Zhang** [oceanbase/oceanbase#282]
![image](https://user-images.githubusercontent.com/42762957/127801760-9e8b8dc9-85d3-438e-9061-afffb759d556.png)

**Comment by longdafeng** [comment]
Please check whether the disk is full or not?

**Comment by Amber1990Zhang** [comment]
> Please check whether the disk is full or not?

![image](https://user-images.githubusercontent.com/42762957/127815386-00b7eebe-ee8c-44a4-877a-466a44de3c70.png)
I think the disk space is enough.

**Comment by simonjoylet** [comment]
exec `select last_trace_id();` and search the log for more details.
