### ISSUE TITLE
是不是拿tidb 改的？

### ISSUE THREAD

**Issue by alvin-su** [oceanbase/oceanbase#29]
如果是拿tidb改的，请告知广大开发者

**Comment by hnwyllmm** [comment]
要是拿TiDB的代码开源出来，pingcap老板早就拿刀砍过来了吧

**Comment by triump2020** [comment]
肯定不是啊 ，OB 2010 年就开源过 ，TIDB 2016 才起步.

**Comment by MizuhaHimuraki** [comment]
感谢提问，

OceanBase为自主研发的数据库系统，已有十年研发历史，但在做开源方面OceanBase还是个新手，还有很多需要和前辈们学习的地方。

**Comment by dragonly** [comment]
大家不要魔怔了。。
OB代码一看就跟TiDB八竿子打不着，大家不要见得风就是雨，看看代码再说啊。。
看不懂代码就别乱说。。

**Comment by mjhmllover** [comment]
看了几行代码啊  就说是用Tidb改的。。。毛爷爷告诉我们  有了调查才有发言权！！！

**Comment by triump2020** [comment]
更欣赏OB 的设计， 紧耦合 ，以后的性能上限会更高.   在很多核心功能实现上，都走了一条比较难的路，我想应该是追求极致。
     比如:  OB  基于paxos 实现 ， OB 的租户资源隔离， OB 的1PC 实现，OB 的 分布式sql 计算框架,  OB 的 HTAP 实现方式, OB 为了更好利用CPU,引入了协程框架 等，这些比目前所有开源NewSql 数据库 走的更远.  
   OB 的缺点是:  1. 紧耦合，实现复杂，不利于社区参与. 2. 有的模块抽象不精准，不优雅, 代码非常难懂, 因为逻辑复杂，模块之间边界不清晰.   代码风格 不优雅， 比如函数里面全是if....else...... ，变量的声明全部放在前面，像C 的风格， 看的头疼....
   
不过这些都可以忍, 谁叫你nb 呢

**Comment by alvin-su** [comment]
@mjhmllover  看不懂源码，看有人在讲，所以在这里求证下，用不是真的说是拿TIDB改的，难道不能问一下？？

**Comment by alvin-su** [comment]
@dragonly  正因为看不懂源码，所以才在这里求证，没看到我是打的问号吗？？？

**Comment by SevenBlue2018** [comment]
最近刚接触ob，ob是用c和c++写的啊，牛逼是牛逼，但是开源出来，能参与贡献的开发群体是不是相对少很多，对于其发展是不是会存在一定限制？
