### ISSUE TITLE
OMS添加mysql侧数据源时连接测试报错

### ISSUE THREAD

**Issue by wuyinzhou** [oceanbase/oceanbase#296]
mysql侧开启ssl参数时OMS添加mysql侧数据源连接测试报错：
mysql> show variables like '%ssl%';
+---------------+-----------------+
| Variable_name | Value           |
+---------------+-----------------+
| have_openssl  | YES             |
| have_ssl      | YES             |

报错提示不够明显，报错内容如下：
请求数据库 [jdbc:mysql://xxxip:xxxport?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false] 失败，错误消息：Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.。

**Comment by hitandrun-zz** [comment]
oms的版本是什么呢？我们在oms 3.1.0-bp2上修复了这个问题

**Comment by wuyinzhou** [comment]
> oms的版本是什么呢？我们在oms 3.1.0-bp2上修复了这个问题

oms.feature_3.1.0.202106232137.tar.gz，刚好差了一个版本？

**Comment by hitandrun-zz** [comment]
是专有云用户么？我们有群支持的

**Comment by hitandrun-zz** [comment]
先升级到oms 3.1.0-bp2
