### ISSUE TITLE
社区版跨库查询视图，会报错

### ISSUE THREAD

**Issue by yzsntdkj** [oceanbase/oceanbase#298]
社区版跨库查询视图，会报以下错误，但企业版不会。
--社区版
mysql> SELECT database();
+------------+
| database() |
+------------+
| NULL       |
+------------+
1 row in set (0.00 sec)

mysql> select * from oceanbase.CDB_OB_BACKUP_SET_EXPIRED;
ERROR 1046 (3D000): No database selected
mysql> use sys;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from oceanbase.CDB_OB_BACKUP_SET_EXPIRED;
ERROR 1356 (42S22): View 'oceanbase.CDB_OB_BACKUP_SET_EXPIRED' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
mysql> use oceanbase;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from oceanbase.CDB_OB_BACKUP_SET_EXPIRED;
Empty set (0.00 sec)

--企业版
mysql> SELECT database();
+------------+
| database() |
+------------+
| NULL       |
+------------+
1 row in set (0.00 sec)

mysql> select * from oceanbase.CDB_OB_BACKUP_SET_EXPIRED;
Empty set (0.01 sec)

mysql> use sys;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from oceanbase.CDB_OB_BACKUP_SET_EXPIRED;
Empty set (0.01 sec)

**Comment by shendachuan** [comment]
Thanks for your feedback. We will patch this bugfix to community edition soon.

**Comment by xuhuleon** [comment]
Backup is not ready in community version yet. we will release backup later.
