### ISSUE TITLE
Clarify prerequisite to README

### ISSUE THREAD

**Issue by blindpirate** [oceanbase/oceanbase#3]
On Ubuntu 20.04, `build.sh` complains:

```
➜  oceanbase git:(master) bash build.sh debug --init --make
grep: /etc/redhat-release: No such file or directory
```

Is it required to use RedHat or CentOS? If so, can it be clarified in README prerequisite?

**Comment by oceanbase-admin** [comment]
Thanks for your feedback. 

Right now, we just support centos 7.x, doesn't support centos 8.x,  please refer to 

https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/resource-preparation

**Comment by MizuhaHimuraki** [comment]
Thanks for your feedback.

You can use docker to build OceanBase with "centos:7" image. If you can read Chinese, you can refer to this [documentation](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code). We will provide it in English later.

**Comment by MizuhaHimuraki** [comment]
duplicate of #56
