### ISSUE TITLE
是否可以支持Mac系统编译

### ISSUE THREAD

**Issue by YangHao666666** [oceanbase/oceanbase#30]

**Comment by MizuhaHimuraki** [comment]
如您是X86_64架构的macbook pro是可以使用4c8g以上的"centos:7" docker镜像进行体验的，可以参考以下文档 [编译](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code) 或 [部署](https://open.oceanbase.com/quickStart)

但是受限于设备自身的算力与内存瓶颈，很难获得最佳体验。

**Comment by YangHao666666** [comment]
> 如您是X86_64架构的macbook pro是可以使用4c8g以上的"centos:7" docker镜像进行体验的，可以参考以下文档 [编译](https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code) 或 [部署](https://open.oceanbase.com/quickStart)
> 
> 但是受限于设备自身的算力与内存瓶颈，很难获得最佳体验。

docker用起来不是特别方便，所以想问下是否后续会支持Mac系统

**Comment by xiaozhongwang** [comment]
自己支持提交
