### ISSUE TITLE
无法取消进行中的migrate

### ISSUE THREAD

**Issue by vzong** [oceanbase/oceanbase#303]
ObUnitManager::cancel_migrate_unit
cancel migrate unit永远返回失败，server migrate in denied。OB_SERVER_MIGRATE_IN_DENIED = -4551;

如果是migrate状态中，!is_migrate_in_blocked()返回false，can_migrate_in返回false。
https://github.com/oceanbase/oceanbase/blob/master/src/share/ob_server_status.h
  bool can_migrate_in() const
  {
    return is_active() && in_service() && !is_migrate_in_blocked();
  }

can_migrate_in返回false，!status.can_migrate_in()返回true。导致报-4551，永远无法取消migrate unit。
https://github.com/oceanbase/oceanbase/blob/master/src/rootserver/ob_unit_manager.cpp
else if (!status.can_migrate_in() && !is_gts_unit) {
    ret = OB_SERVER_MIGRATE_IN_DENIED;
    LOG_WARN("server can not migrate in", "server", unit.migrate_from_server_, K(status), K(ret));
  }

**Comment by jw-guo** [comment]
Thanks for your suggestion. In current version, we can set the parameter resource_soft_limit to 100 to disable the unit balance. 
Please refer to: https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/resource_soft_limit
