### ISSUE TITLE
Any plan support  PostgreSQL protocol and syntax

### ISSUE THREAD

**Issue by jiamo** [oceanbase/oceanbase#31]

**Comment by yangzhifeng** [comment]
No, we don't have the plan.

**Comment by raywill** [comment]
No plan to do this

**Comment by longdafeng** [comment]
Support PostgresSQL is a pretty huge project for us, it will involve a lot of things, such as who is our target . 

So it is a complicated issue for us, right now we have no plan to do this. 

if you really need it, you can touch our commerical team.  www.oceanbase.com
