### ISSUE TITLE
能否提供CDC的能力让数据流入下游数据产品，例如kafka、es、cassandra等

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [oceanbase/oceanbase#311]
能否提供CDC的能力让数据流入下游数据产品，例如kafka、es、cassandra等

**Comment by whhe** [comment]
We are working on this and will provide a solution based on [canal](https://github.com/alibaba/canal) in this month.

**Comment by whhe** [comment]
You can use our branch of canal for CDC now, see https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/qlz77w
