### ISSUE TITLE
duplicate define of macro ATOMIC_FAA

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#325]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**
 in file `deps/oblib/src/lib/atomic/ob_atomic.h`
macro `ATOMIC_FAA` double defined

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by watchpoints** [comment]
only once。#define ATOMIC_FAA(val, addv) ATOMIC_FAAx(val, addv, LA_ATOMIC_ID)
