### ISSUE TITLE
租户维护系统表缺陷

### ISSUE THREAD

**Issue by vzong** [oceanbase/oceanbase#329]
table_id=1103909674287330在gv$partition有数据，但是在gv$table里面没有数据。
后面定位到table_id=1103909674287330是系统表__all_weak_read_service。
gv$table只有sys租户的__all_weak_read_service，没有普通租户的__all_weak_read_service。
普通租户维护系统表有缺陷。

mysql> select * from gv$table where table_id=1103909674287330;
Empty set (0.04 sec)

mysql> select * from gv$partition where table_id=1103909674287330;
+-----------+------------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
| tenant_id | table_id         | tablegroup_id | partition_id | svr_ip      | svr_port | sql_port | unit_id | partition_cnt | zone | role | member_list                                                                                           | row_count | data_size | data_version | partition_checksum | data_checksum | row_checksum | column_checksum | rebuild | replica_type | required_size | status                | is_restore | quorum |
+-----------+------------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
|      1004 | 1103909674287330 |          NULL |            0 | 10.5.68.130 |     5022 |    55776 |    1002 |             0 | nt2  |    2 | 10.5.68.130:5022:1628838766847724,10.5.68.132:5022:1628838766847724,10.5.68.134:5022:1628838766847724 |         1 |       625 |           15 |                  0 |    3310686714 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
|      1004 | 1103909674287330 |          NULL |            0 | 10.5.68.132 |     5022 |    55776 |    1001 |             0 | nt1  |    1 | 10.5.68.130:5022:1628838766847724,10.5.68.132:5022:1628838766847724,10.5.68.134:5022:1628838766847724 |         1 |       625 |           15 |                  0 |    3310686714 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
|      1004 | 1103909674287330 |          NULL |            0 | 10.5.68.134 |     5022 |    55776 |    1003 |             0 | nt3  |    2 | 10.5.68.130:5022:1628838766847724,10.5.68.132:5022:1628838766847724,10.5.68.134:5022:1628838766847724 |         1 |       625 |           15 |                  0 |    3310686714 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
+-----------+------------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
3 rows in set (0.20 sec)

mysql> select * from __tenant_virtual_show_create_table where table_id=1099511628002\G
*************************** 1. row ***************************
            table_id: 1099511628002
          table_name: __all_weak_read_service
        create_table: CREATE TABLE `__all_weak_read_service` (
  `gmt_create` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `gmt_modified` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `level_id` bigint(20) NOT NULL,
  `level_value` varchar(128) NOT NULL,
  `level_name` varchar(128) NOT NULL,
  `min_version` bigint(20) DEFAULT NULL,
  `max_version` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`level_id`, `level_value`)
) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = COMPACT COMPRESSION = 'none' REPLICA_NUM = 3 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 10 TABLEGROUP = 'oceanbase'
character_set_client: utf8mb4
collation_connection: utf8mb4_general_ci
1 row in set (0.01 sec)

mysql> select * from gv$table where table_name='__all_weak_read_service';
+-----------+-------------+---------------+-------------------------+---------------+---------------+---------------+-----------------+------------+-------------+--------------+----------------+---------------------------------------+----------------+-----------+---------+--------------+------------+------------+----------------+----------------+----------+--------------------+--------------------+--------------+-----+-----------+----------------+
| tenant_id | tenant_name | table_id      | table_name              | database_id   | database_name | tablegroup_id | tablegroup_name | table_type | zone_list   | primary_zone | collation_type | locality                              | schema_version | read_only | comment | index_status | index_type | part_level | part_func_type | part_func_expr | part_num | sub_part_func_type | sub_part_func_expr | sub_part_num | dop | auto_part | auto_part_size |
+-----------+-------------+---------------+-------------------------+---------------+---------------+---------------+-----------------+------------+-------------+--------------+----------------+---------------------------------------+----------------+-----------+---------+--------------+------------+------------+----------------+----------------+----------+--------------------+--------------------+--------------+-----+-----------+----------------+
|         1 | sys         | 1099511628002 | __all_weak_read_service | 1099511627777 | oceanbase     | 1099511627777 | oceanbase       |          0 | nt1;nt2;nt3 | nt1;nt2,nt3  |             45 | FULL{1}@nt1, FULL{1}@nt2, FULL{1}@nt3 |            944 |         0 |         |            1 |          0 |          0 |              0 |                |        1 |                  0 |                    |            1 |   1 |         0 |             -1 |
+-----------+-------------+---------------+-------------------------+---------------+---------------+---------------+-----------------+------------+-------------+--------------+----------------+---------------------------------------+----------------+-----------+---------+--------------+------------+------------+----------------+----------------+----------+--------------------+--------------------+--------------+-----+-----------+----------------+
1 row in set (0.04 sec)

mysql> select * from gv$partition where table_id=1099511628002;
+-----------+---------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
| tenant_id | table_id      | tablegroup_id | partition_id | svr_ip      | svr_port | sql_port | unit_id | partition_cnt | zone | role | member_list                                                                                           | row_count | data_size | data_version | partition_checksum | data_checksum | row_checksum | column_checksum | rebuild | replica_type | required_size | status                | is_restore | quorum |
+-----------+---------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
|         1 | 1099511628002 | 1099511627777 |            0 | 10.5.68.130 |     5022 |    55776 |       2 |             0 | nt2  |    2 | 10.5.68.130:5022:1628755996875010,10.5.68.132:5022:1628755996875010,10.5.68.134:5022:1628755996875010 |         1 |       625 |           15 |                  0 |    1271347674 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
|         1 | 1099511628002 | 1099511627777 |            0 | 10.5.68.132 |     5022 |    55776 |       1 |             0 | nt1  |    1 | 10.5.68.130:5022:1628755996875010,10.5.68.132:5022:1628755996875010,10.5.68.134:5022:1628755996875010 |         1 |       625 |           15 |                  0 |    1271347674 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
|         1 | 1099511628002 | 1099511627777 |            0 | 10.5.68.134 |     5022 |    55776 |       3 |             0 | nt3  |    2 | 10.5.68.130:5022:1628755996875010,10.5.68.132:5022:1628755996875010,10.5.68.134:5022:1628755996875010 |         1 |       625 |           15 |                  0 |    1271347674 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
+-----------+---------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
3 rows in set (0.20 sec)

mysql> select * from gv$partition where table_id=1103909674287330;
+-----------+------------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
| tenant_id | table_id         | tablegroup_id | partition_id | svr_ip      | svr_port | sql_port | unit_id | partition_cnt | zone | role | member_list                                                                                           | row_count | data_size | data_version | partition_checksum | data_checksum | row_checksum | column_checksum | rebuild | replica_type | required_size | status                | is_restore | quorum |
+-----------+------------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
|      1004 | 1103909674287330 |          NULL |            0 | 10.5.68.130 |     5022 |    55776 |    1002 |             0 | nt2  |    2 | 10.5.68.130:5022:1628838766847724,10.5.68.132:5022:1628838766847724,10.5.68.134:5022:1628838766847724 |         1 |       625 |           15 |                  0 |    3310686714 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
|      1004 | 1103909674287330 |          NULL |            0 | 10.5.68.132 |     5022 |    55776 |    1001 |             0 | nt1  |    1 | 10.5.68.130:5022:1628838766847724,10.5.68.132:5022:1628838766847724,10.5.68.134:5022:1628838766847724 |         1 |       625 |           15 |                  0 |    3310686714 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
|      1004 | 1103909674287330 |          NULL |            0 | 10.5.68.134 |     5022 |    55776 |    1003 |             0 | nt3  |    2 | 10.5.68.130:5022:1628838766847724,10.5.68.132:5022:1628838766847724,10.5.68.134:5022:1628838766847724 |         1 |       625 |           15 |                  0 |    3310686714 |            0 |                 |       0 |            0 |       4194304 | REPLICA_STATUS_NORMAL |          0 |      3 |
+-----------+------------------+---------------+--------------+-------------+----------+----------+---------+---------------+------+------+-------------------------------------------------------------------------------------------------------+-----------+-----------+--------------+--------------------+---------------+--------------+-----------------+---------+--------------+---------------+-----------------------+------------+--------+
3 rows in set (0.18 sec)

mysql> select * from __all_weak_read_service;
+----------------------------+----------------------------+----------+-------------+------------+------------------+------------------+
| gmt_create                 | gmt_modified               | level_id | level_value | level_name | min_version      | max_version      |
+----------------------------+----------------------------+----------+-------------+------------+------------------+------------------+
| 2021-08-12 16:13:20.155047 | 2021-08-26 15:47:32.062358 |        0 |             | CLUSTER    | 1629964051887828 | 1629964051887828 |
+----------------------------+----------------------------+----------+-------------+------------+------------------+------------------+
1 row in set (0.00 sec)

**Comment by cyujing** [comment]
system table in Normal tenant  don't have schema，so can not find in  gv$table，This is meet design expectations，but will cause confusion，we can fix it as a bug；

**Comment by vzong** [comment]
> system table in Normal tenant don't have schema，so can not find in gv$table，This is meet design expectations；

why gv$partition can find system table schema. it's very confusing. 
a better degign would be for gv$partition and gv$table with same rules.

**Comment by cyujing** [comment]
Now，In sys tenant，normal table schema is in __all_table,sys table schema is in all_core_table；gv$patition can find system table and user table； In Normal tenant gv$table is inherit __all_table;

You give us a good suggestion; We consider optimize it later；
