### ISSUE TITLE
Golang Prepared Statements 报错 Error 1235: Not supported feature or function

### ISSUE THREAD

**Issue by Listson** [oceanbase/oceanbase#331]
**Describe the bug (__must be provided__)**
使用Golang SQL Prepared Statements连接ob执行报错：Error 1235: Not supported feature or function，同样的代码在mysql 5.7中执行正常，请问是ob不支持这个特性？

复现方式如下：
创建一张测试表结构
```
create table test(id int)
```
golang测试代码
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	//dns := fmt.Sprintf(`root:xxxxx@tcp(127.0.0.1:3306)/testdb?multiStatements=true`) // mysql连接
	dns := fmt.Sprintf(`root@xxxx:xxxx@tcp(127.0.0.1:2881)/testdb?multiStatements=true`) // ob连接
	DB, _ := sql.Open("mysql", dns)
	//设置数据库最大连接数
	DB.SetConnMaxLifetime(100)
	//设置上数据库最大闲置连接数
	DB.SetMaxIdleConns(10)
	stmt, err := DB.Prepare("INSERT INTO test(id) VALUES (?)")
	if err != nil {
		panic(err)
	}
	res, err := stmt.Exec(1)
	if err != nil {
		panic(err)
	}

	fmt.Println(res.RowsAffected())
}

```

**Comment by longdafeng** [comment]
默认是关掉的, 你用系统租户打开, 再试一下
alert system set _ob_enable_prepared_statement = true;

**Comment by Listson** [comment]
> 默认是关掉的, 你用系统租户打开, 再试一下
> alert system set _ob_enable_prepared_statement = true;

感谢回复，想请教一下是出于什么原因默认关闭这个特性？我理解这是一个很常用的功能，很多orm框架会用到这个特性，例如golang gorm框架

**Comment by Listson** [comment]
> 默认是关掉的, 你用系统租户打开, 再试一下
> alert system set _ob_enable_prepared_statement = true;

@longdafeng  感谢回复，想请教一下是出于什么原因默认关闭这个特性？我理解这是一个很常用的功能，很多orm框架会用到这个特性，例如golang gorm框架

**Comment by rongfengliang** [comment]
> 默认是关掉的, 你用系统租户打开, 再试一下 alert system set _ob_enable_prepared_statement = true;


alert 拼写错了，应该是 ALTER
```code
ALTER system set _ob_enable_prepared_statement =true;
````
