### ISSUE TITLE
ObAggregateProcessor::collect_aggr_result CRASH

### ISSUE THREAD

**Issue by vzong** [oceanbase/oceanbase#345]
src/sql/engine/aggregate/ob_aggregate_processor.cpp
int ObAggregateProcessor::collect_aggr_result(AggrCell& aggr_cell, const ObExpr* diff_expr, const ObAggrInfo& aggr_info)

observer (OceanBase 3.1.2)
REVISION: 20210618150922-a5962b40a38d98117ec9ed1a08554fa0c4c8a389
BUILD_BRANCH: 3_1_x_release
BUILD_TIME: Jun 18 2021 15:39:59
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 
Copyright (c) 2011-2020 Alipay Inc.

[2021-09-08 14:06:25.184078] USER_ERR extend_concat_str_buf (ob_aggregate_processor.cpp:1614) [18516][1304][YB420A3C3736-0005C9CCDE993076] [lt=7] [dc=0] Row 2 was cut by GROUP_CONCAT()
[2021-9-8 14:6:25.184184] INFO [run1@ob_signal_worker.cpp:195] [19183][Y7369676E616C-1] receive request, req=1, accumulated=1
CRASH ERROR!!! sig=11, sig_code=128, sig_addr=0, timestamp=1631081185474594, tid=18516, tname=TNT_L0_1, trace_id=12378267465526-1629256628646006, extra_info=((null)), lbt=0x99aeea9 0x99b0486 0x7fbcd4f6c5cf 0x7fbcd4864cf5 0x2ae52b3 0x2ae1350 0x7470a1b 0x7471d9a 0x28103ee 0x84ca17b 0x2bcfeb0 0x84d37d6 0x84d4b37 0x27e4ab6 0x27e2682 0x27dd694 0x6e1850a 0x3105e4f 0x97d5756 0x97d2bcf 0x97ce09e

0x99aeea9 _ZN9oceanbase6common14safe_backtraceEPclRl + 41
0x99b0486 _ZN9oceanbase6common11coredump_cbEiP9siginfo_t + 230
0x7fbcd4f6c5cf _end + -1580899865
0x7fbcd4864cf5 _end + -1588270835
0x2ae52b3 _ZN9oceanbase3sql20ObAggregateProcessor19collect_aggr_resultERNS1_8AggrCellEPKNS0_6ObExprERKNS0_10ObAggrInfoE + 15027
0x2ae1350 _ZN9oceanbase3sql20ObAggregateProcessor7collectElPKNS0_6ObExprE + 400
0x7470a1b _ZN9oceanbase3sql16ObMergeGroupByOp23rollup_and_calc_resultsElPKNS0_6ObExprE + 187
0x7471d9a _ZN9oceanbase3sql16ObMergeGroupByOp18inner_get_next_rowEv + 554
0x28103ee _ZN9oceanbase3sql10ObOperator12get_next_rowEv + 46
0x84ca17b _ZN9oceanbase3sql20ObRemoteBaseExecutePINS_5obrpc18ObExecutorRpcProxy5ObRpcILNS2_15ObRpcPacketCodeE1308EvEEE16sync_send_resultERNS0_13ObExecContextERKNS0_14ObPhysicalPlanERNS_6common9ObScannerE + 2251
0x2bcfeb0 _ZN9oceanbase3sql20ObRemoteBaseExecutePINS_5obrpc18ObExecutorRpcProxy5ObRpcILNS2_15ObRpcPacketCodeE1308EvEEE19execute_remote_planERNS0_13ObExecContextERKNS0_14ObPhysicalPlanE + 720
0x84d37d6 _ZN9oceanbase3sql20ObRemoteBaseExecutePINS_5obrpc18ObExecutorRpcProxy5ObRpcILNS2_15ObRpcPacketCodeE1308EvEEE16execute_with_sqlERNS0_12ObRemoteTaskE + 1062
0x84d4b37 _ZN9oceanbase3sql23ObRpcRemoteSyncExecuteP7processEv + 23
0x27e4ab6 _ZN9oceanbase3rpc5frame14ObReqProcessor3runEv + 198
0x27e2682 _ZN9oceanbase3omt17ObWorkerProcessor7processERNS_3rpc9ObRequestE + 786
0x27dd694 _ZN9oceanbase3omt10ObThWorker6workerERlS2_Ri + 6724
0x6e1850a _ZN9oceanbase3omt10ObThWorker3runEl + 42
0x3105e4f _ZNSt17_Function_handlerIFvvEZN9oceanbase3lib13CoKThreadTempINS2_16CoUserThreadTempINS2_10CoSetSchedEEEE5startEvEUlvE_E9_M_invokeERKSt9_Any_data + 79
0x97d5756 _ZN9oceanbase3lib10CoSetSched6Worker3runEv + 38
0x97d2bcf _ZN9oceanbase3lib9CoRoutine7__startEN5boost7context6detail10transfer_tE + 335
0x97ce09e trampoline + 2

**Comment by shendachuan** [comment]
Thanks for your feedback. We have fixed this problem in later version.
