### ISSUE TITLE
启动集群报错

### ISSUE THREAD

**Issue by Macintosh-c** [oceanbase/oceanbase#347]
Get local repositories and plugins ok
Open ssh connection ok
Cluster param config check ok
Check before start observer ok
[WARN] (127.0.0.1) The recommended value of fs.aio-max-nr is 1048576 (Current value: 65536)
[WARN] (127.0.0.1) The recommended number of open files is 655350 (Current value: 65536)
[WARN] (127.0.0.1) clog and data use the same disk (/)

Start observer x
[ERROR] failed to start 127.0.0.1 observer: /root/observer/bin/observer -r 127.0.0.1:2882:2881 -o __min_full_resource_pool_memory=268435456,memory_limit=8G,system_memory=4G,stack_size=512K,cpu_count=4,cache_wash_threshold=1G,workers_per_cpu_quota=10,schema_history_expire_time=1d,net_thread_count=4,sys_bkgd_migration_retry_num=3,minor_freeze_times=10,enable_separate_sys_clog=0,enable_merge_by_turn=False,datafile_disk_percentage=20,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4 -z zone1 -p 2881 -P 2882 -c 1 -d /root/observer/store -i lo -l DEBUG
rs list: 127.0.0.1:2882:2881
optstr: __min_full_resource_pool_memory=268435456,memory_limit=8G,system_memory=4G,stack_size=512K,cpu_count=4,cache_wash_threshold=1G,workers_per_cpu_quota=10,schema_history_expire_time=1d,net_thread_count=4,sys_bkgd_migration_retry_num=3,minor_freeze_times=10,enable_separate_sys_clog=0,enable_merge_by_turn=False,datafile_disk_percentage=20,enable_syslog_wf=False,enable_syslog_recycle=True,max_syslog_file_count=4
zone: zone1
mysql port: 2881
rpc port: 2882
cluster id: 1
data_dir: /root/observer/store
devname: lo
log level: DEBUG
[2021-09-08 17:43:57.772696] ERROR [LIB] use_daemon (utility.cpp:1197) [24746][0][Y0-0000000000000000] [lt=0] create daemon process fail(errno=12) BACKTRACE:0x91613ee 0x91270c7 0x211abbd 0x2119ba8 0x91b857b 0x21177a8 0x7f78a5dd3505 0x2116ae9
[2021-09-08 17:43:57.773861] ERROR [LIB] start_daemon (utility.cpp:1219) [24746][0][Y0-0000000000000000] [lt=1161] create daemon process fail(ret=-4015) BACKTRACE:0x91613ee 0x91270c7 0x211abbd 0x2119ba8 0x91b8606 0x21177a8 0x7f78a5dd3505 0x2116ae9

[ERROR] oceanbase-ce start failed

执行obd cluster start demo 报上述错误

**Comment by akaError** [comment]
from your warnings, refers to:
https://open.oceanbase.com/docs/observer-cn/V3.1.2/10000000000014805
https://open.oceanbase.com/docs/observer-cn/V3.1.2/10000000000014806

but the best config to boost observer should be get from obd deploy, refers to:
https://github.com/oceanbase/oceanbase/wiki/how_to_debug
