### ISSUE TITLE
How to run unit test?

### ISSUE THREAD

**Issue by happyhust** [oceanbase/oceanbase#351]
If I submit one pull request, how to verify my patch works fine. 
Please tell us how to do unit test. 

I want to do unit test before submit my pull request

**Comment by LINxiansheng** [comment]
## Firstly build the release version. 
`bash build.sh release --init --make`
## Secondly build the unittest.
- `cd build_release`
- Add your function to the corresponding module's makefile.
- make the unittest `make`
## Run the unittest
`sh run_tests.sh`

**Comment by watchpoints** [comment]
this is all test,not one fucntions

**Comment by akaError** [comment]
> this is all test,not one fucntions
`vim run_tests.sh`

内容很简单如下

![image](https://user-images.githubusercontent.com/97499944/158325503-7d716af0-dd02-4ca4-a5d3-d3851df5d74c.png)
一看我也觉得没有可以参数指定了，但我也好想测单个，虽然没看出来啥，但可以得出用的是ctest, 搜一下可以知道是cmake的测试框架，那就从cmake入手
又看到这个

![image](https://user-images.githubusercontent.com/97499944/158325731-b142df58-37f2-4ad9-9381-bddde8706acd.png)

盲猜有关系，vim起来
![image](https://user-images.githubusercontent.com/97499944/158325785-1c49ac10-96ab-464b-ac5c-298a21990190.png)
里面有好多目录，注释一下，成了

![image](https://user-images.githubusercontent.com/97499944/158325338-c470070d-bceb-45a3-a436-cdbb499a2136.png)


所以如果你想只测单个文件，将文件夹下只放一个就好了，当然，这种只是取巧，还是得回头去改原CMakeLists.txt
