### ISSUE TITLE
ob作为源端，实时同步怎么实现

### ISSUE THREAD

**Issue by zhbdesign** [oceanbase/oceanbase#354]
ob作为源端，实时同步怎么实现

**Comment by whhe** [comment]
目前商业版有OMS可以实现 https://www.oceanbase.com/product/oms

针对社区版OceanBase，我们正在向[canal](https://github.com/alibaba/canal)中加入OceanBase的数据源支持，目前已经在测试阶段，很快就会发布。
另外，社区版的OMS也在开发当中，敬请期待。

**Comment by xyl93** [comment]
> 目前商业版有OMS可以实现 https://www.oceanbase.com/product/oms
> 
> 针对社区版OceanBase，我们正在向[canal](https://github.com/alibaba/canal)中加入OceanBase的数据源支持，目前已经在测试阶段，很快就会发布。
> 另外，社区版的OMS也在开发当中，敬请期待。

请问下社区版oms大概计划是啥时会推出？

**Comment by whhe** [comment]
> > 目前商业版有OMS可以实现 https://www.oceanbase.com/product/oms
> > 针对社区版OceanBase，我们正在向[canal](https://github.com/alibaba/canal)中加入OceanBase的数据源支持，目前已经在测试阶段，很快就会发布。
> > 另外，社区版的OMS也在开发当中，敬请期待。
> 
> 请问下社区版oms大概计划是啥时会推出？

最早10月就会发出来

**Comment by whhe** [comment]
OMS for OceanBase CE is released now, see https://open.oceanbase.com/softwareCenter/community.
