### ISSUE TITLE
How to use Agentserver to quickly take over logical incremental backup tasks?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#362]

**Comment by xuhuleon** [comment]
3.x not support agentserver any more

**Comment by longdafeng** [comment]
please refer to https://www.oceanbase.com/docs/knowledgeBase/how-to-use-agentserver-to-quickly-take-over-the-task

But 3.x doenst' support angentserver any more. 

OceanBase 数据库大多数情况下会以同城三机房架构进行部署，因此备份恢复服务器也应该进行多机房部署，以防止主或备机房网络脑裂或其他网络故障情况下，备份任务会受到影响。本文主要介绍主机房不可用情况下，如何做到任务接管。
