### ISSUE TITLE
Which level of database management does the data file of OB database correspond to?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#365]

**Comment by longdafeng** [comment]
OceanBase 数据库目前具有两类数据文件，这两类数据文件都是集群级的。

OceanBase 数据库的两类数据文件为：

Clog 相关：包含 Clog（也称为 Redo Log 或 WAL 日志） 和它的索引文件。

data 文件：保存各个分区的数据，包括各个分区的 Checkpoint 点。
