### ISSUE TITLE
Disk fault detection principle of OceanBase database V2.X

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#367]

**Comment by simonjoylet** [comment]
for OceanBase V2.x, please refer to https://www.oceanbase.com/docs/knowledgeBase/disk-failure-detection-for-apsaradb-for-oceanbase-v2-x

for OceanBase V3.1.x or later, we use the parameter `data_storage_warning_tolerance_time` and `data_storage_error_tolerance_time` for better detection
