### ISSUE TITLE
What are suspended and long transactions？How to check?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#369]

**Comment by CynthiaLee97** [comment]
When a transaction is opened for more than 600s and has not been committed, we call it a long transaction.And the transaction does not end for more than 600s after the user initiates a commit, which is called a suspended transaction.
You can use the following statement to query.
long transaction:
       SELECT count(1)
       FROM __all_virtual_trans_stat
       WHERE part_trans_action<=2
               AND ctx_create_time < date_sub(now(), INTERVAL 600 SECOND)
               AND is_exiting != 1;
suspended transaction:
      SELECT count(1) FROM __all_virtual_trans_stat
      WHERE part_trans_action > 2
	  AND ctx_create_time < date_sub(now(), INTERVAL 600 SECOND)
	  AND is_exiting != 1;

**Comment by simonjoylet** [comment]
please refer to https://www.oceanbase.com/docs/knowledgeBase/suspended-and-long-transactions
