### ISSUE TITLE
oceanbase/deps/logmessage  is empty，but cmakelists.txt need it

### ISSUE THREAD

**Issue by xyl93** [oceanbase/oceanbase#384]
oceanbase/deps/logmessage  is empty，but cmakelists.txt need it

cmakelists.txt. 36. 
add_subdirectory(deps/logmessage)

then i remove this line
cmake can continue ,but return error, show fatal error: 'LogRecord.h' file not found

**Comment by LINxiansheng** [comment]
Thanks for your question.
This is a mistake by me, please pull the code again and rebuild the oceanbase.

**Comment by LINxiansheng** [comment]
Thanks for your question.
This is a mistake by me, please pull the code again and rebuild the oceanbase.

**Comment by xyl93** [comment]
> Thanks for your question. This is a mistake by me, please pull the code again and rebuild the oceanbase.

hi,
I pull the lasted code and build the oceanbase with OB_BUILD_LIBOBLOG ON
but i have another question when clone git@github.com:oceanbase/oblogmsg.git .

- Submodule 'logmessage' (git@github.com:oceanbase/oblogmsg.git) registered for path 'deps/logmessage'
Cloning into 'deps/logmessage'...
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:oceanbase/oblogmsg.git' into submodule path 'deps/logmessage' failed
CMake Error at src/liboblog/CMakeLists.txt:9 (message):
  git submodule update --init failed with 1, please checkout submodules



then i use the command to clone it ,also failed.  
Is that repository existed ?
