### ISSUE TITLE
OceanBase是否支持集群间同步数据？oblogproxy和oblogClient是否有更详细说明？

### ISSUE THREAD

**Issue by zhangjig** [oceanbase/oceanbase#396]
想要基于开源版本OceanBase做两个OB集群复制功能，最新版本开源了oblogproxy和oblogClient，但是没有看到如何与OB做整个，如何与消息队列集成的相关文档？

是需要使用oblogClient完全重新实现吐出到消息队列？

**Comment by SanmuWangZJU** [comment]
见https://open.oceanbase.com/answer/detail?id=13700038
