### ISSUE TITLE
Compile error on centos 7

### ISSUE THREAD

**Issue by zetatez** [oceanbase/oceanbase#407]
uname -a
    Linux MiWiFi-R4CM-srv 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lscpu
    Architecture:          x86_64
    CPU op-mode(s):        32-bit, 64-bit
    Byte Order:            Little Endian
    CPU(s):                4
    On-line CPU(s) list:   0-3
    Thread(s) per core:    1
    Core(s) per socket:    4
    Socket(s):             1
    NUMA node(s):          1
    Vendor ID:             GenuineIntel
    CPU family:            6
    Model:                 165
    Model name:            Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Stepping:              5
    CPU MHz:               2904.004
    BogoMIPS:              5808.00
    Hypervisor vendor:     KVM
    Virtualization type:   full
    L1d cache:             32K
    L1i cache:             32K
    L2 cache:              256K
    L3 cache:              16384K
    NUMA node0 CPU(s):     0-3
    Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase avx2 invpcid rdseed clflushopt flush_l1d arch_capabilities

bash build.sh release --init --make
    [ 65%] Building CXX object src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_cache/0_cxx.cxx.o
    [ 65%] Building CXX object src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_stat/0_cxx.cxx.o
    [ 65%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/2_cxx.cxx.o
    [ 65%] Built target ob_clog
    Consolidate compiler generated dependencies of target ob_archive
    [ 65%] Building CXX object src/archive/CMakeFiles/ob_archive.dir/Unity/unity_ob_archive_common/0_cxx.cxx.o
    [ 65%] Building CXX object src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_common/0_cxx.cxx.o
    /bin/sh: line 1: 16465 Killed                  /root/oceanbase/deps/3rd/usr/local/oceanbase/devtools/bin/clang++ -DPACKAGE_NAME="\"OceanBase CE\"" -DPACKAGE_STRING="\"OceanBase CE 3.1.1\"" -DPACKAGE_VERSION=\"3.1.1\" -DRELEASEID=\"1\" -I/root/oceanbase/src -I/root/oceanbase/deps/oblib/src -I/root/oceanbase/deps/easy/src/include -I/root/oceanbase/deps/easy/src -I/root/oceanbase/deps/3rd/usr/local/oceanbase/deps/devel/include -fdebug-prefix-map=/root/oceanbase=. --gcc-toolchain=/root/oceanbase/deps/3rd/usr/local/oceanbase/devtools -fcolor-diagnostics -I/root/oceanbase/deps/3rd/usr/local/oceanbase/devtools/lib/clang/11.0.1/include -O2 -g -DNDEBUG -fPIC -Wno-invalid-offsetof -D_GLIBCXX_USE_CXX11_ABI=0 -fmax-type-align=8 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D_NO_EXCEPTION -Wall -Wextra -Wformat -Wno-deprecated -fno-omit-frame-pointer -mtune=core2 -Wno-address-of-packed-member -Wno-sign-compare -Werror -Wno-inconsistent-missing-override -fno-delete-null-pointer-checks -Wno-delete-non-virtual-dtor -Wno-dynamic-class-memaccess -Wno-format-security -Wno-reserved-user-defined-literal -Wno-sometimes-uninitialized -Wno-unused-value -Wno-self-assign -Wno-overloaded-virtual -Wno-unused-private-field -Wno-mismatched-tags -Wno-unused-variable -Wno-tautological-compare -Wno-psabi -Wno-c99-designator -D_GNU_SOURCE -Winvalid-pch -Xclang -include-pch -Xclang /root/oceanbase/build_release/src/CMakeFiles/server_pch.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /root/oceanbase/build_release/src/CMakeFiles/server_pch.dir/cmake_pch.hxx -MD -MT src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_common/0_cxx.cxx.o -MF CMakeFiles/ob_share.dir/Unity/unity_ob_share_common/0_cxx.cxx.o.d -o CMakeFiles/ob_share.dir/Unity/unity_ob_share_common/0_cxx.cxx.o -c /root/oceanbase/build_release/src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_common/0_cxx.cxx
    make[2]: *** [src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_common/0_cxx.cxx.o] Error 137
    make[1]: *** [src/share/CMakeFiles/ob_share.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 65%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_privilege_check/0_cxx.cxx.o
    [ 65%] Built target ob_archive
    [ 65%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/15_cxx.cxx.o
    [ 65%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/12_cxx.cxx.o
    [ 69%] Building CXX object src/rootserver/CMakeFiles/ob_rootserver.dir/Unity/unity_ob_rootserver_backup/0_cxx.cxx.o
    ...
    ...
    [ 82%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_session/0_cxx.cxx.o
    [ 82%] Built target ob_sql
    make: *** [all] Error 2

**Comment by longdafeng** [comment]
it's weird, Centos 7.x is the recommended os. 

what's your gcc/g++/cmake version?

**Comment by zetatez** [comment]
According to the building process, the build.sh script will automatically download cmake, gcc/g++ and llvm, so it should be independent of the operating system's own gcc version. Is that correct?

**Comment by zetatez** [comment]
Thank you very much! My problem solved.  Patch #8a64f46 works for me. I will follow your advice and try several other ways later. Thanks again！
