### ISSUE TITLE
How to merge pull requests (The current way is to create a merge commit)?

### ISSUE THREAD

**Issue by YangHao666666** [oceanbase/oceanbase#41]
1.   Merge PR的时候可以只有正常的那个commit msg记录，不要出现merge branch/merge pr这种commit吗？这样不利于查看提交记录
2.  commit msg里面最好统一一下格式，最好可以带上issue号，这样后续再看这个提交的时候可以很清楚的知道这个提交的由来

**Comment by JingsongLi** [comment]
+1 to use:
- squash and merge
or
- rebase and merge

No use of merge commit

**Comment by yangbodong22011** [comment]
Refer : https://github.com/redis/redis/commits/unstable
