### ISSUE TITLE
希望ob后续可以考虑支持类似mysql的date_format和datetime_format变量

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#426]
在mysql里上支持以下变量修改时间和日期的格式
mysql> show variables where variable_name in ('date_format','datetime_format','time_format');
+-----------------+-------------------+
| Variable_name   | Value             |
+-----------------+-------------------+
| date_format     | %Y-%m-%d          |
| datetime_format | %Y-%m-%d %H:%i:%s |
| time_format     | %H:%i:%s          |
+-----------------+-------------------+
3 rows in set (0.00 sec)

在ob里目前仅支持time_format的变量：
oceanbase> show variables like '%format%';
+--------------------------+----------+
| Variable_name            | Value    |
+--------------------------+----------+
| ob_enable_transformation | ON       |
| time_format              | %H:%i:%s |
+--------------------------+----------+
2 rows in set (0.01 sec)

希望ob后续可以考虑支持类似mysql的date_format和datetime_format变量。

**Comment by liboyang0730** [comment]
> 在mysql里上支持以下变量修改时间和日期的格式 mysql> show variables where variable_name in ('date_format','datetime_format','time_format'); +-----------------+-------------------+ | Variable_name | Value | +-----------------+-------------------+ | date_format | %Y-%m-%d | | datetime_format | %Y-%m-%d %H:%i:%s | | time_format | %H:%i:%s | +-----------------+-------------------+ 3 rows in set (0.00 sec)
> 
> 在ob里目前仅支持time_format的变量： oceanbase> show variables like '%format%'; +--------------------------+----------+ | Variable_name | Value | +--------------------------+----------+ | ob_enable_transformation | ON | | time_format | %H:%i:%s | +--------------------------+----------+ 2 rows in set (0.01 sec)
> 
> 希望ob后续可以考虑支持类似mysql的date_format和datetime_format变量。

这两个系统变量在 MySQL 5.7 并没有被使用，是废弃的系统变量，而且已经在 MySQL 8.0 被删除了。详见：https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html。
