### ISSUE TITLE
【兼容性】执行同一段语句，mysql中可以执行，ob报错

### ISSUE THREAD

**Issue by countdownlatch** [oceanbase/oceanbase#435]
执行语句：SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
mysql结果执行成功，如下图
<img width="845" alt="1635325258(1)" src="https://user-images.githubusercontent.com/11144949/139034445-3479563b-8e6b-4548-b1ac-926df4ee7cda.png"> 
oceanbase报错，如下图
<img width="978" alt="1635325318(1)" src="https://user-images.githubusercontent.com/11144949/139034621-488aa96d-7357-498a-8554-8357638db049.png">

mysql版本为：5.7.35-0ubuntu0.18.04.1
oceanbase版本为：企业版3.1.2

执行show charset，结果如下
oceanbase：
<img width="618" alt="1635325523(1)" src="https://user-images.githubusercontent.com/11144949/139035194-8f58fcee-8ca5-4eed-8a79-75770c2eafa9.png">
mysql：
<img width="694" alt="1635325575(1)" src="https://user-images.githubusercontent.com/11144949/139035334-85599fd5-3418-4b9b-b5dd-c04fb8de2d30.png">

影响：使用python的sqlalchemy包操作oceanbase时，会出现WARN，不影响使用，如下：
<img width="1797" alt="1635325638(1)" src="https://user-images.githubusercontent.com/11144949/139035528-fb1fa255-d219-40de-b284-1474a67e3339.png">

**Comment by hnwyllmm** [comment]
close as fixed
