### ISSUE TITLE
Failed to build oceanbase in Deepin 20.2.4

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#436]
```
./build.sh --init debug
[ERROR] 'Deepin 20.2.4 (unknown)' is not supported yet.

```
查看了配置， 应该是缺少这些rpm
```

```
repo=http://mirrors.aliyun.com/oceanbase/development-kit/el/7/x86_64/

[deps]
devdeps-gtest-1.8.0-3.el7.aarch64.rpm
devdeps-isa-l-static-2.22.0-3.el7.aarch64.rpm
devdeps-libcurl-static-7.29.0-3.el7.aarch64.rpm
devdeps-libunwind-static-1.5.0-3.el7.aarch64.rpm
devdeps-mariadb-connector-c-3.1.12-3.el7.aarch64.rpm
devdeps-openssl-static-1.0.1e-3.el7.aarch64.rpm
devdeps-libaio-0.3.112-3.el7.aarch64.rpm

[tools]
obdevtools-bintuils-2.30-3.el7.aarch64.rpm
obdevtools-bison-2.4.1-3.el7.aarch64.rpm
obdevtools-ccache-3.7.12-3.el7.aarch64.rpm
obdevtools-cmake-3.20.2-3.el7.aarch64.rpm
obdevtools-flex-2.5.35-3.el7.aarch64.rpm
obdevtools-gcc-5.2.0-3.el7.aarch64.rpm
obdevtools-llvm-11.0.1-3.el7.aarch64.rpm

```

**Comment by longdafeng** [comment]
@LINxiansheng , Thanks for your help. 
I can fix this issue by myself. 

But right now, Deepin OS can't support "uname -p", I will push them fix this issue firstly.

**Comment by hnwyllmm** [comment]
不在计划中
