### ISSUE TITLE
DataX同步数据到OB过程中observer crash

### ISSUE THREAD

**Issue by justdba** [oceanbase/oceanbase#439]
**Describe the bug (__must be provided__)**
datax query from mysql insert into oceanbase， 20w+/s， runing about 10minute，observer crash one by one！

gdb /home/op1/oceanbase/bin/observer core.64724

(gdb) where
#0  0x00007fe9f701e49b in raise () from /lib64/libpthread.so.0
#1  0x0000000009795135 in oceanbase::common::coredump_cb(int, siginfo_t*) ()
#2  <signal handler called>
#3  0x00007fe9f686c207 in raise () from /lib64/libc.so.6
#4  0x00007fe9f686d8f8 in abort () from /lib64/libc.so.6
#5  0x000000000966c069 in ob_abort() ()
#6  0x000000000847564b in oceanbase::memtable::ObMemtableCtx::trans_replay_end(bool, long, unsigned long) ()
#7  0x0000000008b59110 in oceanbase::transaction::ObPartTransCtx::trans_replay_commit_(long, long) ()
#8  0x0000000008b5ecf6 in oceanbase::transaction::ObPartTransCtx::replay_commit_log(oceanbase::transaction::ObTransCommitLog const&, long, unsigned long) ()
#9  0x0000000008bf5997 in oceanbase::transaction::ObTransService::replay(oceanbase::common::ObPartitionKey const&, char const*, long, long, unsigned long, long, bool, long, long&) ()
#10 0x00000000088d5a9d in oceanbase::replayengine::ObLogReplayEngine::do_replay_task(oceanbase::storage::ObIPartitionGroup*, oceanbase::storage::ObReplayLogTask*, long, long&) ()
#11 0x00000000088d244c in oceanbase::replayengine::ObLogReplayEngine::handle_replay_log_task_(oceanbase::common::ObPartitionKey const&, oceanbase::storage::ObIPartitionGroup*, oceanbase::storage::ObReplayLogTaskQueue*, bool&) ()
#12 0x00000000088d0305 in oceanbase::replayengine::ObLogReplayEngine::handle(void*) ()
#13 0x0000000009715fd9 in oceanbase::common::ObSimpleThreadPool::run1() ()
#14 0x00000000032f01cf in oceanbase::lib::ThreadPool::run0() ()
#15 0x0000000002bf4284 in std::_Function_handler<void (), oceanbase::lib::CoKThreadTemp<oceanbase::lib::CoUserThreadTemp<oceanbase::lib::CoSetSched> >::start()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#16 0x00000000095718e5 in oceanbase::lib::CoSetSched::Worker::run() ()
#17 0x0000000009570572 in oceanbase::lib::CoRoutine::__start(boost::context::detail::transfer_t) ()
#18 0x000000000956d09f in make_fcontext ()
#19 0x0000000000000000 in ?? ()

**Your Environments (__must be provided__)**

* OS: `Linux 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Compliler: `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)`
* CPU: `lscpu`
* Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
Stepping:              4
CPU MHz:               2499.841
CPU max MHz:           3000.0000
CPU min MHz:           800.0000
BogoMIPS:              4400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              14080K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke spec_ctrl intel_stibp flush_l1d
* Commit id (e.g. `a3ffc7d8`)

[op1@XXXX bin]$ ./observer  -V
./observer -V
observer (OceanBase CE 3.1.1)

**Comment by longdafeng** [comment]
There is no more details, it is hard to reproduce this issue, close this issue right now,
