### ISSUE TITLE
Size overflow for execute long sql

### ISSUE THREAD

**Issue by lilt108** [oceanbase/oceanbase#440]
**Bug info**

I have a long sql like `select a, b, c from tbl_name where id in (1w+ id)`, and the sql file is 144k . when I execute this sql, OceanBase return the msg: ERROR 4019 (HY000): Size overflow.

**Environments**

* OS: `Linux A03-R05 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
* Compliler: `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)`
* CPU: `Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`

**How To Reproduce**

1. write a long sql like `select a, b, c from tbl_name where id in (1w+ id)`
2. sava above sql into a file, the filename is long-sql.sql
2. connect to Oceanbase
3. source /path/long-sql.sql

**Expected behavior**

ERROR 4019 (HY000): Size overflow

**Additional context**

observer version: `oceanbase-ce-3.1.1-1.el7.x86_64.rpm`
obproxy version：`obproxy-3.1.0-1.el7.x86_64.rpm`

**Comment by shendachuan** [comment]
Thanks for your feedback. We have fixed this bug in latest version.
