### ISSUE TITLE
GCC compiling fails

### ISSUE THREAD

**Issue by cyberspicecai** [oceanbase/oceanbase#442]
**Please check the FAQ documentation before raising an issue**
      checked，no related.
Please check the old issues before raising an issue in case someone has asked the same question that you are asking.
     Searched, no releated.
**Describe the bug (__must be provided__)**
      Modified the cmake/Env.cmake: ob_define(OB_USE_CLANG OFF)
                                                          ob_define(OB_USE_LLVM_LIBTOOLS OFF)
      After the above modification,  the compiling can reach linking stage:
[100%] Built target ob_storage
[100%] Built target ob_rootserver
[100%] Linking CXX static library liboceanbase_static.a
[100%] Built target oceanbase_static
[100%] Linking CXX executable observer
 but there are many "undefined reference" errors.
../../deps/oblib/src/liboblib.a(1_cxx.cxx.o): In function `oceanbase::common::ob_io_cancel(io_context*, iocb*, io_event*)':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/io/ob_io_common.cpp:87: undefined reference to `io_cancel'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::close()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:151: undefined reference to `mysql_close'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLResultImpl::close()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:112: undefined reference to `mysql_free_result'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::ping()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:237: undefined reference to `mysql_ping'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedParam::init()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_param.cpp:37: undefined reference to `mysql_stmt_param_count'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedParam::bind_param()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_param.cpp:59: undefined reference to `mysql_stmt_bind_param'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedResult::init()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_result.cpp:37: undefined reference to `mysql_stmt_field_count'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedResult::bind_result_param()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_result.cpp:60: undefined reference to `mysql_stmt_bind_result'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLResultImpl::next()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:128: undefined reference to `mysql_fetch_row'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:130: undefined reference to `mysql_fetch_lengths'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedStatement::execute_query()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:123: undefined reference to `mysql_stmt_execute'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:126: undefined reference to `mysql_stmt_store_result'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:124: undefined reference to `mysql_stmt_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:125: undefined reference to `mysql_stmt_error'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:127: undefined reference to `mysql_stmt_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:128: undefined reference to `mysql_stmt_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedStatement::execute_update()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:105: undefined reference to `mysql_stmt_execute'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:106: undefined reference to `mysql_stmt_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:107: undefined reference to `mysql_stmt_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedStatement::close()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:89: undefined reference to `mysql_stmt_close'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:90: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:91: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::commit()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:199: undefined reference to `mysql_commit'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:200: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:201: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::rollback()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:184: undefined reference to `mysql_rollback'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:185: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:186: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::start_transaction(bool)':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:169: undefined reference to `mysql_real_query'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:164: undefined reference to `mysql_real_query'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:165: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:166: undefined reference to `mysql_error'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:170: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:171: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedStatement::init(oceanbase::common::sqlclient::ObMySQLConnection&, char const*)':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:66: undefined reference to `mysql_stmt_init'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:69: undefined reference to `mysql_stmt_prepare'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:70: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_statement.cpp:71: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLPreparedResult::next()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_prepared_result.cpp:84: undefined reference to `mysql_stmt_fetch'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::escape(char const*, long, char*, long, long&)':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:221: undefined reference to `mysql_real_escape_string'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLStatement::execute_update(long&)':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:86: undefined reference to `mysql_real_query'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:102: undefined reference to `mysql_affected_rows'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:87: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:88: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnectionPool::ObMySQLConnectionPool()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection_pool.cpp:44: undefined reference to `mysql_server_init'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLConnection::connect(char const*, char const*, char const*)':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:120: undefined reference to `mysql_init'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:121: undefined reference to `mysql_options'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:122: undefined reference to `mysql_options'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:123: undefined reference to `mysql_options'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:125: undefined reference to `mysql_real_connect'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:138: undefined reference to `mysql_options'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:127: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_connection.cpp:128: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLResultImpl::init()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:48: undefined reference to `mysql_store_result'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:60: undefined reference to `mysql_num_fields'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:68: undefined reference to `mysql_num_fields'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:69: undefined reference to `mysql_fetch_fields'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:49: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:50: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLStatement::execute_query()':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:119: undefined reference to `mysql_real_query'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:120: undefined reference to `mysql_errno'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:126: undefined reference to `mysql_error'
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_statement.cpp:123: undefined reference to `mysql_error'
../../deps/oblib/src/liboblib.a(2_cxx.cxx.o): In function `oceanbase::common::sqlclient::ObMySQLResultImpl::get_row_count() const':
./build_release/deps/oblib/src/lib/./deps/oblib/src/lib/mysqlclient/ob_mysql_result_impl.cpp:99: undefined reference to `mysql_num_rows'
collect2: error: ld returned 1 exit status
make[2]: *** [src/observer/observer] Error 1
make[1]: *** [src/observer/CMakeFiles/observer.dir/all] Error 2
make: *** [all] Error 2

**Your Environments (__must be provided__)**

* OS: `uname -a`: Linux bogon 4.19.91-009.alpha.ali4000.alios7.x86_64 #1 SMP Wed Dec 30 11:56:30 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: `g++ --version` or `clang++ --version`:
*gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.5.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://aone.alibaba-inc.com/project/767688/issue/ --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --without-isl --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.5.1 20190307 (Alibaba 6.5.1-1 2.17) (GCC)
 clang++ --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
* CPU: `lscpu`: lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           1
Model name:                      AMD EPYC 7451 24-Core Processor
Stepping:                        2

* Commit id (e.g. `a3ffc7d8`)
 git rev-parse HEAD  ea1c67200f7e616e112249fdf17925e78c0700f2
**How To Reproduce(__must be provided__)**
   

1. Step 1
    modify the cmake/Env.cmake:
   ob_define(OB_USE_CLANG OFF)
   ob_define(OB_USE_LLVM_LIBTOOLS OFF)
    and compile.
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.
   pls ref to the above

**Comment by longdafeng** [comment]
@MizuhaHimuraki  could you please take a look at this issue?

**Comment by longdafeng** [comment]
@cyberspicecai  we are not going to support gcc 6.5.1

We are going to switch CLang/LLVM,  due to LLVM provide a lot of performance tunning method especially on SIMD part. 
but in order to keep comatible to gcc, we just support gcc 5.2.0.
