### ISSUE TITLE
A multistatement query issued by a ruby application fails to run on oceanbase mysql tenant.

### ISSUE THREAD

**Issue by obpilot** [oceanbase/oceanbase#443]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

A multistatement query issued by a ruby application fails to run on oceanbase mysql tenant.

**Your Environments (__must be provided__)**

* OS: `uname -a`
* Compliler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1. Step 1
prepare an oceanbase mysql tenant .
2. Step 2
log in the mysql tenant and run query : SET NAMES utf8, @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483, @@SESSION.sql_mode = 'STRICT_ALL_TABLES
3. Step 3

**Expected behavior**

**Additional context**

Provide logs and configs, or any other context to trace the problem.

observer.log: 

[2021-11-03 08:56:48.332686] WARN [SERVER] process (obmp_query.cpp:290) [314][448][YB427F000001-0005CFCB8F98ED70] [lt=6] [dc=0] fail execute sql(sql_id="", sql=SET NAMES utf8, @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483, @@SESSION.sql_mode = 'STRICT_ALL_TABLES', sessid=3221505018, ret=-5001, ret="OB_ERR_PARSE_SQL", need_disconnect=false)

**Comment by longdafeng** [comment]
@shendachuan  please take a look at this issue.

**Comment by longdafeng** [comment]
This bug has been fixed in this Tuesday
