### ISSUE TITLE
ob_log_archive_and_restore_driver.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#445]
/code/oceanbase/src/clog/ob_log_archive_and_restore_driver.cpp
 archvie (suggestion: archie)

**Comment by DayChan** [comment]
zhengbumingbai认领

**Comment by DayChan** [comment]
zhengbumingbai 认领

**Comment by DayChan** [comment]
solved in #587

**Comment by DayChan** [comment]
close this issue pls
