### ISSUE TITLE
ob_log_cascading_mgr.cpp with misspelled word

### ISSUE THREAD

**Issue by lindemin** [oceanbase/oceanbase#451]
/code/oceanbase/src/clog/ob_log_cascading_mgr.cpp
 becaming (suggestion: becoming)
 assgin (suggestion: assign)
 replcace (suggestion: replace)
 stadnby (suggestion: standby)
 cascad (suggestion: cascade)
 regitster (suggestion: register)
 aysnc (suggestion: async)
 rpelica (suggestion: replica)
 succeussfully (suggestion: successfully)
 colocates (suggestion: colocated)
 cadidate (suggestion: candidate)
 talbe (suggestion: tale)
 follwer (suggestion: follower)
 lcoation (suggestion: location)

**Comment by fkuner** [comment]
认领
