### ISSUE TITLE
ob mysql 模式下DATETRUNC函数，报sql语法错误

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#469]
```sql
create table t(a datetime);
insert into t values('2019-11-10 12:11:12'),('2020-01-11 13:12:11'),('2018-08-10 13:11:11');



SELECT ADDDATE( CONCAT( DATE_FORMAT( `t`.`a`, '%Y-' ), (3*(QUARTER(`t`.`a`)-1)+1), '-01 00:00:00' ), INTERVAL 0 SECOND ) AS `calc`
FROM `t`
GROUP BY 1   
```

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near '(`t`.`a`)-1)+1), '-01 00:00:00' ), INTERVAL 0 SECOND ) AS `calc' at line 1

**Comment by shendachuan** [comment]
It seems that there is no DATETRUNC in this query. Besides, DATETRUNC is not supported in MySQL.
