### ISSUE TITLE
The CLA website is too slow for chinese users. Should we run a new server for CLA?

### ISSUE THREAD

**Issue by seeflood** [oceanbase/oceanbase#47]
**Is your feature request related to a problem? Please describe.**
The CLA website is too slow for chinese users to open .
I can't sign it without VPN

**Describe the solution you'd like**
run a new server for CLA

**Describe alternatives you've considered**

**Additional context**

**Comment by MizuhaHimuraki** [comment]
Thanks for your feedback.

We will resolve this problem later.

**Comment by longdafeng** [comment]
Setup one CLA server  is pretty complicated, we must pass a lot of security check by our companies, it is too hard for us. 
We have no plan to so this, here is what I can answer to you. 

Thanks again.
