### ISSUE TITLE
How to optimize the rate of supplemental replicas and replica relocation?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#471]

**Comment by liboyang0730** [comment]
在 OceanBase 数据库中可以通过设置一些配置项来优化增补副本、副本搬迁速率。此回答适用于以下场景的增补副本、副本搬迁速率优化：
- 节点替换（故障替换）
- 节点下线后重新上线（停机维护）
- 节点上 Unit 分布不符合预期，手工迁移租户 Unit

可以通过设置一些配置项来优化增补副本、副本搬迁速率。
### 配置方法


- 设置数据拷贝并发数为 100。
``data_copy_concurrency`` 用于设置系统中并发执行的数据迁移复制任务的最大并发数，默认为 20，取值范围为 [1,+∞)。
```
ALTER SYSTEM SET data_copy_concurrency = 100;
```

- 设置服务器上数据传出并发数为 10。
``server_data_copy_out_concurrency`` 用于设置单个节点迁出数据的最大并发数，默认为 2，取值范围为 1 ~ 1000。
```
ALTER SYSTEM SET server_data_copy_out_concurrency = 10;
```

- 设置服务器上数据传入并发数为 10。
``server_data_copy_in_concurrency`` 用于设置单个节点迁入数据的最大并发数，默认为 2，取值范围为 1 ~ 1000。
```
ALTER SYSTEM SET server_data_copy_in_concurrency = 10;
```

- 设置系统后端网络带宽占用调整为 90。
``sys_bkgd_net_percentage`` 用于设置后台系统任务可占用网络带宽百分比，默认为 60，取值范围为 0 ~ 100。
```
ALTER SYSTEM SET sys_bkgd_net_percentage = 90
```
注意只有在当前集群负载低于 50% 时才可以调整 ``sys_bkgd_net_percentag``，否则请保持该参数默认值 60。
