### ISSUE TITLE
better human-readable output format of explain

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#476]
ob的explain展示执行计划的时候，仅依靠 缩进 来展示层次关系。对于一个复杂的plan，采用深度优先打印plan以后，往往一个join的两个子树相差很远，看起来非常费劲。建议引入如下的树状连接线来展示，非常易读。
![image](https://user-images.githubusercontent.com/5187215/140475409-0d0a4a50-a1ce-4cbd-b9dc-3ab19167f73c.png)

**Comment by fkuner** [comment]
fkuner认领

**Comment by JayL-zxl** [comment]
> fkuner认领

上面已经领完了啊。。。

**Comment by hnwyllmm** [comment]
long time no response
