### ISSUE TITLE
What is the protocol type, released version and the Mac OS compatibility

### ISSUE THREAD

**Issue by cai-peng** [oceanbase/oceanbase#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
The codebase is 3.1.

**Comment by longdafeng** [comment]
It can't run in mac directly, but you can run it in docker of Mac. The minimal requirement is 2core8Gmemory.

**Comment by titati** [comment]
does it support both Oracle mode and mysql mode?

**Comment by Chuanhui** [comment]
It supports mysql mode only by now.
