### ISSUE TITLE
[MySQL] BIN_TO_UUID(), UUID_TO_BIN() function

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#480]
Mysql 8.0函数

[BIN_TO_UUID](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_bin-to-uuid)
[UUID_TO_BIN](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid-to-bin)
[IS_UUID](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_is-uuid)

**Comment by shendachuan** [comment]
Thanks for your feedback. OceanBase is compatible with MySQL 5.6 now, and we are trying to support MySQL 5.7 features.
