### ISSUE TITLE
OceanBase game issue list

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#488]
- https://github.com/oceanbase/oceanbase/issues/486
- https://github.com/oceanbase/oceanbase/issues/483
- https://github.com/oceanbase/oceanbase/issues/482
- https://github.com/oceanbase/oceanbase/issues/481
- https://github.com/oceanbase/oceanbase/issues/480
- https://github.com/oceanbase/oceanbase/issues/477
- https://github.com/oceanbase/oceanbase/issues/476
- https://github.com/oceanbase/oceanbase/issues/474
- https://github.com/oceanbase/oceanbase/issues/470
- https://github.com/oceanbase/oceanbase/issues/469
- https://github.com/oceanbase/oceanbase/issues/462

**Comment by Leozki** [comment]
认领#476

**Comment by b41sh** [comment]
认领 #480

**Comment by keuin** [comment]
认领#481

**Comment by nautaa** [comment]
认领 #483

**Comment by yangzecai** [comment]
认领 #477

**Comment by MiaoMiaoGarden** [comment]
认领#470

**Comment by jaingmengmeng** [comment]
认领462

**Comment by Moonm3n** [comment]
认领 #469

**Comment by Zhuchengyu04** [comment]
认领#486

**Comment by superhail** [comment]
认领 #474

**Comment by fkuner** [comment]
认领 #474

**Comment by LJYer** [comment]
认领 #482

**Comment by LLLSH9** [comment]
认领#462

**Comment by rainays** [comment]
认领#476

**Comment by SpadeSe** [comment]
认领#480

**Comment by Dousir9** [comment]
认领#476

**Comment by dongzeyu** [comment]
认领474

**Comment by dongzeyu** [comment]
认领#474

**Comment by lhcmaple** [comment]
认领 #523
外面的issue

**Comment by JiangNanMax** [comment]
认领[#501 ](url)

**Comment by Whorra** [comment]
认领 #517

**Comment by lyxiong0** [comment]
认领#505

**Comment by jacklightChen** [comment]
认领 #525 
Solved in #559

**Comment by fkuner** [comment]
认领#514

**Comment by yan-tingyun** [comment]
认领#516

**Comment by Whorra** [comment]
认领 #502

**Comment by rainays** [comment]
认领 #448

**Comment by yan-tingyun** [comment]
认领#511

**Comment by rainays** [comment]
认领#460

**Comment by hey-kong** [comment]
认领#522

**Comment by a920264845** [comment]
认领

**Comment by LLThomas** [comment]
认领#456

**Comment by ingdex** [comment]
认领#517

**Comment by zaiwind** [comment]
认领[#444](https://github.com/oceanbase/oceanbase/issues/444)

**Comment by DayChan** [comment]
认领#509

**Comment by wshonline** [comment]
认领#504

**Comment by DayChan** [comment]
认领#445

**Comment by wshonline** [comment]
push_d_
认领#457

**Comment by ligen131** [comment]
ligen131
认领 #273 
solved in #589

**Comment by JameyWoo** [comment]
JameyWoo
认领 #449

**Comment by wangqiim** [comment]
wangqiim
认领 #603

**Comment by Dousir9** [comment]
HoniiTro19
认领 #602

**Comment by JameyWoo** [comment]
JameyWoo
认领 #449

**Comment by zjx1230** [comment]
zjx1230
认领 #600

**Comment by tata24** [comment]
haohaoTaTa
认领 #596

**Comment by JameyWoo** [comment]
JameyWoo
认领 #604

**Comment by smithYangda** [comment]
CardinalGuo
认领 #602

**Comment by tata24** [comment]
HaoHaoTaTa
认领 #606

**Comment by WangAShao** [comment]
WangAShao
认领 #596

**Comment by WangYuanZhen123123** [comment]
lmjhh
认领#604

**Comment by zhouhuahui** [comment]
My-OB-contest
认领 #618

**Comment by Issac-Newton** [comment]
TenThousand 
认领 #449

**Comment by cnissnzg** [comment]
cnissnzg
认领 #504
