### ISSUE TITLE
Can `oceanbase` be deployed in k8s environment?

### ISSUE THREAD

**Issue by iosmanthus** [oceanbase/oceanbase#49]
For most the popular distributed database, they could be deployed in k8s environment by various operators like [cockroach-operator](https://github.com/cockroachdb/cockroach-operator), [cass-operator](https://github.com/k8ssandra/cass-operator), [tidb-operator](https://github.com/pingcap/tidb-operator). I am curious if `oceanbase` has tools like these to deploy itself in k8s env? If it does, any documentation am I missing?

**Comment by longdafeng** [comment]
We are plan to do, but the priority is pretty slow,

**Comment by longdafeng** [comment]
we are looking forward your contribution for this part, if you can.

**Comment by iosmanthus** [comment]
> we are looking forward your contribution for this part, if you can.

Obviously, I can't 😕. There is no documentation to explain what replication protocol and schema change approach oceanbase is using. Waiting for more infomation for contributors! I look forward to it! However, are you providing cloud service for [oceanbase](https://www.oceanbase.com/product/cloud)?

**Comment by saltonz** [comment]
You might want to check about this [ApsaraDB for OceanBase](https://www.alibabacloud.com/product/oceanbase)

**Comment by iosmanthus** [comment]
OT: ApsaraDB is a branding or a unified storage engine? @saltonz

**Comment by yangzhifeng** [comment]
> OT: ApsaraDB is a branding or a unified storage engine? @saltonz

I think ApsaraDB is a brand for Aliyun Cloud DBaaS, like ApsaraDB for MongoDB.

**Comment by yangzhifeng** [comment]
> > we are looking forward your contribution for this part, if you can.
> 
> Obviously, I can't 😕. There is no documentation to explain what replication protocol and schema change approach oceanbase is using. Waiting for more infomation for contributors! I look forward to it! However, are you providing cloud service for [oceanbase](https://www.oceanbase.com/product/cloud)?

OceanBase use a different approach from some other systems: the cluster management and auto fail-over etc. is self-contained feature controlled by the RootService. See `src/rootserver'.

**Comment by LINxiansheng** [comment]
Now the new product ob-operator can do this job.
https://github.com/oceanbase/ob-operator
