### ISSUE TITLE
update cpu_count does not work on an active server

### ISSUE THREAD

**Issue by wuyinzhou** [oceanbase/oceanbase#491]
version:ce ob
step1:
    start server with:
    /home/op1/oceanbase/bin/observer -r 10.61.128.150:5022:2881;10.58.118.249:5022:2881;10.61.128.151:5022:2881;10.110.95.73:5022:2881;10.110.61.122:5022:2881;10.110.95.81:5022:2881 -o datafile_size=16G,memory_limit=16G,system_memory=4G,stack_size=512K,_**cpu_count=8**_,__min_full_resource_pool_memory=268435456,cache_wash_threshold=1G,workers_per_cpu_quota=10,schema_history_expire_time=1d,net_thread_count=4,major_freeze_duty_time=Disable,minor_freeze_times=10,enable_separate_sys_clog=0,enable_merge_by_turn=False,datafile_disk_percentage=40,idc=idc2 -z zone2 -p 2881 -P5022 -c 1 -d /data/observer/store -i bond0 -n myapp -l ERROR

step2:
    alter system set cpu_count=24

step3:check
    show parameters like 'cpu_count';
    => value:24
**_seems like the change works._**

step4:another check
SELECT a.zone,concat(a.svr_ip,':',a.svr_port) observer, cpu_total, (cpu_total-cpu_assigned) cpu_free, round(mem_total/1024/1024/1024) mem_total_gb, round((mem_total-mem_assigned)/1024/1024/1024) mem_free_gb, usec_to_time(b.last_offline_time) last_offline_time, usec_to_time(b.start_service_time) start_service_time,usec_to_time(b.stop_time) stop_time,b.status
  FROM __all_virtual_server_stat a JOIN __all_server b ON (a.svr_ip=b.svr_ip AND a.svr_port=b.svr_port)
  ORDER BY a.zone, a.svr_ip;
**_=>cpu_total:6_**
find that cpu_total has not changed, and i can't create a new resource pool because of the lack of cpu_total

maybe it's a bug?
the introduction of cpu_count from [https://www.oceanbase.com/docs/oceanbase-database/oceanbase-database/V2.2.50/cpu_count-1](https://www.oceanbase.com/docs/oceanbase-database/oceanbase-database/V2.2.50/cpu_count-1) says that this parameter does not need restart to take effect, but actually 'cpu_count' hasn't change until i restart the process of observer.

**Comment by longdafeng** [comment]
Thanks  for you feedback. 

we will take a look at this issue. 

alter system set cpu_count=24 
just modify the cpu count setting.

**Comment by obpilot** [comment]
The parameter cpu_count is very special and can be modified during observer initialization. 

Try to  restart every observer , one by one.  OR change the obd deploy configuration using "obd cluster edit-config obcluster" and "obd cluster restart obcluster"

```bash
su - admin
kill `pidof observer`
sleep 30
cd /home/admin/oceanbase-ce && bin/observer -o "cpu_count=24"
```

check observer status, wait until the server is active and start_service_time is normal :

```sql
select a.zone,concat(a.svr_ip,':',a.svr_port) observer, cpu_total, (cpu_total-cpu_assigned) cpu_free, round(mem_total/1024/1024/1024) mem_total_gb, round((mem_total-mem_assigned)/1024/1024/1024) mem_free_gb, usec_to_time(b.last_offline_time) last_offline_time, usec_to_time(b.start_service_time) start_service_time, b.status, usec_to_time(b.stop_time) stop_time, b.build_version 
from __all_virtual_server_stat a join __all_server b on (a.svr_ip=b.svr_ip and a.svr_port=b.svr_port)
order by a.zone, a.svr_ip;
```

go on with another observer.

**Comment by wuyinzhou** [comment]
in fact ,after restart observer, the change of cpu works.
what make me puzzled is that According to the official website introduction, this parameter is able to be applied without observer restart. I wonder if the official website introduction partly wrong?

https://www.oceanbase.com/docs/oceanbase-database/oceanbase-database/V2.2.50/cpu_count-1
![image](https://user-images.githubusercontent.com/55736968/141423961-01ce5dbd-0be4-42b1-99dd-7c1d50d6e6d7.png)

**Comment by longdafeng** [comment]
This is document's mistake, it need restart

**Comment by JLY2015** [comment]
I am trying to describe how cpu_count work. In fact, cpu_count is a parameter which is used for lots of situations, such as all tenant stat table（__all_virtual_observer_stat ). Actually , it really changed when you type 'alter system set cpu_count=24'，but to tenant unit stat, it should be actived after restart an observer,  just like you start an observer using a new unit config to create tenant.
