### ISSUE TITLE
MkDocs encountered as error

### ISSUE THREAD

**Issue by happyhust** [oceanbase/oceanbase#493]
```
MkDocs encountered as error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')
  in "/home/happyhust/repo/oceanbase/docs/mkdocs.yml", line 81, column 20
```

**Comment by edouard-lopez** [comment]
You need to install the extension first
```sh
pip install --user  mkdocs-material-extensions mkdocs-material
```

**Comment by caifeizhi** [comment]
> You need to install the extension first
> 
> ```shell
> pip install --user  mkdocs-material-extensions mkdocs-material
> ```

hi @edouard-lopez , thank you for your advice. 
This issue has already been closed, and the related documentation has been moved to a separate document repository(https://github.com/oceanbase/oceanbase-doc). 
And some more, how(or why) did you start paying attention to this issue.

**Comment by edouard-lopez** [comment]
Find this issue via search engine, I'm not using oceanbase but MkDocs
