### ISSUE TITLE
OB 新版本描述和Roadmap信息希望后续能更加完善

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#500]
历次版本发布，没有明确指出是否需要用户升级，OceanBase Roadmap不完善，缺少发布的版本和时间信息。

**Comment by longdafeng** [comment]
I will update the roadmap before 20th Nov.

**Comment by longdafeng** [comment]
https://github.com/oceanbase/oceanbase/wiki/roadmap
