### ISSUE TITLE
The tenant Locality change fails, how to deal with the merge timeout?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#527]

**Comment by LINxiansheng** [comment]
1. Firstly update the table locality and insure that is equal with the tenant locality.
`obclient> ALTER TABLE table_name SET locality= 'F{1}@z1,F{1}@z2,F{1}@z3,F{1}@z4,F{1}@z5';`
2.Secondly update tenant locality.
`obclient> ALTER TENANT test_tenant set locality = 'F{1}@z1,F{1}@z2,F{1}@z3,F{1}@z4,F{1}@z5,F{1}@z6';`
3. Thirdly retry merge. `obclient> ALTER SYSTEM MAJOR FREEZE;`
