### ISSUE TITLE
Are there any common problems with OceanBase database transactions?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#529]

**Comment by LINxiansheng** [comment]
For example:

1. Does OceanBase support close Clog during table change level or transactions level?
No.
2. When crossing multiple OBserver can readonly transaction execute continuously if we change the ownership?
Before v3.2, if other zone feedback the data then the sql will occur error, if not the sql execute continuously.
After v3.2, the sql execute continuously.
