### ISSUE TITLE
 What are the common problems encountered by the RootService service in the OceanBase database?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#533]

**Comment by LINxiansheng** [comment]
For example,

1. Can we set the RootService and observer in one machine?
Yeah.
2. Does every Zone has at least one RootService?
No
3. Which RootService is owner or servants among multiple Zones? How to electing it?
Exactly in multiple Zones there is owner-member relationship.
When the cluster created, the cluster set a RootService as owner. When the RootService crash and then the cluster will electing a new one.
4. When all the RootServices have trouble in one Zone, can the Zone is healthy?
Yes.
