### ISSUE TITLE
How to configure the lock timeout period of the OceanBase database request?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#537]

**Comment by LINxiansheng** [comment]
You can set `ob_trx_lock_timeout`.

1. When you set `ob_trx_lock_timeout` -1 and the timeout is `ob_query_timeout`
2. When you set `ob_trx_lock_timeout` not -1 and the timeout is the smaller one between `ob_trx_lock_timeout` and `ob_query_timeout`
