### ISSUE TITLE
[voice of client]something is missing in obagent 's document

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#544]
客户上线后, 回访问题跟踪

吐槽文档：反馈监控不给力，测试过 obagent，有两个问题：文档读起来“费劲？”以及文档的内容不满足诉求，比如怎么接外部报警（邮件、钉钉等）目前 prometheus 配置没有这项，同时用户习惯使用 grafana 来判断，文档也没有涉及。除此之外，各个组件没有统一的部署工具能一套打包

**Comment by hnwyllmm** [comment]
文档已完善：
https://github.com/oceanbase/obagent/tree/master/docs
