### ISSUE TITLE
单机, 一个observer, oracle租户. 下面没有指定partition, 报错是不是因为有默认partitions?

### ISSUE THREAD

**Issue by junfx** [oceanbase/oceanbase#57]
单机, 一个observer, oracle租户. 下面没有指定partition, 报错是不是因为有默认partitions?

```sql
create table bmsql_config (
cfg_name    varchar2(30) primary key,
cfg_value   varchar2(50)
);
create tablegroup tpcc_group;
create table bmsql_warehouse (
w_id        integer   not null,
w_ytd       decimal(4,2),
w_tax       decimal(4,4),
w_name      varchar2(10),
w_street_1  varchar2(20),
w_street_2  varchar2(20),
w_city      varchar2(20),
w_state     char(2),
w_zip       char(9),
primary key(w_id)
)tablegroup='tpcc_group';
ORA-00600: internal error code, arguments: -4179, table and tablegroup use different partition options not allowed
```

**Comment by leslieyuchen** [comment]
w_state     char(2),
w_zip       char(9),
primary key(w_id)
)**tablegroup='tpcc_group'**;
Because you specified tablegroup in create table， you need to create the specified tablegroup before creating the table

**Comment by junfx** [comment]
> w_state char(2),
> w_zip char(9),
> primary key(w_id)
> )**tablegroup='tpcc_group'**;
> Because you specified tablegroup in create table， you need to create the specified tablegroup before creating the table

创建了, 见第二个分号.

**Comment by njusegsdc** [comment]
Maybe you have another tablegroup named lower case tpcc_group, otherwise it will report tablegroup not exist when you create table bmsql_warehouse, since when you create the tablegroup, tpcc_group is treated as upper case while 'tpcc_group' is treated as lower case.

**Comment by njusegsdc** [comment]
You can find all existed tablegroup with `select * from all_virtual_tablegroup_real_agent;`

**Comment by njusegsdc** [comment]
OceanBase CE does not support Oracle mode, so asking at [OceanBase community](https://www.oceanbase.com/community/answer) will be a better choice.
