### ISSUE TITLE
Potential deaklock or meaningless wait in latch in routine mode.

### ISSUE THREAD

**Issue by qiwei9743** [oceanbase/oceanbase#570]
I'm trying to review the code of ob_latch part.  In function ObLatchWaitQueue::wait, how it could sleep with function lib::CO_WAIT(timeout) without functionality of futex_wait.

In function ObLatchWaitQueue::wait,  ObLatchWaitQueue::wakeup may be invoked between try_lock and lib::CO_WAIT(timeout).

| time\thread.      |     ObLatchWaitQueue::wait.(thread 1) | ObLatchWaitQueue::wakeup (thread 2) |
| ---- | ---- | ----| 
| 1 | try_lock |  - |
| 2 | - |  iib::CO_WAKEUP(*(cr_wait)); | 
|3 | lib::CO_WAIT(timeout) | -|

thread 1 will wait there.

**Comment by hnwyllmm** [comment]
the code will not be used so we won't fix it
