### ISSUE TITLE
How does the oceanbase send logging information to the console or file through obclient or mysql client to help with debugging?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#572]

**Comment by hitandrun-zz** [comment]
在通过外部文件导入数据时，需要使用回显功能显示每条执行结果对应的 SQL。可以通过以下方式开启回显。

1.通过 OBClient 或 MySQL 客户端连接 OceanBase 数据库。
2.执行以下命令，将信息输出到日志。 其中 
$log_name
 表示日志文件。
obclient> TEE $log_name;
1.执行外部脚本。其中 
$sql
 表示外部 SQL 文件。
obclient> SOURCE $sql;
1.关闭日志。
obclient> NOTEE;
