### ISSUE TITLE
OceanBase PITR （时间点级别恢复）目前缺失文档

### ISSUE THREAD

**Issue by beifangxiuwhx** [oceanbase/oceanbase#575]
文档缺陷，目前开源版本已经支持PITR，却没有使用说明。

**Comment by longdafeng** [comment]
@Amber1990Zhang  please take a look at this issue

**Comment by longdafeng** [comment]
https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/perform-full-recovery

@beifangxiuwhx please take a look at this document, if this document can't meet your requirement, please feel free to raise.
