### ISSUE TITLE
我想知道这个文档是用什么技术栈写的。。。。求回复

### ISSUE THREAD

**Issue by wo8335224** [oceanbase/oceanbase#58]
![image](https://user-images.githubusercontent.com/10435131/120497486-06969a80-c3f1-11eb-8a7b-ad5f02305c33.png)

我想知道这个文档是用什么技术栈写的。。。。求回复

**Comment by Alfred-Lau** [comment]
react, antd, yuque 样式，接口是node对 icms数据封装了一层
