### ISSUE TITLE
How to create a PL system package for the Ocean Base database ？

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#581]

**Comment by hitandrun-zz** [comment]
适用版本
OceanBase 数据库 V2.X 版本

创建 PL 系统包
按以下步骤创建 PL 系统包：
登录到 sys 租户。
开启升级模式，指定 sys 租户的兼容模式为 Oracle模式。
obclient> use oceanbase;
obclient> ALTER SYSTEM SET enable_upgrade_mode = true;
obclient> SET ob_compatibility_mode='oracle';
使用 CREATE PACKAGE 语句创建 PL 系统包。
obclient> CREATE PACKAGE <package_name> <package_body>;
还原 sys 租户的设置。
obclient> SET ob_compatibility_mode='mysql';
obclient> ALTER SYSTEM SET enable_upgrade_mode = false;

**Comment by longdafeng** [comment]
Open Source Eition doesn't support this feature
