### ISSUE TITLE
How to configure GBK character set for Oracle tenants?

### ISSUE THREAD

**Issue by TUshan333** [oceanbase/oceanbase#591]

**Comment by hitandrun-zz** [comment]
创建 GBK 租户
通过在 CREATE TENANT 语句中增加 charset=gbk，指定租户使用的字符集。创建租户的示例语句如下。
obclient> CREATE TENANT oracle replica_num = 1, 
          resource_pool_list=('pool1'), 
          charset=gbk 
          SET ob_tcp_invited_nodes='%', 
          ob_compatibility_mode='oracle',
          parallel_max_servers=10,
          parallel_servers_target=10, 
          ob_sql_work_area_percentage=20,
          secure_file_priv = "";
连接创建的 Oracle 租户，验证 

NLS_CHARACTERSET
 变量的值是否为 GBK。
obclient> SELECT * FROM V$NLS_PARAMETERS WHERE PARAMETER='NLS_CHARACTERSET';
+------------------+----------+--------+
| PARAMETER        | VALUE    | CON_ID |
+------------------+----------+--------+
| NLS_CHARACTERSET | ZHS16GBK |      0 |
+------------------+----------+--------+


注意
CREATE TABLE 语句中，charset不是变量，因此应放在 SET 子句前。
Oracle 租户中，字符集是租户级的概念，因此租户中所有用户表的 CHAR、VARCHAR2、CLOB 字段都是 GBK 字符集；但系统表中的 CHAR 与 VARCHAR2 字段仍会保留 UTF8 字符集。
Oracle 租户中，字符集不可修改，即不能通过 
ALETR
 语句修改租户、数据库、表与列的字符集。

**Comment by longdafeng** [comment]
Opensource Edition doesn't support this version
