### ISSUE TITLE
[WhiteScan] [DEADCODE] src/sql/engine/cmd/ob_table_executor.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#595]
----8<--------------8<-------
576:        } else if (OB_FAIL(common_rpc_proxy->alter_table(alter_table_arg, res))) {
577:          LOG_WARN("rpc proxy alter table for adding index failed",
578:              K(ret),
579:              "dst",
580:              common_rpc_proxy->get_server(),
581:              K(alter_table_arg));
582:        } else {
583:          obrpc::ObIndexArg* index_arg = alter_table_arg.index_arg_list_.at(0);
584:          obrpc::ObCreateIndexArg* create_index_arg = NULL;
Condition "NULL == index_arg", taking false branch. Now the value of "index_arg" is not "nullptr". major
585:          if (OB_ISNULL(index_arg)) {
586:            ret = OB_ERR_UNEXPECTED;
587:            LOG_WARN("index arg is null", K(ret), K(i));
588:          } else if (obrpc::ObIndexArg::ADD_INDEX != index_arg->index_action_type_) {
589:            ret = OB_ERR_UNEXPECTED;
590:            LOG_WARN("index action type should be add index", K(ret), K(i));
At condition "!!(NULL == (create_index_arg = static_cast<oceanbase::obrpc::ObCreateIndexArg *>(index_arg)))", the value of "NULL == (create_index_arg = static_cast<oceanbase::obrpc::ObCreateIndexArg *>(index_arg))" must be equal to 0. major
Assigning: "create_index_arg" = "static_cast<oceanbase::obrpc::ObCreateIndexArg *>(index_arg)". major
At condition "!!(NULL == (create_index_arg = static_cast<oceanbase::obrpc::ObCreateIndexArg *>(index_arg)))", the value of "create_index_arg" cannot be "nullptr". major
The condition "!!(NULL == (create_index_arg = static_cast<oceanbase::obrpc::ObCreateIndexArg *>(index_arg)))" cannot be true. major
591:          } else if (OB_ISNULL(create_index_arg = static_cast<obrpc::ObCreateIndexArg*>(index_arg))) {
Medium:(DEADCODE)
CWE561: Code can never be reached because of a logical contradiction
Execution cannot reach this statement: "ret = -4016;".

src/sql/engine/cmd/ob_table_executor.cpp: oceanbase::sql::ObAlterTableExecutor::alter_table_rpc_v1(oceanbase::obrpc::ObAlterTableArg &, oceanbase::obrpc::ObAlterTableRes &, oceanbase::common::ObIAllocator &, oceanbase::obrpc::ObCommonRpcProxy *, oceanbase::sql::ObSQLSessionInfo *, bool)
592:            ret = OB_ERR_UNEXPECTED;
593:            LOG_WARN("create index arg is null", K(ret), K(i));
594:          } else if (!is_sync_ddl_user) {
595:            create_index_arg->index_schema_.set_table_id(res.index_table_id_);
596:            create_index_arg->index_schema_.set_schema_version(res.schema_version_);
597:            if (OB_FAIL(create_index_executor.sync_check_index_status(
598:                    *my_session, *common_rpc_proxy, *create_index_arg, allocator))) {
599:              LOG_WARN("failed to sync_check_index_status", K(ret), K(*create_index_arg), K(i));
600:            } else {
601:              added_index_table_ids.push_back(res.index_table_id_);
602:            }

**Comment by J0kerMh** [comment]
认领
