### ISSUE TITLE
[WhiteScan] [DEADCODE] src/sql/code_generator/ob_code_generator_impl.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#596]
----8<--------------8<-------
3398:    ObDistinct* distinct_op = NULL;
3399:    RowDesc* out_row_desc = NULL;
3400:    RowDesc* input_row_desc = NULL;
3401:    const int32_t* input_projector = NULL;
3402:    int64_t input_projector_size = 0;
3403:    const ObIArray<ObRawExpr*>& distinct_columns = op.get_distinct_exprs();
3404:    if (OB_UNLIKELY(1 != child_ops.count())) {
3405:      ret = OB_ERR_UNEXPECTED;
3406:      LOG_ERROR("wrong # of children ops", K(ret));
At condition "({...; false;})", the value of "({...; false;})" must be equal to 0. major
At condition "({...; false;})", the value of "({...; false;})" must be "nullptr". major
The condition "({...; false;})" cannot be true. major
3407:    } else if (FALSE_IT((input_row_desc = child_ops.at(0).second,
3408:                   input_projector = child_ops.at(0).first->get_projector(),
3409:                   input_projector_size = child_ops.at(0).first->get_projector_size()))) {
Medium:(DEADCODE)
CWE561: Code can never be reached because of a logical contradiction
Execution cannot reach this statement: "ret = -4016;".

src/sql/code_generator/ob_code_generator_impl.cpp: oceanbase::sql::ObCodeGeneratorImpl::convert_distinct(oceanbase::sql::ObLogDistinct &, oceanbase::common::ObSEArray<std::pair<oceanbase::sql::ObPhyOperator *, oceanbase::sql::RowDesc *>, 2l, oceanbase::common::ModulePageAllocator, false> const &, oceanbase::common::ObSEArray<std::pair<oceanbase::sql::ObPhyOperator *, oceanbase::sql::RowDesc *>, 2l, oceanbase::common::ModulePageAllocator, false> &)
3410:      ret = OB_ERR_UNEXPECTED;
3411:    } else if (OB_FAIL(create_phy_op_desc(phy_op_type, distinct_op, out_row_desc, out_ops, op.get_op_id()))) {
3412:      LOG_WARN("failed to create phy op and desc", K(ret));
3413:    } else if (OB_FAIL(copy_row_desc(*input_row_desc, *out_row_desc))) {
3414:      LOG_WARN("failed to copy row desc", K(ret), K(*child_ops.at(0).second));
3415:    } else if (OB_FAIL(distinct_op->init(distinct_columns.count()))) {
3416:      OB_LOG(WARN, "fail to init distinct column count", K(ret));
3417:    } else {
3418:      distinct_op->set_block_mode(op.get_block_mode());
3419:      ColumnIndexProviderImpl idx_provider(*child_ops.at(0).second, input_projector, input_projector_size);
3420:      LOG_DEBUG(

**Comment by tata24** [comment]
认领

**Comment by WangYuanZhen123123** [comment]
认领

**Comment by happyhust** [comment]
I want take this issue, please assign it to me.
