### ISSUE TITLE
[WhiteScan] [EVALUATION_ORDER] src/sql/code_generator/ob_static_engine_cg.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#599]
2228:      LOG_WARN("generate index table location failed", K(ret));
2229:    } else if (OB_FAIL(subplans.allocate_array(phy_plan_->get_allocator(), ObMultiPartDeleteOp::DML_OP_CNT))) {
2230:      LOG_WARN("allocate dml subplan temp array failed", K(ret));
2231:    } else {
2232:      SeDMLSubPlan& dml_subplan = subplans.at(ObMultiPartDeleteOp::DELETE_OP);
2233:      const ObIArray<ObColumnRefRawExpr*>& index_exprs = index_dml_info.column_exprs_;
2234:      if (OB_SUCC(ret)) {
2235:        int64_t index_col_cnt = index_exprs.count();
2236:        dml_subplan.access_exprs_.set_allocator(&phy_plan_->get_allocator());
Medium:(EVALUATION_ORDER)
CWE758: Statement contains multiple side-effects on the same value with an undefined evaluation order
In "ret = !!(0 != (ret = dml_subplan.access_exprs_.init(index_col_cnt)))", "ret" is written in "ret" (the assignment left-hand side) and written in "!!(0 != (ret = dml_subplan.access_exprs_.init(index_col_cnt)))" but the order in which the side effects take place is undefined because there is no intervening sequence point.

src/sql/code_generator/ob_static_engine_cg.cpp: oceanbase::sql::ObStaticEngineCG::convert_global_index_delete_info(oceanbase::sql::ObLogDelUpd &, oceanbase::sql::TableColumns const &, oceanbase::common::ObIArray<oceanbase::sql::ObOpSpec *> &, oceanbase::sql::ObTableDMLInfo &)
2237:        if (OB_FAIL(OB_FAIL(dml_subplan.access_exprs_.init(index_col_cnt)))) {
2238:          LOG_WARN("fail to allocate array", K(ret));
2239:        }
2240:      }
2241:      OZ(generate_exprs_replace_spk(index_exprs, dml_subplan.access_exprs_));
2242:      OZ(convert_delete_subplan(op, index_dml_info, dml_subplan));
2243:      OZ(subplan_roots.push_back(dml_subplan.subplan_root_));
2244:    }
2245:  }
2246:  return ret;
2247:}

**Comment by kicurry** [comment]
认领

**Comment by hnwyllmm** [comment]
PR已合并
