### ISSUE TITLE
[WhiteScan] [CHECKED_RETURN] src/share/ob_debug_sync.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#604]
src/lib/io/ob_io_request.cpp
----8<--------------8<-------
169:
170:ObIOMaster::~ObIOMaster()
171:{
172:  reset();
173:}
174:
175:int ObIOMaster::init()
176:{
177:  int ret = OB_SUCCESS;
Example 1: "this->cond_.init(IO_CONTROLLER_COND_WAIT)" has its value checked in "0 != (ret = this->cond_.init(IO_CONTROLLER_COND_WAIT))". major
178:  if (OB_FAIL(cond_.init(ObWaitEventIds::IO_CONTROLLER_COND_WAIT))) {
179:    COMMON_LOG(WARN, "fail to init thread condition", K(ret));
180:  }
181:  return ret;
182:}
183:
184:int ObIOMaster::open(const ObIOMode mode, const ObIOInfo& info, ObIOCallback* read_callback)
185:{
186:  int ret = OB_SUCCESS;
187:
188:  if (mode >= IO_MODE_MAX || !info.is_valid()) {
src/observer/ob_sstable_checksum_updater.cpp
----8<--------------8<-------
113:    ret = OB_INIT_TWICE;
114:    LOG_WARN("ObSSTableChecksumUpdater has already been inited", K(ret));
115:  } else if (OB_FAIL(TG_CREATE(lib::TGDefIDs::STableChecksumUp, tg_id_))) {
116:    LOG_WARN("ObSSTableChecksumUpdater create tg failed", K(ret));
117:  } else if (OB_FAIL(task_queue_.init(this,
118:                 !lib::is_mini_mode() ? UPDATER_THREAD_CNT : MINI_MODE_UPDATER_THREAD_CNT,
119:                 max_partition_cnt,
120:                 "ChecksumTask"))) {
121:    LOG_WARN("fail to init task queue", K(ret));
Example 5: "this->cond_.init(DEFAULT_COND_WAIT)" has its value checked in "0 != (ret = this->cond_.init(DEFAULT_COND_WAIT))". major
122:  } else if (OB_FAIL(cond_.init(ObWaitEventIds::DEFAULT_COND_WAIT))) {
123:    LOG_WARN("failed to init cond", K(ret));
124:  } else if (OB_FAIL(TG_SET_RUNNABLE_AND_START(tg_id_, *this))) {
125:    LOG_WARN("failed to start thread", K(ret));
126:  } else {
127:    is_inited_ = true;
128:  }
129:  return ret;
130:}
131:
132:int ObSSTableChecksumUpdater::batch_process_tasks(const ObIArray<ObSSTableChecksumUpdateTask>& tasks, bool& stopped)
/data/1/xiaoma/open_source/oceanbase/deps/oblib/src/lib/queue/ob_seq_queue.cpp
----8<--------------8<-------
27:    ret = OB_INVALID_ARGUMENT;
28:    _OB_LOG(ERROR, "init(limit=%ld, buf=%p): INVALID_ARGUMENT", limit, buf);
29:  } else if (limit_ > 0 || NULL != items_) {
30:    ret = OB_INIT_TWICE;
31:  } else if (NULL == (items_ = (buf ?: (SeqItem*)buf_holder_.get(sizeof(SeqItem) * limit)))) {
32:    ret = OB_ALLOCATE_MEMORY_FAILED;
33:    _OB_LOG(ERROR, "buf_holder.get(%ld)=>NULL", sizeof(SeqItem) * limit);
34:  } else {
35:    for (int64_t i = 0; OB_SUCC(ret) && i < N_COND; ++i) {
Example 2: "this->cond_[i].init(SEQ_QUEUE_COND_WAIT)" has its value checked in "0 != (ret = this->cond_[i].init(SEQ_QUEUE_COND_WAIT))". major
36:      if (OB_FAIL(cond_[i].init(ObWaitEventIds::SEQ_QUEUE_COND_WAIT))) {
37:        _OB_LOG(ERROR, "fail to init cond, ret=%d,", ret);
38:      }
39:    }
40:
41:    if (OB_SUCC(ret)) {
42:      limit_ = limit;
43:      memset(items_, 0, sizeof(SeqItem) * limit);
44:      for (int64_t i = 0; i < limit; i++) {
45:        items_[i].seq_ = -1;
46:      }
/data/1/xiaoma/open_source/oceanbase/src/observer/ob_uniq_task_queue.h
----8<--------------8<-------
165:{
166:  int ret = common::OB_SUCCESS;
167:  const int64_t group_count = 128;
168:  if (inited_) {
169:    ret = common::OB_INIT_TWICE;
170:    SERVER_LOG(WARN, "init twice", K(ret));
171:  } else if (thread_num <= 0 || queue_size <= 0 || OB_ISNULL(updater)) {
172:    ret = common::OB_INVALID_ARGUMENT;
173:    SERVER_LOG(WARN, "invalid argument", K(thread_num), K(queue_size), K(updater));
Example 4: "this->cond_.init(PARTITION_TABLE_UPDATER_COND_WAIT)" has its value checked in "0 != (ret = this->cond_.init(PARTITION_TABLE_UPDATER_COND_WAIT))". major
174:  } else if (OB_FAIL(cond_.init(common::ObWaitEventIds::PARTITION_TABLE_UPDATER_COND_WAIT))) {
175:    SERVER_LOG(WARN, "fai to init condition, ", K(ret));
176:  } else if (OB_FAIL(task_map_.create(queue_size, common::ObModIds::OB_PARTITION_TABLE_TASK))) {
177:    SERVER_LOG(WARN, "create hash map failed", K(ret), K(queue_size));
178:  } else if (OB_FAIL(group_map_.create(group_count, common::ObModIds::OB_PARTITION_TABLE_TASK))) {
179:    SERVER_LOG(WARN, "create hash map failed", K(ret), K(group_count));
180:  } else if (OB_FAIL(processing_task_map_.create(queue_size, common::ObModIds::OB_PARTITION_TABLE_TASK))) {
181:    SERVER_LOG(WARN, "create hash map failed", K(ret));
182:  } else {
183:    this->set_thread_count(static_cast<int32_t>(thread_num));
184:    queue_size_ = queue_size;
/data/1/xiaoma/open_source/oceanbase/src/share/ob_debug_sync.cpp
----8<--------------8<-------
418:
419:void ObDSEventControl::Event::reset()
420:{
421:  ObDLinkBase<Event>::reset();
422:  signal_cnt_ = 0;
423:  waiter_cnt_ = 0;
424:  name_.reset();
425:}
426:
Condition "events_@dim0 < 2480UL", taking true branch. major
Jumping back to the beginning of the loop. major
Condition "events_@dim0 < 2480UL", taking false branch. major
427:ObDSEventControl::ObDSEventControl() : stop_(false)
428:{
Condition "i < 2480L /* static_cast<int64_t>(sizeof (this->events_) / sizeof (this->events_[0])) */", taking false branch. major
Condition "i < 2480L /* static_cast<int64_t>(sizeof (this->events_) / sizeof (this->events_[0])) */", taking true branch. major
429:  for (int64_t i = 0; i < ARRAYSIZEOF(events_); ++i) {
Condition "!this->free_.add_first(&this->events_[i])", taking false branch. major
430:    if (!free_.add_first(&events_[i])) {
431:      LOG_ERROR("add empty node to list should always success");
432:    }
Jumping back to the beginning of the loop. major
433:  }
Medium:(CHECKED_RETURN)
CWE252: Value returned from a function is not checked for errors before being used
Calling "init" without checking return value (as is done elsewhere 24 out of 29 times).

src/share/ob_debug_sync.cpp: oceanbase::common::ObDSEventControl::ObDSEventControl()
434:  cond_.init(ObWaitEventIds::DEBUG_SYNC_COND_WAIT);
435:}
436:
437:ObDSEventControl::~ObDSEventControl()
438:{
439:  stop();
440:}
441:
442:ObDSEventControl::Event* ObDSEventControl::alloc_event()
443:{
444:  Event* e = NULL;
src/lib/thread/ob_dynamic_thread_pool.cpp
----8<--------------8<-------
49:int ObDynamicThreadPool::init(const char* thread_name)
50:{
51:  int ret = OB_SUCCESS;
52:
53:  if (is_inited_) {
54:    ret = OB_INIT_TWICE;
55:    COMMON_LOG(WARN, "cannot init twice", K(ret));
56:  } else if (OB_FAIL(task_queue_.init(MAX_TASK_NUM))) {
57:    COMMON_LOG(WARN, "failed to init task queue", K(ret));
Example 3: "this->cond_.init(DYNAMIC_THREAD_POOL_COND_WAIT)" has its value checked in "0 != (ret = this->cond_.init(DYNAMIC_THREAD_POOL_COND_WAIT))". major
58:  } else if (OB_FAIL(cond_.init(ObWaitEventIds::DYNAMIC_THREAD_POOL_COND_WAIT))) {
59:    STORAGE_LOG(WARN, "failed to init cond", K(ret));
60:  } else if (OB_FAIL(task_thread_cond_.init(ObWaitEventIds::DYNAMIC_THREAD_POOL_COND_WAIT))) {
61:    STORAGE_LOG(WARN, "failed to init cond", K(ret));
62:  }
63:
64:  if (OB_SUCC(ret)) {
65:    thread_name_ = thread_name;
66:    is_inited_ = true;
67:    is_stop_ = false;
68:    ATOMIC_STORE(&thread_num_, 0);

**Comment by JameyWoo** [comment]
JameyWoo 认领

**Comment by WangYuanZhen123123** [comment]
认领
