### ISSUE TITLE
[WhiteScan] [OVERRUN] src/share/datum/ob_datum_funcs.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#605]
src/share/datum/ob_datum_funcs.cpp
----8<--------------8<-------
161:        ObOTimestampData tmp_data = datum.get_##TYPE();                                    \
162:        res = T::hash(&tmp_data.time_us_, static_cast<int32_t>(sizeof(int64_t)), seed);    \
163:        res = T::hash(&tmp_data.time_ctx_.DESC, static_cast<int32_t>(sizeof(VTYPE)), res); \
164:      }                                                                                    \
165:      return res;                                                                          \
166:    }                                                                                      \
167:  };
168:
169:DEF_DATUM_TIMESTAMP_HASH_FUNCS(ObTimestampTZType, otimestamp_tz, desc_, uint32_t);
High:(OVERRUN)
CWE119: Out-of-bounds access to a buffer
Overrunning buffer pointed to by "&tmp_data.time_ctx_.time_desc_" of 2 bytes by passing it to a function which accesses it at byte offset 31.

/data/1/xiaoma/open_source/oceanbase/src/share/datum/ob_datum_funcs.cpp: oceanbase::common::DatumHashCalculator<(oceanbase::common::ObObjType)37, oceanbase::common::ObWyHash>::calc_datum_hash(oceanbase::common::ObDatum const &, unsigned long)
Condition "datum->is_null()", taking false branch. major
170:DEF_DATUM_TIMESTAMP_HASH_FUNCS(ObTimestampLTZType, otimestamp_tiny, time_desc_, uint16_t);
High:(OVERRUN)
CWE119: Out-of-bounds access to a buffer
Overrunning buffer pointed to by "&tmp_data.time_ctx_.time_desc_" of 2 bytes by passing it to a function which accesses it at byte offset 31.

src/share/datum/ob_datum_funcs.cpp: oceanbase::common::DatumHashCalculator<(oceanbase::common::ObObjType)38, oceanbase::common::ObWyHash>::calc_datum_hash(oceanbase::common::ObDatum const &, unsigned long)
Condition "datum->is_null()", taking false branch. major
171:DEF_DATUM_TIMESTAMP_HASH_FUNCS(ObTimestampNanoType, otimestamp_tiny, time_desc_, uint16_t);
172:
173:OB_INLINE static uint64_t datum_varchar_hash(
174:    const ObDatum& datum, const ObCollationType cs_type, const bool calc_end_space, const uint64_t seed, hash_algo algo)
175:{
176:  return ObCharset::hash(cs_type, datum.get_string().ptr(), datum.get_string().length(), seed, calc_end_space, algo);
177:}
178:
179:OB_INLINE static uint64_t datum_lob_locator_hash(
180:    const ObDatum& datum, const ObCollationType cs_type, const uint64_t seed, hash_algo algo)
181:{

**Comment by fkuner** [comment]
认领
