### ISSUE TITLE
[WhiteScan] [CHECKED_RETURN] src/sql/code_generator/ob_column_index_provider.cpp

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#606]
src/sql/resolver/dml/ob_multi_table_insert_resolver.cpp
----8<--------------8<-------
614:      value_desc->set_dependant_expr(const_cast<ObRawExpr*>(column_ref->get_dependant_expr()));
615:      value_desc->set_ref_id(stmt->get_insert_table_id(), column_ref->get_column_id());
616:      value_desc->set_expr_level(current_level_);
617:      value_desc->set_column_attr(ObString::make_string(OB_VALUES), column_ref->get_column_name());
618:      if (ob_is_enumset_tc(column_ref->get_result_type().get_type()) &&
619:          OB_FAIL(value_desc->set_enum_set_values(column_ref->get_enum_set_values()))) {
620:        LOG_WARN("failed to set_enum_set_values", K(*column_ref), K(ret));
621:      }
622:      if (OB_SUCC(ret)) {
Example 5: "value_desc->add_flag(IS_COLUMN)" has its value checked in "0 != (ret = value_desc->add_flag(IS_COLUMN))". major
623:        if (OB_FAIL(value_desc->add_flag(IS_COLUMN))) {
624:          LOG_WARN("failed to add flag IS_COLUMN", K(ret));
625:        } else if (OB_FAIL(stmt->get_values_desc().push_back(value_desc))) {
626:          LOG_WARN("failed to push back values desc", K(ret), K(*value_desc));
627:        } else { /*do nothing*/
628:        }
629:      }
630:    }
631:  }
632:  return ret;
633:}
src/sql/code_generator/ob_code_generator_impl.cpp
----8<--------------8<-------
4756:    } else {
4757:      ARRAY_FOREACH(*table_columns, i)
4758:      {
4759:        ObColumnRefRawExpr* col_expr = table_columns->at(i);
4760:        if (OB_UNLIKELY(OB_ISNULL(col_expr) || !col_expr->has_flag(IS_COLUMN))) {
4761:          ret = OB_ERR_UNEXPECTED;
4762:          LOG_ERROR("Expected basic column", K(col_expr));
4763:        } else if (OB_FAIL(col_row_desc.add_column(col_expr))) {
4764:          LOG_WARN("failed to add column desc", K(ret), K(i));
Example 1: "col_expr->add_flag(IS_COLUMNLIZED)" has its value checked in "0 != (ret = col_expr->add_flag(IS_COLUMNLIZED))". major
4765:        } else if (OB_FAIL(col_expr->add_flag(IS_COLUMNLIZED))) {
4766:          LOG_WARN("failed to add flag IS_COLUMNLIZED", K(ret));
4767:        } else {
4768:        }
4769:      }  // end for
4770:
4771:      // add virtual column
4772:      ARRAY_FOREACH(*table_columns, i)
4773:      {
4774:        ObColumnRefRawExpr* col_expr = table_columns->at(i);
4775:        if (col_expr->is_generated_column()) {
src/sql/resolver/expr/ob_raw_expr_info_extractor.cpp
----8<--------------8<-------
158:      (T_FUN_SYS_RAND == expr.get_expr_type() || T_FUN_SYS_SEQ_NEXTVAL == expr.get_expr_type() ||
159:          T_FUN_SYS_AUTOINC_NEXTVAL == expr.get_expr_type() || T_FUN_SYS_ROWNUM == expr.get_expr_type() ||
160:          T_FUN_SYS_ROWKEY_TO_ROWID == expr.get_expr_type() || T_OP_CONNECT_BY_ROOT == expr.get_expr_type() ||
161:          T_FUN_SYS_CONNECT_BY_PATH == expr.get_expr_type() || T_FUN_SYS_GUID == expr.get_expr_type() ||
162:          T_FUN_SYS_STMT_ID == expr.get_expr_type() || T_FUN_SYS_SLEEP == expr.get_expr_type() ||
163:          T_OP_PRIOR == expr.get_expr_type() || T_OP_GET_USER_VAR == expr.get_expr_type())) {
164:    is_const_expr = false;
165:  }
166:  if (is_const_expr) {
Example 4: "expr->add_flag(IS_CONST_EXPR)" has its value checked in "0 != (ret = expr->add_flag(IS_CONST_EXPR))". major
167:    if (OB_FAIL(expr.add_flag(IS_CONST_EXPR))) {
168:      LOG_WARN("failed to add flag IS_CONST_EXPR", K(ret));
169:    }
170:  } else if (cnt_const_expr) {
171:    if (OB_FAIL(expr.add_flag(CNT_CONST_EXPR))) {
172:      LOG_WARN("failed to add flag CNT_CONST_EXPR", K(ret));
173:    }
174:  }
175:  return ret;
176:}
177:
178:int ObRawExprInfoExtractor::add_calculable(ObOpRawExpr& expr)
179:{
180:  int ret = OB_SUCCESS;
181:  if (T_OBJ_ACCESS_REF == expr.get_expr_type()) {
Example 2: "expr->add_flag(IS_CALCULABLE_EXPR)" has its value checked in "0 != (ret = expr->add_flag(IS_CALCULABLE_EXPR))". major
182:    if (OB_FAIL(expr.add_flag(IS_CALCULABLE_EXPR))) {
183:      LOG_WARN("add expr flag IS_CALCULABLE_EXPR failed", K(ret));
184:    }
185:  } else if (T_OP_ORACLE_OUTER_JOIN_SYMBOL == expr.get_expr_type()) {
186:    if (OB_FAIL(expr.add_flag(IS_OUTER_JOIN_SYMBOL))) {
187:      LOG_WARN("failed to add flag IS_CALCULABLE_EXPR", K(ret));
188:    }
189:  } else if (not_calculable_expr(expr)) {
190:    // not calculable expr, skip it
191:  } else if (T_OP_AND == expr.get_expr_type() || T_OP_OR == expr.get_expr_type()) {
192:    if (OB_FAIL(expr.add_flag(IS_CALCULABLE_EXPR))) {
----8<--------------8<-------
386:      if (OB_SUCCESS == ret && right_expr->has_flag(IS_SUB_QUERY)) {
387:        // operators also needs to add ALL/ANY flag
388:        ObQueryRefRawExpr* right_ref = static_cast<ObQueryRefRawExpr*>(right_expr);
389:        if (right_ref->get_output_column() > 1 || right_ref->is_set()) {
390:          // The result of the subquery is a vector or a set, then the comparison operator must be
391:          // converted to the corresponding subquery expr operator
392:          expr.set_expr_type(get_subquery_comparison_type(expr.get_expr_type()));
393:        }
394:        if (expr.get_subquery_key() == T_WITH_ALL) {
Example 3: "expr->add_flag(IS_WITH_ALL)" has its value checked in "0 != (ret = expr->add_flag(IS_WITH_ALL))". major
395:          if (OB_FAIL(expr.add_flag(IS_WITH_ALL))) {
396:            LOG_WARN("failed to add flag IS_WITH_ALL", K(ret));
397:          }
398:        } else if (expr.get_subquery_key() == T_WITH_ANY) {
399:          if (OB_FAIL(expr.add_flag(IS_WITH_ANY))) {
400:            LOG_WARN("failed to add flag IS_WITH_ANY", K(ret));
401:          }
402:        } else {
403:          if (OB_FAIL(expr.add_flag(IS_WITH_SUBQUERY))) {
404:            LOG_WARN("failed to add flag IS_WITH_SUBQUERY", K(ret));
405:          }
src/sql/code_generator/ob_column_index_provider.cpp
----8<--------------8<-------
49:      SQL_CG_LOG(WARN, "failed to add column", K(ret), K(*raw_expr));
50:    }
51:  }  // end for
52:  return ret;
53:}
54:
55:int RowDesc::add_column(ObRawExpr* raw_expr)
56:{
57:  int ret = OB_SUCCESS;
Condition "!!(NULL == raw_expr)", taking false branch. major
58:  if (OB_ISNULL(raw_expr)) {
59:    ret = OB_INVALID_ARGUMENT;
60:    SQL_CG_LOG(WARN, "invalid argument", K(ret));
Condition "!!(0 /* oceanbase::common::OB_SUCCESS */ != (ret = this->exprs_.oceanbase::common::ObSEArrayImpl<oceanbase::sql::ObRawExpr *, 256l, oceanbase::common::ModulePageAllocator, false>::push_back(raw_expr)))", taking false branch. major
61:  } else if (OB_FAIL(exprs_.push_back(raw_expr))) {
62:    SQL_CG_LOG(WARN, "failed to add raw_expr", K(ret), K(*raw_expr));
63:  } else {
64:    int64_t idx = OB_INVALID_INDEX;
65:    ret = expr_idx_map_.get_refactored(reinterpret_cast<int64_t>(static_cast<jit::expr::ObExpr*>(raw_expr)), idx);
Condition "-4200 /* oceanbase::common::OB_HASH_EXIST */ == ret", taking false branch. major
66:    if (OB_HASH_EXIST == ret) {
67:      ret = OB_SUCCESS;
Condition "-4201 /* oceanbase::common::OB_HASH_NOT_EXIST */ == ret", taking true branch. major
68:    } else if (OB_HASH_NOT_EXIST == ret) {
Condition "!!(0 /* oceanbase::common::OB_SUCCESS */ != (ret = this->expr_idx_map_.set_refactored(long const(reinterpret_cast<int64_t>(static_cast<oceanbase::jit::expr::ObExpr *>(raw_expr))), long const(this->exprs_.count() - 1), 0, 0, 0)))", taking false branch. major
69:      if (OB_FAIL(expr_idx_map_.set_refactored(
70:              reinterpret_cast<int64_t>(static_cast<jit::expr::ObExpr*>(raw_expr)), exprs_.count() - 1))) {
71:        SQL_CG_LOG(WARN, "failed to set", K(ret), K(*raw_expr));
72:      } else {
73:        ret = OB_SUCCESS;
74:      }
Falling through to end of if statement. major
75:    } else if (OB_FAIL(ret)) {
76:      SQL_CG_LOG(WARN, "failed to get hashmap", K(ret));
77:    }
78:  }
Condition "!!(0 /* oceanbase::common::OB_SUCCESS */ == (ret = ret))", taking true branch. major
Condition "!raw_expr->has_flag(IS_COLUMNLIZED)", taking true branch. major
79:  if (OB_SUCC(ret) && !raw_expr->has_flag(IS_COLUMNLIZED)) {
Medium:(CHECKED_RETURN)
CWE252: Value returned from a function is not checked for errors before being used
Calling "add_flag" without checking return value (as is done elsewhere 87 out of 93 times).

src/sql/code_generator/ob_column_index_provider.cpp: oceanbase::sql::RowDesc::add_column(oceanbase::sql::ObRawExpr *)
80:    raw_expr->add_flag(IS_COLUMNLIZED);
81:  }
82:  return ret;
83:}
84:
85:int RowDesc::replace_column(ObRawExpr* old_expr, ObRawExpr* new_expr)
86:{
87:  int ret = OB_SUCCESS;
88:  int64_t idx = OB_INVALID_INDEX;
89:  if (OB_ISNULL(new_expr)) {
90:    ret = OB_INVALID_ARGUMENT;

**Comment by tata24** [comment]
认领
