### ISSUE TITLE
The LSM-tree storage engine into OceanBase

### ISSUE THREAD

**Issue by He-XiaoLong** [oceanbase/oceanbase#61]
![image](https://user-images.githubusercontent.com/57213420/120593424-10acad80-c472-11eb-82ea-e40334d1de09.png)
请问OB现使用的LSM-tree存储引擎只有两层吗？这种做法系统内的写放大是不是比较严重，相对于传统的多层来说

**Comment by simonjoylet** [comment]
There are four levels in lsm tree of ob 3.1. These levels are L0 memtable, L1 dump memtable, L2 Minor sstable, L3 major sstable.
LSM tree allow us to balance read amplification, write amplification, and space amplification by adjust the levels and compaction strategy.
OceanBase choose one strategy which prefers to reduce read amplification and space amplification by lower levels and reduce write amplification by reuse data blocks.

**Comment by He-XiaoLong** [comment]
Since most of the key ranges of sstable in the  L1  overlap, and there are four levels,  it is not very friendly to range queries. Does oceanbase do any optimization for range query (e.g., prefix or range bloom filter)?

**Comment by simonjoylet** [comment]
Four levels mean range scan in each level and a four-way merge. Only data from L1 may overlap. OceanBase try to keep a small number of sstable in L1. 
There is bloom filter for point query in OceanBase, but there is no range bloom filter for range query. For this optimization, pr is welcome.

**Comment by simonjoylet** [comment]
OceanBase build bloom filter automatically by monitoring empty reads. If the count of empty read is more than threshold of bf_cache_miss_count_threshold, the bloom filter will be built as an async task. If the bloom filter build task is triggered by point query, the columns of bloom filter are all rowkey columns. If the bloom filter build task is triggered by range query, the columns of bloom filter is the common prefix columns of the query.
See function schedule_build_bloomfilter in "src/storage/ob_partition_scheduler.cpp"
