### ISSUE TITLE
Why can't passed the unit test with native code?

### ISSUE THREAD

**Issue by zjx1230** [oceanbase/oceanbase#610]
After I clone the branch oceanbase_competition of oceanbase, I want to try running a unit test. I did the unit test according to the [document,](https://github.com/oceanbase/oceanbase/wiki/how_to_contribute) but there was a problem.

`  FAILED  ] ObHashSetDumpTest.test_dump_except (1249 ms)
[----------] 6 tests from ObHashSetDumpTest (7509 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (7509 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] ObHashSetDumpTest.test_single
[  FAILED  ] ObHashSetDumpTest.test_except
[  FAILED  ] ObHashSetDumpTest.test_intersect
[  FAILED  ] ObHashSetDumpTest.test_dump_union
[  FAILED  ] ObHashSetDumpTest.test_dump_intersect
[  FAILED  ] ObHashSetDumpTest.test_dump_except

 6 FAILED TESTS
 Start  52: test_merge_sort_receive
 52/219 Test  #52: test_merge_sort_receive ...............................   Passed    0.32 sec`

* OS: `Linux ob-game-server-40 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Compliler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
* CPU: `Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:              7
CPU MHz:               2500.002
BogoMIPS:              5000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni`

* Commit id (942e2c664455cf8a6c9335222371b3ce6e6647e0)

**How To Reproduce**

1. git clone https://gitee.com/oceanbase/oceanbase.git -b oceanbase_competition
2. cd oceanbase
3. bash build.sh debug --init --make
4. wait for about 10 minutes
5. cd build_debug/unittest/
6. make -j 4
7. ./run_tests.sh

**Expected behavior**

passed

**Comment by akaError** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/97499944/158929399-e89b208e-e8c6-40d2-8d82-16388ef8891a.png">
