### ISSUE TITLE
Add  `default_storage_engine ` system variable for better  compatible with MySQL 

### ISSUE THREAD

**Issue by rongfengliang** [oceanbase/oceanbase#632]
**Is your feature request related to a problem? Please describe.**

currently try to add `oceanbase`  as Jira  system Datasource throw  `Unknown system variable 'default_storage_engine'`

**Describe the solution you'd like**

Maybe we can Add `default_storage_engine` system variable  (sys or tenant level , also we can change it ) 

**Additional context**
Version 3.1.1

**Comment by hnwyllmm** [comment]
Thanks for your advice. We will discuss later.

**Comment by hnwyllmm** [comment]
We think the system variable will make oceanbase more compatible with mysql.
Your PR is welcome. Thanks again.

**Comment by hnwyllmm** [comment]
`default_storage_engine` is supported in 3.1.4 and higher version
