### ISSUE TITLE
服务器资源扩容后数据重新重新分布的问题

### ISSUE THREAD

**Issue by hwd920** [oceanbase/oceanbase#633]
一个集群里有一个zone，zone里有五台服务器，在集群里创建了分区表，每个表设置5个分区，这个表的5个分区会分散到每台服务上。现在我如果要做动态的扩容，原本zone里只有一台服务器，在集群里创建了分区表，每个表设置5个分区，创建好表后，zone里增加了4台服务器，重新设置好相关配置后，发现老的数据分区并没有分布到新加的服务器上。请问如果我想把老的数据转到新的服务器上，要怎么处理呢？资源扩容后OceanBase会自动做数据的重新分布吗？

**Comment by hnwyllmm** [comment]
可以参考这篇文档：
https://open.oceanbase.com/docs/knowledgeBase/how-to-scale-out-the-oceanbase-cluster

**Comment by hwd920** [comment]
> 

感谢回复。有点疑问，我们现在在用OceanBase，想用到OceanBase的集群能力，不想每个请求都是去到单个的服务器，因此每个表都设计成类似有5个分区的分区表，创建表的时候一个zone里可能只有两三台服务器，后期会往zone里不断添加服务器，因此要把之前已经创建好的分区迁移到新的服务器上去，这个要怎么操作呢？

**Comment by hnwyllmm** [comment]
抱歉，回复比较晚。
你的场景是很典型的扩容场景。
基本的操作步骤有：
1. 在新的服务器上启动一个新的observer（OB不认为增加一台机器，就是要立即做扩容，所以没有把加机器就自动扩容的动作加进来）
2. 将新启动的observer加入到集群中
3. 执行扩容操作，比如将资源单元 (resource_unit) 数量调整变大，不建议一次将数据容量扩的很大，比如从100直接扩容到500
4. 等待数据自动迁移完成（注意，数据迁移完成之前，不建议做新的扩容或缩容）

操作的步骤，都可以在https://open.oceanbase.com/docs/knowledgeBase/how-to-scale-out-the-oceanbase-cluster 文章中看到。按照你的描述，重点内容在 “将 OBServer 添加到已有的 Zone ”这个章节。

因为你的问题比较专业，并且OB在实际使用和测试场景中，可能还需要进一步的帮助，因此邀请你加入钉钉社区群 33254054，这样我们可以更快的进行交流。

**Comment by Lukiya** [comment]
https://open.oceanbase.com/docs/knowledgeBase/how-to-scale-out-the-oceanbase-cluster
这个文章404找不到。。。。执行ADD SERVER指令提示我Timeout咋搞。
