### ISSUE TITLE
怎样监控日志备份是否断流

### ISSUE THREAD

**Issue by beifangxiuwhx** [oceanbase/oceanbase#662]
日志备份是一个持续进行的流程。

生产上以业务优先的备份设置，可能会出现日志备份断流的问题，如何通过OB内部元数据表或者其他途径监控到日志备份断流？

以及如何获取准确的可恢复时间窗口（包含出现断流的场景）？

**Comment by chris-sun-star** [comment]
可以查看这个表

**Comment by chris-sun-star** [comment]
可以查看这个表

**Comment by chris-sun-star** [comment]
可以查看这个表里面的信息 CDB_OB_BACKUP_ARCHIVELOG_SUMMARY，一般LOG_ARCHIVE_ROUND=1是没有中断过，如果是异常中断，异常恢复之后会追之前的断点，如果日志没有被回收掉，会追到完整的日志，如果是手动中断，再次开始会从最新的日志开始备份

可恢复时间窗口需要通过解析备份的文件来进行判断

具体信息可以参考官网上的文档:
https://www.oceanbase.com/docs/oceanbase-database/oceanbase-database/V3.1.2/backup-and-recovery-related-views

**Comment by chris-sun-star** [comment]
Close this issue since there's no more update
