### ISSUE TITLE
Add Feat support convert  Non-partitioned  table  to partitioned table 

### ISSUE THREAD

**Issue by rongfengliang** [oceanbase/oceanbase#664]
**Is your feature request related to a problem? Please describe.**

current not support convert Non-partitioned  table to partitioned table  add  this feature may be useful 

**Additional context**

oceanbase 3.1.1

**Comment by hnwyllmm** [comment]
Thanks for your advice. This feature is supported at the latest oceanbase and is tested now. Please take attention on our release note.
