### ISSUE TITLE
Can't find the definition of variables (src/storage/ob_sstable_row_iterator.cpp#L469)

### ISSUE THREAD

**Issue by wangqiim** [oceanbase/oceanbase#676]
https://github.com/oceanbase/oceanbase/blob/6047bd0c383ff8b80ec71f7f20a8b7908e36cf61/src/storage/ob_sstable_row_iterator.cpp#L469

I can't find the definition of the variables `read_handle_cnt` and `micro_handle_cnt`. But it can pass the compiler.

**Comment by YoungYang0820** [comment]
You can take a look at the definition of macro K_(), it actually uses **read_handle_cnt_**, which is a field of the class

**Comment by wangqiim** [comment]
> You can take a look at the definition of macro K_(), it actually uses **read_handle_cnt_**, which is a field of the class

Oh, thanks, make sense.
