### ISSUE TITLE
初始化observer，observer/store/sstable下仅有一个block_file且size很大

### ISSUE THREAD

**Issue by piuuuuuu** [oceanbase/oceanbase#682]
为什么初始化observer后observer/store/sstable仅有一个block_file且size很大？

![image](https://user-images.githubusercontent.com/73813663/145018675-a869b58d-b1d0-4914-90f3-bc3838efd4cb.png)

**Comment by caifeizhi** [comment]
OB的SSTable空间是预分配的，ObServer启动的时候就会向操作系统fallocate 一定指定的空间（取决于配置datafile_size和datafile_disk_percentage）
