### ISSUE TITLE
ob_admin缺少io_bench模块

### ISSUE THREAD

**Issue by beifangxiuwhx** [oceanbase/oceanbase#694]
.

**Comment by beifangxiuwhx** [comment]
1. 开源版的ob_admin没有io_bench功能

2. 如果我直接把结果文件放到etc目录下，开源版集群能和商业版一样自动优化参数么

**Comment by simonjoylet** [comment]
1. ob_admin的io_bench功能暂未放到开源版，这个需求我会带回讨论。
2. 可以，io_resource.conf在开源版observer上依然生效。
