### ISSUE TITLE
__all_virtual_sql_audit 加下trace_id索引

### ISSUE THREAD

**Issue by liuqian1990** [oceanbase/oceanbase#707]
`MySQL [oceanbase]> select * from v$sql_audit where TRACE_ID = 'YB420A581585-0005D157C1DE3263';
Empty set (1.73 sec)`

**Comment by longdafeng** [comment]
这个是一个view, 问一下: 为什么要加索引, 是查询太慢了吗? 我看你1.73 秒, 如果是手动输sql, 这个速度是可以接受的. 
是没有跟踪到你的数据吗?

这个sql_audit  保存的数据是有限的, 你是期望数据能持久化存下来吗?

**Comment by hnwyllmm** [comment]
太久没有新的信息就关闭了。
如果有新的问题，欢迎重新打开。
