### ISSUE TITLE
你们的联系方式是空的，不存在的？

### ISSUE THREAD

**Issue by cnmade** [oceanbase/oceanbase#71]
```

找不到地址由于系统找不到电子邮件地址&nbsp;open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。 | 找不到地址由于系统找不到电子邮件地址&nbsp;open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。 | 找不到地址 | 由于系统找不到电子邮件地址&nbsp;open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。
-- | -- | -- | --
找不到地址由于系统找不到电子邮件地址&nbsp;open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。 | 找不到地址 | 由于系统找不到电子邮件地址&nbsp;open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。
找不到地址
由于系统找不到电子邮件地址&nbsp;open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。
以下为远程服务器的响应：554 RCPT (open_contact@oceanbase.com) dosn't exist




```

**Comment by raywill** [comment]
Thank you for your feedback.


Could any one follow up to check this? This email address is at the bottom of [https://open.oceanbase.com](https://open.oceanbase.com)

![image](https://user-images.githubusercontent.com/248295/120733348-8fa8f100-c519-11eb-964c-b6720484c8fa.png)


By the way, @cnmade  I find some email address at the bottom of the official website [https://www.oceanbase.com(https://www.oceanbase.com)

Hope this could help :-)

![image](https://user-images.githubusercontent.com/248295/120733158-2de88700-c519-11eb-99c2-06ace5a2a566.png)

**Comment by cnmade** [comment]
@MizuhaHimuraki 邮箱地址是虚的？就直 接关了问题？

找不到地址
由于系统找不到电子邮件地址 open_contact@oceanbase.com，或该地址无法接收邮件，因此无法递送您的邮件。
以下为远程服务器的响应：
554 RCPT (open_contact@oceanbase.com) dosn't exist

**Comment by MizuhaHimuraki** [comment]
> @MizuhaHimuraki 邮箱地址是虚的？就直 接关了问题？

Sorry to close this issue without your consent.

I have sent your feedback to the maintainer of the website. But I think the website's mistakes are not suitable for GitHub issue tracking system, because the wrong emails are not part of THIS project.

So, reporting those issues on this [page](https://www.oceanbase.com/community/answer) will be a better choice.

**Comment by raywill** [comment]
@cnmade

Thank you very much. the email address is fixed. open_contant@oceanbase.com is reachable now.

**Comment by cnmade** [comment]
Thanks for let me know, Is it open_contant@oceanbase.com   or open_contact@oceanbase.com?
Which one is the right email address.

**Comment by cnmade** [comment]
by my test, open_contact@oceanbase.com now ok for send email
