### ISSUE TITLE
The document which show how to sync data between OB and MySQL use two different package

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#711]
According to document https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/use-canal-to-incrementally-migrate-data-to-oceanbase-database

It shows use the alibaba/canal package, but when sync data from OB to mysql, it will use OceanBase/canal

Suggestion:
Unify the two package,  avoid user download two different package, leading misuse package. 
Please modify  some configuration like "conf/example/instance.properties" document to  support sync data from MySQL to OB.

**Comment by whhe** [comment]
Link updated.
The `conf/canal.properties` file in the latest release package was inconsistent with the source code and was updated yesterday.
