### ISSUE TITLE
monitoring indicators unit in oceanbase.gv$sysstat view | 相关视图中监控指标的单位缺失

### ISSUE THREAD

**Issue by joeyzxw** [oceanbase/oceanbase#713]
when using oceanbase.gv$sysstat to capture some monitoring indicators, I found that there is no unit for monitoring indicators values in the view. Especially for some time indicators, it is hard to judge whether it is in ms or us.

当通过查询oceanbase 库中的gv$sysstat/v$sysstat视图可以查看当前observer的运行指标。
但在视图中没有包含监控指标值的单位。特别是一些时间指标，不好判断到底是以ms为单位还是以us为单位。

**Comment by simonjoylet** [comment]
the default unit of `time` type is `us`. 
the default unit of `size` is `byte`.

**Comment by longdafeng** [comment]
@Amber1990Zhang  please add some document to tell user the unit. 

https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/gv-sysstat
