### ISSUE TITLE
[feature] Support Kafka Connect

### ISSUE THREAD

**Issue by whhe** [oceanbase/oceanbase#720]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a tool to support [Kafka Connect](https://kafka.apache.org/documentation/#connect), like: https://github.com/mongodb/mongo-kafka

**Describe alternatives you've considered**
I'm not sure which component should this feature added on, I guess it may be liboblog or a new component.

**Additional context**
See topics: 
- https://github.com/topics/kafka-connect
- https://github.com/topics/kafka-connector

**Comment by simonjoylet** [comment]
thank you for your advice. this proposal needs more discussion.

**Comment by whhe** [comment]
OMS Community Edition and Canal for OceanBase can support to migrate data to Kafka now, and the [RocketMQ connector](https://github.com/apache/rocketmq-connect) is on the way. I will close this issue for now.
