### ISSUE TITLE
ERROR 1045 (42000): Access denied for user 'root@sys#obdemo'@'127.0.0.1' (using password: YES)

### ISSUE THREAD

**Issue by zhenchuan1** [oceanbase/oceanbase#721]
基于教程https://developer.aliyun.com/article/789554 搭建ob docker
执行：
```
sudo su admin
obclient -h127.1 -uroot@sys#obdemo -P2883 -prootPWD123 -c -A oceanbase
```
报ERROR 1045 (42000): Access denied for user 'root@sys#obdemo'@'127.0.0.1' (using password: YES)

**Comment by askdb** [comment]
> https://developer.aliyun.com/article/789554

您好，可以使用oceanbase官方仓库下的docker镜像，使用方法如下链接所示：
https://open.oceanbase.com/docs/tutorials/quickstart/V1.0.0/2-2-how-to-quickly-experience-oceanbase

**Comment by zhenchuan1** [comment]
> > https://developer.aliyun.com/article/789554
> 
> 您好，可以使用oceanbase官方仓库下的docker镜像，使用方法如下链接所示： https://open.oceanbase.com/docs/tutorials/quickstart/V1.0.0/2-2-how-to-quickly-experience-oceanbase

成功了，感谢
