### ISSUE TITLE
虚拟表__all_virtual_server_stat更新不及时

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#730]
虚拟表__all_virtual_server_stat更新不及时
在修改资源单元规格或者新建租户的时候，资源本身够分配会提示无法创建或者修改。

**Comment by hnwyllmm** [comment]
__all_virtual_server_stat 信息更新的频率是一个心跳时间，可以等一个心跳时间再做调整

**Comment by hnwyllmm** [comment]
没有新的回复，关闭issue。
如果还有问题，随时重新打开。
