### ISSUE TITLE
插入数据失败，无任何返回

### ISSUE THREAD

**Issue by ywf1001** [oceanbase/oceanbase#731]
import mysql.connector
import datetime
query = 'insert into test(id, name, create_time) values (\'test:123\',\'technology\','
dt = '\''+str(datetime.datetime.now().replace(microsecond=0))+'\''
print(dt)
query += dt+');'
mysql_dev = mysql.connector.connect(host='xxx.xxx.xx.xx', port=2881, user='root', password='123456', db='test_db')
cursor = mysql_dev.cursor()
cursor.execute(query)
cursor.close()

使用上面这段代码来插入数据到表里，没有任何返回，请协助看下，哪里的问题，或者是我的写法有问题，请指正

**Comment by chris-sun-star** [comment]
root@OceanBase152081:~# python test.py
  File "test.py", line 3
    query = 'insert into test(id, name, create_time) values ('test:123','technology','
                                                              ^
SyntaxError: invalid syntax
