### ISSUE TITLE
observer tag v3.1.1_CE_BP1 debug编译失败

### ISSUE THREAD

**Issue by BraveLz** [oceanbase/oceanbase#738]
## 问题描述：
拉了oceanbase tag v3.1.1_CE_BP1的代码进行debug版编译，报了错停止了， 这种问题怎么排查
## 操作流程：
参考https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/get-the-oceanbase-database-by-using-source-code
进行源码编译：
git clone https://github.com/oceanbase/oceanbase.git
git checkout v3.1.1_CE_BP1
yum install wget rpm* cpio make glibc-devel glibc-headers
.....
sh build.sh init
sh build.sh debug
...
make -j4 observer
## 报错信息：
[ 68%] Building CXX object src/storage/CMakeFiles/ob_storage.dir/Unity/unity_ob_storage_gts/0_cxx.cxx.o
[ 68%] Building CXX object src/storage/CMakeFiles/ob_storage.dir/Unity/unity_ob_storage_common/2_cxx.cxx.o
[ 68%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/5_cxx.cxx.o
[ 68%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/1_cxx.cxx.o
make[3]: *** [src/storage/CMakeFiles/ob_storage.dir/build.make:142: src/storage/CMakeFiles/ob_storage.dir/Unity/unity_ob_storage_common/2_cxx.cxx.o] Killed
make[2]: *** [CMakeFiles/Makefile2:10665: src/storage/CMakeFiles/ob_storage.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 68%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_rewrite/1_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_code_generator/0_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_dtl/0_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/8_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/13_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/4_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/16_cxx.cxx.o
make[3]: *** [src/rootserver/CMakeFiles/ob_rootserver.dir/build.make:126: src/rootserver/CMakeFiles/ob_rootserver.dir/Unity/unity_ob_rootserver_common/0_cxx.cxx.o] Killed
make[2]: *** [CMakeFiles/Makefile2:10561: src/rootserver/CMakeFiles/ob_rootserver.dir/all] Error 2
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/6_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_executor/2_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/15_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/0_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/10_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/7_cxx.cxx.o
[ 72%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_engine/12_cxx.cxx.o
[ 77%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_resolver/4_cxx.cxx.o
[ 77%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_resolver/5_cxx.cxx.o
[ 77%] Building CXX object src/sql/CMakeFiles/ob_sql.dir/Unity/unity_ob_sql_rewrite/0_cxx.cxx.o
[ 77%] Built target ob_sql
make[1]: *** [CMakeFiles/Makefile2:10903: src/observer/CMakeFiles/observer.dir/rule] Error 2
make: *** [Makefile:3280: observer] Error 2
[root@localhost build_debug]#

**Comment by longdafeng** [comment]
@LINxiansheng , please take a look at this issue.

**Comment by LINxiansheng** [comment]
> make[3]: *** [src/storage/CMakeFiles/ob_storage.dir/build.make:142: src/storage/CMakeFiles/ob_storage.dir/Unity/unity_ob_storage_common/2_cxx.cxx.o] Killed
make[2]: *** [CMakeFiles/Makefile2:10665: src/storage/CMakeFiles/ob_storage.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

The greatest possibility is that OOM(out of memory)
We use Unity Build to speed up the compilation but it take a bad result is that it need more memory than the normal compilation way.
So although I do not know your os information I recommend that you use at least more than 8G memory and 4CPU.

**Comment by BraveLz** [comment]
yes, the problem is indeed OOM. thanks @longdafeng @LINxiansheng

**Comment by Tusen183** [comment]
为什么我分配了10个G都不够编译？

**Comment by hnwyllmm** [comment]
从你的报错，看不出来是内存不够还是磁盘不够

**Comment by Tusen183** [comment]
已经解决了。我用WSL编译的，用htop观察发现，在编译Unity相关的类的时候内存涨到了10G左右，CPU就不动了。后面我把内存加到12G SWAP加到8G就通过编译了。 @hnwyllmm
