### ISSUE TITLE
OCP社区版功能建议：同集群不同server间数据目录能否不一致？

### ISSUE THREAD

**Issue by dcosmos** [oceanbase/oceanbase#740]
目前在使用OCP社区版时，同一集群内部的不同server必须使用同样的目录。
比如server1使用/data1/oceanbase/目录，server2就无法使用/data2/oceanbase/作为目录。
但我们公司的生产机器无法保证完全同构的，有的机器3个盘，有的机器1个盘，1个盘的机器根本就没有data2这个磁盘。
所以使用起来不够方便，其实之前使用OBD部署都可以不同server不同目录的，所以希望能在OCP中也支持这个功能。

**Comment by longdafeng** [comment]
Thanks for your feedback, we will take a look at this issue. 

We will try to support this with a gentle method.
