### ISSUE TITLE
OCP社区版功能建议：添加主机新建凭据是否能支持GSSAPI？

### ISSUE THREAD

**Issue by dcosmos** [oceanbase/oceanbase#741]
在OCP社区版中，添加主机需要新建凭据，目前支持两种形式：密码和SSH私钥。
但我们公司的生产机器之间都是通过GSSAPI方式实现的ssh互通，并不支持上述两种方式。
目前只能强行使用私钥方式去临时解决，但后面机器规模大了之后，就会比较麻烦。
希望后面OCP进行ssh登陆能支持GSSAPI的方式。

注：其实之前用OBD部署以及安装OCP社区版的过程中，都遇到了这个问题，但那些脚本都是开源的，所以简单改了一下就可以支持。如果后续能支持这个方式，那最好OBD部署以及安装OCP社区版的过程也可以支持这种方式。

**Comment by longdafeng** [comment]
谢谢反馈. 这个需求, 我们可以支持的

能帮忙把你修改支持gssapi 的方式 提一个pull request 到我们obd 里面吗?  我们也好参考参考你们这个实现.
