### ISSUE TITLE
Better compatible with  mysql  golang driver or packages 

### ISSUE THREAD

**Issue by rongfengliang** [oceanbase/oceanbase#742]
**Is your feature request related to a problem? Please describe.**

currently do some tests with golang  driver  find s error

- `while parameter _ob_enable_prepared_statement is disabled, prepared statement not supported`

- `Alter charset or collation type not supported`
 
- xorm  do With Sync2  for multi-time will cause `duplicate`

Maybe add some  notes or do better test for golang or  other languages  MySQL driver ?

**Comment by longdafeng** [comment]
Thanks for your feedback, we will take a look at this issue. 
The go mysql driver should works well in theory, I guess the go mysql runs with 8.0 mysql protocol, but OB just support 5.6 & 5.7 mysql protocol. 

Anyway, we will take a look at this issue.

**Comment by whhe** [comment]
1. Prepare statement is disabled by default, you can enable it by following command:

```mysql
ALTER system set _ob_enable_prepared_statement = true;
```

2. You may get this error message when trying to alter charset or collationon on a column, as  it is not supported now. https://github.com/oceanbase/oceanbase/blob/d5a5ed425138755e2624f51564fba40404ac6b8a/src/share/schema/ob_table_schema.cpp#L3672

3. AFAIK xorm Sync2 method syncs table with `CREATE TABLE IF NOT EXISTS`, so I'm wondering what kind of `duplicate` did you get. Maybe you can provide more details on this.

**Comment by rongfengliang** [comment]
@whhe  for xorm Sync2  you can see this   

https://github.com/juicedata/juicefs/issues/1262 
https://github.com/juicedata/juicefs/blob/main/pkg/meta/sql.go#L358

**Comment by whhe** [comment]
> @whhe for xorm Sync2
> 
> [juicedata/juicefs#1262](https://github.com/juicedata/juicefs/issues/1262) https://github.com/juicedata/juicefs/blob/main/pkg/meta/sql.go#L358

It should be related to the following code:

https://gitea.com/xorm/xorm/src/commit/cd36b112ae482f4fa9f0c590e103e32211a2ad80/dialects/mysql.go#L522

```go
func (db *mysql) GetTables(queryer core.Queryer, ctx context.Context) ([]*schemas.Table, error) {
	args := []interface{}{db.uri.DBName}
	s := "SELECT `TABLE_NAME`, `ENGINE`, `AUTO_INCREMENT`, `TABLE_COMMENT` from " +
		"`INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB' OR `ENGINE` = 'TokuDB')"
```

The `GetTables` method here will always return nil as OceanBase does not contain these engines like `InnoDB`, so xorm will always try to create new tables and indexs. This issue can't be fixed by OceanBase server, maybe you should request a fix to xorm. 

BTW `select version();` can be used to determine if it is an OceanBase server since 3.1.2-CE, you can deal with compatibility processing based on this function.

**Comment by rongfengliang** [comment]
@whhe  @longdafeng  https://docs.pingcap.com/zh/tidb/v4.0/information-schema-engines/ . current tidb use default  innodb  this may be a better choice

**Comment by whhe** [comment]
> @whhe @longdafeng https://docs.pingcap.com/zh/tidb/v4.0/information-schema-engines/ . current tidb use default innodb this may be a better choice

There is another table that can be used to check it like `select version();`:
```mysql
mysql> select * from information_schema.ENGINES;
+-----------+---------+-----------------------+--------------+----+------------+
| Engine    | Support | Comment               | Transactions | XA | Savepoints |
+-----------+---------+-----------------------+--------------+----+------------+
| OceanBase | YES     | Supports transactions | YES          | NO | NO         |
+-----------+---------+-----------------------+--------------+----+------------+
1 row in set (0.02 sec)
```

I think it is appropriate to add `OceanBase` to  `ENGINE` column of ` information_schema.TABLES`, you can raise a proposal in a new issue and so we can focus on it and discuss with the community.

**Comment by whhe** [comment]
Further discussion moves to #756
