### ISSUE TITLE
It had better rewrite ocp_installer.sh script with python

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#743]
The script is implemented by bash shell script,  it is very hard to debug. 

At the same time, there is no enough log to show the installation details. 

It should be implemented by python. 

Add more logs

**Comment by chris-sun-star** [comment]
ocp 3.3.0-ce-bp1 provides a more interactive way to install ocp
ocp_installer.sh will launch a service with web interface, user can config and install ocp follow the steps
