### ISSUE TITLE
ocp创建集群-安装路径设置

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#747]
指定了路径后，提示路径不存在:
主机xx中/data/1目录不存在
主机xx中/data/log1目录不存在

建议：
可以自动创建指定的路径并授相应的权限。

**Comment by chris-sun-star** [comment]
这里主要是出于两个方面考虑，自动创建路径有可能会创建在 “/” 目录下面，其实不符合预期，自动修改权限对于已存在的路径可能会影响其他用户
