### ISSUE TITLE
In OCP, failed to uninstall t-oceanbase-ocp-agent 

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#749]
in OCP, when add one node which have been installed oceanbase before, it will uninstall ocp agent , 

but failed to uninstall ocp agent

it should uninstall t-oceanbase-ocp-agent

**Comment by chris-sun-star** [comment]
the problem is cause by yum mistakenly detects ocp-agent a dependency of nc
actually ocp-agent or any other package ocp may install should not be a dependency of other package
it's safe to remove the packages installed by ocp without checking dependency

**Comment by chris-sun-star** [comment]
ocp-agent is not supposed to be any package's dependency, use force uninstall
