### ISSUE TITLE
ocp should tell user why failed to pass the path test

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#750]
![image](https://user-images.githubusercontent.com/374091/148936902-632d6f59-54a0-456a-9d3e-c31f6391c52f.png)

**Comment by chris-sun-star** [comment]
<img width="560" alt="Screenshot 2022-03-21 at 11 26 15" src="https://user-images.githubusercontent.com/85611200/159201514-b697a09c-5e72-4150-aeab-4d797a1faa07.png">
throw error with detailed message
