### ISSUE TITLE
ocp haven't modify neither /etc/security/limits.conf nor /etc/sysctl.conf

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#751]
ocp haven't modify the file  /etc/security/limits.conf or /etc/sysctl.conf

https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/optional-configure-limits-conf
https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/optional-configure-sysctl-conf

**Comment by chris-sun-star** [comment]
ocp will set the value of limits before start observer process by command
sysctl values affects more then observer process, should be set by user manually 
maybe provide a script, the user can check using the script before install observer on the host

**Comment by longdafeng** [comment]
This issue has been fixed in 3.3.x version
