### ISSUE TITLE
ocp won't create the user admin automatically

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#752]
考虑一下, 当机器没有admin账户时, 如果配置机器时, 配置的是root 账户, 要不要自动帮用户创建admin 账户. 

在后续的添加主机的过程中, 会自动创建目录/home/admin/ocp_agent, 如果没有创建admin 用户的话, /home/admin的目录就是root 用户权限, 有一点不合理

解决办法1: 
如果添加机器的用户身份是root, 如果没有admin 账户, 则可以自动帮助创建admin 账户, 并以admin 账户创建/home/admin/ocp_agent
如果添加机器的用户身份是非root 账户, 则要求用户已经创建了admin 账户.  并且该用户可以在/home/admin/ 下进行读写操作. (在添加机器时做一个检查, 是否通过身份)

解决办法2:
创建ocp_agent 目录在用户的自己目录下创建,  但这可能导致后续的一些操作会出问题.

**Comment by chris-sun-star** [comment]
这个问题主要是打包rpm的时候，安装路径设置在了/home/admin, ocp-agent实际上是以root用户来启动的， 并没有依赖admin用户，在之后的版本可以考虑使用其他的非/home/admin路径
其他对admin用户有依赖的地方，可以提示出来，让用户创建

**Comment by chris-sun-star** [comment]
add admin user precheck, fixed in version 3.1.1-ce-bp1
