### ISSUE TITLE
Questions on the partition of OB

### ISSUE THREAD

**Issue by JinHai-CN** [oceanbase/oceanbase#754]
The several replicas of the same partition in OceanBase can form a PAXOS group, and the partitions seems to be created with DDL in the database. I would like to ask if OceanBase does not have the concept of fixed size data shards like TiDB's raft-group. If so, how does OceanBase deal with the scenario that the partition is too big to be accommodated by a single node, and how does OceanBase do load balancing when the partition size is unbalanced.

**Comment by simonjoylet** [comment]
1. OceanBase do not support fixed size data shard by now.
2. the DBA need to schedule about partition method and partition count of a certain table. maybe this is not easy, but it will benefit the performance.
3. OceanBase support balance strategy based on the size of partition.

**Comment by JinHai-CN** [comment]
Do you have any future plans to address the issue of when partitions are too large and require data sharding?

**Comment by simonjoylet** [comment]
yes, OceanBase will support 2 features to solve this issue.
1. table re-defination. this will allow users to change the schema of a table by ddl operation.
2. auto split and merge in the partition. this will help user to forget data sharding.
they are both on the way

**Comment by JinHai-CN** [comment]
> yes, OceanBase will support 2 features to solve this issue.
> 
> 1. table re-defination. this will allow users to change the schema of a table by ddl operation.
> 2. auto split and merge in the partition. this will help user to forget data sharding.
>    they are both on the way

1. That's OK.
2. Auto split and merge the partitions, may lead to more or less partitions than the user defined. 
For example, one user defines 2 partitions of a table according to the DATE fields which are Partition1(2022/1/23) & Partition2(2022/1/24) . If Partition1 size is too large, it will split into two partitions. How does OB split the partition according to the DATE field?

**Comment by simonjoylet** [comment]
well, our design is bit different of your description. please wait for the release and try it.

**Comment by JinHai-CN** [comment]
> well, our design is bit different of your description. please wait for the release and try it.

Any document or text mentioned the behavior?

**Comment by simonjoylet** [comment]
> > well, our design is bit different of your description. please wait for the release and try it.
> 
> Any document or text mentioned the behavior?

there are some design docs, but they are not released now.

**Comment by JinHai-CN** [comment]
> > > well, our design is bit different of your description. please wait for the release and try it.
> > 
> > 
> > Any document or text mentioned the behavior?
> 
> there are some design docs, but they are not released now.

When the design documents will be released?

**Comment by JLY2015** [comment]
> 

Thank you for your attention to OceanBase,  if you want to know about auto split and table re-defination，please turn to https://ask.oceanbase.com for more informations.
