### ISSUE TITLE
ocp安装部署建议

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#757]
在Install obproxy（6/20）-Check if command exists 的时候会去检查obproxy的机器上是否安装nc软件（listMap={commands_to_check=[nc]），如果没有安装就会失败。

建议：
可以在ocp部署的时候放一个所有依赖的工具包，当安装部署期间当前主机上没有安装的时候可以自动去安装。

**Comment by chris-sun-star** [comment]
因为主机可能会有各种系统，版本，带所有的工具包不太现实，可以在任务之前做检查

**Comment by chris-sun-star** [comment]
Duplicate of #758

**Comment by chris-sun-star** [comment]
fixed in version 3.1.1-ce-bp1, add precheck
