### ISSUE TITLE
dereference null pointer

### ISSUE THREAD

**Issue by wangqiim** [oceanbase/oceanbase#759]
https://github.com/oceanbase/oceanbase/blob/24d4669c242418ebe972f01f900fd6f9a0622271/src/storage/ob_multiple_multi_scan_merge.cpp#L191-L242
in line 234, I meet segment fault.
in line 231. I think if branch should be `(OB_ISNULL(iter = iters_.at(tables.count() - 1 - i)))`?

Maybe the bug description is call virtual function on null pointer rather than dereference null pointer.

**Comment by hnwyllmm** [comment]
great job!
Can you push a pull request?

**Comment by wangqiim** [comment]
> great job! Can you push a pull request?

ok

**Comment by akaError** [comment]
could u please provide way to reproduce this bug ?

**Comment by wangqiim** [comment]
> could u please provide way to reproduce this bug ?

There some commits and test files. So I provide these through Baidupan(https://pan.baidu.com/s/1_abBPw5fBqagabNyYIhtNA?pwd=eqa6)

**Comment by akaError** [comment]
quite detailed, Thanks！

> > could u please provide way to reproduce this bug ?
> 
> There some commits and test files. So I provide these through Baidupan(https://pan.baidu.com/s/1_abBPw5fBqagabNyYIhtNA?pwd=eqa6)
