### ISSUE TITLE
the resource of `invisible sys unit` is not reported to the rootserver

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#761]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**
通过select * from oceanbase.__all_virtual_server_stat; 命令查看到的节点使用的资源，比实际的使用的资源要少。
当前所有observer节点都会创建sys unit，但不是所有节点都能从__all_unit 表中展示出来sys_unit。
除此之外，在心跳消息中，observer上报当前节点使用资源信息时，有些节点也没有上报sys unit(因为自身unit列表不包含sys unit)。

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**
select * from oceanbase.__all_virtual_server_stat 能看到隐藏sys unit的资源信息

**Additional context**

Provide logs and configs, or any other context to trace the problem.

**Comment by JLY2015** [comment]
Fixed:  https://github.com/oceanbase/oceanbase/pull/663

**Comment by JLY2015** [comment]
This bug was fixed in OceanBase 4.0.0
