### ISSUE TITLE
ocp添加observer节点建议

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#766]
在使用ocp新部署OB集群时,可以针对指定的参数去设置，但是在新添加observer节点的时候不能修改参数，导致体验不好。比如：
在测试环境使用的时候机器资源有限，默认值的要求很高，部署很容易失败。

**Comment by cyujing** [comment]
ob集群部署的机器建议使用同构的机器，因为ob的有些参数是集群级别的，如关键的参数memory_limit,system_memory就是集群级别的参数，ob整个集群参考一个值，通常集群级别的参数以rs上的参数值为准，所以如果是异构的机器，资源要按照规格最小的那台机器算，部署数据库一般要求尽量用独占的机器，当前的设计异构部署只能按照最小规格的机器的资源设置，会造成一定的资源浪费，一般不推荐这样用；
你反馈的问题的另外一个方面，如果部署前已经修改了部分参数，新增的机器其实是不需要特别设置的，沿用之前集群的参数设置，如果用了默认值那应该是有bug的，我们会验证一下这个场景，如果是这样处理的会修掉；

**Comment by cyujing** [comment]
已经确认新增的机器集群级别的配置项是沿用之前集群的参数设置不需要设置；
