### ISSUE TITLE
支持 qps-rt P95 P99的统计

### ISSUE THREAD

**Issue by toukii** [oceanbase/oceanbase#767]
目前qps-rt的统计是依赖 OB 系统表 v$sysstat 的统计信息：
promethes 表达式为：`sum(rate(ob_sysstat{stat_id = "40001", ob_cluster_name="$ob_cluster_name"}[2m])) by(tenant_name)  / sum(rate(ob_sysstat{stat_id = "40000", ob_cluster_name="$ob_cluster_name" }[2m])) by(tenant_name)` 
只能计算平均值，P95, P99监控更有价值。

**Comment by caifeizhi** [comment]
谢谢你的反馈，目前OB sysstat表的统计项都是键值类型，所以obagent采集的数据也不能提供直方图的语义；
目前有两种改法：
1. 添加 rt_p95,  rt_p99 这样的额外统计项；
2. observer直接提供prometheus的exporter，rt采用直方图提供；
我们接下来会分析哪种实现方式更合适，也欢迎你提出更好的建议

**Comment by longdafeng** [comment]
Done, This feature has been supported in 3.1.4.

**Comment by hnwyllmm** [comment]
use `show query_response_time;` to get the results.
