### ISSUE TITLE
How to get the src.rpm of the dependency package

### ISSUE THREAD

**Issue by zhangwenlong8911** [oceanbase/oceanbase#769]
Hello, I tried to compile oceanbase on other architectures, but the following packages are only x86_64, where can I get src.rpm, thank you
```
repo=http://mirrors.aliyun.com/oceanbase/development-kit/el/8/x86_64/

[deps]
devdeps-gtest-1.8.0-3.el8.x86_64.rpm
devdeps-isa-l-static-2.22.0-3.el8.x86_64.rpm
devdeps-libcurl-static-7.29.0-3.el8.x86_64.rpm
devdeps-libunwind-static-1.5.0-3.el8.x86_64.rpm
devdeps-mariadb-connector-c-3.1.12-3.el8.x86_64.rpm
devdeps-openssl-static-1.0.1e-3.el8.x86_64.rpm
devdeps-libaio-0.3.112-3.el8.x86_64.rpm

[tools]
obdevtools-bintuils-2.30-3.el8.x86_64.rpm
obdevtools-bison-2.4.1-3.el8.x86_64.rpm
obdevtools-ccache-3.7.12-3.el8.x86_64.rpm
obdevtools-cmake-3.20.2-3.el8.x86_64.rpm
obdevtools-flex-2.5.35-3.el8.x86_64.rpm
obdevtools-gcc-5.2.0-3.el8.x86_64.rpm
obdevtools-llvm-11.0.1-3.el8.x86_64.rpm
```

**Comment by zhangwenlong8911** [comment]
@MizuhaHimuraki  Hello, I have viewed these packages above, found that these packages are not quite the same as el8, there is an oceanbase directory in these packages, I want to build these packages, does the spec of these packages is opensource code? how can i get zhe src.rpm? could you help me to get the spec file of these packages

**Comment by longdafeng** [comment]
We are going to support ARM in March 2022.  


If you want to have a try, all of these package you can download from Internet, we have shown the package's name and version. But due to there are thousands of platform, we are afraid that you is likely to meet some other problem. 

You can join the DingDing group 33254054 for further quesiton.

**Comment by LINxiansheng** [comment]
We do some discussion about the problem and then we will public the oceanbase 3rd party dependency build rpm spec files as soon as possible.

**Comment by LINxiansheng** [comment]
Please refer https://github.com/oceanbase/ob-deps
