### ISSUE TITLE
[问题] 100多兆的数据，使用load data，竟然超时

### ISSUE THREAD

**Issue by peng19832** [oceanbase/oceanbase#771]
load data百兆大小数据，报超时
![image](https://user-images.githubusercontent.com/9590209/150950773-c1ecc3b3-860c-4063-86ef-27e622d8360a.png)
![image](https://user-images.githubusercontent.com/9590209/150950924-e89619e9-9eda-4423-8ae0-50611c3b9ce1.png)

**Comment by longdafeng** [comment]
大概率, 你的姿势不对, 我自己load tpch 100g的数据, 含建索引建表所有操作, 单磁盘机器上是80分钟. 

你这个里面需要提供几个数据
1. 你硬件配置
2. 你oceanbase的配置文件
3. 你load 的时候, 是不是直接在sys 租户里面load data, sys 租户是给系统用的, 不是给应用用的, 你应用租户配置的资源是多少?

**Comment by caifeizhi** [comment]
set @@ob_query_timeout = 1000000000;
set @@ob_trx_timeout = 1000000000;
然后再load data
