### ISSUE TITLE
oceanbase编译报错，提示找不到sql_parser_mysql_mode_lex.c

### ISSUE THREAD

**Issue by zhangwenlong8911** [oceanbase/oceanbase#776]
我下载的openanolis/anolisos:8.4-x86_64的容器，使用bash build.sh --init命令进行编译，过程中报错如下：请问是不能在openanolis容器中编译吗，bash build.sh debug --init --make命令也是同样错误

CMake Error at src/sql/parser/CMakeLists.txt:65 (add_library):
  Cannot find source file:

    sql_parser_mysql_mode_lex.c

CMake Error at src/sql/parser/CMakeLists.txt:65 (add_library):
  No SOURCES given to target: ob_sql_proxy_parser_objects

CMake Error at src/sql/parser/CMakeLists.txt:93 (add_library):
  No SOURCES given to target: ob_sql_server_parser_static

CMake Error at src/sql/parser/CMakeLists.txt:72 (add_library):
  No SOURCES given to target: ob_sql_server_parser_objects

CMake Error at src/sql/parser/CMakeLists.txt:88 (add_library):
  No SOURCES given to target: ob_sql_proxy_parser_static

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by longdafeng** [comment]
@LINxiansheng  Please take a look at this issue

**Comment by LINxiansheng** [comment]
I saw a bison run error in the compilation process.
I will fix it as soon as possible.

**Comment by LINxiansheng** [comment]
yum install m4

**Comment by fanruinet** [comment]
> yum install m4
@LINxiansheng Would you like to add this "m4" dependency to the document? https://github.com/oceanbase/oceanbase/wiki/how_to_build
