### ISSUE TITLE
[voice of client] Separate OMS from OCP

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#778]
Right now,  When install OMS, it need install OCP firstly. 

But some clients doesn't install OCP, they setup DBPaas by themselves, in this kind of case, there is no OCP in the system. 

But they need OMS, 

Can we run OMS without OCP?

**Comment by chris-sun-star** [comment]
OMS need to fetch root service list of oceanbase，ocp privide a bunch of apis to register or query such info
now, we provide a Golang implementation of these apis, https://github.com/oceanbase/oceanbase/tree/master/tools/ob-configserver
