### ISSUE TITLE
obd安装oceanbase报错

### ISSUE THREAD

**Issue by chenweihua** [oceanbase/oceanbase#78]
**Please check the FAQ documentation before raising an issue**

Please check the old issues before raising an issue in case someone has asked the same question that you are asking.

**Describe the bug (__must be provided__)**

**Your Environments (__must be provided__)**

* OS:  Linux  3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)` or `clang version 3.4.2 (tags/RELEASE_34/dot2-final)`
* CPU: `Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    1
座：                 32
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              79
型号名称：        Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
步进：              1
CPU MHz：             2099.998
BogoMIPS：            4199.99
超管理器厂商：  VMware
虚拟化类型：     完全
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           256K
L3 缓存：           20480K
NUMA 节点0 CPU：    0-15
NUMA 节点1 CPU：    16-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch epb invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm rdseed adx smap xsaveopt dtherm ida`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__must be provided__)**

1.  mini-single.yml
"""
user:
  username: root
  key_file: /root/.ssh/id_rsa
oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
    - 127.16.7.105
  global:
    home_path: /data/observer
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: ens192
    mysql_port: 2883
    rpc_port: 2882
    zone: zone1
    cluster_id: 1
    datafile_size: 8G
    # please set memory limit to a suitable value which is matching resource.
    memory_limit: 16G
    system_memory: 4G
    stack_size: 512K
    cpu_count: 16
    cache_wash_threshold: 1G
    __min_full_resource_pool_memory: 268435456
    workers_per_cpu_quota: 10
    schema_history_expire_time: 1d
    # The value of net_thread_count had better be same as cpu's core number.
    net_thread_count: 4
    major_freeze_duty_time: Disable
    minor_freeze_times: 10
    enable_separate_sys_clog: 0
    enable_merge_by_turn: FALSE
    datafile_disk_percentage: 20
"""
2. obd cluster deploy chenwh -c /root/mini-single.yaml
3. obd cluster start chenwh 
4. obd mirror list
[root@frxs-archive-7-105 ~]# obd mirror list
+------------------------------------------------------------+
|                   Mirror Repository List                   |
+--------------------------------+--------+------------------+
| name                           | type   | update time      |
+--------------------------------+--------+------------------+
| OceanBase-community-stable-el7 | remote | 2021-06-02 09:11 |
| OceanBase-development-kit-el7  | remote | 2021-06-02 09:11 |
| local                          | local  | 2021-06-04 19:53 |
+--------------------------------+--------+------------------+

Download oceanbase-ce-3.1.0-1.el7.x86_64.rpm (44.17 M): 100% [#######################################################################################################################################################################] Time: 0:00:13   3.49 MB/s
Package oceanbase-ce-3.1.0 is available
install oceanbase-ce-3.1.0 for local ok
+-------------------------------------------------------------------+
|                              Packages                             |
+--------------+---------+------------------------------------------+
| Repository   | Version | Md5                                      |
+--------------+---------+------------------------------------------+
| oceanbase-ce | 3.1.0   | 56f57e9843e719d830ec03c206d914f4b3adc82b |
+--------------+---------+------------------------------------------+
Open ssh connection ok
Remote oceanbase-ce-3.1.0-56f57e9843e719d830ec03c206d914f4b3adc82b repository install ok
Remote oceanbase-ce-3.1.0-56f57e9843e719d830ec03c206d914f4b3adc82b repository lib check !!
[WARN] 127.16.7.105 oceanbase-ce-3.1.0-56f57e9843e719d830ec03c206d914f4b3adc82b require: libmariadb.so.3

Try to get lib-repository
Download oceanbase-ce-libs-3.1.0-1.el7.x86_64.rpm (413.07 K): 100% [#################################################################################################################################################################] Time: 0:00:00   3.59 MB/s
Package oceanbase-ce-libs-3.1.0 is available
install oceanbase-ce-libs-3.1.0 for local ok
Use oceanbase-ce-libs-3.1.0-b70d3839280f145a86af26811bbfcdfaeb645509 for oceanbase-ce-3.1.0-56f57e9843e719d830ec03c206d914f4b3adc82b
Remote oceanbase-ce-libs-3.1.0-b70d3839280f145a86af26811bbfcdfaeb645509 repository install ok
Remote oceanbase-ce-3.1.0-56f57e9843e719d830ec03c206d914f4b3adc82b repository lib check ok
127.16.7.105 initializes cluster work home
chenwh deployed

error:
[root@frxs-archive-7-105 data]# obd cluster start chenwh
Get local repositories and plugins ok
Start observer ok
observer program health check ok
Connect to observer ok
Initialize cluster
Cluster bootstrap x
Cluster init failed

conf:  如果您采用本地安装，即中控机器和目标机器是同一台机器

**Comment by chenweihua** [comment]
本地安装不能设置IP要设置为127.0.01

**Comment by watchpoints** [comment]
> 本地安装不能设置IP要设置为127.0.01

官方例子 就是127.0.0.1呀
