### ISSUE TITLE
在未选择数据库的情况下，就create outline，会导致查看outline报错

### ISSUE THREAD

**Issue by dcosmos** [oceanbase/oceanbase#780]
执行步骤：
1. 通过obclient，执行一次业务sql
2. 通过以下语句获取到刚刚执行的sql的sql_id
    select sql_id from oceanbase.gv$plan_cache_plan_stat where query_sql like "业务sql";
3. 通过obclient -c连接数据库，然后没有use我的业务库，而是在默认数据库下进行创建outline的操作：
    MySQL [(none)]> CREATE OUTLINE ob_out on "647EF62257D0957DE5AA5D192AE83818" using hint /*......*/;
4. 然后通过以下语句查看outline，会报错：
    MySQL [(none)]> select * from oceanbase.gv$outline;
    ERROR 4016 (HY000): Internal error
5. 尝试去drop outline，也会报错：
    MySQL [(none)]> drop outline ob_out;
    ERROR 5265 (HY000): Outline '__outline_default_db.ob_out' doesn't exist
    use了几个数据库，也都显示同样的错误。

**Comment by caifeizhi** [comment]
谢谢反馈，经排查是outline虚拟表实现有bug，我们会在3.1.3带上这个bugfix

**Comment by dcosmos** [comment]
多谢！

**Comment by akaError** [comment]
already fix internal
