### ISSUE TITLE
Violation of C++ code style

### ISSUE THREAD

**Issue by tabokie** [oceanbase/oceanbase#79]
**Describe the bug (__must be provided__)**

While skimming through the source code, I found that visibility modifier (`public`, `private`) is indented two spaces ([example](https://github.com/oceanbase/oceanbase/blob/377fa3d62f0b4a7a20dd2e7ebaaa0ef38f190759/src/observer/ob_cache_size_calculator.h#L31)), which has violated the [official code style](https://open.oceanbase.com/docs/oceanbase-code-style-guide/oceanbase-code-style-guide/V3.1.0/class-format) and the repo clang-format rule (`AccessModifierOffset: 0`).

There might be other violations that I haven't observed at first sight.

**Your Environments (__must be provided__)**

No need.

**How To Reproduce(__must be provided__)**

No need.

**Expected behavior**

Consistent specification of code style.

Since the open source code has already diverged with internal version (no comment and such), maybe we can do a global format? Or we can change the document and clang-format rule to be more consistent with existing codebase.

**Additional context**

No.

**Comment by LINxiansheng** [comment]
set it -4
