### ISSUE TITLE
建议修改__all_virtual_server_stat统计资源跟分配资源的计算逻辑保持一致

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#792]
问题复现：
memory_limit=12g,
system_memory=4g,
cpu_count=16,
cpu_reserved=2,

sys租户min_cpu=2.5,max_cpu=5,min_memory=2g,max_memory=5g

使用__all_server和__all_virtual_server_stat关联查询
cpu_free=11.5
memory_free=6g

新建一个如下规格后创建资源池都提示资源不足
create resource unit u1
min_cpu=3,max_cpu=3,
min_memory='3g',max_memory='4g',
min_iops=200,max_iops=400,
max_session_num=100,
max_disk_size='4g';

create resource unit u2
min_cpu=10,max_cpu=10,
min_memory='3g',max_memory='3g',
min_iops=200,max_iops=400,
max_session_num=100,
max_disk_size='4g';

问题修复建议：
将__all_virtual_server_stat里统计资源剩余和创建资源池里面的统计逻辑保持一致，都按照capicity减去单台observer上所有对应资源的max之和来计算。
比如：
observer1  memory_limit=16g,system_memory=4g,上有u1/u2/u3 规格都是min_memory=1g,max_memory=2g
那么统计出来的剩余可用内存应该是 16-4-2\*3=6g,
目前的__all_virtual_server_stat统计是按照min值来统计的，导致剩余内存为16-4-1\*3=9g,当分配9g的时候又不够分配。

**Comment by hnwyllmm** [comment]
感谢你的这个问题，非常好。
这些数据确实容易造成误解，展示数据不够清晰。但是考虑到兼容性，相关的修改需要慎重考虑。

**Comment by JLY2015** [comment]
__all_virtual_server_stat
