### ISSUE TITLE
about easy_pool_cleanup_new

### ISSUE THREAD

**Issue by haoyu234** [oceanbase/oceanbase#793]
https://github.com/oceanbase/oceanbase/blob/9324f96e5f6e438e70482e91675c0583faa79984/deps/easy/src/util/easy_pool.c#L243-L244

在申请内存时, 传入的大小不是`sizeof(easy_pool_cleanup_t)`, 而是`sizeof(easy_pool_t)`, 这样写是有什么性能上的考虑吗?

**Comment by JLY2015** [comment]
Thank you for your attention to OceanBase, if you want to know more about OceanBase details, please turn to https://ask.oceanbase.com, thanks.
