### ISSUE TITLE
go语言怎么连接oceanbase呢？

### ISSUE THREAD

**Issue by WenTao-Love** [oceanbase/oceanbase#794]
在网上有博客记录到github.com/aliyun/go-driver-ob
这个go连接oceanbase数据库的driver包。
为什么现在在官方都不找到go-driver-ob呢？
求支持go driver!

**Comment by rongfengliang** [comment]
@WenTao-Love  目前版本 golang 直接链接还是会有一些问题的，需要调整一些配置， 参考 https://github.com/oceanbase/oceanbase/issues/331 https://github.com/oceanbase/oceanbase/issues/742

比如开启
```code
ALTER system set _ob_enable_prepared_statement =true;
```

**Comment by LINxiansheng** [comment]
Please refer https://github.com/oceanbase/oceanbase-doc/blob/V3.1.2/zh-CN/7.developer-guide/2.connect-to-oceanbase-database/7.connect-to-oceanbase-through-golang-driver.md

**Comment by WenTao-Love** [comment]
@LINxiansheng @rongfengliang @longdafeng 感谢三位大佬，我们公司是使用OceanBase的Oracle模式，go折腾了很久，还是有些问题。哎……只能退回又长又臭的Java开发了，哎……

**Comment by WenTao-Love** [comment]
真心希望能有个官方版的吧。

**Comment by longdafeng** [comment]
你到我们钉群, 可以直接@我详细聊吧

**Comment by WenTao-Love** [comment]
@longdafeng 好的，谢谢。请问钉钉号是：[33254054]吗？
