### ISSUE TITLE
能否在安装时启用playground 方式

### ISSUE THREAD

**Issue by farmwork911** [oceanbase/oceanbase#797]
在ob安装体验时，因为安装过程涉及到的步骤较多，能否像tidb 中用于测试的方式使用playground的方式简化安装配置流程。

1、下载并安装 TiUP。
curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
2、声明全局环境变量。
source .bash_profile
3、在当前 session 执行以下命令启动集群。
tiup playground

三步即可完成用于测试的环境布署，希望OB也能采用这种方式以降低入门的难度。

**Comment by hnwyllmm** [comment]
已实现，参考 [快速上手](https://open.oceanbase.com/quickStart)中 obd demo 相关内容
