### ISSUE TITLE
description of system stat/event

### ISSUE THREAD

**Issue by xuji755** [oceanbase/oceanbase#802]
**Is your feature request related to a problem? Please describe.**
 Need Document for  descriprtion of "wait event" and "sysstat"
**Describe the solution you'd like**

Oceanbase provides v$sysstat/v$session_event views, which are critical for operation and maintenance.
However, I can only find the definition of these views in the Oceanbase documentation, and can't find the meaning of each wait event/statistic.
The Oracle database has similar documentation, which is described in detail in the complete reference. Hopefully Oceanbase will also provide similar documentation.

**Comment by longdafeng** [comment]
Thanks for your feedback, @Amber1990Zhang , please take a look at this issue. 

We will try to fix this issue before the next feature release 3.1.3 (3/31).
