### ISSUE TITLE
`_ob_enable_prepared_statement` does not work

### ISSUE THREAD

**Issue by whhe** [oceanbase/oceanbase#805]
While `_ob_enable_prepared_statement` is `FALSE`, prepare statements can still be executed in OceanBase 3.1.2-CE.

**Comment by caifeizhi** [comment]
please provide more info, such as "How to reproduce this problem"

**Comment by whhe** [comment]
The issue still exists in `3.1.3-OceanBase CE`.

**Comment by whhe** [comment]
Still exists in `3.1.4-OceanBase CE`.

**Comment by whhe** [comment]
Same in `5.7.25-OceanBase_CE-v4.0.0.0`
