### ISSUE TITLE
视图报错

### ISSUE THREAD

**Issue by liuqian1990** [oceanbase/oceanbase#808]
`MySQL [oceanbase]>  select * from v$ob_all_clusters;
ERROR 1356 (42S22): View 'oceanbase.v$ob_all_clusters' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them`

oceanbase.__all_virtual_all_clusters 这个内部视图不存在，是否是用__all_virtual_clusters

**Comment by akaError** [comment]
谢谢，经验证的确存在一些问题，已经反馈相关的同学，下个版本会带上

**Comment by JLY2015** [comment]
The __ob_all_clusters/__all_virtual_clusters/__all_virtual_all_clusters views are not exist in OceanBase4.0 anymore. We will close this issue and we are looking forward for your more suggestions.
