### ISSUE TITLE
[Question]: After the cluster is restarted, the leader replicas are not evenly distributed

### ISSUE THREAD

**Issue by donghy-coredumped** [oceanbase/oceanbase#813]
### Describe your question

1. sysbench init  leader distributed:
+-------------+------------------+------------+--------------+-------+--------------------+--------+--------------+
| tenant_name | table_id         | table_name | partition_id | ZONE  | observer           | ROLE   | primary_zone |
+-------------+------------------+------------+--------------+-------+--------------------+--------+--------------+
| tenant_2    | 1100611139453874 | sbtest1    |            0 | zone3 | 10.140.118.7:2882  | leader |              |
| tenant_2    | 1100611139453892 | sbtest10   |            0 | zone3 | 10.140.118.7:2882  | leader |              |
| tenant_2    | 1100611139453894 | sbtest11   |            0 | zone1 | 10.140.114.12:2882 | leader |              |
| tenant_2    | 1100611139453896 | sbtest12   |            0 | zone2 | 10.140.60.14:2882  | leader |              |
| tenant_2    | 1100611139453876 | sbtest2    |            0 | zone1 | 10.140.114.12:2882 | leader |              |
| tenant_2    | 1100611139453878 | sbtest3    |            0 | zone2 | 10.140.60.14:2882  | leader |              |
| tenant_2    | 1100611139453880 | sbtest4    |            0 | zone3 | 10.140.118.7:2882  | leader |              |
| tenant_2    | 1100611139453882 | sbtest5    |            0 | zone1 | 10.140.114.12:2882 | leader |              |
| tenant_2    | 1100611139453884 | sbtest6    |            0 | zone2 | 10.140.60.14:2882  | leader |              |
| tenant_2    | 1100611139453886 | sbtest7    |            0 | zone3 | 10.140.118.7:2882  | leader |              |
| tenant_2    | 1100611139453888 | sbtest8    |            0 | zone1 | 10.140.114.12:2882 | leader |              |
| tenant_2    | 1100611139453890 | sbtest9    |            0 | zone2 | 10.140.60.14:2882  | leader |              |
+-------------+------------------+------------+--------------+-------+--------------------+--------+--------------+
12 rows in set (0.009 sec)
The leader is evenly distributed to multiple zones

2.reset cluster
root@dhy01 sysbench]# obd cluster stop cluster
Get local repositories and plugins ok
Open ssh connection ok
Stop observer ok
Stop obproxy ok
cluster stopped
[root@dhy01 sysbench]# obd cluster start cluster
Get local repositories and plugins ok
Open ssh connection ok
Load cluster param plugin ok
Check before start observer ok
Check before start obproxy ok
Start observer ok
observer program health check ok
Connect to observer ok
Wait for observer init ok
+-------------------------------------------------+
|                     observer                    |
+---------------+---------+------+-------+--------+
| ip            | version | port | zone  | status |
+---------------+---------+------+-------+--------+
| 10.140.114.12 | 3.1.2   | 2881 | zone1 | active |
| 10.140.118.7  | 3.1.2   | 2881 | zone3 | active |
| 10.140.60.14  | 3.1.2   | 2881 | zone2 | active |
+---------------+---------+------+-------+--------+

Start obproxy ok
obproxy program health check ok
Connect to obproxy ok
+-------------------------------------------------+
|                     obproxy                     |
+---------------+------+-----------------+--------+
| ip            | port | prometheus_port | status |
+---------------+------+-----------------+--------+
| 10.140.114.12 | 2883 | 2884            | active |
+---------------+------+-----------------+--------+
cluster running
3.leader distributed:
+-------------+------------------+------------+--------------+-------+-------------------+--------+--------------+
| tenant_name | table_id         | table_name | partition_id | ZONE  | observer          | ROLE   | primary_zone |
+-------------+------------------+------------+--------------+-------+-------------------+--------+--------------+
| tenant_2    | 1100611139453874 | sbtest1    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453892 | sbtest10   |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453894 | sbtest11   |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453896 | sbtest12   |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453876 | sbtest2    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453878 | sbtest3    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453880 | sbtest4    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453882 | sbtest5    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453884 | sbtest6    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453886 | sbtest7    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453888 | sbtest8    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
| tenant_2    | 1100611139453890 | sbtest9    |            0 | zone3 | 10.140.118.7:2882 | leader |              |
+-------------+------------------+------------+--------------+-------+-------------------+--------+--------------+
12 rows in set (0.019 sec)

After observing for a period of time, the leader is not evenly distributed

**Comment by donghy-coredumped** [comment]
observer version:3.1.2

**Comment by askdb** [comment]
1、obd 是什么版本呢？
2、确认一下select * from gv$tenant where tenant_name='tenant_2' \G

**Comment by donghy-coredumped** [comment]
1. OceanBase Deploy: 1.2.1
REVISION: 9f2fb49eca02d9a5efecaab5994fe7abddf81a79
BUILD_BRANCH: (HEAD
BUILD_TIME: Jan 04 2022 13:23:40OURCE
Copyright (C) 2021 OceanBase
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law

2.root@127.0.0.1 : oceanbase 10:48:36> select * from gv$tenant where tenant_name = 'tenant_2';
+-----------+-------------+-------------------+--------------+----------------+------+-----------+---------------------------------------------+
| tenant_id | tenant_name | zone_list         | primary_zone | collation_type | info | read_only | locality                                    |
+-----------+-------------+-------------------+--------------+----------------+------+-----------+---------------------------------------------+
|      1001 | tenant_2    | zone1;zone2;zone3 | RANDOM       |              0 |      |         0 | FULL{1}@zone1, FULL{1}@zone2, FULL{1}@zone3 |
+-----------+-------------+-------------------+--------------+----------------+------+-----------+---------------------------------------------+

**Comment by donghy-coredumped** [comment]
谢谢，是zone配置的问题
