### ISSUE TITLE
the default memory resource of sys tenant cannot be configured

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#814]
**Is your feature request related to a problem? Please describe.**
the default memory of sys tenant cannot be modified. refer the code below
```c++
int64_t ObServerConfig::get_max_sys_tenant_memory()
{
  int64_t max_sys_tenant_memory =
      std::min(static_cast<int64_t>(MAX_SYS_TENANT_MEM_FACTOR * static_cast<double>(get_server_memory_avail())),
          DEFAULT_MAX_SYS_MEMORY);

  return max_sys_tenant_memory;
}
```
the value of MAX_SYS_TENANT_MEM_FACTOR is 0.3

**Describe the solution you'd like**
create a new config item for sys tenant.

**Describe alternatives you've considered**

**Additional context**

**Comment by JLY2015** [comment]
It's fixed in OceanBase 4.0
