### ISSUE TITLE
Document issue: Redundant "hbase -> HBase" in document

### ISSUE THREAD

**Issue by fanruinet** [oceanbase/oceanbase#815]
文档[开源数据库OceanBase源码解读（九）：tableAPI和OB多模型](https://open.oceanbase.com/blog/8600129?currentPage=1)的正文中出现了非常多的“hbase -> HBase”，非常影响阅读，请改正。例如：

> 在刚刚发布的 [OceanBase社区版 3.1.1](https://link.zhihu.com/?target=https%3A//mp.weixin.qq.com/s/YmH7Yv4ZltUZJJ8hXAwh6Q) 中，OceanBase 开放了一组新的 API 叫做 Table API ，**hbase -> HBase** 。本文作为源码解读系列的第九篇，将介绍 Table API ，**hbase -> HBase** 和 OceanBase 多模型，以及 tableAPI 相关代码。

**Comment by akaError** [comment]
谢谢反馈，已经反馈给运营发文章的同学去处理，文章已经是上年的，可能需要一点时间去看看

**Comment by fanruinet** [comment]
文档已修复。
