### ISSUE TITLE
[Question]: CPU 超卖

### ISSUE THREAD

**Issue by sjztbyl** [oceanbase/oceanbase#818]
### Describe your question

最近节点cpu总是被跑满，卡的都连接不进去，节点22C，租户分配cpu为12c，就算跑满也才12c，但现在的情况是把服务器CPU直接跑满，后来得知是cpu_quota_concurrency参数导致的，默认4、也就是租户虽然分配了12c、但实际可以跑的12cx4、也就是cpu使用率不是1200%而是4800%、如果是这样，那OB的资源限制又有什么意义呢。节点22c，最高cpu可跑到2200%。但其实租户配置6c，使用率已经达到2400%了。资源隔离没有任何意义，我可以这么理解吗

**Comment by JLY2015** [comment]
we are very appreciate to your advisement. Also，we will very thankful if you turn to  https://ask.oceanbase.com to give us more of your suggestions.
