### ISSUE TITLE
ce ocp取消接管集群

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#823]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
fixed by oceanbase 3.1.3, please use obd switch the user who running oceanbase to the user 'admin', so the ocp can take over the whole cluser. 

How to switch the user who running oceanbase to the user 'admin'?
Please refer to OBD document
