### ISSUE TITLE
物理备份何时支持S3对象存储？或者是国产备份软件？

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#826]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
当前已经支持了oss, 你可以直接试一把


另外, s3 要到4.0 后才能支持

**Comment by caifeizhi** [comment]
duplicate #574

**Comment by hnwyllmm** [comment]
closed by dd842750326b7c74f70ffaa670b1da229a497712
