### ISSUE TITLE
登录失败处理策略

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#827]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akaError** [comment]
please detail your question

**Comment by longdafeng** [comment]
Thanks, could you please give us more details, otherwise we can't give you suggestion or get to know how to fix it.

**Comment by oceanbase123** [comment]
开源版本不支持登录失败处理策略相关的功能；该功能从商业版3.2开始支持的。

**Comment by oceanbase123** [comment]
修改配置项：connection_control_failed_connections_threshold
修改为 connection_control_min_connection_delay  或者  connection_control_max_connection_delay 时
报错：ERROR 5099 (42000): System config unknown

**Comment by askdb** [comment]
目前这个参数只有在商业版OceanBase上才有，社区版上没有提供。
