### ISSUE TITLE
查询报错Request to read too old versioned data

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#829]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
Could you please give us more context?

**Comment by oceanbase123** [comment]
查询偶尔会报错：Request to read too old versioned data，语句为3个表做join，其中两个表是查询3天内的数据

**Comment by longdafeng** [comment]
当前查询所依赖的数据版本已经被回收，用户需要根据查询设置UNDO的保留时间，例如： set global undo_retention=xxx  (默认单位是秒)
