### ISSUE TITLE
[Document issue]: Package "m4" is required but not mentioned in how_to_build wiki

### ISSUE THREAD

**Issue by fanruinet** [oceanbase/oceanbase#830]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
Windows Subsystem for Linux, Ununtu 20.04 distribution.
```

### Fast Reproduce Steps(Required)

I followed the [how_to_build](https://github.com/oceanbase/oceanbase/wiki/how_to_build) document to compile the OceanBase source code.

### Actual Behavior

The error described in issue [776](https://github.com/oceanbase/oceanbase/issues/776) occurred.

### Expected Behavior

The code should compile without error. The procedures in [how_to_build](https://github.com/oceanbase/oceanbase/wiki/how_to_build) should be complete.

### other information

There's a solution "yum install m4" mentioned in issue 776 and it worked for me. Document [how_to_build](https://github.com/oceanbase/oceanbase/wiki/how_to_build) should be modified to include this dependency.

**Comment by longdafeng** [comment]
Thanks, I will fix it right now

**Comment by longdafeng** [comment]
Done
