### ISSUE TITLE
OB执行计划不够智能

### ISSUE THREAD

**Issue by vzong** [oceanbase/oceanbase#833]
### Describe your question

oceanbase执行计划不够智能。
r_id有索引，但是TABLE LOOKUP太早，早于SORT LIMIT。

+-----------+
| @@version |
+-----------+
| 3.1.2     |
+-----------+

mysql> desc select * from tablex where r_id>=505870491 order by r_id asc limit 15\G
*************************** 1. row ***************************
Query Plan: 
===========================================================
|ID|OPERATOR            |NAME         |EST. ROWS|COST     |
-----------------------------------------------------------
|0 |EXCHANGE IN REMOTE  |             |15       |861921702|
|1 | EXCHANGE OUT REMOTE|             |15       |861921334|
|2 |  LIMIT             |             |15       |861921334|
|3 |   TOP-N SORT       |             |15       |861921334|
|4 |    TABLE LOOKUP    |tablex       |19023339 |828071168|
|5 |     TABLE SCAN     |tablex(r_id) |19023339 |9484352  |
===========================================================

mysql> desc select r_id from tablex where r_id>=505870491 order by r_id asc limit 15\G
*************************** 1. row ***************************
Query Plan:
======================================================
|ID|OPERATOR            |NAME         |EST. ROWS|COST|
------------------------------------------------------
|0 |EXCHANGE IN REMOTE  |             |15       |47  |
|1 | EXCHANGE OUT REMOTE|             |15       |46  |
|2 |  TABLE SCAN        |tablex(r_id) |15       |46  |
======================================================

mysql> desc select * from tablex where r_id in(select r_id from tablex where r_id>=505870491 order by r_id asc limit 15)\G
*************************** 1. row ***************************
Query Plan: 
======================================================
|ID|OPERATOR            |NAME         |EST. ROWS|COST|
------------------------------------------------------
|0 |EXCHANGE IN REMOTE  |             |16       |1400|
|1 | EXCHANGE OUT REMOTE|             |16       |1028|
|2 |  NESTED-LOOP JOIN  |             |16       |1028|
|3 |   SUBPLAN SCAN     |VIEW2        |15       |47  |
|4 |    MERGE DISTINCT  |             |15       |47  |
|5 |     SUBPLAN SCAN   |VIEW1        |15       |47  |
|6 |      TABLE SCAN    |tablex(r_id) |15       |46  |
|7 |   TABLE LOOKUP     |tablex       |1        |65  |
|8 |    TABLE SCAN      |tablex(r_id) |1        |5   |
======================================================

**Comment by akaError** [comment]
could you attach sql for us to rebuild the same table as yours ?

**Comment by simonjoylet** [comment]
good catch, thank you!
this will be supported on 4.0, which may be released this year.

**Comment by longdafeng** [comment]
This problem has been resolved in Commercial 3.2, due to the patch need be based on 3.2 code base, it 's hard to be ported to 3.1.X Community version. 

You can use hint to modify the plan, please refer to https://open.oceanbase.com/quicksearch?q=hint%20index&scope=docs

We will support this feature in OB 4.1

**Comment by hnwyllmm** [comment]
3.x is freezed
