### ISSUE TITLE
__all_sys_parameter功能介绍

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#834]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by askdb** [comment]
修改的集群级别的参数后除了为持久化到参数文件外，同时会持久化到表__all_sys_parameter，
如果修改的是租户级别的参数除了持久化到参数文件外，同时会持久化到表__tenant_parameter，
这2个表可以用来粗略（这里说的粗略，指有一些默认值默认就在__all_sys_parameter）统计我们创建OB集群后修改过哪些参数。

**Comment by longdafeng** [comment]
修改原来的title 是 “为什么sys租户中__all_sys_parameter视图里只有7条记录？而通过show parameters 却能看到很多记录？”
