### ISSUE TITLE
通过 mysql -h182.119.80.127 -P52883 -uroot@sys -p无法连接数据库，未设置过密码，报错1045，access denied for user 'root'@'***.***.***.***' (using password : YES)

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#835]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
It seems we have resolve this problem in DingTalk group, it seems usage problem
