### ISSUE TITLE
社区版支持ALTER TABLE t_obtest ADD CONSTRAINT pk_t_obtest_id PRIMARY KEY(id)吗？

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#836]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
Right now, OB doesn't support this feature in 3.x, ob will support this in 4.1

**Comment by JLY2015** [comment]
Add constraint primary key is supported in OceanBase4.0.0
