### ISSUE TITLE
磁盘扩容咨询

### ISSUE THREAD

**Issue by oceanbase123** [oceanbase/oceanbase#837]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by longdafeng** [comment]
帮助调整一下 title


文档https://open.oceanbase.com/docs/observer-cn/V3.1.2/10000000000013244中提到的：创建后无法调整大小。您可以通过加减机器为 OceanBase 数据库进行扩容和缩容。目前，OceanBase 数据库不支持单机的磁盘级扩容和缩容这句话。我发现通过上调 datafile_disk_percentage ，重启observer后block_file文件会变大，系统里查询可用空间也变大了。那么1、到底能不能磁盘扩容呢？ 2、 通过这种方式扩大的空间可用吗？真的用到了会不会报错？

**Comment by longdafeng** [comment]
这种就是我们官方推荐的扩容方式, 已经在蚂蚁集团内部大面积使用, 没有问题, 而且你扩容后, 你db 可用空间变大了, 文件也变大了, 说明已经生效了. 

我们后期会实现一个功能: data_file 大小按需申请, 不会一下子全部把空间占住
