### ISSUE TITLE
内部表咨询

### ISSUE THREAD

**Issue by joyboy2022** [oceanbase/oceanbase#839]
### Describe your question

在学习OB的过程中会用到很多内部表查询相关的状态信息，但是在官网上搜不到内部表的定义与字段含义，请求在官网中加入内部表的定义与字段解释，降低学习难度

**Comment by watchpoints** [comment]
内部表文档地址：在git docs\docs\docs-cn\13.reference-guide\1.system-view\3.performance-view 目录。

可以根据obcp 或者问题 遇到问题在查找。

**Comment by longdafeng** [comment]
The latest document is in https://github.com/oceanbase/oceanbase-doc/tree/V3.1.2/zh-CN/12.reference-guide/1.system-views/2.performance-views

**Comment by longdafeng** [comment]
理论上, 这些内部虚拟表都是内部debug 和监控使用, 因为, 他们经常性因为内部设计的变动而发生改变, 现在不打算公开

如果需要对部分表有强烈诉求, 就提出来, 我们将这些表expose 出来, 作为一个接口固化下来
