### ISSUE TITLE
建议添加list分区根据范围查询可以使用到分区裁剪的功能

### ISSUE THREAD

**Issue by askdb** [oceanbase/oceanbase#840]
问题复现步骤

1、创建测试表：
CREATE TABLE tblist (
    id INT NOT NULL,
    store_id INT
)
PARTITION BY LIST(store_id) (
    PARTITION a VALUES IN (1,5,6),
    PARTITION b VALUES IN (2,7,8),
    PARTITION c VALUES IN (3,9,10),
    PARTITION d VALUES IN (4,11,12)
);

2、模拟测试数据：
insert into tblist
values (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),
(7,7),(8,8),(9,9),(10,10),(11,11),(12,12);

3、在社区版OB（3.1.2版本）
explain select * from tblist where store_id>5 and store_id<8;
扫描所有的分区 partitions(p[0-3])

4、原生MySQL（5.7版本）
explain extended select * from tblist where store_id>5 and store_id<8;
使用到分区裁剪 partitions(p[0-1])

**Comment by longdafeng** [comment]
This bug has been fixed in the 4.0
