### ISSUE TITLE
[Question]: 建议将【软件下载】->【加载更多】功能去掉，直接显示全软件

### ISSUE THREAD

**Issue by ChrisYuan** [oceanbase/oceanbase#842]
### Describe your question

建议将页面：https://open.oceanbase.com/softwareCenter/community 底下的【加载更多】按钮去掉或者设置为更明显状态，本身需要下载的软件就不多，灰色的小字体很容易忽略。

**Comment by longdafeng** [comment]
收到, 谢谢啊
