### ISSUE TITLE
[Question]: 建议将obclient和libobclient两个rpm包合并

### ISSUE THREAD

**Issue by ChrisYuan** [oceanbase/oceanbase#843]
### Describe your question

既然libobclient包属于obclient包的依赖，并无单独功能，建议将两个包合并为一个rpm包，这样使用更顺滑。

**Comment by longdafeng** [comment]
之前没有合, 主要原因是开源协议的问题, libobclient 是lgpl 的协议, obclient 的代码是木兰宽松协议, 一旦合在一起就会被协议污染掉. 

代码是必须分开的, binary 必须分开, 不过rpm 是不是能合, 我们咨询一下法务看看

**Comment by longdafeng** [comment]
https://open.oceanbase.com/ask/detail?id=20400610

**Comment by ChrisYuan** [comment]
好的，如果因为协议问题确实不能合并，我就把该问题关掉，不能因为方便而触犯一些潜在的法律问题
