### ISSUE TITLE
ODC 查询结果数值类型应该右对齐。

### ISSUE THREAD

**Issue by 196619446** [oceanbase/oceanbase#849]
![image](https://user-images.githubusercontent.com/54446046/160342627-2ea3b960-75f4-4a78-995a-54a09cf3032f.png)

**Comment by yizhou-xw** [comment]
感谢反馈，关于不同数据类型的显示格式，我们正在规划专题进行优化，这个建议会包含到需求里

**Comment by yizhou-xw** [comment]
此问题在 ODC 3.4.0 已解决，推荐升级使用 ODC 最新版，当前最新版是 ODC 4.1.2 。
