### ISSUE TITLE
[Question]: 如何获取数据表中最新的数据最新时间？

### ISSUE THREAD

**Issue by FunnyNames** [oceanbase/oceanbase#856]
### Describe your question

该怎么获取数据表中最新的数据更新时间，类似于mysql8的information_schema.table 表中的update_time字段，目前这个版本主要兼容5.7，貌似这个字段只会记录数据表结构的更新时间，最新的写数据的时间没有被记录，是不是某个变量需要设置一下？

**Comment by hnwyllmm** [comment]
看了下 MySQL的文档，[MySQL :: MySQL 5.7 Reference Manual :: 24.3.25 The INFORMATION_SCHEMA TABLES Table](https://dev.mysql.com/doc/refman/5.7/en/information-schema-tables-table.html)

这里说的update_time没有明确的约束，一定是最后的表数据更新时间。并且不同的存储引擎，表现可能还不同。所以即使在MySQL上也不建议使用此字段处理业务。

另外在OB上，这种功能实现起来就很困难了。OB是分布式数据库，每次更新数据时，要把每个表更新的时间，汇总到某个地方，成本还是蛮高的。所以OB不会考虑实现这个功能，最少短期内不会考虑。
