### ISSUE TITLE
[Question]:  mac m1 docker 运行oceanbase/oceanbase-ce:3.1.3 启动失败

### ISSUE THREAD

**Issue by yinhualong** [oceanbase/oceanbase#859]
### Describe your question

平台：mac m1 arm64
容器平台： docker desktop V4.5.0
docker版本：Server Version: 20.10.12  Storage Driver: overlay2
运行镜像：oceanbase/oceanbase-ce standalone-3.1.3
启动命令：docker run -p 2881:2881 --name obstandalone --platform linux/amd64 -e MINI_MODE=1 -d oceanbase/oceanbase-ce:standalone-3.1.3

启动过程中的问题：
启动执行 docker logs obstandalone 有以下信息

generate boot.yaml ...
/root/boot/_boot: line 11: 1: command not found
create boot dirs and deploy ob cluster ...
/root/boot/_boot: line 25: 1: command not found
Package oceanbase-ce-3.1.3 is available.

大概过一到二分钟再执行 docker logs obstandalone  有以下信息

generate boot.yaml ...
/root/boot/_boot: line 11: 1: command not found
create boot dirs and deploy ob cluster ...
/root/boot/_boot: line 25: 1: command not found
Package oceanbase-ce-3.1.3 is available.
install oceanbase-ce-3.1.3 for local ok
Cluster param config check ok
Open ssh connection ok
Generate observer configuration ok
oceanbase-ce-3.1.3 already installed.
+-------------------------------------------------------------------------------------------+
|                                          Packages                                         |
+--------------+---------+-----------------------+------------------------------------------+
| Repository   | Version | Release               | Md5                                      |
+--------------+---------+-----------------------+------------------------------------------+
| oceanbase-ce | 3.1.3   | 10000292022032916.el7 | eab08e5d473bd4884fdf2ac4d7dff6a329b68abe |
+--------------+---------+-----------------------+------------------------------------------+
Repository integrity check ok
Parameter check ok
Open ssh connection ok
Remote oceanbase-ce-3.1.3-eab08e5d473bd4884fdf2ac4d7dff6a329b68abe repository install ok
Remote oceanbase-ce-3.1.3-eab08e5d473bd4884fdf2ac4d7dff6a329b68abe repository lib check ok
Cluster status check ok
Initializes observer work home ok
obcluster deployed
Get local repositories and plugins ok
Open ssh connection ok
Load cluster param plugin ok
Check before start observer ok
[WARN] (127.0.0.1) clog and data use the same disk (/)

Start observer x
[ERROR] OBD-2002: Failed to start 127.0.0.1 observer: /root/ob/bin/observer: error while loading shared libraries: libmariadb.so.3: cannot open shared object file: No such file or directory

[ERROR] oceanbase-ce start failed
See https://open.oceanbase.com/docs/obd-cn/V1.2.0/10000000000017237.

**Comment by caifeizhi** [comment]
Thank you for your feedback. We will reply to you after local reproduction

**Comment by caifeizhi** [comment]
我使用了mac m1 arm64复现了你这个环境的问题，几个问题我描述下原因：

**问题1：**
> generate boot.yaml ...
/root/boot/_boot: line 11: 1: command not found
create boot dirs and deploy ob cluster ...
/root/boot/_boot: line 25: 1: command not found
Package oceanbase-ce-3.1.3 is available.

这个是由于docker镜像里面判断MINI_MODE的shell脚本实现的有缺陷，只能处理MINI_MODE=true这种输入，代码参照：https://github.com/oceanbase/oceanbase/blob/3edc7f7144de711ce23cad3f93f6b71c6f5afc70/tools/docker/standalone/boot/_boot#L11
这个问题我们会在下一次发布docker镜像的时候改掉

**问题2：**
> [ERROR] OBD-2002: Failed to start 127.0.0.1 observer: /root/ob/bin/observer: error while loading shared libraries:

OBD使用ldd来判断哪些依赖库缺失，如果有缺失，才会去下载依赖库 https://github.com/oceanbase/obdeploy/blob/7ac5be6c8f60b678c8fb8fd74c1d41fa8bc91c04/core.py#L668
但是，我在镜像里面执行ldd的时候，发现该命令直接是失效了
[root@0a1f23083714 bin]# ldd observer
ldd: exited with unknown exit code (139)
这个ldd失效，会导致OBD没有自动去下载依赖库

**问题3：**
手动安装依赖库，并指定依赖库路径后，启动observer，仍然有报错：
[2022-04-11 13:47:17.904234] ERROR [CLOG] init (ob_log_file_pool.cpp:120) [2461][0][Y0-0000000000000000] [lt=27] [dc=0] io setup fail(errmsg="Function not implemented") BACKTRACE:0x99bdb8e 0x9792f11 0x22732f4 0x2272ddb 0x2272b41 0x75e1521 0x756305c 0x320ebf8 0x3214d86 0x3212610 0x3210d04 0x3228188 0x3230175 0x88358f1 0x8834618 0x7d09c9a 0x92d3111 0x92c8d87 0x226f945 0x40017e1555 0x226e629
经排查，这个docker镜像依赖的kernel os不支持io

**Comment by yinhualong** [comment]
> 我使用了mac m1 arm64复现了你这个环境的问题，几个问题我描述下原因：
> 
> **问题1：**
> 
> > generate boot.yaml ...
> > /root/boot/_boot: line 11: 1: command not found
> > create boot dirs and deploy ob cluster ...
> > /root/boot/_boot: line 25: 1: command not found
> > Package oceanbase-ce-3.1.3 is available.
> 
> 这个是由于docker镜像里面判断MINI_MODE的shell脚本实现的有缺陷，只能处理MINI_MODE=true这种输入，代码参照：
> 
> https://github.com/oceanbase/oceanbase/blob/3edc7f7144de711ce23cad3f93f6b71c6f5afc70/tools/docker/standalone/boot/_boot#L11
> 
> 
> 这个问题我们会在下一次发布docker镜像的时候改掉
> **问题2：**
> 
> > [ERROR] OBD-2002: Failed to start 127.0.0.1 observer: /root/ob/bin/observer: error while loading shared libraries:
> 
> OBD使用ldd来判断哪些依赖库缺失，如果有缺失，才会去下载依赖库 https://github.com/oceanbase/obdeploy/blob/7ac5be6c8f60b678c8fb8fd74c1d41fa8bc91c04/core.py#L668 但是，我在镜像里面执行ldd的时候，发现该命令直接是失效了
> 
> ```
> [root@0a1f23083714 bin]# ldd observer
> ldd: exited with unknown exit code (139)
> ```
> 
> 这个ldd失效，会导致OBD没有自动去下载依赖库
> 
> **问题3：** 手动安装依赖库，并指定依赖库路径后，启动observer，仍然有报错： [2022-04-11 13:47:17.904234] ERROR [CLOG] init (ob_log_file_pool.cpp:120) [2461][0][Y0-0000000000000000] [lt=27] [dc=0] io setup fail(errmsg="Function not implemented") BACKTRACE:0x99bdb8e 0x9792f11 0x22732f4 0x2272ddb 0x2272b41 0x75e1521 0x756305c 0x320ebf8 0x3214d86 0x3212610 0x3210d04 0x3228188 0x3230175 0x88358f1 0x8834618 0x7d09c9a 0x92d3111 0x92c8d87 0x226f945 0x40017e1555 0x226e629 经排查，这个docker镜像依赖的kernel os不支持io_setup，也有人提过相关的issue，但是似乎现在仍然没有得到解决：[multiarch/qemu-user-static#114](https://github.com/multiarch/qemu-user-static/issues/114) 目前，OB启动依赖该功能，所以启动失败了
> 
> 结论，**目前MAC M1电脑暂时是无法跑OB的**，我们会再接下来的一段时间继续寻求解决方案

收到您的回复，感谢您的解答

**Comment by akaError** [comment]
最新已经支持docker部署
