### ISSUE TITLE
[Bug]: the value of data_dir isn't accuracy

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#876]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```
observer version: V3.1.3

### Fast Reproduce Steps(Required)

dir_data参数值不准确，可以通过
`show variables like '%data_dir%'; `
来查看

### Actual Behavior

显示为/usr/local/mysql/data

### Expected Behavior

显示为ob实际data file使用的目录

### other information

来源：贵州双龙 https://open.oceanbase.com/ask/detail?id=20400117

**Comment by hnwyllmm** [comment]
已修正
