### ISSUE TITLE
The errocode isn't same as the value in the log

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#877]
当前ob做了错误码转换，用户看到的错误码1406和日志中的错误码5167不一致，给用户排查问题带来困难；

代码中返回客户端错误信息时，使用的是LOG_USER_XX。现在的实现是，LOG_USER 会在当前返回客户端的信息中输出一些信息，包括错误码，比如1406，然后再打印一条普通的日志。
可以考虑在普通的日志中输出返回给用户的信息。
当前LOG_USER的实现关键信息如下，其中errcode 是内部错误码(比如 5167)，umsg是根据错误码转换的信息。内外错误码转换使用数组 MYSQL_ERRNO （针对MySQL模式）
#define _LOG_USER_MSG(level, errcode, umsg, args...)                                                        \
  do {                                                                                                      \
    OB_LOGGER.log_user_message(level, errcode, umsg, ##args);                                               \
    (OB_LOGGER.is_async_log_used() ? OB_LOGGER.async_log_message("", OB_LOG_NUM_LEVEL(level), umsg, ##args) \
                                   : OB_LOGGER.log_message("", OB_LOG_NUM_LEVEL(level), umsg, ##args));     \
  } while (0)

**Comment by hnwyllmm** [comment]
已修复。
