### ISSUE TITLE
[Question]: OCP接管OB集群新增凭据无法删除

### ISSUE THREAD

**Issue by sjztbyl** [oceanbase/oceanbase#883]
### Describe your question

版本：ocp-ce-3.1.1-bp1   OceanBase：3.1.3
![image](https://user-images.githubusercontent.com/96521778/164157182-07eff37f-fc95-4683-841f-a8d5a4b714c5.png)

**Comment by askdb** [comment]
https://open.oceanbase.com/docs/ocp-cn/V3.1.1/10000000000012766

`**删除连接凭据**
在 OCP 系统界面的右上角，单击当前登录用户名，选择 密码箱 。

进入 密码箱 页面。

出于安全考虑，页面上的密码均显示为 *** 。

在 主机 页签中找到要修改的连接对象。

单击该对象 操作 列的 删除 。

系统弹出删除确认的对话框。

单击 删除 。

说明

删除凭证后将不可访问该主机，请谨慎操作。`

**Comment by chris-sun-star** [comment]
直接在任务页面来删除密码箱的记录不是很安全，这里只展示了凭证的名字，其他信息也不是很完全，有可能误删其他凭证记录，造成一些主机无法访问，所以还是要在密码箱的页面来进行操作
