### ISSUE TITLE
[Bug]: 不能通过information_schema.columns表查找到视图的列信息

### ISSUE THREAD

**Issue by wg2049** [oceanbase/oceanbase#885]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
root_(none)_2883> select @@version;
+--------------------+
| @@version          |
+--------------------+
| 3.1.2-OceanBase CE |
+--------------------+
1 row in set (0.01 se
```

### Fast Reproduce Steps(Required)

create  view test.v_t1 as select c1,c3 from test.t1;

select table_schema,table_name,column_name from information_schema.columns where table_schema='test' and table_name='v_t1';

### Actual Behavior

![图片](https://user-images.githubusercontent.com/24307595/164419089-68287038-7d39-40b2-8d5c-8690767fa212.png)

**Comment by hnwyllmm** [comment]
当前版本下实现此功能会带来一些无法控制的场景，所以当前不考虑修复此问题。
不过，会考虑在下一个大版本迭代上在底层解决掉这种问题。
我先把issue 关闭，如果还有其它想法，欢迎随时重新打开。
