### ISSUE TITLE
[使用 Docker 部署 OceanBase 数据库]章节最后的【运行 sysbench 脚本】命令报错

### ISSUE THREAD

**Issue by ChrisYuan** [oceanbase/oceanbase#886]
**文档链接：**

[2.quick-start](https://github.com/oceanbase/oceanbase-doc/tree/V3.1.3/zh-CN/2.quick-start)
2.use-docker-to-deploy-oceanbase-database.md

**报错信息：**

$ docker exec -it obstandalone sysbench cleanup
sysbench 1.0.20 (using bundled LuaJIT 2.1.0-beta2)

FATAL: Cannot find benchmark 'cleanup': no such built-in test, file or module

$ docker exec -it obstandalone sysbench prepare
sysbench 1.0.20 (using bundled LuaJIT 2.1.0-beta2)

FATAL: Cannot find benchmark 'prepare': no such built-in test, file or module

$ docker exec -it obstandalone sysbench run
sysbench 1.0.20 (using bundled LuaJIT 2.1.0-beta2)

FATAL: Cannot find benchmark 'run': no such built-in test, file or module

**Comment by hnwyllmm** [comment]
please try it again with use latest docker image.
I'll close the issue but feel free to reopen it if anything is wrong.
