### ISSUE TITLE
[Question]: 求问有ob_admin的编译文档吗

### ISSUE THREAD

**Issue by stupidstan** [oceanbase/oceanbase#892]
### Describe your question

如题，想使用这个工具，但是比较缺失资料，感谢

**Comment by whhe** [comment]
正常直接运行 `make ob_admin` 应该就可以编出来

https://open.oceanbase.com/docs/observer-cn/V3.1.3/0000000000162070

**Comment by longdafeng** [comment]
下次可以在开源官网搜索 ob_admin 即可找到答案
