### ISSUE TITLE
ocp部署集群时的密码规则校验逻辑

### ISSUE THREAD

**Issue by marcelyz** [oceanbase/oceanbase#893]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marcelyz** [comment]
请教下，如果我想设置一个不符合它规则的密码， 这个密码校验规则可以关掉吗？或者我在命令行那修改掉密码，会对ocp有影响吗？
![image](https://user-images.githubusercontent.com/22769274/166877419-2774b606-a4ca-40f6-a493-d248f4ead2e0.png)

**Comment by chris-sun-star** [comment]
现在是关不掉的，如果创建之后，修改了root用户密码，会有影响，如果是一般用户的密码应该没有影响

**Comment by marcelyz** [comment]
> 

您好，也就是说，我在命令行修改非root用户的密码， 对ocp是没有影响的是吧

**Comment by chris-sun-star** [comment]
是的，租户下的普通用户密码是没有影响的
