### ISSUE TITLE
[Bug]: 在大量insert into时，表结构中字段允许为Null且有默认值的时候，不能命中执行计划缓存

### ISSUE THREAD

**Issue by TobyYaochen** [oceanbase/oceanbase#897]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
observer V3.1.2
- Hardware parameter:OS type & Compliler & CPU etc. 
OS type:linux CPU:40c Memory 256G
- Others
```

### Fast Reproduce Steps(Required)

TPS 7000/s，
单条insert行为，insert into table1(c1,c2....)value(1,2......)
表结构：
CREATE TABLE `table1` (
  `c1` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `c2` varchar(20) DEFAULT '' COMMENT '',
  `c3` varchar(20) DEFAULT '' COMMENT '',
  `c4` bigint(20) DEFAULT '0' COMMENT ''
  PRIMARY KEY (`c1`),
  KEY `idx_c2` (`c2`) BLOCK_SIZE 16384 local,
  KEY `idx_c4_c3` (`c4`, `c3`) BLOCK_SIZE 16384 local
) AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 ROW_FORMAT = COMPACT COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 3 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0 COMMENT = '测试用表'
 partition by hash(c1) partitions 128;

### Actual Behavior

gv$sql_audit中发现执行时间达到30多ms
select trace_id,ELAPSED_TIME,is_hit_plan from gv$sql_audit where tenant_id = 1001 and db_name = 'testdb' and ELAPSED_TIME>20000 and usec_to_time(REQUEST_TIME) >= '2022-05-06 17:00:00' and query_sql like '%insert into%' order by ELAPSED_TIME desc limit 10

+-------------------------------+--------------+-------------+
| trace_id                      | ELAPSED_TIME | is_hit_plan |
+-------------------------------+--------------+-------------+
| YB420A3AE9D1-0005DE40EDCB3CB4 |        39936 |           0 |
| YB420A6DCC79-0005DE40665F8077 |        39677 |           0 |
| YB420A6DCC79-0005DE40635CD13D |        39546 |           0 |
| YB420A6DCC79-0005DE407304E47C |        39319 |           0 |
| YB420A6DCC79-0005DE40753693E1 |        39142 |           0 |
| YB420A6DCC79-0005DE406BB84898 |        38703 |           0 |
| YB420A3AE9D1-0005DE40CB9BBDCD |        38289 |           0 |
| YB420A6DCC79-0005DE405F6FC1A4 |        38258 |           0 |
| YB420A6DCC79-0005DE4076E663E2 |        38212 |           0 |
| YB420A6DCC79-0005DE4075369D65 |        38001 |           0 |
+-------------------------------+--------------+-------------+

observer.log中有相关报错：
[2022-05-06 17:46:17.270502] WARN  [SQL.ENG] assign (ob_expr_frame_info.cpp:137) [208534][2014][YB420A3AE9D1-0005DE40EDCB3CB4] [lt=13] [dc=0] length is null and ptr not null(ret=-4002, *other_expr_datum={len: 0, ptr: 0x7f860e4e1846})

**Comment by akaError** [comment]
already fix this bug
