### ISSUE TITLE
How to deploy OceanBase on Macos by docker

### ISSUE THREAD

**Issue by zhouxiangxiang** [oceanbase/oceanbase#90]
How to compile, deploy, debug OceanBase on Macos

**Comment by LINxiansheng** [comment]
Now a good way is to build a centos7 image on the mac.
How to install immediately on the mac are on the way.

**Comment by watchpoints** [comment]
docker

**Comment by longdafeng** [comment]
Doesn't support build OceanBase on Mac

But you can deploy oceanbase on Mac by docker. 

@LINxiansheng  Could you please help to write one ducument to show how to deploy oceanbase docker on Mac

**Comment by LINxiansheng** [comment]
The OceanBase docker image was finished and it must go through some checks before uploading to the docker hub.
If you want to run the OceanBase on Mac now maybe you can run it on a Centos7 image.
Refer it : https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/deploy-an-oceanbase-database-by-using-docker

**Comment by LINxiansheng** [comment]
Please refer it:
https://hub.docker.com/r/oceanbase/obce-mini
