### ISSUE TITLE
[Question]: 社区版文档中关于租户级别参数不准确

### ISSUE THREAD

**Issue by TobyYaochen** [oceanbase/oceanbase#900]
### Describe your question

在查看社区版oceanbase的帮助文档时发现，关于租户级别的参数，在社区版的oceanbase中不适用或者找不到。
社区版文档连接：
https://open.oceanbase.com/docs/observer-cn/V3.1.2/0000000000194593

报错结果：
MySQL [oceanbase]> ALTER SYSTEM SET enable_clog_persistence_compress=True;
ERROR 5099 (42000): System config unknown

_flush_clog_aggregation_buffer_timeout 这个参数找不到
MySQL [oceanbase]> show parameters like '_flush_clog_aggregation_buffer_timeout';
Empty set (0.011 sec)

**Comment by askdb** [comment]
> ### Describe your question
> 在查看社区版oceanbase的帮助文档时发现，关于租户级别的参数，在社区版的oceanbase中不适用或者找不到。 社区版文档连接： https://open.oceanbase.com/docs/observer-cn/V3.1.2/10000000000014524
> 
> 报错结果： MySQL [oceanbase]> ALTER SYSTEM SET enable_clog_persistence_compress=True; ERROR 5099 (42000): System config unknown
> 
> _flush_clog_aggregation_buffer_timeout 这个参数找不到 MySQL [oceanbase]> show parameters like '_flush_clog_aggregation_buffer_timeout'; Empty set (0.011 sec)

目前 enable_clog_persistence_compress 没有在社区版OB上开放这个参数。
_flush_clog_aggregation_buffer_timeout  以下划线开头的参数属于隐藏的参数，使用show parameters查看不到，可以使用如下的sql进行查看：
select * from __all_virtual_sys_parameter_stat where name='_flush_clog_aggregation_buffer_timeout';

**Comment by caifeizhi** [comment]
我补充一下：
1. 第一个问题实际上我们文档和代码没有完全对上，这个我们会集中梳理一下系统变量、配置项这部分文档；
2. 隐藏配置项不能直接show出来，是符合OB的设计的，目前主要的问题是有部分”隐藏配置项“不应该被隐藏，比如在文档中性能调优部分的配置项理论上都应该是”非隐藏“的，这个我们后续也需要集中梳理一遍；

**Comment by TobyYaochen** [comment]
多谢，后续希望社区文档更加完善。
