### ISSUE TITLE
[Bug]: sql语句中'--'注释无法识别

### ISSUE THREAD

**Issue by nmj1992** [oceanbase/oceanbase#905]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

![lQLPDhtoesTYhUTNAXjNBCewPbI5hcBPEKUCe9o_BIADAA_1063_376](https://user-images.githubusercontent.com/28852549/167420996-4087734a-3037-4951-9a2e-8d19dea78cb6.png)

注释'--'，依然被识别为sql语句的一部分执行，导致报错

### Actual Behavior

![lQLPDhtoesTYhUTNAXjNBCewPbI5hcBPEKUCe9o_BIADAA_1063_376](https://user-images.githubusercontent.com/28852549/167421033-22d09079-5a75-4c4a-848d-972dc89d4bf7.png)

**Comment by longdafeng** [comment]
大概率是你的客户端链接 问题. 

https://open.oceanbase.com/docs/observer-cn/V3.1.2/10000000000015882
<img width="504" alt="image" src="https://user-images.githubusercontent.com/374091/167563581-9b80c2bd-5533-4b8e-8e4e-6d71aac93229.png">


注释是一个高频使用场景, 应该是不会有问题, https://open.oceanbase.com/docs/observer-cn/V3.1.3/10000000000096777

**Comment by akaError** [comment]
'--,c_status',in mysql mode '--' need one more space differ with '#', use '-- ,c_status'

**Comment by nmj1992** [comment]
> '--,c_status',in mysql mode '--' need one more space differ with '#', use '-- ,c_status'

正解- -我漏了空格，，，，习惯了使用oracle，不需要空格
