### ISSUE TITLE
odc独立session模式，增加session状态标识

### ISSUE THREAD

**Issue by nmj1992** [oceanbase/oceanbase#914]
3.3版本的ODC，新增加了独立session功能，建议增加一个session活动标识；

假设我同时打开A、B两个窗口，B窗口是一个长达30分钟的olap任务，回到A-sql窗口进行开发的时候，B窗口还在运行中，可以添加一个标识，清晰的看到B窗口的session状态，query还是sleep状态；

![image](https://user-images.githubusercontent.com/28852549/167675640-32d0f4c7-f93d-409d-8792-c49190ca106a.png)

**Comment by yizhou-xw** [comment]
hello @nmj1992 , thanks so much for suggestion, we will evaluate at next version.

**Comment by yizhou-xw** [comment]
最新版 ODC 已支持 session 状态标识，效果如下图所示：

![image](https://user-images.githubusercontent.com/54161870/231415646-0d5ae094-2320-48c5-8047-720d29d1b42e.png)
