### ISSUE TITLE
[Bug]: v$ob_all_clusters 引用了不存的表

### ISSUE THREAD

**Issue by liuqian1990** [oceanbase/oceanbase#915]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
MySQL [oceanbase]> select version();
+--------------------+
| version()          |
+--------------------+
| 3.1.3-OceanBase CE |
+--------------------+
1 row in set (0.00 sec)
```

### Fast Reproduce Steps(Required)

`MySQL [oceanbase]> select * from v$ob_all_clusters\G`

### Actual Behavior

`ERROR 1356 (42S22): View 'oceanbase.v$ob_all_clusters' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them`

### Expected Behavior

得出正常值

### other information

`SHOW CREATE TABLE v$ob_all_clusters;`
`CREATE VIEW `v$ob_all_clusters` AS        SELECT cluster_id,              cluster_name,              cluster_role,              cluster_status,              rootservice_list,              redo_transport_options       FROM oceanbase.__all_virtual_all_clusters`
`MySQL [oceanbase]> select * from oceanbase.__all_virtual_all_clusters;
ERROR 1146 (42S02): Table 'oceanbase.__all_virtual_all_clusters' doesn't exist`

**Comment by caifeizhi** [comment]
这个确实是个bug，v$ob_all_clusters依赖的__all_virtual_all_clusters；
目前，代码中，后者删除了，前者未删除；

**Comment by a1iive** [comment]
v$ob_all_clusters abandoned on 4.0
