### ISSUE TITLE
memory 1G building is Killed

### ISSUE THREAD

**Issue by watchpoints** [oceanbase/oceanbase#92]
**Describe the bug (must be provided)**
```
get-the-oceanbase-database-by-using-source-code
make  -j4  observer
[ 59%] Linking CXX static library liboblib.a [ 59%] Built target oblib  Consolidate compiler generated dependencies of target ob_share [ 59%] Building CXX object src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_partition_table/0_cxx.cxx.o make[3]: 
[src/share/CMakeFiles/ob_share.dir/build.make:110: src/share/CMakeFiles/ob_share.dir/Unity/unity_ob_share_partition_table/0_cxx.cxx.o] Killed  

```
**Your Environments (must be provided)**
- mac
- Docker:
- Mem:1g
- cpu:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian

**How To Reproduce(must be provided)**
https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code

**Expected behavior**
 build   success

**Comment by simonjoylet** [comment]
for a better building experience, the machine for building OceanBase requires at least 16GB memory and 4 physical core.
see: https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code
the actual memory used can be estimated like: parallel * 2G, which means that at least 2GB memory is required for each compile thread.

**Comment by watchpoints** [comment]
dmesg:
```
[  190.823177] Out of memory: Killed process 2991 (clang++) total-vm:2494472kB, anon-rss:1559356kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:4736kB oom_score_adj:0
[  190.959066] oom_reaper: reaped process 2991 (clang+
```

**Comment by watchpoints** [comment]
> dmesg:
> 
> ```
> [  190.823177] Out of memory: Killed process 2991 (clang++) total-vm:2494472kB, anon-rss:1559356kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:4736kB oom_score_adj:0
> [  190.959066] oom_reaper: reaped process 2991 (clang+
> ```

普通电脑根本没有这样配置呀！

**Comment by watchpoints** [comment]
> for a better building experience, the machine for building OceanBase requires at least 16GB memory and 4 physical core.
> see: https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.0/get-the-oceanbase-database-by-using-source-code
> 
> > 最低硬件规格：
> > CPU：4C8T Intel(R) Core i7-4770HQ @ 2.20GHz
> > 内存：16GB 1600MHz DDR3
> > 存储：空闲容量大于 50G 的机械硬盘
> 
> the actual memory used can be estimated like: parallel * 2G, which means that at least 2GB memory is required for each compile thread.

普通电脑根本没有这样配置，上面建议 应该生产环境，非普通开发环境吧。我在寻找最低配置。

**Comment by simonjoylet** [comment]
if your memory is limited, try swap(virtual memory).

**Comment by hnwyllmm** [comment]
if your memory is limited, use the -j2 instead of -j4.
lower the concurrency

**Comment by watchpoints** [comment]
> 
> if your memory is limited, use the -j2 instead of -j4.
> lower the concurrency

Same error

**Comment by watchpoints** [comment]
fixed , memory  requires 3g
