### ISSUE TITLE
[Bug]: 二级分区表清理和删除报错not supported，与文档描述不一致。已在文档中提交pull requests

### ISSUE THREAD

**Issue by zhangjig** [oceanbase/oceanbase#924]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
3.1.3-ce-bp
```

### Fast Reproduce Steps(Required)

1. 建表
CREATE TABLE t_range_range (c1 int, c2 int, c3 int) partition BY range(c1)
subpartition BY range (c2)
subpartition template
(
subpartition rp1 VALUES less than (100),
subpartition rp2 VALUES less than (200),
subpartition rp3 VALUES less than (300)
)
(
partition p0 VALUES less than (100),
partition p1 VALUES less than (200),
partition p2 VALUES less than (300)
);

2. 执行清理二级分区
 ALTER TABLE t_range_range  TRUNCATE SUBPARTITION rp1;

3.执行删除二级分区
ALTER TABLE t_range_range  DROP SUBPARTITION p1;

### Actual Behavior

2和3都执行报错
![739wkqh292ibnpnb0mcugmmn4_0](https://user-images.githubusercontent.com/37869031/168290864-439f4229-f57c-4bb9-91d2-79017c8c1006.jpg)

### Expected Behavior

2和3都执行成功

**Comment by akaError** [comment]
thanks for ur contribution!
