### ISSUE TITLE
better method to view the process of sql 

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/oceanbase#926]
**Is your feature request related to a problem? Please describe.**
当前OB提供了一个非常方便查看SQL执行过程的方法，大概步骤是这样的：
```sql
set ob_enable_trace_log='on';
do something
show trace;
```
但是这么做还是挺麻烦的，可以提供更简单的方式吗？比如：
```sql
trace do something
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by a1iive** [comment]
we have supported `SELECT /*+trace_log=on*/c1 FROM t1 LIMIT 2;`
ref:https://www.oceanbase.com/docs/community-observer-cn-10000000000901823
