### ISSUE TITLE
[Bug]: OceanBase MySQL模式不支持没有主键的表，修改表时增加主键

### ISSUE THREAD

**Issue by YUFEIFUT** [oceanbase/oceanbase#930]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

1. 创建一张没有主键的表，如下：
![image](https://user-images.githubusercontent.com/55017929/168742462-acdb9439-dad6-443c-af47-c19477f0420d.png)

2. 修改表，为它添加主键
![image](https://user-images.githubusercontent.com/55017929/168742528-37ef9e42-2914-46e1-99c1-5c07630c56f0.png)

3. 然后出现如下错误
![image](https://user-images.githubusercontent.com/55017929/168742240-7b1e810f-956a-4a90-a01c-d3024df940dc.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/55017929/168742095-7fc16c7e-0895-47c0-b7b3-b532e4fa8d3e.png)

### Expected Behavior

期待支持这个语法

**Comment by YoungYang0820** [comment]
We are going to support this feature soon

**Comment by YUFEIFUT** [comment]
Thank you a lot

**Comment by YUFEIFUT** [comment]
well done
