### ISSUE TITLE
[Bug]: Oracle模式下，使用Mybatis的情况下，设置useGeneratedKeys参数值为true，在执行添加记录之后获取不到数据库自动生成的主键ID

### ISSUE THREAD

**Issue by YUFEIFUT** [oceanbase/oceanbase#931]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

1. 建一张表【Oracle模式下】
![image](https://user-images.githubusercontent.com/55017929/168750632-9a58d647-b524-463d-9147-70a651d46a57.png)

2. 为当前表创建序列
![image](https://user-images.githubusercontent.com/55017929/168750813-81f6594a-36c5-4c65-b1ce-e72825302166.png)

3. 创建触发器，在执行前的
![image](https://user-images.githubusercontent.com/55017929/168750977-04dfaea8-ac2c-4c67-8787-710df309aaf2.png)

4. 创建 Java 实体类
![image](https://user-images.githubusercontent.com/55017929/168751234-9d032019-324c-45da-a77d-5b62c5389201.png)

5. 定义 Java Mapper 文件
![image](https://user-images.githubusercontent.com/55017929/168751541-73e9a67c-71f1-4d43-ad14-fec45a2063af.png)

6. SQL Mapper
![image](https://user-images.githubusercontent.com/55017929/168751690-043e6ee6-45a3-4461-b84f-bed296dad843.png)

7. 调用
![image](https://user-images.githubusercontent.com/55017929/168751780-38e9c4fb-64dd-454b-85a0-e728f8a7b099.png)

8. 调用输出
![image](https://user-images.githubusercontent.com/55017929/168752008-9f83081f-df75-407f-82c7-70c6c06635f5.png)

9. 结论
    OceanBase没有返回自动生成的主键，这种方式在Oracle中是可以返回这个主键的

### Actual Behavior

referring 《Fast Reproduce Steps(Required)》

### Expected Behavior

期望 OceanBase For Oracle 能够做到【对于支持自动生成记录主键的数据库，如：MySQL，SQL Server，此时设置useGeneratedKeys参数值为true，在执行添加记录之后可以获取到数据库自动生成的主键ID】

**Comment by codeworkerlize** [comment]
使用的jdbc和observer的版本是多少？

**Comment by YUFEIFUT** [comment]
jdbc：oceanbase-client-1.1.7.jar 以及 oceanbase-client-1.1.10.jar 两个都试过，都有这个问题
OceanBase For Oracle版本：3.1.2_20211

**Comment by codeworkerlize** [comment]
oracle数据库 并不支持issues上描述的设置useGeneratedKeys="true" ，oracle数据库本身不支持的，我们OB也是一样。如果非要使用oracle模式下序列+触发器 做主键自增，必须设置useGeneratedKeys="false"。

**Comment by YUFEIFUT** [comment]
好的，了解了，我这边使用其他的方法解决了哈
