### ISSUE TITLE
support load data local 

### ISSUE THREAD

**Issue by nmj1992** [oceanbase/oceanbase#941]
当前load data语句，不支持本地文件模式，需要用户先将文件传输至observer服务器后，才能使用load data语句～

这导致这个功能对于数据开发有一定鸡肋。绝大多数公司，DBA人员和数据开发人员，不同角色设置了不同的人，通常登陆数据库服务器权限掌握在DBA那里～而load data 会是开发人员的高频使用场景，只需要通过obclient 或是mysql客户端远程登录ob使用～在这种背景下，使用load data不支持local模式，会比较困难～

Obloader 实际上是命令行导数功能，和load data 的使用场景还是有一定差异，而且，更偏向于DBA使用～

**Comment by caifeizhi** [comment]
谢谢 @nmj1992 提的建议，需求我们收到了；这里是否能补充一下，从用户视角使用obloader和LOAD DATA LOCAL的区别，方便我们更好的评估这个需求

**Comment by nmj1992** [comment]
obloader：需进入linux命令行界面进行操作，并且obloader命令所需要管理的参数太多了；集群、租户信息等等~
load data local：在sql控制台写语句即可，理论上甚至可以在本地的odc写语句将数据导入；无需再额外输入账户密码等信息；代码简易程度远小于obloader；
实际例子：业务分析师，OLAP场景，维护了一个本地数据集；在分析时，自己写了一个sql的代码逻辑，每次改完本地数据；可以把load data local作为一大个脚本里的一段，进行跑批处理~

**Comment by caifeizhi** [comment]
收到建议，非常感谢，我们会评估一下

**Comment by longdafeng** [comment]
We are going to support this feature in the next version 3.1.5.  

Right now, we start to design the implementation.

**Comment by yizhou-xw** [comment]
It seems should assign to obclient ?
mysql jdbc support load data already, for security reason, ODC disable this feature by set jdbcUrl parameter `allowLoadLocalInfile=false`.

**Comment by hnwyllmm** [comment]
supported by 4d4732b7c73a6c110c60756eec97909a10c23817
