### ISSUE TITLE
[Feature]Tag the user in OCP user management page. 

### ISSUE THREAD

**Issue by nmj1992** [oceanbase/oceanbase#942]
建议增加一个用户信息或是备注之类的字段～
数据库用户较多的情况下，可以通过这个信息标注每个用户的作用～通常这种这种信息，现在大家都是备注记在自己本地excel……

**Comment by chris-sun-star** [comment]
👍
好的，这个建议会带给OCP产品团队

**Comment by longdafeng** [comment]
After discussion with the RD, it is hard to implement this function. 
It is hard add extra information on the current user's schema in the database. 

Cancel this requirement.
