### ISSUE TITLE
[Bug]: django fail to connection to OceanBase, please support variable of "storage_engine"

### ISSUE THREAD

**Issue by fox1987** [oceanbase/oceanbase#952]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others



Observe版本：oceanbase-3.2.2-20220221213651.el7.x86_64
```

### Fast Reproduce Steps(Required)

python3.9.6
django框架3.2.7

使用python连接ob的mysql模式报这个错。OperationalError at xxx
(1193, "Unknown system variable 'storage_engine'")

### Actual Behavior

OperationalError at xxx
(1193, "Unknown system variable 'storage_engine'")
应该是OB不支持这个系统变量

### Expected Behavior

连接Mysql是没问题的

**Comment by caifeizhi** [comment]
多谢反馈，我们会评估下如何更好的支持这种场景

**Comment by caifeizhi** [comment]
我简单看了一下，这个报错是因为ob没有支持storage_engine这个系统变量，因为ob现在没有可插拔的存储引擎；我们可以考虑从语法上兼容这个系统变量，不过我们可能还得继续评估一下，django对这个变量的返回值有没有特殊依赖，比如会不会因为返回“innodb”就执行一些特殊的查询语句；

**Comment by caifeizhi** [comment]
[        if self._mysql_storage_engine != "InnoDB":](https://github.com/django/django/blob/6f73eb9d90cfec684529aab48d517e3d6449ba8c/django/db/backends/mysql/features.py#L337)
这里依赖值一定是InnoDB

https://github.com/django/django/blob/6f73eb9d90cfec684529aab48d517e3d6449ba8c/django/db/backends/mysql/features.py#L309
这里依赖值不是MyISAM就行

**Comment by LINxiansheng** [comment]
Fix the issue，please refer 9cc87d83437ed09bc19737d9f01d48848324b7ab
