### ISSUE TITLE
Create Table in "oceanbase" database

### ISSUE THREAD

**Issue by liuqian1990** [oceanbase/oceanbase#953]
### Describe your question

`
MySQL [mysql]> use oceanbase;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [oceanbase]> create table test (a int);
Query OK, 0 rows affected (0.05 sec)

MySQL [oceanbase]> drop table test;
Query OK, 0 rows affected (0.02 sec)

`

**Comment by caifeizhi** [comment]
We don't forbid creating database in “oceanbase” database. Do you think we should?
