### ISSUE TITLE
How to fetch slow query?

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#957]
Checking slow query is one of the most import job of DBA, OCP should provide the feature show the slow queries and top queries.

@chris-sun-star  when the feature is ready?

**Comment by chris-sun-star** [comment]
OCP already has this feature
Top SQL displays sqls sorting by specific order
Slow SQL displays sqls which elapsed time exceeds the threshold
![Screenshot 2022-06-07 at 14 34 07](https://user-images.githubusercontent.com/85611200/172312014-6fb15dc6-96c0-43b8-b28f-a2b87ebfb82d.png)
