### ISSUE TITLE
[feature] Support suspend backup process. 

### ISSUE THREAD

**Issue by yzsntdkj** [oceanbase/oceanbase#958]
### Describe your question

增量备份进程偶尔会卡住(kill无效)，导致后续无法创建索引，目前临时解决办法是
1>将*.*.*.*从ob集群中delete，让rootservice做下转移(影响业务[leader分区会强制转移])
2>将*.*.*.*上的ob服务stop+start，释放掉is_cancel=1的无用任务。
3>kill掉备份卡死的任务，让ob内部自动置失败。

ob是否有好的办法， 在不影响业务情况下，通过命令行将备份任务中止掉，或增加备份超时设置，自动中止。

问题描述：
1>3.1.2-ce集群下发现有些表，创建索引很快，但有些表建索引时会卡住，长时间无法结束。

2>排查正在执行的任务，发现备份任务连续2天未结束 ,想取消(alter system cancle backup)，但没有用。

尝试拿官文档上的命令"ALTER SYSTEM CANCEL ALL BACKUP FORCE"来取消备份任务，但是报语法错误。

3>查看当前有哪些任务在执行,发现group分区合并异常(is_cancel=1)，备份和分区合并任务冲突，备份长时间无法结束。
select * from __all_virtual_sys_task_status order by start_time asc limit 2\G;
*************************** 1. row ***************************
start_time: 2022-04-05 00:09:10.343103
 task_type: group partition migration
   task_id: YB420A6DC918-0005DA37971F5FE0  --合并
    svr_ip:*.*.*.*
  svr_port: 2882
 tenant_id: 1001
   comment: group partition migration executor: group_task_id=YB420A6DC918-0005DA37971F5FE0 partition_count=953 partition_id=27 key={tid:1100611139456982, partition_id:27, part_cnt:0}, op_type=BACKUP_REPLICA_OP, src="*.*.*.*:2882", dest="*.*.*.*:2882",
 is_cancel: 1
*************************** 2. row ***************************
start_time: 2022-04-05 00:11:38.670154
 task_type: partition backup task
   task_id: YB420A3C2C7C-0005DA45B91FF580  --备份
    svr_ip: 10.60.44.124
  svr_port: 2882
 tenant_id: 1001
   comment: single partition migration: group_task_id=YB420A6DC918-0005DA37971F5FE0 key={tid:1100611139457294, partition_id:18, part_cnt:0}, op_type=BACKUP_REPLICA_OP, src="*.*.*.*:2882", dest="*.*.*.*:2882",dest_memstore_percent=100
 is_cancel: 0
4>采用临时方案，等备份进程中止
5>再次添加索引，可以正常添加。

**Comment by JLY2015** [comment]
hi，你好，感谢反馈问题，关于停止增量备份，以及增量备份无法停止的问题排查，您可以参考下面描述步骤：
1. 执行alter system cancel backup 或 ALTER SYSTEM CANCEL ALL BACKUP FORCE 停止备份
2. 查看任务是否已经停止：SELECT * FROM CDB_OB_BACKUP_PROGRESS，如果STATUS=COMPLETED则表示已经停止，如果STATUS=RUNNING，则表明任务未停止，如果备份任务还处在running状态，执行如下：
	1. 查看当前的任务：select * from __all_virtual_sys_task_status
	2. 停止任务：alter system cancel task XXX，其中XXX为上述 select * from __all_virtual_sys_task_status中的group_task_id
	3. 查看status，如果依然STATUS=RUNNING，则查看虚拟表中is_cancel=1且op_type=BACKUP_REPLICA_OP的dest字段所示的机器上搜索日志
	4. 查看关于备份打印：grep "ob_partition_backup" observer.log.*
￼
另外从您的描述上看，您使用的是3.1.2-ce版本，改版本的增量备份存在部分bug，在3.1.3版本上已经修复，如有必要欢迎体验新版本。
如上

**Comment by longdafeng** [comment]
After discussion with @yzsntdkj , I think the real reqirement is supporting suspend the backup process.
