### ISSUE TITLE
OMS CE: kafka or rocketmq data source links are invalid, please help supplement the documentation，thanks a lot！

### ISSUE THREAD

**Issue by zetatez** [oceanbase/oceanbase#967]
**Is your feature request related to a problem? Please describe.**

OMS： https://open.oceanbase.com/docs/oms-cn/V3.3.0/10000000000237914

The following two links are invalid:
  - https://open.oceanbase.com/docs/oms-cn/V3.3.0/data-synchronization/2.create-a-synchronization-channel/create-a-data-synchronization-link-from-oceanbase-to-Kafka.md
  - https://open.oceanbase.com/docs/oms-cn/V3.3.0/data-synchronization/2.create-a-synchronization-channel/create-a-data-synchronization-link-from-oceanbase-to-rocketmq.md

**Describe the solution you'd like**
Please help supplement the documentation，thanks a lot！

**Comment by whhe** [comment]
You can click the `edit` button on the webpage and modify these links directly. The two refs in the repo should be:
- https://github.com/oceanbase/oms-doc/blob/V3.3.0/zh-CN/3.user-guide/3.data-synchronization/3.create-a-synchronization-project/1.create-a-sync-project-from-oceanbase-to-Kafka.md
- https://github.com/oceanbase/oms-doc/blob/V3.3.0/zh-CN/3.user-guide/3.data-synchronization/3.create-a-synchronization-project/2.create-a-sync-project-from-oceanbase-to-rocketmq.md

**Comment by zetatez** [comment]
I am the user. I mean, the add kafka or rocketmq data source sections are missing documents.

**Comment by whhe** [comment]
> I am the user. I mean, the add kafka or rocketmq data source sections are missing documents.

What I'm trying to say is that anyone who finds a problem with the docs can fix it directly, it's the most efficient way to deal with doc issues. Of course, If you don't have time to do this, we can fix it later.

**Comment by zetatez** [comment]
> > I am the user. I mean, the add kafka or rocketmq data source sections are missing documents.
> 
> What I'm trying to say is that anyone who finds a problem with the docs can fix it directly, it's the most efficient way to deal with doc issues. Of course, If you don't have time to do this, we can fix it later.

**Comment by zetatez** [comment]
> > I am the user. I mean, the add kafka or rocketmq data source sections are missing documents.
> 
> What I'm trying to say is that anyone who finds a problem with the docs can fix it directly, it's the most efficient way to deal with doc issues. Of course, If you don't have time to do this, we can fix it later.

Thanks! The problem is I do't know how, so I asked for it.
