### ISSUE TITLE
[Feature] Provide one method to find out the hot partition.

### ISSUE THREAD

**Issue by TyphoonTai** [oceanbase/oceanbase#971]
读写热点始终是数据库的一个核心问题，分布式数据库中的热点读写容易导致其中单台server的性能抖动。希望能增加一个功能来帮助判断一个时间段内哪些partition是热点parititon，可能有点类似于tidb中判断hot region的TIDB_HOT_REGIONS表。原有的oceanbase中的gv$partition_audit视图只记录了partition的读写操作数量，而且是全局性质的，并不好帮助线上排障。

**Comment by raywill** [comment]
this is a feature good to have，we should think about it

**Comment by longdafeng** [comment]
Thanks for your feedback, we will support this function in the 3.1.5.

**Comment by hnwyllmm** [comment]
DONE
