### ISSUE TITLE
[Feature]Please support the function of modify after or change the column sequence.  

### ISSUE THREAD

**Issue by Liuhw-1025** [oceanbase/oceanbase#974]
我们在使用中发现，通过navicat直接修改一个默认为null的int类型fdz字段，修改为默认为0。
<img width="932" alt="image" src="https://user-images.githubusercontent.com/19581484/175490188-252c941d-5a16-4105-b95c-e91f30521d0f.png">
通过查看日志提示为[2022-06-24 13:19:03.501862] WARN  [SQL] stmt_query (ob_sql.cpp:171) [21616][1208][YB427F000001-0005E1F1854B6179] [lt=10] [dc=0] fail to handle text query(stmt=ALTER TABLE `wcnkafa`.`gj` 
MODIFY COLUMN `fdz` int(1) NULL DEFAULT 0 AFTER `codeOrName`, ret=-4007)
与老师沟通反馈后，希望完善功能，感谢支持。

**Comment by askdb** [comment]
在OB4.x 上会支持修改列属性的时候可以调整列的位置顺序，
如果我们没有修改列位置顺序的情况，可以考虑先在sql命令行中完成表结构的ddl变更。

**Comment by caifeizhi** [comment]
partial supported in 4.0 version (Only syntax support, does not actually change the column order)

**Comment by hnwyllmm** [comment]
DONE
