### ISSUE TITLE
Optimize one piece of SQL Engine regex code 

### ISSUE THREAD

**Issue by wzzz** [oceanbase/oceanbase#976]
https://github.com/oceanbase/oceanbase/blob/e44cddde95b13f52ff4a24763e2df74e54d77400/src/sql/engine/expr/ob_expr_regexp_context.cpp#L853

**Comment by caifeizhi** [comment]
这部分代码确实有一定冗余，可以进行代码的优化。你是否有兴趣改一下？

**Comment by dimstars** [comment]
has been fixed on 4.0
