### ISSUE TITLE
建议增加一个查看错误码的命令

### ISSUE THREAD

**Issue by wangzk0206** [oceanbase/oceanbase#978]
是否能够或者已经实现了类似oracle那种查看某个错误码的命令。例如：oerr ora 4013

**Comment by caifeizhi** [comment]
有个ob_error的工具，目前已经在utils的rpm包中发行；
当时的讨论记录：https://github.com/oceanbase/oceanbase/discussions/185

**Comment by longdafeng** [comment]
We have provide ob_error tools, so close this issue.
