### ISSUE TITLE
[Bug]: When ocp3.3 takes over the OB cluster with obproxy, when the cluster_id is not empty, the cluster is not accessible

### ISSUE THREAD

**Issue by timeout-coder** [oceanbase/oceanbase#979]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others

./observer -V
observer (OceanBase CE 3.1.3)

REVISION: 10100032022041510-a09d3134c10665f03fd56d7f8bdd413b2b771977
BUILD_BRANCH: 3.1.3_bp1
BUILD_TIME: Apr 15 2022 02:16:22
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

./obproxy -V
obproxy (OceanBase 3.2.3 2)
REVISION: 6-local-99faebfc7130b70ad0f56330a28cab6a32ec9a33
BUILD_TIME: Mar 30 2022 01:53:08

ocp-all-in-one:3.3.0-ce
```

### Fast Reproduce Steps(Required)

1、安装一套ob集群with obproxy
2、安装ocp云管平台
3、通过ocp接管ob集群，当选择obproxy接管时，

### Actual Behavior

错误信息：
当前集群不可访问

### Expected Behavior

ocp可以正常接管ob集群

### other information

无

**Comment by askdb** [comment]
ocp 接管页面提示的选填cluster_id，如果填上之后，则表示登录的时候用户名格式变成如下：
user_name@tenant_name#cluster_name:cluster_id

如果是手动部署或者obd 部署的话，以上用户名格式是无法登录成功的。这里的选填，经过测试验证，仅用来支持接管其他ocp部署的OceanBase 环境的情况，在ocp里cluster_name和cluster_id结合起来才能唯一标识一个集群。

**Comment by ChrisYuan** [comment]
![image](https://user-images.githubusercontent.com/2404284/176811627-851605d5-8ba7-4b0b-b701-61855b90936c.png)

![image](https://user-images.githubusercontent.com/2404284/176811646-e8b8e377-9352-4b23-a859-d8c81a2460c3.png)

Refer to screenshots above, pic1 shows the default value is 0, pic 2 shows the default value after initialized is 1, which one is correct? Is this a bug? 

BTW, Using `obclient -h127.1 -P2883 -uroot@sys#obcluster:0 -A -c oceanbase -p` can login cluster ( although cluster_id is 1).

**Comment by chris-sun-star** [comment]
> 

cluster id is set by command line parameter, `-c {cluster_id}`,  you can check observer start command by `ps -ef | grep observer`

**Comment by ChrisYuan** [comment]
> > 
> 
> cluster id is set by command line parameter, `-c {cluster_id}`, you can check observer start command by `ps -ef | grep observer`

OK, got it, many thanks~
