### ISSUE TITLE
no obvious “secure_file_priv” prompt when load data error

### ISSUE THREAD

**Issue by cheeloosoft** [oceanbase/oceanbase#981]
when I load data into oceanbase , sometime forget  SET GLOBAL secure_file_priv = "" , then oceanbase report an error as follows:

MySQL [test]> LOAD DATA /*+ parallel(4) */ INFILE '/tmp/data1657100245991.csv'
    -> REPLACE INTO TABLE TEST1
    -> FIELDS TERMINATED BY ','
    -> ;
ERROR 1227 (42501): Access denied

No  any more useful information to help solve the problem .
 
**Describe alternatives you've considered**
Suggest that when such problems occur，prompt key information such as：
the server is running with --secure-file-priv option so it can not execute this statment , please execute first:
SET GLOBAL secure_file_priv = "" 

**Additional context**

**Comment by caifeizhi** [comment]
Thanks for your suggestion, in current version, the error code is confuse; Maybe we should change another error code with more error message;

**Comment by caifeizhi** [comment]
![image](https://user-images.githubusercontent.com/5435903/177685713-db4a44b8-cca0-45ef-a050-e5a04193ebb1.png)
Mysql have a better error message
