### ISSUE TITLE
[Feature] Provide a parameter to assign the size of clog disk

### ISSUE THREAD

**Issue by Vendredimatin** [oceanbase/oceanbase#990]
**Is your feature request related to a problem? Please describe.**
一般情况下，observer使用独立的磁盘空间存放clog，并提供了一个配置项clog_disk_utilization_threshold用于控制clog的复用下限。正常运行情况下clog磁盘空间不会超过80%，超过则会报 "clog disk is almost full" 的错误，提醒 DBA 处理。

**但是**，存在多observer跑在一块磁盘空间的情况，当所有observer的clog磁盘使用空间加起来超过磁盘的80%时会报 "clog disk is almost full"的错误，DBA处理时会发现负责的单observer的clog磁盘使用空间并没有超过80%，会产生不符合预期的现象。

**Describe the solution you'd like**
为observer增加一个配置项clog_disk_limit_size，明确指明clog磁盘大小。

**Is your feature request related to a problem? Please describe.**
In general, the observer uses independent disk space to store clogs, and provides a configuration item clog_disk_utilization_threshold to control the lower limit of clog reuse. Under normal operation, the clog disk space will not exceed 80%. If it exceeds, the error "clog disk is almost full" will be reported, and the system will remind the DBA to deal with it.

**However**, it is possible that multiple observers run on one disk. When the total used clog disk space of all observers exceeds 80% of the total disk space, the error "clog disk is almost full" will be reported. In this case, DBA will find an unexpected situation that the The clog disk usage space of the observer which he manages does not exceed 80%.

**Describe the solution you'd like**
Provide a parameter(clog_disk_limit_size) to determine the clog disk size of an observer.

**Comment by longdafeng** [comment]
We are goint to support this feature in 3.1.5.
