### ISSUE TITLE
[Question]: when connect to oceanbase without -A option,it occurs error 'segment fault(core dump)'

### ISSUE THREAD

**Issue by youyoucao2018** [oceanbase/oceanbase#993]
### Describe your question

[Question]: when connect to oceanbase without -A option,it occurs error 'segment fault(core dump)'

**Comment by youyoucao2018** [comment]
[root@ob01-tst-xc-124-40 ~]# mysql -h127.1 -uroot@xctest -P2883 -p123456
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 16
Server version: 5.6.25 OceanBase 3.1.3 (r10000292022032916-3d79cacb37012cf61b7cb8faf00d9a6bb152bcd1) (Built Mar 29 2022 08:20:39)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use oceanbase;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

段错误 (核心已转储)

**Comment by youyoucao2018** [comment]
<img width="950" alt="4badf41345704ced47217a95685dc8c" src="https://user-images.githubusercontent.com/47956118/179488510-2cb7423d-d9c5-4ead-92b5-3740f3565e4a.png">

**Comment by youyoucao2018** [comment]
<img width="948" alt="企业微信截图_16581386137708" src="https://user-images.githubusercontent.com/47956118/179489398-82943dec-6909-4abc-86e8-418f1ebba028.png">

**Comment by youyoucao2018** [comment]
<img width="947" alt="企业微信截图_165813863690" src="https://user-images.githubusercontent.com/47956118/179489544-d459e6f0-cabd-47f4-ade9-6642ce846301.png">

**Comment by youyoucao2018** [comment]
以上是执行dmesg命令后的结果

**Comment by caifeizhi** [comment]
It seems mysql console(not observer) coredump？Can you please supply some more information?
1. OS && chip platform 
2. The coredump stack of mysql; (In centos, you can find core file use `cat /proc/sys/kernel/core_pattern`)

**Comment by youyoucao2018** [comment]
[root@ob01-tst-xc-124-40 ~]# uname -a
Linux ob01-tst-xc-124-40 4.19.90-23.8.v2101.ky10.x86_64 #1 SMP Mon May 17 17:08:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@ob01-tst-xc-124-40 ~]# cat /proc/cpuinfo | grep 'model name' |uniq
model name      : Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
[root@ob01-tst-xc-124-40 ~]# cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h

**Comment by watchpoints** [comment]
![image](https://user-images.githubusercontent.com/5937331/179882253-bfbf2208-74ac-46dd-8f2e-609f1120fd4c.png)

**Comment by caifeizhi** [comment]
mysql console is mysql-5.5.52:
1.It seems that some compat problem in mysql 5.5 with oceanbase 3.1.4-ce; but in you coredump stack, we can not found enough information for trouble shooting
You can try:
1. use mysql 5.7 to connect oceanbase;
2. use obclient to connect oceanbase;

**Comment by jaqazwsx** [comment]
应该是mysql命令的问题，mysql是麒麟5.5.52版本的，我们在其他机器上用5.7的mysql命令登录，use oceanbase就没问题

**Comment by jaqazwsx** [comment]
好的
