### ISSUE TITLE
[Question]: How to use OceanBase JDBC driver?

### ISSUE THREAD

**Issue by hsien999** [oceanbase/oceanbase#994]
### Describe your question

使用社区版的OceanBase（最新版的docker oceanbase-ce），JDBC驱动oceanbase-client有没有比较完善的文档？例如url连接的"jdbc:oceanbase://xxx"和"jdbc:oceanbase:oracle://xxx"有什么区别？我在Mysql模式上尝试了两种方式都可以。我现在想做一个对OceanBase适配的SQL Parser，但是我如何判断当前是MySQL还是Oracle模式呢？

**Comment by akaError** [comment]
can u detail ur idea? what kinds of sql parser ? what's links between jdbc and parser?

**Comment by longdafeng** [comment]
Please use oceanbase as MySQL when oceanbase works under MySQL mode, especially for jdbc url,  jdbc driver, jdbc setting.  please use mysql-connector-java-5.1.47

**Comment by hsien999** [comment]
> Please use oceanbase as MySQL when oceanbase works under MySQL mode, especially for jdbc url, jdbc driver, jdbc setting. please use mysql-connector-java-5.1.47

@longdafeng Thank you for your reply! However, I am still confused about how to determine the compatibility mode of Oceanbase by jdbc url, i.e., what is the difference between "jdbc:oceanbase://xxx" and "jdbc:oceanbase:oracle://xxx"? If there is no difference, can I only tell the difference by detecting the actual physical database?
