### ISSUE TITLE
[Bug]: Any obproxy or observer can't be run in the machine where OCP will install metadb to

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#996]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

If there are obproxy or observer run in the machine where OCP will install metadb to, 

1. ocp install script will kill the old obproxy or observer
2. even if the metadb's obproxy port have been changed, it will still leading to port conflict. 

### Actual Behavior

for example, firstly OCP install script will kill the old obproxy fistly.
then it will start obproxy with port 2883 and 2884, there is no way to set obproxy's rpc port
it will leading port conflict.

![image](https://user-images.githubusercontent.com/374091/179767401-50da1272-d67e-47e7-b3ca-5b074c7f00e1.png)

### Expected Behavior

1. provide comments to tell user to choose a fresh machine in the ocp's config.yaml.
2. support port setting for observer/obproxy, not only sql port, but also rpc port.

**Comment by chris-sun-star** [comment]
ocp 3.3.0-ce-bp1 fixed this issue, the installer script will filter the listen port when kill process
