### ISSUE TITLE
[Bug]:gv$sql_audit中sql_id乱码 

### ISSUE THREAD

**Issue by TobyYaochen** [oceanbase/oceanbase#997]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

```markdown
- OB Version 3.1.1
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others
```

### Fast Reproduce Steps(Required)

select sql_id from oceanbase.gv$sql_audit  limit 100;

### Actual Behavior

MySQL [oceanbase]> select sql_id from oceanbase.gv$sql_audit  limit 100;
+----------------------------------+
| sql_id                           |
+----------------------------------+
| 2351C88EB78C36BCCD2F397CF7C3901C |
| 4B9D3DE3F19D5943005F4D4A38944780 |
| 2351C88EB78C36BCCD2F397CF7C3901C |
| 8F72989849002A8DC7314B5E6AFE17EF |
|                                  |
| DCCE94F61B7E074C2A648A1C9CE3442A |
| 2351C88EB78C36BCCD2F397CF7C3901C |
|  Ⳡ        P  ȳ            |
| 	c
                     3ᡐ 䕾          |
|             .                  |
| 2351C88EB78C36BCCD2F397CF7C3901C |
| 2351C88EB78C36BCCD2F397CF7C3901C |

**Comment by akaError** [comment]
this problem has been fixed in higher version , could update or pull the latest version ?
